### ISSUE TITLE
Creating an option with prompt always prompts even if the option isn't added to command call

### ISSUE THREAD

**Issue by reinaldorauch** [pallets/click#1015]
Hi, I'm having an issue when I add a prompt or password prompt option to my command. It will prompt even if the command doesn't have that option specified when calling the command in terminal.

I used this cookiecutter template to generate the boilerplate code:
https://github.com/nvie/cookiecutter-python-cli

And the default configs generate a working command that i used to test this:

1. I added an password_prompt decorator in the main command at `my_tool/cli.py`:
```python
import click


@click.command()
@click.option('--as-cowboy', '-c', is_flag=True, help='Greet as a cowboy.')
@click.password_option('--password', '-p', help='Input a password')
@click.argument('name', default='world', required=False)
def main(name, as_cowboy):
    """My Tool does one thing, and one thing well."""
    greet = 'Howdy' if as_cowboy else 'Hello'
    click.echo('{0}, {1}.'.format(greet, name))
```
2. Installed in the project virtualenv with pip
```
pip install --editable .
```

3. Calling the my-tool command in virtualenv makes click prompt for the password:
```
$ my-tool
Password:
```

As it is an option I thought that it wouldn't prompt it it isn't passed when calling the command.

There is something that I'm missing?

**Comment by LuckyJosh** [comment]
That is by design I would guess,
the documentation example shows this behaviour as well:
http://click.pocoo.org/5/options/#password-prompts

**Comment by LuckyJosh** [comment]
Just below the section I referenced above comes the section about callbacks, those might be usefull to you:

http://click.pocoo.org/5/options/#callbacks-and-eager-options

**Comment by fdavis** [comment]
related to #736
