### ISSUE TITLE
Allow showing default values globally.

### ISSUE THREAD

**Issue by mchwalisz** [pallets/click#1018]
Feature request, as in #646, we already had a discussion how to easily show default values for options. As `context_settings` is already used to configure global settings anyway, the idea would be to allow the following:

```python
@click.command(
    help='Command helptext',
    context_settings=dict(show_default=True))
@click.option("--test", default="foobar", help="Option helptext")
def cli(test):
    pass
```

Which should enable `show_default` for all options and give the following help text:

```bash
$ cli --help
Usage: cli [OPTIONS]

  Command helptext

Options:
  --test TEXT   Option helptext. Default: 'foobar'
  --help        Show this message and exit.
```

**Comment by mchwalisz** [comment]
If implemented correctly (haven't looked into the code). It should also work for `@click.group()`

**Comment by lukeyeager** [comment]
Temporary workaround:
```Python
import functools

import click

click_option = functools.partial(click.option, show_default=True)

@click.command()
@click_option('--name', default='Luke')
def say_hi(name):
    print(name)

if __name__ == '__main__':
    say_hi()
```

**Comment by drorata** [comment]
Thanks @lukeyeager for the nice idea. 

Is this enhancement aligns with the package's developers agenda?

**Comment by jcrotts** [comment]
This seems to be fixed in https://github.com/pallets/click/pull/1225 .

**Comment by drorata** [comment]
The merged #1225 is not yet part of version 7.0, is that right? When is it planned to be released?

**Comment by ehles** [comment]
we have a lot of cli commands and a huge more params for them and going to show default, so we very appreciate for releasing this feature.
anyway a year has passed since release 7.0, do you have any plans for releasing 7.1? 
Thanks.

**Comment by pohmelie** [comment]
Spent some times to dig this. It confusing that [documentation](https://click.palletsprojects.com/en/7.x/api/#click.Context) promotes this feature, but it is actually not there.

**Comment by altendky** [comment]
The lack of a `latest` selection for version, or any actual releases, is a bit odd.

![image](https://user-images.githubusercontent.com/543719/73092006-b973f180-3ea9-11ea-80a4-9ffadee1f97d.png)

**Comment by davidism** [comment]
Just like git, `master` contains the latest development code, and 7.x contains the latest 7.x branch code. I'm not sure what's odd about that.

**Comment by altendky** [comment]
![image](https://user-images.githubusercontent.com/543719/73093106-db6e7380-3eab-11ea-8c42-5454641a6570.png)

I may have incorrectly referred to lacking 'latest'.  So I think the click 'master' is what others often refer to in this context as 'latest'.  They also then have 'stable' which...  I think is the most recent release?  Then they have the actual releases rather than just development branches.  If click offered 7.0 rather than just 7.x docs then people running 7.0 could see the docs for their actual version they are running rather than a preview of features they do not yet have access to via released versions on PyPI.

**Comment by altendky** [comment]
Though yes, this change does also seem to have been missing the `versionadded` note.

**Comment by pohmelie** [comment]
But this change did not added to any version yet. Latest version is 7.0 and it lacks of this feature.

**Comment by altendky** [comment]
@pohmelie, correct.  So I set the version added to 7.1 in the PR.  I think some projects have you put a marker in and then they have a tool that autofills the proper version when making a release.  My quick look around Click didn't show that.  But, if I missed it, whoever reviews the PR will hopefully catch it and teach me.
