### ISSUE TITLE
CI does not test documentations

### ISSUE THREAD

**Issue by dawran6** [pallets/click#1019]
Currently CI does not check any documentation error, e.g. syntax error or wrong reference link. It'd be nice to build documentation automatically on every PR.

As an example: Flask has a CI job to test the documentation in the [.travis.yml](https://github.com/pallets/flask/blob/master/.travis.yml#L10), which refers to the TOXENV defined in its [tox.ini](https://github.com/pallets/flask/blob/master/tox.ini#L40).

**Comment by davidism** [comment]
This has been fixed at least since we moved to Azure Pipelines then GitHub Actions.
