### ISSUE TITLE
Options same shorthand letter overlap

### ISSUE THREAD

**Issue by smarlowucf** [pallets/click#1024]
click==6.7
Python 3.6.5

If you have two options which share a letter but have different case the lowercase option is placed as the value for the uppercase option when only it is provided:

Example:
```
  -r, --region TEXT
  -R, --running-instance TEXT
```

`> ... -r us-west-1`

This passes `running_instance="us-west-1"` to the method.

Whereas using both works fine:

`> ... -r us-west-1 -R instance-123`

Passes `running_instance="instance-123", region="us-west-1"`

Update: This happens to the first option no matter the case:

Example 2:
```
  -R, --running-instance TEXT
  -r, --region TEXT
```

`> ... -R instance-123`

Yields `region="instance-123"`.

**Comment by sujatapatnaik52** [comment]
@smarlowucf I was trying to reproduce the same bug with python3.6.5 and click 6.7 in local vm and I am unable to see the above scenario. Have a look at the code

**Code :** 

```import click 

def validate_running_instance(ctx, param, value):
    click.echo("Validating running_instance %s" % value)
    return value

def validate_region(ctx, param, value):
    click.echo("Validating region %s" % value)
    return value

@click.command()
@click.option('-R', '--running-instance', help = 'Name value', callback=validate_running_instance)
@click.option('-r', '--region', help = 'Number value', callback=validate_region)
def test(running_instance, region):
    click.echo(running_instance)
    click.echo(region)

if __name__=='__main__':
    test()
```

**Output** : 

```
1. [root@OSS oss]# python3.6 test.py -R hello
Validating running_instance hello
Validating region None
hello

```
```
2. [root@OSS oss]# python3.6 test.py -r hello
Validating region hello
Validating running_instance None

hello
```

Is this the same type of scenario you are referring to in the above example or did I missed something here?? can you please clarify the same??

**Comment by smarlowucf** [comment]
@sujatapatnaik52 Sorry I did not include a full example. I also figured out the problem. I have a choice type that I wanted to be case insensitive. So according to https://github.com/pallets/click/issues/569 I added `context_settings=dict(token_normalize_func=str.lower))`. This makes the choice option case insensitive but also all of the option codes (-r == -R).

.test.py
```
import click


@click.command(context_settings=dict(token_normalize_func=str.lower)))
@click.option(
        '-r',
        '--region',
        help='Cloud provider region to test image.'
)
@click.option(
        '-R',
        '--running-instance-id',
        help='The ID or Name of running instance to test.'
)
def test(region, running_instance_id):
    click.echo('Region: {}'.format(region))
    click.echo('Instance: {}'.format(running_instance_id))


if __name__ == '__main__':
    test()
```

```
> python test.py -R test
Region: None
Instance: test
```

```
python test.py -r test
Region: None
Instance: test
```

**Comment by smarlowucf** [comment]
It appears there's a `case_sensitive` option in master https://github.com/pallets/click/pull/887/commits/138a6e3ad1dbe657e09717bc05ebfbc535f4770d but probably won't be available in a release until 7.x?

**Comment by davidism** [comment]
That will be in 7. If you can, would you check out master and confirm it works for what you need?

**Comment by smarlowucf** [comment]
@davidism Yeah the `case_sensitive` option will work for the choice fields in place of `context_settings=dict(token_normalize_func=str.lower))`.

Is it expected for `context_settings=dict(token_normalize_func=str.lower))` to make the option codes also case insensitive? If so this can be closed.

**Comment by davidism** [comment]
Everything is a token, so yes, that's expected.
