### ISSUE TITLE
Allow omission of options

### ISSUE THREAD

**Issue by cefn** [pallets/click#1029]
I have an already-well-defined operation, with defaults specified 'pythonically', which I would like to invoke through Click. Unfortunately, because options can't be omitted in the function call, it's impossible to take advantage of the defaults already specified, meaning they would have to be specified in multiple places meaning lots of complexity.

Here is my function (with implementation omitted)...

```python
def run(release=None, port=None, baud=1500000, erase=True, device=None):
    pass
``` 

Wrapping this with Click looks like...

```python
@click.command()
@click.option("--release", "-r")
@click.option("--port", "-p")
@click.option("--baud", "-b")
@click.option("--erase", "-e")
@click.option("--device", "-d")
def main(*a, **k):
    run(*a, **k)
```

However, because click always passes None values rather than omitting values I end up with **k populated like...

```
{'release': None, 'port': None, 'baud': None, 'erase': None, 'device': None}
```

Having every option passed as a None value destroys any chance of me pythonically defining defaults.

I propose adding an 'optional' argument to Option so the None values would not be in the **k dict in the first place. Then the new click decorators would look like...

```python
@click.command()
@click.argument("target", type=click.Choice(brains), optional=True)
@click.option("--release", "-r", optional=True)
@click.option("--port", "-p", optional=True)
@click.option("--baud", "-b", optional=True)
@click.option("--erase", "-e", optional=True)
@click.option("--device", "-d", optional=True)
def main(*a, **k):
    run(*a, **k)
```

And the new **k from a no-arg call to the cli would look like...

```
{}
```

**Comment by cefn** [comment]
For others encountering this limitation, the following workaround, which filters and drops None values before passing on to the underlying call is reasonably elegant, and makes the use of pythonic defaults possible again, although explicit support without this workaround would be very welcome...

```python
@click.command()
@click.option("--release", "-r")
@click.option("--port", "-p")
@click.option("--baud", "-b")
@click.option("--erase", "-e")
@click.option("--device", "-d")
def main(*a, **k):
    k = dict((name,value) for name, value in k.items() if value is not None)
    run(*a, **k)
```

**Comment by ali1234** [comment]
That won't work in the following case:

`@click.option('--whatever', type=(int, int))`

because the default value for that option is `(None, None)` and if you try to set the default to `None`, eg:

`@click.option('--whatever', type=(int, int), default=None)`

then click will not accept the default and raises an exception. In general the workaround can be extended to catch these cases something like this::

`... if not (value is None or (isinstance(value, tuple) and all(x is None for x in value)))`

**Comment by jcrotts** [comment]
As I mentioned in the related issue I think this similarly could be solved with callbacks, parsing in the function body or potentially sub classes.

I'm not sure there is much value in adding more flags to option, but I think it is at least in line with the existing API of option.

Check out this example from the docs: https://github.com/pallets/click/blob/master/examples/validation/validation.py
