### ISSUE TITLE
What is the most elegant way of accepting an option on both the group and subcommands?

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [pallets/click#1034]
I have a tool with subcommands, similar to `git`. Most subcommands share one or two parameters. I would like to offer the user to pass in those parameters either before or after the subcommand.

I know I can pass the context and additionally make the subcommands accept the same params, but that seems like a lot of unnecessary boilerplate. Is there a setting to search for an option/param regardless of its position on the command line?

**Comment by davidism** [comment]
That's just not how Click is designed to work. The options go next to the command the modify. You can probably do something with the context, but that's up to you to explore.
