### ISSUE TITLE
.format() help strings?

### ISSUE THREAD

**Issue by altendky** [pallets/click#1035]
I am presently wanting to show the user the environment variable name which can be used for options where I offer that.  I thought it might be reasonable for click to format the help string and insert stuff like the env var.

``` python3
@click.option(
    '--config-file',
    type=click.File(),
    help='the config file (settable via {envvar})',
    envvar='MY_CONFIG_FILE',
)
```
Which would result in the help string `the config file (settable via MY_CONFIG_FILE)`.  I presume there are others that might be nice but I haven't thought much about it yet.  Perhaps the type string (`PATH` in this case I think), default, etc.

**Comment by danishprakash** [comment]
this looks interesting, @jcrotts mind if I take this up if nobody else is? Also, is there anything I should know regarding the implementation if I were to start working on this?

**Comment by jcrotts** [comment]
@danishprakash feel free to a look at it. I am happy to help if you have specific questions. It is ultimately up to @davidism if it gets merged in though.

**Comment by altendky** [comment]
@davidism thanks, that does sound like what I wanted.  Hopefully I can go back and switch to that in my code soon.
