### ISSUE TITLE
Testing documentation needs to make reference to `result.stderr`.

### ISSUE THREAD

**Issue by bradwood** [pallets/click#1036]
This is clearly handled in the code, but the current docs on this only refers to the stdout case.

**Comment by bradwood** [comment]
Actually, I've just realised the .`stdout` and `.stderr` attributes on only on `result` in the master branch and not the latest released tag.  :(   I need these... Is the master safe to install, or should I wait for the next pypi tagged version? If so, when is that likely to ship?

Thanks.

**Comment by jcrotts** [comment]
6.8 and 7.0 Should be coming soon https://github.com/pallets/click/issues/885
Master is relatively safe. 

Feel free to submit a PR for the documentation improvement.

**Comment by bporter125** [comment]
This should be resolved since 7.0 has been released and it is referenced in the docs here: https://click.palletsprojects.com/en/7.x/api/?highlight=clirunner#click.testing.Result.stderr
