### ISSUE TITLE
Add changelog for 7.0

### ISSUE THREAD

**Issue by davidism** [pallets/click#1038]
@pallets/click Need someone go through the log since 6.7 and make sure we have a changelog entry for each feature and bug fix. I want to get 7.0 released.

    git log 6.7..

Take a look at the Flask changelog for an example of the format I've started using.

If someone has the time to do this, assign yourself to this issue.

**Comment by jcrotts** [comment]
I can work on this.

**Comment by jcrotts** [comment]
@davidism accidentally pushed a commit to master it only had some changes to the CHANGES file, switching over to a fork.

**Comment by discosultan** [comment]
Thanks for the changelog @jcrotts.

Can this be closed now? Also, is there anything else stopping the 7.0 release?

**Comment by sirosen** [comment]
I think we can consider this closed, as there is a changelog, and @davidism said he's working on doing the 7.0 release with the changes we currently have.
