### ISSUE TITLE
Unable reference hyphenated option with flag 

### ISSUE THREAD

**Issue by lightclient** [pallets/click#1041]
When I run the following snippet I get `Invalid start character for option (has-hyphen)`, but if I change `has-hyphen` to `hyphen` it works fine. The expected outcome is for `has-hyphen` to also work.

python 3.6.5
click 6.6

```
import click

@click.command()
@click.option('--has-hyphen')
@click.option('-o', 'has-hyphen', flag_value='value')
def main():
    pass

if __name__ == '__main__':
    main()
```

**Comment by sujatapatnaik52** [comment]
I think the option which you are trying is not only with flags, I see the similar behaviour without the flags as well,
```
@click.command()
@click.option('-o', 'hi-hello')
def main(hi-hello):
    click.echo(hi-hello)
    pass

if __name__ == '__main__':
    main()
```
Upon looking at the code, it seems click doesn't allow the options to begin with alphanumeric characters provided the option is having a long name. click considers **hi-hello** as the long name for that option.

In the below example where **hi-hello** is changed to **hello** and see the behaviour
**Code:**
```
import click

@click.command()
@click.option('-o', 'hello')
def main(hello):
    click.echo(hello)
    pass

if __name__ == '__main__':
    main()
```
**Output:**
```
[root@OSS oss]# python3.6 test.py --help
Usage: test.py [OPTIONS]

Options:
  -o TEXT
  --help   Show this message and exit.
```
In the output above, if you see the long name for the option is empty and hence you are not getting any error as there is no validation done here. however, in the above case, the long-name was **hi-hello** and it was getting validated. I hope you got the difference. 

I think click should not allow any long name which starts with alphanumeric without considering it has a hyphen or not. Maintainers can take a decision for labelling it accordingly. 

In the mean while you can use **--has-hyphen**. This works fine.

**Comment by davidism** [comment]
`has-hyphen` is not an option name, it needs to start with the long option prefix `--`.
