### ISSUE TITLE
User-customizable aliases

### ISSUE THREAD

**Issue by tuukkamustonen** [pallets/click#1042]
While click has http://click.pocoo.org/6/advanced/#command-aliases, it doesn't allow _user_ to add custom aliases. `git` has this:

    git config --global alias.bd "branch -d"

Which saves to `.gitconfig` and then you can just `git bd <branch>`.

I know this is something that has been _kinda_ discussed before (https://github.com/pallets/click/issues/28) but let's have an actual ticket for it.

I think the `git` model is great because it:

1. Allows end-user to add aliases
2. Support shell tab-completion

Any chance something similar could make it into click?

**Comment by davidism** [comment]
There is an example of this here: https://github.com/pallets/click/tree/master/examples/aliases. This should probably be linked from the docs section you linked.
