### ISSUE TITLE
Wrong Parameter in "Yes Parameters" Documentation

### ISSUE THREAD

**Issue by rwhitt2049** [pallets/click#1043]
In the documentation for [Yes Parameters](http://click.pocoo.org/5/options/#yes-parameters), the `help` parameter is used in `click.confirmation_option()`. This doesn't seem to produce the right output when run. 

Should it instead be:

```python
@click.command()
@click.confirmation_option(prompt='Are you sure you want to drop the db?')
def dropdb():
    click.echo('Dropped all tables!')
```

It's currently: 
![image](https://user-images.githubusercontent.com/4194594/41486223-51a29d92-70a9-11e8-95f0-7697c1db583e.png)

**Comment by robintully** [comment]
This has been fixed in the most recent version of the documentation, which can be found here [Yes Parameters](https://click.palletsprojects.com/en/7.x/options/#yes-parameters)
