### ISSUE TITLE
Use argparse features for click 

### ISSUE THREAD

**Issue by thechief389** [pallets/click#1046]
Sorry for duplicate issue. I accidentally posted the other and it ended up getting closed.

# Original Issue

It would be cool if argparse was introduced into click's custom parser.

Subcommands can still be used with the decorator method. But argparse also support a lot of things out-of-the box that wouldn't need to be reimplemented in click, such as prefix_chars. It also has features that click doesn't even have, like customized order of commands, options, and args, and replacement of default help section headers and usage format.

**Comment by ThiefMaster** [comment]
click is meant to be a replacement for argparse - so if you want argparse features in click, they should rather be implemented in click.

**Comment by thechief389** [comment]
Click has a lot of problems such as not handling -h by default and doesn't support mutually exclusive options and customization of the help message (such as changing the name of the sections and sorting commands and args)

**Comment by ThiefMaster** [comment]
You are welcome to open a pull request, e.g. to add an option to include `-h` for the builtin `--help` option.

**Comment by davidism** [comment]
Regarding `-h`, it's not recognized by the built-in help command because it can commonly be used for other arguments. Regarding argparse in general, if there is a specific feature that is not supported, please open an issue for it. In general though, we are not trying to match argparse.
