### ISSUE TITLE
merge click-completion in click

### ISSUE THREAD

**Issue by glehmann** [pallets/click#1060]
Originally the enhancement of the completion in click was considered as better hosted in a separated project in click-contrib, but now some new completion features has been added in click, duplicating the features in click-contrib. I think it would be interesting to merge both implementations in click.

Fortunately, two different approaches have been used and I think they both have some advantages:
* click-completion focuses on the completion at the type level
* click focuses on the completion at the command level

as seen in https://github.com/click-contrib/click-completion/pull/12 , both can be useful depending on the use case.

My hope with this issue is to:
* validate that we actually want to merge both completions
* discuss how to do it

in order to actually produce a pull request for the merge

@stopthatcow @Konubinix

**Comment by davidism** [comment]
@thechief389 they are in click-contrib. The whole point of this is to discuss combining efforts.

**Comment by davidism** [comment]
I've been trying to address the open PRs about completion before 7.1, and I've come to the conclusion that Click's completion system needs a comprehensive redesign. I'd like to discuss what that looks like in #1484.

I'm not sure where click-completion fits at this point. I would love to get Click's completion support to the point where click-completion can be deprecated, and I would love to bring on the completion maintainers to help here. But I don't think I want to just copy click-completion into Click anymore. How do you feel about closing this and discussing more at #1484?

**Comment by davidism** [comment]
Closing in favor of #1484.
