### ISSUE TITLE
click.BOOL type defaults to None for flag options.

### ISSUE THREAD

**Issue by giladg-FB** [pallets/click#1062]
[click v6.7]: The following has undesired(?) behavior: 
`@click.option('--overwrite', default=False, is_flag=True, type=click.BOOL)`
results in `overwrite=None` if flag is missing (namely, `--overwrite`  is not specified in CLI).

dropping type=click.BOOL:
`@click.option('--overwrite', default=False, is_flag=True)`
results in `overwrite=False`, which is the expected behavior. 

This results in having to check for the default as both False or None, or simply not(flag). Manageable, but not great. Is this the desired behavior here?

**Comment by davidism** [comment]
It doesn't make sense to set both `is_flag` and `type=bool`. `is_flag` means "doesn't take user input, switch on presence`. `type` is for converting user input, so `--overwrite y` or `--overwrite n`.

Admittedly, that interaction between the two is a bit weird, but your second example is correct.

**Comment by giladg-FB** [comment]
@davidism , got it, thanks; closing.
