### ISSUE TITLE
Add option to restrict Files/Paths to specific filetypes

### ISSUE THREAD

**Issue by Benjamin-Lee** [pallets/click#1063]
Title says it all. Would be a nice feature to have, especially when passing in multiple files via repeated options. Right now I have to do something ugly like this:

```python
    if f is None:
        raise ValueError("Must provide FASTA file.")
    for filename in f:
        if not filename.endswith(("fa", "fasta")):
            raise ValueError("Must provide FASTA file.")
```

where f is a `Path`

**Comment by Benjamin-Lee** [comment]
I do think that `PurePath.suffix` is the right tool for the job, but I think it should be integrated into click. so that the type checking logic can happen internally.

**Comment by davidism** [comment]
File extensions don't mean anything. This is something that can be done with a custom type if you need it.
