### ISSUE TITLE
Add an option to prefix error messages with the prog_name

### ISSUE THREAD

**Issue by blueyed** [pallets/click#1067]
Currently you will get something like `Error: No such command "foo".`.

I have tried wrapping commands in something like the following (in `__main__.py`, used via entrypoints), but I would like to keep the default `show` behavior, e.g. for UsageErrors, which is not possible easily:

```python
def wrap_for_errormsg(f, *args, **kwargs):
    try:
        f(*args, standalone_mode=False, **kwargs)
    except Exception as exc:
        from click.exceptions import ClickException
        if isinstance(exc, ClickException):
            import sys
            from click.utils import echo

            msg = 'covimerage: error: %s' % (exc.format_message(),)
            echo(msg, err=True)
            sys.exit(exc.exit_code)


def main():
    from .cli import main
    wrap_for_errormsg(main.main, prog_name='covimerage')


def run():
    from .cli import run
    wrap_for_errormsg(run.main, prog_name='covimerage-run')


if __name__ == '__main__':
    main()

```

I think it makes even sense to prepend the prog_name in general - which appears to be common sense for GNU utils at least, e.g. `ls`.

This is relevant for when a program is used in a pipe, script etc, where it is not clear where the error is coming from without this prefix.

**Comment by davidism** [comment]
This might become possible as we expand the formatter (#561), but I don't think it's particularly necessary, so I'm going to close this for now.
