### ISSUE TITLE
Option to change error message or use the argument key in argument method

### ISSUE THREAD

**Issue by amitt001** [pallets/click#1072]
```
@click.argument('--type', metavar='--type <message_type>')
def f(msg_type):
    pass
```

The above will fail because the type is passed as a keyword argument. The below will work:

```
@click.argument('--type', 'msg_type', metavar='--type <message_type>')
def f(msg_type):
    pass
```

but when --type is not passed from the command line the error text returned is:

`Error: Missing argument "msg_type".`

I don't want the user to see the msg_type key because this is for the program's internal use.

Is there a way to change the error text for `argument`?

**Comment by jcrotts** [comment]
You can subclass argument to change the behavior of the metavar if you want. You could also potentially subclass the error itself. 

If this is still an issue for you in click 7 please reopen with a complete example.
