### ISSUE TITLE
support to return input command as text

### ISSUE THREAD

**Issue by tonyfumonkey** [pallets/click#1074]
This may seems wired at first, but it worth discussing.
Using click is great, but sometimes the command is too long, like `some_cmd test --a A --b B --c C --d D ... `
Generally user would prefer `prompt` offered by click, that's great. However, due to more complex logic, user has to provide some extra option-like `--o O` beyond prompt can do, for example, dynamically choosing options.
Thus, is it possible to support a feature/flag let click to return what user has typed including prompt?

**Comment by jcrotts** [comment]
I'm not quite sure what you are asking for, could you please include an example use case.

**Comment by tonyfumonkey** [comment]
A command is called some_command, it has 3 required options A, B, C and 6 optional. 

Right now user could enjoy the prompt function provided by click and quickly typed in those 3 required options. But when typing the optional options, user has to type himself.

So a problem (inconvenience) comes: when an user has to input some optional options most of time, he has to type those large amount of information and it cost lots of time. So my boss ask me to implement a Cli that could return the required commands he typed. For example,

`some_command`
`a: [input required param1]`
`b: [input required param2]`
`c: [input required param3]`

This command could return an error message like this, since we build a RESTful service

`{error: some error}`

But if the CLI can return the command itself combined with running result, the net effect could like this:

`{error: some error}` 
`some_command --a param1 --b param2 --c param3`

Then, the user could copy and paste the original command and add some optional options. This could improve proficiency and ease user, especially cloud user and developers since they are using cumbersome commands repeatedly.

**Comment by davidism** [comment]
`' '.join(sys.argv)`

**Comment by davidism** [comment]
This is most likely already possible, the current context probably has the variables stored somewhere, although I don't know exactly where.

**Comment by tonyfumonkey** [comment]
It is possible but it is cumbersome to implement. Actually I implemented it with checking the option is null and then concatenate the printing string. But for large services with huge numbers of commands, it is not developer-friendly. It would be better if there is a flag to turn on and do this staff.

Or is there any functionality i am not utilizing?

**Comment by davidism** [comment]
Unfortunately, I'm having a hard time understanding what you're trying to describe or why it's an issue. It seems like the information you need is already available, and this doesn't seem like a common use case, so I'm going to close this.
