### ISSUE TITLE
click.poocoo.org not accessible over HTTPS

### ISSUE THREAD

**Issue by kwill** [pallets/click#1076]
**Steps to reproduce:**

* Visit https://click.poocoo.org

**What should happen:**

Click website appears.

**What happens instead?**

Certificate warning.

**Suggested solution:**

Extend the certificate to cover *.poocoo.org

**Comment by davidism** [comment]
None of pocoo.org is, or has been, accessible over https. We are moving away from pocoo.org, nothing will be done about this directly.
