### ISSUE TITLE
Question: Is there a dedicated type for dates?

### ISSUE THREAD

**Issue by devforfu** [pallets/click#1093]
There is a way to validate date string using callbacks. However, is there a dedicated type for dates with specific parsing formats? Something similar to the type `click.IntRange`, like, `click.Date`?

**Comment by jcrotts** [comment]
This tracker is for issues related to the project itself, not general questions.

Checkout https://github.com/click-contrib/click-datetime , it might have what you need.

Otherwise the easiest thing to do would probably be to subclass[click.ParamType(http://click.pocoo.org/5/api/#click.ParamType)
