### ISSUE TITLE
Conceptual Question

### ISSUE THREAD

**Issue by jonericcook** [pallets/click#1094]
Is it possible to place an entire Click CLI application in a `while True` loop? I ask because it would be nice to be able to use the functionality of Click and also be able to keep state. State in the sense that if i run:

$ phonebook setnumber 5555555555

I can run 

$ phonebook getnumber

and get back 5555555555

Any help would be greatly appreciated! :) @mitsuhiko

**Comment by davidism** [comment]
You can rig something up with `invoke`, but I wouldn't recommend it. That's not what Click is designed for. If you want to store state between runs, use a file or database.
