### ISSUE TITLE
Common options for all subcommands 

### ISSUE THREAD

**Issue by halloleo** [pallets/click#1104]
I have an application with two sub commands `read` and `write`:

```
@click.group()
@click.pass_context
def cli(ctx):
    pass

@cli.command()
@click.pass_context
def read(ctx):
    print("read")

@cli.command()
@click.pass_context
def write(ctx):
    print("read")
```

I want to declare a common option `--format`. I know I can add is as a root option via

```
@click.group()
@click.option('--format', default='json')
@click.pass_context
def cli(ctx, format):
    ctx.obj['format'] = format
```

But then I cannot give the option _after_ the subcommand, which in my use case is a lot more natural. So how can I add a common option in one go to the subcommands instead of the root command?

**Comment by davidism** [comment]
This is intentional. It makes parsing more predictable and callback order predictable.

**Comment by halloleo** [comment]
I know. But is there any way to still achive this?
