### ISSUE TITLE
Implementation Question

### ISSUE THREAD

**Issue by mapa17** [pallets/click#1107]
Hi Click community,

i am working on a decorator library myself, and I wonder how do you avoid that during debugging the debugger steps into your library code?

What I try to say is that in my library the decorator modifies a function, including a wrapper that is executed before the user function. During debugging, when I step into the user function, i am first in the library code and only than the function is called.

thx,
Manuel

**Comment by davidism** [comment]
As far as I know we don't. PyCharm's debugger has an option like "only step into my code", but that's not related to Click.

This question may be better suited on the mailing list (flask@python.org), or on a discussion forum. This issue tracker is for issues with Click itself.
