### ISSUE TITLE
sphinx docs

### ISSUE THREAD

**Issue by kotoroshinoto** [pallets/click#1114]
I am aware there is a module for obtaining CLI documentation.

However I would ALSO prefer if the code behind the CLI were to be properly documentable by autodoc in the normal way. (treating it as a method/function, etc.)

This way I could put my CLI documentation alongside the code docs and have the correct formatting when looking at the module in terms of code rather than user interface behavior.

Currently, unless i'm doing something wrong, it appears the decorators from click are hiding the methods, signatures, and docstrings from autodoc, so I end up with an empty module documentation page.

If indeed this is my fault, would you have any guidance for what I ought to do? (I am getting successful output from the click parser ".. click:: module" etc. Its pretty nifty: https://github.com/click-contrib/sphinx-click )

**Comment by davidism** [comment]
If you have a command `example`, then `example.callback` is the original function, which you can point autodoc at. However, note that commands are not intended to be called as standard Python functions after being decorated, so thismay be more confusing than helpful, but that's up to you.

**Comment by davidism** [comment]
I'm not completely familiar with Sphinx-Click, but it sounds like you may be interested in requesting or contributing functionality similar to [`sphinxcontrib.autohttp.flask`](https://sphinxcontrib-httpdomain.readthedocs.io/en/stable/#module-sphinxcontrib.autohttp.flask) and `autohttp.flaskqref`.
