### ISSUE TITLE
Expand unit testing around termui, especially getchar

### ISSUE THREAD

**Issue by sirosen** [pallets/click#1116]
#1115, #583, and a couple of other issues seem to show that there are some subtle cases to handle in `click.getchar`.
But these are hard to test and therefore, presently, untested. I wouldn't be surprised to find other gaps in testing of termui.

I think it would be nice to have some more testing around the termui module, limited to what we can do safely and definitely correctly -- e.g. feed `getchar` a `u'\x04'` and make sure it raises an exception.

The best way to tackle this is probably to start writing more tests and see what's needed and possible.
I'd like to step up and do it myself, but if someone else has the cycles they should feel more than welcome.

**Comment by icreatedanaccount** [comment]
Taking a stab at it

**Comment by icreatedanaccount** [comment]
I am able to expand the coverage by about 15% and test the win-specific version of `getchar` as I develop on Windows. How do you suggest we go about the Linux half (keep the issue open, new one, etc.) ? @sirosen

**Comment by sirosen** [comment]
My big worry was about Windows coverage. For the issues I mentioned, I was firing up Windows VMs and poking and prodding at it, without any kind of tests as a safety net.

I would say that #1315 closes this. At a glance it seems fine/good, but I want to do a more careful read after work before merging.
