### ISSUE TITLE
Let Choice take a dict, and if so, return the value associated with the chosen key.

### ISSUE THREAD

**Issue by pjz** [pallets/click#1118]
It would be nice if I could do something like:

    crypto = Choice({ 'md5': hashlib.md5, 'sha256': hashlib.sha256 })

and then

    @click.option("--hashalg", type=crypto, default='md5')
    ....
        hash = hashalg(content)

...otherwise I have to set up the mappings manually, and make sure they're a list:

    crypto_map = { 'md5': hashlib.md5, 'sha256': hashlib.sha256}
    crypto = Choice(list(crypto_map.keys()))

    @click.option("--hashalg", type=crypto, default='md5')
    ....
        hash = crypto_map[hashalg](content)

..which is a bit of extra complexity that it seems would be commonly needed.

**Comment by davidism** [comment]
It's a good idea, but I'd like to avoid adding more complexity to this. This is something that can be done with a custom type without any changes to Click.

```python
class MappedChoice(click.Choice):
    def convert(self, value, param, ctx):
        value = super().convert(value, param, ctx)
        return self.choices[value]

@click.command()
@click.argument("value", type=MappedChoice({"a": 1, "b": 2}))
def show(value):
    click.echo(value)
```

Note that like the example above, you don't need to call `list(keys)` in your example either, passing a dict should work fine.

Leaving it up to the user to implement this also means they can do other things like attribute access or function calls. Your example could be implemented in a reusable type:

```python
class HashContent(click.Choice):
    def convert(self, value, param, ctx):
        value = super().convert(value, param, ctx)
        f = getattr(hashlib, value)
        return f(ctx.params["content"].encode()).hexdigest()

@click.command()
@click.argument("content")
@click.option("hashed", "--hash", type=HashContent(("md5", "sha1")), default="sha1")
def show(content, hashed):
    click.echo(hashed)
```
