### ISSUE TITLE
Need example with unit testing

### ISSUE THREAD

**Issue by mig82** [pallets/click#1119]
The examples on testing seem to suggest that the function being defined, say `foo` should be nested within it's corresponding unit test, say `test_foo`. This seems weird. I would have expected unit tests to be written either in a separate file or in a separate function, but nesting the definition within the test feels off. Can you please add a basic unit test to one of the examples for more clarity?

**Comment by davidism** [comment]
All that's required is moving the command definition above the test definition.

Marking this as beginner friendly. Please feel free to submit a PR!

**Comment by mig82** [comment]
Right, and then how do you execute all your defined tests in one go?

**Comment by davidism** [comment]
However the test framework you're using (unittest, pytest, etc.) does.

**Comment by dposada** [comment]
I'm assuming that the examples in question are these:

https://click.palletsprojects.com/en/7.x/testing/

**Comment by davidism** [comment]
@dposada looks like #1130 already addressed this issue

**Comment by dposada** [comment]
I went ahead and created #1330. Based on the original poster's confusion, I think it makes sense to give examples that show the source code in a separate module from the test code. Let me know what you think.
