### ISSUE TITLE
Use prompt_toolkit.prompt if available

### ISSUE THREAD

**Issue by sedrubal** [pallets/click#1122]
When [prompt-toolkit](https://github.com/jonathanslenders/python-prompt-toolkit) is installed, you could use `prompt_toolkit.prompt` as drop-in-replacement of `input` or `raw_input`. This would make it possible to navigate with arrow keys and <kbd>Ctrl</kbd>+<kbd>A</kbd> and <kbd>Ctrl</kbd>+<kbd>E</kbd> and more.

#### Example code:

Instead of:
https://github.com/pallets/click/blob/da4a18276003bb02622d721dc07bdbeec0dfbd88/click/termui.py#L17
you could use this:
```py
try:
    from prompt_toolkit import prompt as visible_prompt_func
except ImportError:
    visible_prompt_func = raw_input
```

Related: #181 and #173

If you want, I can make a pull request.

---

Click: 6.7
Python 3.7

**Comment by sedrubal** [comment]
Ok. So do you think it is ok to add prompt_toolkit as dependency and always use `prompt_toolkit.prompt` as `visible_prompt_func`?

**Comment by davidism** [comment]
No, that's what I don't want.

**Comment by sedrubal** [comment]
Alright. So I close this issue, as there are other issues about enhancing the prompt.

**Comment by kdeldycke** [comment]
For context, a reference to `prompt_toolkit` has been proposed to Click documentation at https://github.com/pallets/click/pull/3826.
