### ISSUE TITLE
Progressbar object is no more an iterator

### ISSUE THREAD

**Issue by saimn** [pallets/click#1125]
Hi,

With Click < 7.0, iterating on the bar object was possible:
```
In [8]: with click.progressbar(range(10)) as bar:
   ...:     next(bar)
   ...:     next(bar)
   ...:     
  [#######-----------------------------]   20%
```

With Click 7.0, this is broken:
```
In [2]: with click.progressbar(range(10)) as bar:
   ...:     next(bar)
   ...:     next(bar)
   ...:     
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-85d302084fbb> in <module>()
      1 with click.progressbar(range(10)) as bar:
----> 2     next(bar)
      3     next(bar)
      4 

TypeError: 'ProgressBar' object is not an iterator
```

Is it on purpose ? Seems related to https://github.com/pallets/click/pull/487/commits/82f9c626ffedb284eafe67235b5592be6919106d (#487)

**Comment by davidism** [comment]
Bisect shows 8780a763aab11f69258acccbcb9d0d97e92ebadb, from #796, as the origin of the issue. Prior to that, `ProgressBar` had a `next` method.

@ThiefMaster and @dsully, were involved in that PR.

**Comment by sirosen** [comment]
Since click is a py2/py3 compatible project, we should consider using [`six.Iterator`](https://pythonhosted.org/six/#six.Iterator) to make it easier to ensure that both the py2 and py3 interfaces are satisfied.

This also seems pretty easy to add a test for, based on the example given.

**Comment by davidism** [comment]
Due to various issues, we don't use six in the Pallets projects. I think there was actually an issue with streams due to six that was worked around in Click 7.

I don't mind just adding `__next__` and doing `next = __next__`.

**Comment by georgexsh** [comment]
@saimn does #1163 fix your issue? IMO progressbar object's iterator interface is still broken, see #1556.

**Comment by georgexsh** [comment]
@davidism

**Comment by georgexsh** [comment]
> @pallets pallets deleted a comment from georgexsh 3 days ago

@pallets could anyone explain why my comment get deleted? is there anything violent https://github.com/pallets/click/blob/master/CODE_OF_CONDUCT.md?

**Comment by davidism** [comment]
I explained in the other issue that I didn't want to change this, so for some reason you came over here and started asking about the same thing. This is an old, closed issue. Don't be disruptive.
