### ISSUE TITLE
New feature request: add callback for validating a click prompt

### ISSUE THREAD

**Issue by GigiusB** [pallets/click#1141]
I believe it would be nice (and quick) to add a callback parameter to click.prompt like there is for the options

**Comment by GigiusB** [comment]
Just discovered this can be achieve with the value_proc parameter

**Comment by JeroenSchmidt** [comment]
Perhaps it would be a good idea to update the documentation to make this more clear. I only made the connection between value_proc and callback once I read this issue.

**Comment by jcrotts** [comment]
@JeroenSchmidt Docs PRs are welcome. I could see a short example fitting in https://click.palletsprojects.com/en/7.x/prompts/ .
