### ISSUE TITLE
Allow non-file arguments to be piped in

### ISSUE THREAD

**Issue by tedivm** [pallets/click#1144]
I have a project that has commands that take a single argument, and I would like it if that single argument could be autopopulated with the contents of `stdin` if something has been piped to the project. Right now it seems like my only option would be to make the argument optional and then if it isn't set check stdin myself, and then display an error if that isn't set.

**Comment by davidism** [comment]
This doesn't seem like an appropriate use of pipes. It should be fairly straightforward to implement with a custom `Argument` class as you described, and I'd rather leave it to projects to do that as needed.
