### ISSUE TITLE
Nested groups behave like commands 

### ISSUE THREAD

**Issue by timonbimon** [pallets/click#1154]
Hi there,

when using groups together with commands, the nice thing about the code in the groups is that it only gets run when you run a subcommand (if you invoke the group the default behavior is to show the help message).

However this logic seems to break if we have nested groups.

Minimal example to reproduce:

foo.py
```
import click

@click.group()
def hi():
    print("hi")

@hi.group()
def ho():
    print("ho")

@hi.command()
def he():
    print("ho")

if __name__ == "__main__":
    hi()
```

if we run 

```python foo.py ho```

we get 

```
hi
Usage: test.py ho [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  he
```

I would expect that the 'hi' does not get printed...

Is this expected behaviour or a bug? :)

**Comment by thechief389** [comment]
Do this:
```python
import click


@click.group(invoke_without_command=True)
@click.pass_context
def hi(ctx):
    if ctx.invoked_subcommand is None:
        print("hi")


@hi.group()
def ho():
    print("ho")


@hi.command()
def he():
    print("ho")


if __name__ == "__main__":
    hi()
```

See [Group Invocation Without Command](http://click.palletsprojects.com/en/7.x/commands/#group-invocation-without-command).

Also, use [`click.echo`](http://click.palletsprojects.com/en/7.x/quickstart/#echoing) for Python 2 compatibility.

**Comment by timonbimon** [comment]
awesome thanks!
