### ISSUE TITLE
Remove indent in description in help text

### ISSUE THREAD

**Issue by thechief389** [pallets/click#1155]
When click reads the function docstring, it adds two spaces to the beginning like this:

```
$ cli --help
Usage: cli [OPTIONS]

  First paragraph.

  This is a very long second paragraph and not correctly wrapped but it will
  be rewrapped.

Options:
  --help  Show this message and exit.
```

Usually, CLIs don't have indented paragraphs.

**Comment by jcrotts** [comment]
I actually think the indents make the help more readable. If a lot of people want this we can reevaluate. It should also be possible to patch in yourself.
