### ISSUE TITLE
Example as interactive and option based.

### ISSUE THREAD

**Issue by ghost** [pallets/click#116]
Do you have any examples setting up Click to run as an interactive or prompt driven CLI? Basically, I'm looking to build an interactive CLI which can all be called with one liners including long form options to support other utilities but using the interactive mode when driven by a human. I'm thinking this would work by holding the Click executable open instead of exiting each time waiting for input of the next command, etc. I'm guessing you've already done this and it's just not clear to me in the examples.

**Comment by contactr2m** [comment]
Is there any example of achieving this ? I currently use cmd/cmd2 for interactive shell but it does not handle arguments with spaces etc.. making commands arguments available through click would be better option. 

has anyone implemented it before ?  or any guidance would be appreciated. 
Thank you

**Comment by vimalloc** [comment]
+1

**Comment by vimalloc** [comment]
I've been putting some work into this. I'm sure it will need more work (I'll try and update this if I make changes), but here is an example of how it might be done.


```python
import click
import cmd
import sys

from click import BaseCommand, UsageError


class REPL(cmd.Cmd):
    def __init__(self, ctx):
        cmd.Cmd.__init__(self)
        self.ctx = ctx

    def default(self, line):
        subcommand = line.split()[0]
        args = line.split()[1:]

        subcommand = cli.commands.get(subcommand)
        if subcommand:
            try:
                subcommand.parse_args(self.ctx, args)
                self.ctx.forward(subcommand)
            except UsageError as e:
                print(e.format_message())
        else:
            return cmd.Cmd.default(self, line)


@click.group(invoke_without_command=True)
@click.pass_context
def cli(ctx):
    if ctx.invoked_subcommand is None:
        repl = REPL(ctx)
        repl.cmdloop()


@cli.command()
@click.option('--foo', required=True)
def a(foo):
    print("a")
    print(foo)
    return 'banana'


@cli.command()
@click.option('--foo', required=True)
def b(foo):
    print("b")
    print(foo)

if __name__ == "__main__":
    cli()
```

**Comment by dawran6** [comment]
Not sure when this is added but you can now use [User Input Prompts](http://click.pocoo.org/6/prompts/)
