### ISSUE TITLE
slow response of CLI when installed with setuptools

### ISSUE THREAD

**Issue by leroygr** [pallets/click#1164]
Hi all,

I'm experiencing slow responses of my CLI written with Click 7.9 on Python 3.6.6. 

It takes time to print the help message when calling the CLI when the package has been installed with pip (using setuptools):

```
$ time cli
Usage: cli [OPTIONS] COMMAND [ARGS]...

  Welcome in the CLI!

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

real    0m0,523s
user    0m0,482s
sys     0m0,042s
```
However, I don't get this lag when calling the CLI directly from the source:

```
$ time python myproject/cli.py 
Usage: cli.py [OPTIONS] COMMAND [ARGS]...

  Welcome in the CLI!

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

real    0m0,088s
user    0m0,071s
sys     0m0,016s
```

Here is the content of `myproject/cli.py`:

```
import click

@click.group('cli', invoke_without_command=True)
@click.pass_context
@click.version_option(version='0.0.1', prog_name="test")
def cli(ctx):
    """
    Welcome in the CLI!
    """

    if ctx.invoked_subcommand is None:

        # show help if no option passed to cli
        if all(v==False for v in ctx.params.values()):
            click.echo(ctx.get_help())

if __name__ == '__main__':
    cli()
```

And setup.py is configured like this:
```
setup(
    name=name,
    version=__version__,
    packages=find_packages(),  
    install_requires=install_requires,
    author=author,
    author_email=author_email,
    description=description,
    entry_points='''
        [console_scripts]
        cli=myproject.cli:cli
    ''',
    keywords=keywords,
    cmdclass=cmdclass,
    include_package_data=True,
)
```

Could someone help me with this? This is really inconvenient to get such lag for a CLI.

Thanks,
Greg

**Comment by ThiefMaster** [comment]
Do do you do anything expensive in `myproject/__init__.py` or anything imported from there?

**Comment by leroygr** [comment]
The `myproject/__init__.py`contains a namespace declaration:
`__path__ = __import__('pkgutil').extend_path(__path__, __name__)`

**Comment by ThiefMaster** [comment]
No idea then (even though using namespace packages is usually not a great itea ;))... try running it in a profiler

**Comment by leroygr** [comment]
Any suggestion on how I can profile the `cli` command?

**Comment by ThiefMaster** [comment]
You could simply copy the code from `yourvenv/bin/cli` into a function and run that with the profiler. It's just something like this in there (plus some imports):

    load_entry_point('yourpackage', 'console_scripts', 'cli')()

**Comment by ThiefMaster** [comment]
Closing the issue since it's most likely not a problem in click itself.
