### ISSUE TITLE
Custom Command Level Bash Completion

### ISSUE THREAD

**Issue by altostratous** [pallets/click#1168]
I have reviewed recent change logs and #65. AFAIK click has a hardcoded behavior to get command autocompletion options only based on filtering commands which do not start with what the user has typed. Hence the following case-insensitive use case won't be possible (unless you inject the search function to the bash completion module as a workaround):

```
# Upon pressing double tab after the following
$ click-tool goh
GoHell         GoHere
```
It would be helpful to have something like `autocompletion` option mentioned [here](https://click.palletsprojects.com/en/latest/bashcomplete/#what-it-completes) for Groups as well as options. For example, having a custom search function as a method, or field to be configured for Groups, would be really helpful. 

Also, I am really very motivated to contribute to `click` and will form a PR if you're interested in this feature. 

Regards

**Comment by davidism** [comment]
Completion is being rewritten in #1622.
