### ISSUE TITLE
Feature : make CommandCollection support add_command

### ISSUE THREAD

**Issue by eromoe** [pallets/click#1170]
Hello, 

I want to flat some group command but not all of them. But I found `CommandCollection` didn't support 
them .

```
cli = click.CommandCollection(sources=[etlcli, hdfscli, recommendcli, statcli, mrcli, fixcli])
cli.add_command(dump)
```

got error:

```
AttributeError: 'CommandCollection' object has no attribute 'add_command'
```

**Comment by jcrotts** [comment]
You can still wrap a command as a multi command and use `add_source()` if you need to add a command after you instantiate the object.
I don't think click should add direct support for adding individual commands it seems to contradict the point of the CommandCollection.
http://click.palletsprojects.com/en/7.x/api/#click.CommandCollection
