### ISSUE TITLE
exceptions docs should mention using invoke breaks bash completion

### ISSUE THREAD

**Issue by maxandersen** [pallets/click#1177]
trying to have a central logging of exceptions I followed http://click.palletsprojects.com/en/7.x/exceptions/ using `make_context` and `command.invoke(ctx)` to get full control.

It took me a while to realize that doing that skips all bash autocompletion support;
meaning you must use `command.main` for that.

**Comment by Itisfilipe** [comment]
Hi, can you give us more details about how you are instantiating the `Command` class?  I have been doing some tests and it seems to work with context arguments
```python
import click

@click.command()
@click.argument('myarg')
def cli(myarg):
    return myarg

with cli.make_context('foo', ['something']) as ctx:
    rv = cli.invoke(ctx)
    assert rv is 'something'

```
![test](http://g.recordit.co/XoHcyTcA4M.gif)

and for previously defined auto-complete arguments
```python
import click

def get_colors(ctx, args, incomplete):
    colors = [('red', 'help string for the color red'),
              ('blue', 'help string for the color blue'),
              ('green', 'help string for the color green')]
    return [c for c in colors if incomplete in c[0]]

@click.command()
@click.argument('myarg', autocompletion=get_colors)
def cli(myarg):
    return myarg

with cli.make_context('foo', ['something']) as ctx:
    rv = cli.invoke(ctx)
    assert rv is 'something'
```

![test2](http://g.recordit.co/6ZQTCQz5jQ.gif)
