### ISSUE TITLE
CommandCollection doesn't run the callback from original group

### ISSUE THREAD

**Issue by gordonwrigley** [pallets/click#1179]
We have plugins that export a click group which we pull into our command line by composing them together with a CommandCollection. However some of the plugins do important setup in their group callbacks and the CommandCollection doesn't run those.
We've fixed this by replacing the CommandCollection's callback with the group's callback in get_command. I don't know Click well enough to know if this is right but it makes sense to me.

```
    def get_command(self, ctx, cmd_name):
        for source in self.sources:
            cmd = source.get_command(ctx, cmd_name)
            if cmd is not None:
                self.callback = source.callback
                return cmd
        return None
```

**Comment by jcrotts** [comment]
Closing this, as I think it is a duplicate issue of https://github.com/pallets/click/issues/347 .

Thanks for the work around though, that is helpful. Please reopen if I have misunderstood.
