### ISSUE TITLE
Support contextmanagers in context

### ISSUE THREAD

**Issue by hsharrison** [pallets/click#1184]
It would be nice to have direct support for context managers in context. Right now I'm doing:

    from contextlib import contextmanager

    @contextmanager
    def some_context_manager():
        try:
            # do stuff
            yield
            # do stuff
        finally:
            # do stuff

    

    @click.command()
    @click.pass_context
    def some_command(context):
        context_manager = some_context_manager()
        context_manager.__enter__()
        context.call_on_close(lambda: context_manager.__exit__(None, None, None))
        # Do stuff

But it would be great to have a `contextlib.ExitStack` embedded in click's context so that I could instead do:

    @click.command()
    @click.pass_context
    def some_command(context):
        context.stack.enter_context(some_context_manager())

Any interest in this feature?

**Comment by davidism** [comment]
This should already be possible by subclassing `Context`. I don't think it needs to be integrated with Click at this time.

**Comment by antoine-gallix** [comment]
@davidism Could you please explain how that can be done? Maybe that could end up in the documentation instead of a feature for start. It's not obvious to me how a command can run a subcommand into a context manager.
