### ISSUE TITLE
Add module version to help page

### ISSUE THREAD

**Issue by DahlitzFlorian** [pallets/click#1189]
Click is a great tool for creating command-line interfaces. One downside in my opinion is, that you are not able to customize the auto-generated help page, so that for instance you can add the version of your cli/module/package in the help pages heading. Or is it possible?

Thanks in advance!

**Comment by DahlitzFlorian** [comment]
For all those looking for a solution for a similar issue, I find a work around and published an article explaining how to solve it with sample code. Feel free to read and reuse it. 

The issue itself is still up-to-date, so I won't close the issue.

**Comment by davidism** [comment]
You can use a custom `Command.format_help_text` to inject it. Also related to #561
