### ISSUE TITLE
Slow Bash Start Up

### ISSUE THREAD

**Issue by altostratous** [pallets/click#1203]
## Description
After activating the bash completion in the `/etc/bash.bashrc` the shell start up is slowed down. 
## Cause
The issue is related to our wide python imports which makes the click application slow while responding to the `/etc/bash.bashrc`.
## Proposed Fix
This can be fixed with checking whether the call is a simple completion call with source instruction before importing rest of modules.

**Comment by davidism** [comment]
What is the "rest of the modules"? Most modules are dependent on others, it's unlikely we'd be able to both support completion and not import things.
