### ISSUE TITLE
How I can transfer data from one click command to another command?

### ISSUE THREAD

**Issue by omkarkhatavkar** [pallets/click#1204]
Question: How I can transfer data from one click command to another command?

Example : 
```python

class Config(object):

    def __init__(self):
        self.repo_path = "/test/test_repo/"

pass_config = click.make_pass_decorator(Config, ensure=True)


@cli.command()
@click.option('--clone-path', default="/test/test_repo/",
              help="Pass the path to clone repos to",)
@pass_config
def set_config(config, clone_path):
    config.repo_path = "/tmp/test"


@cli.command()
def show_my_path(config)
    print(config.repo_path)
```

Now when we run show-my-path it will print => "/test/test_repo/" 

My requirement was to print => "/tmp/test"

**Comment by davidism** [comment]
`yourapp set_config /tmp/test` is a completely separate run from `yourapp show_my_path`. You'll need to store your state in a persistent way, such as in a config file.
