### ISSUE TITLE
Supported versions?

### ISSUE THREAD

**Issue by stephenfin** [pallets/click#1210]
What versions of **click** are classed as supported? Is it just the latest (7.x) or is 6.x still supported? `CONTRIBUTING.rst` doesn't provide any information about backporting bugfixes so I'm assuming the former, but I'd like to know before I drop support for click 5.x in https://github.com/click-contrib/sphinx-click

**Comment by davidism** [comment]
7.x is supported. 6.x would receive critical fixes if there was a security issue for example, but generally will not be developed further.

**Comment by stephenfin** [comment]
Excellent. 5.x is unsupported, presumably?

**Comment by davidism** [comment]
Yes, no more commits to 5.x.
