### ISSUE TITLE
Documentation examples make testing hard

### ISSUE THREAD

**Issue by korg** [pallets/click#1214]
Im just looking to try click out but many of the examples dont run because they dont have

```python
if __name__=="__main__": cli()
```

Im just trying to work out if there is a reason for this (other than saving a few lines of doc).

I know this is probably obvious to people using click already but your documentation requires beginners to take example code and add in other lines to make it work. Might it at least be worth making the first example on each page work and adding a comment before the if __name__ line along the lines of "remember to add this...."

In the documentation, first example on page:
https://click.palletsprojects.com/en/7.x/arguments/
https://click.palletsprojects.com/en/7.x/commands/

Other examples...
https://github.com/pallets/click/tree/master/examples/naval
and i know that is because it is intended to be used via setup (as the readme says) but isnt it worth making example code run directly?

**Comment by davidism** [comment]
There are plenty of examples of how to run scripts. I don't want to add this to literally every example in the docs, as that becomes noisy, and it's assumed you already understand how to run the script when you're reading further in the docs. As to the example, I'm fine leaving it as is, as you say it's an example of entry points.
