### ISSUE TITLE
Wrong regexp for click.unstyle()

### ISSUE THREAD

**Issue by asvetlov** [pallets/click#1216]
The function uses `strip_ansi()` which in turn depends on `_ansi_re` regex: https://github.com/pallets/click/blob/master/click/_compat.py#L18

The pattern is: `r'\033\[((?:\d|;)*)([a-zA-Z])'`.
It is a little not full: `\033[?25l` and `\033[?25h` ANSI sequences used by cursor show/hide are not covered by the pattern.

I've changed it to `r'\033\[([;\?0-9]*)([a-zA-Z])'`, it fixes my problem.

**Comment by sekenned** [comment]
Yup.  
```
>>> import re
>>>
>>> # https://github.com/pallets/click/blob/master/click/_compat.py#L18
... _ansi_re = re.compile(r'\033\[((?:\d|;)*)([a-zA-Z])')
>>>
>>> # https://github.com/pallets/click/blob/master/click/_compat.py#L569
... def strip_ansi(value):
...     return _ansi_re.sub('', value)
...
>>> test_string = "\033[?25leggs and spam\033[?25h"
>>> strip_ansi(test_string)
'\x1b[?25leggs and spam\x1b[?25h'
>>>
>>> # suggested update
... _ansi_re = re.compile(r'\033\[([;\?0-9]*)([a-zA-Z])')
>>> strip_ansi(test_string)
'eggs and spam'
>>>
```
Will submit PR.

**Comment by sekenned** [comment]
https://github.com/pallets/click/pull/1297
