### ISSUE TITLE
How to refer to the script name in doc text ? 

### ISSUE THREAD

**Issue by maxandersen** [pallets/click#1223]
the script name is calculated dynamically for -h, so I was wondering how to refer to that dynamic script name in doc strings ?

ie. instead of having to write "This script does x" is there a way to do something like "{script} does x" ?

This is mainly to be able to write something like the following in doc strings:

"""List areas.
      The NAME parameter works like a filter that is used to find all areas that contain that name.

      Examples:
           $ {script} area list "Kitchen" # all areas with the substring Kitchen
           $ {script} area list "Kitchen.*Light" # all areas that matches the regular expression.
"""

**Comment by davidism** [comment]
I think the only thing that's dynamic is whether it's `command` or `python -m command`. My suggestion would be to just assume `command` for the docs.

This would be solved by #561, the project could override the formatter to allow variable replacement.

**Comment by davidism** [comment]
You can also override `Command.format_help_text` to inject it.
