### ISSUE TITLE
Click doesn't respect argument types

### ISSUE THREAD

**Issue by SoniEx2** [pallets/click#1224]
With this program:

```python
import click

class Frequency(click.ParamType):
    name = 'frequency'
    def convert(self, value, param, ctx):
        try:
            f = float(value)
            if 0.0 < f < 20000.0:
                return lambda sth: setattr(sth.st, 'freq', f)
            else:
                raise ValueError
        except ValueError:
            self.fail('%s is not a valid frequency' % value, param, ctx)

FREQUENCY = Frequency()

@click.command()
@click.option("-f", "ops", type=FREQUENCY, multiple=True)
@click.option("-n", "--new", "ops", flag_value=lambda sth: 0, multiple=True)
def foo(ops):
    for op in ops:
        print(op, type(op))

if __name__ == "__main__":
    foo()
```

calling it as `./foo -f 1` should print something along the lines of:

    <function Frequency.convert.<locals>.<lambda> at 0x7f339643bc80> <class 'function'>

but instead prints something along the lines of:

    1 <class 'str'>

**Comment by davidism** [comment]
You named both the options `"ops"`. The parser sees `-f` and adds the raw value under `"ops"`. The parser doesn't see `-n`, so it doesn't set the raw value to `flag_value`. The opts are converted in order. The first option sees the raw value and stores the expected processed value. The second option, which is a `String` type, sees the same raw value and overwrites the stored processed value.

I'm not entirely clear what you're trying to do with that code, but there's probably a more appropriate construct or processing you can do. Perhaps a different command for new, or something from #257 for a mutually exclusive option.

**Comment by SoniEx2** [comment]
So you mean everything should be the same `type=` and I should change what I return based on `param`? I wanna be able to do `./foo -f 1 -n -f 2 -n -f 3` and so on, like the `beep` command.

I thought each @option had its own type, not each... thingy in `def foo([here]):` with its own type. This is not clearly documented and the issue should be kept open until it's either clearly documented or changed.
