### ISSUE TITLE
Print command hierarchy? 

### ISSUE THREAD

**Issue by schollii** [pallets/click#1227]
Is there already a helper function to print the command hierarchy? For example `print(main)` would show
```
Group1
   Group2
       Cmd1
       Cmd2
   Group3
       Cmd3
       Cmd4
```
Seems this would be relatively straightforward via the `Group.commands` which enables to traverse the hierarchy, but I was wondering if this already exists so I don't reinvent the wheel.

**Comment by whwright** [comment]
I totally wrote a plugin to do this thing this weekend! Hopefully you find it helpful.

https://github.com/whwright/click-command-tree

**Comment by schollii** [comment]
Good to know. FWIW I just added this directly in my code: 
```
def _print_cmd_tree(ctx, cmd, spacer=2*' ', indent=0):
    try:
        sub_commands = sorted(cmd.commands)
    except AttributeError:
        return

    for sub_cmd_name in sub_commands:
        print(indent*spacer + sub_cmd_name)
        sub_cmd = cmd.get_command(ctx, sub_cmd_name)
        _print_cmd_tree(ctx, sub_cmd, spacer=spacer, indent=indent + 1)


@main.command()
@click.pass_context
def cmd_hierarchy(ctx):
    _print_cmd_tree(ctx, main)
```
