### ISSUE TITLE
bash completion replaces underscores with dashes

### ISSUE THREAD

**Issue by noqqe** [pallets/click#1235]
Hi,

since I've upgraded to click 7.0 the bash completion replaces underscores (_) in command names with dashes (-)

```
@click.command(short_help="Delete a group")
@click.option("groupname", '-g', '--group', type=str, required=True)
@click.option("--yes", is_flag=True, default=False)
@click.pass_context
def delete_group(ctx, yes, groupname):
    """
    Deletes a group identified by its short ID
```

the help message it looks like this:

```
Options:
  --version                   Show the version and exit.
  -e, --env [prod|stage|dev]  Choose environment to execute commands
  -h, --help                  Show this message and exit.

Commands:
  create_project          Creates a new project
  delete_group            Delete a group
  [...]
```

Gif example here:
![feb-19-2019 10-47-51](https://user-images.githubusercontent.com/203902/53005579-d8653a80-3433-11e9-91a9-f0865c3c0b17.gif)

**Comment by ThiefMaster** [comment]
Click 7 uses dashes instead of underscores in command names (which is actually more common in CLIs). See #1123
