### ISSUE TITLE
Avoid duplicating argument code used by multiple subcommands

### ISSUE THREAD

**Issue by ekallevig** [pallets/click#1237]
I have a group of subcommands that all operate on a list of URLs that can optionally be passed as an argument. How can I assign this argument to the group instead to avoid duplicating the argument definition on every subcommand?

Current code:
```
from config import site_list

@click.group()
def cli():
    pass

@cli.command()
@cli.argument('sites', nargs=-1)
def subcommand_one():
    if sites:
        site_list = sites
    etc...
    
@cli.command()
@cli.argument('sites', nargs=-1)
def subcommand_two():
    if sites:
        site_list = sites
    etc...
```
Example invocation:
```
$ python sites.py subcommand_one www.example.com www.example2.com
```
I tried moving the argument decorator to the group like this:

```
@click.group()
@click.argument('sites', nargs=-1)
def cli(sites):
    if sites:
        site_list = sites
    pass
```
But then I would get this error: 
```
$ python sites.py subcommand_one
Usage: sites.py [OPTIONS] [SITES] COMMAND [ARGS]...
Try "sites.py --help" for help.

Error: Missing command.
```

**Comment by jcrotts** [comment]
Good question.
I think this has been answered before, see this https://github.com/pallets/click/issues/108 for the relevant discussion.

Here is a somewhat related SO post.
https://stackoverflow.com/questions/44158287/adding-common-parameters-to-groups-with-click

If i misunderstood what you were asking for please feel free to continue the discussion.
