### ISSUE TITLE
setuptools integration using "Scripts in Packages" example - not working

### ISSUE THREAD

**Issue by be-rock** [pallets/click#1239]
I am following the setuptools example using a python3.7.1 conda virtual env from the documentation [here](https://click.palletsprojects.com/en/7.x/setuptools/) and continue to receive an error:

`ModuleNotFoundError: No module named 'yourpackage.scripts'`

```
yourpackage/
├── __init__.py
├── main.py
├── scripts
│   ├── __init__.py
│   └── yourscript.py
├── setup.py
└── utils.py
```
```
#scripts/yourscript.py

import click

@click.command()
def cli():
    """Example script."""
    click.echo('Hello World!')
```

```
# setup.py

from setuptools import setup, find_packages
setup(
    name='yourpackage',
    version='0.1',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'Click',
    ],
    entry_points='''
        [console_scripts]
        yourscript=yourpackage.scripts.yourscript:cli
    ''',
)
```

```
$ pip install -e .
Looking in indexes: https://InternalArtifactoryUrl
Obtaining file:///private/tmp/yourpackage
Requirement already satisfied: Click in /Users/myusername/miniconda3/envs/test_20190220/lib/python3.7/site-packages (from yourpackage==0.1) (7.0)
Installing collected packages: yourpackage
  Found existing installation: yourpackage 0.1
    Uninstalling yourpackage-0.1:
      Successfully uninstalled yourpackage-0.1
  Running setup.py develop for yourpackage
Successfully installed yourpackage

$ which yourscript
/Users/myusername/miniconda3/envs/test_20190220/bin/yourscript

$ yourscript
Traceback (most recent call last):
  File "/Users/myusername/miniconda3/envs/test_20190220/bin/yourscript", line 11, in <module>
    load_entry_point('yourpackage', 'console_scripts', 'yourscript')()
  File "/Users/myusername/miniconda3/envs/test_20190220/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/myusername/miniconda3/envs/test_20190220/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Users/myusername/miniconda3/envs/test_20190220/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Users/myusername/miniconda3/envs/test_20190220/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'yourpackage.scripts'
```

I also tried:
`export PYTHONPATH=/tmp/yourpackage/`
and continue to receive the error when running `yourscript`

**UPDATE**
The workaround was simply:
`export PYTHONPATH=/tmp/yourpackage/`

Is it possible to update the documentation to make it clearer to newcomers such as myself?

Thanks!

**Comment by bittner** [comment]
I've [verified the documentation](https://github.com/pallets/click/blob/master/docs/setuptools.rst#scripts-in-packages), and I think the mistake is on your side (sorry!).

You're placing `setup.py` inside your package folder. The docs don't suggest that. By convention, it's in fact always placed outside of it.

Do you think `setup.py` should also be shown in the "directory tree" example in the docs you mention? That would maybe make things easier to do it the "copy & paste" way for setuptools beginners.

**Comment by davidism** [comment]
I guess it's implied that you would put project data like `setup.py` at the project level, not inside the project.

```
project/
    setup.py
    package/
        __init__.py
```

**Comment by bittner** [comment]
I'll add that to the docs in the directory listing. Maybe it's not automatically clear for someone working with setuptools for the first time. -- No big deal.

**Comment by bittner** [comment]
Thanks, @be-rock, for reporting the issue! Do [the docs](https://click.palletsprojects.com/en/master/setuptools/#scripts-in-packages) make things clearer for you now?

**Comment by be-rock** [comment]
Yes, very much so @bittner.  Thanks!  And yes I am new to setuptools so appreciate the extra bit of clarification.
