### ISSUE TITLE
Document that default should be a tuple when used with the multiple flag

### ISSUE THREAD

**Issue by dazza-codes** [pallets/click#1246]
If a choice option also allows multiple values, the default value is split into single chars and no longer matches one of the choices.

The desired behavior is to specify multiple format options and have each one of them validated against the choice options available.  The default value can be one of the choice options.

### choice option allows multiple values, with a default
```
@click.option('--format',
              default='one',
              multiple=True,
              show_default=True,
              type=click.Choice(["one", "two"]),
```

### error
```
Error: Invalid value for "--format": invalid choice: o. (choose from one, two)
```

**Comment by darrenleeweber** [comment]
The documentation on this combination of options could be improved with an explicit note that a default value needs to be a tuple or a list, e.g. `default=('one',)` works.

**Comment by NargiT** [comment]
With `prompt=True` this is does not work with 7.0
```
@click.option('--environments', 
   prompt=True, 
   type=click.Choice(['prod','stg','dev']),
   show_default=True,
   multiple=True,
   default=('prod'))
```

### Error
> Environments (prod, stg, dev): [('prod',)]: prod
> Error: invalid choice: p. (choose from prod, stg, dev)
> Environments (prod, stg, dev): [('prod',)]: ('prod',stg)
> Error: invalid choice: (. (choose from prod, stg, dev)

**Comment by darrenleeweber** [comment]
@NargiT - maybe it works with `default=('prod', )` (note the added comma)

**Comment by NargiT** [comment]
Actually my example has an error so I had the comma in the running code. The prompt does not work if I want to change the default, pressing enter without changing works.

**Comment by jcrotts** [comment]
Thanks for reporting the bug @NargiT, I'm going to make a new issue for this, since this issue is about a doc improvement.

**Comment by bporter125** [comment]
I'll add some notes to the options doc for this.

**Comment by bporter125** [comment]
https://github.com/pallets/click/pull/1308
