### ISSUE TITLE
Bash completion understands options even after "--"

### ISSUE THREAD

**Issue by bertolinocastro** [pallets/click#1247]
Click Bash Completion prints out `command`'s options for any string starting with a single dash even after the double dash separator.

I'm facing this problem because I'm trying to create a wrapper with Click and I would like to use Click's auto completion to print out options from my wrapped program.

So, supposing that I'm wrapping `git` and my program is called `logbuch`, my command line would be something like:
```sh
logbuch -g -- commit -<TAB>
```

Supposing I'm doing some workaround in-code to get the `git commit`'s options, I'm returning that as a list of strings from a callback to my `command` `argument` `autocompletion` param. Like this:
```sh
@click.argument('arg',nargs=-1,type=click.STRING,autocompletion=auto_comp_callback)
```

Is there any way to prevent Click from completing my `program`'s options instead of calling my `callback`? I have read this [code](https://github.com/pallets/click/blob/master/click/_bashcomplete.py#L246) and it sounds like that Click does not check for double dashes before calling the `start_of_option` at line 246.

Besides that, I think that this issue goes in opposite way to this statement at [Click docs](https://click.palletsprojects.com/en/7.x/arguments/#option-like-arguments): " After the `--` marker, all further parameters are accepted as arguments."

I'm using `python3.7` with Click installed by `python3.7 -m pip install click`.

**Comment by bertolinocastro** [comment]
I have commited a fix for this issue on my (Click fork)[https://github.com/bertolinocastro/click/commit/55fcf198118d683163dc07265ba0cdfde5c57ff7]. I'm not doing a pull request since I'm not envolved with Click's development and you guys will certainly do a better fix.

**Comment by davidism** [comment]
Please make a PR here. Plenty of community members make PRs, otherwise nothing would ever get fixed.

**Comment by bertolinocastro** [comment]
I just did that. Please, tell me if I need to do anything else.
