### ISSUE TITLE
subcommand_metavar modifies help only partially

### ISSUE THREAD

**Issue by xarx00** [pallets/click#1249]
### Brief description

After renaming the COMMAND parameter in the usage string, the "Commands" section of the help is not renamed.

### Example

The following script customizes `subcommand_metavar`:
```python
import click

@click.group()
def cli(**kwargs):
    pass
cli.subcommand_metavar = "OBJECT [ARGS]..."

@cli.command()
def obj1(**kwargs):
    pass

if __name__ == '__main__':
    cli()
```
It's help output looks like this:

> Usage: test.py [OPTIONS] **OBJECT** [ARGS]...
> 
> Options:
>   --help  Show this message and exit.
> 
> **Commands**:
>   obj1
> 

But there seems to be no way to change the "Commands" section name to "Objects" without overriding the `click.MultiCommand.format_commands()` method.

### Possible solution

I suggest introduction of a property similar to "subcommand_metavar", say **"subcommands_section_name"**, that would contain the section name.

### Click version

I use Click 6.4.0, but the problem hasn't been fixed till version 7.

**Comment by jcrotts** [comment]
This is fixes in version 7.X, click 6 is only receiving security bug fixes at this point.
