### ISSUE TITLE
open_file(..., 'x', atomic=True) error is misleading

### ISSUE THREAD

**Issue by gmacon** [pallets/click#1250]
When using `open_file(path, 'x', atomic=True)`, the exception error message mentions the non-existent "overwrite" parameter. It looks like this message was copied from python-atomicwrites. Perhaps it should change to recommend that package instead?

* Click 7.0
* Python 3.7.2

**Comment by davidism** [comment]
Is this issue asking for the message to be changed or to move to a different library?

**Comment by gmacon** [comment]
I'm asking for the message to be changed to recommend that programmers who use that combination move to another library.

**Comment by davidism** [comment]
Duplicate of #320
