### ISSUE TITLE
Choice - dropdown list instead of all comma separated values in one line

### ISSUE THREAD

**Issue by Constantin07** [pallets/click#1251]
Hi All,

This is more a question.
I'm using a choice prompt with a list of values which are quite long (each value is more than 30 characters in length).

```python
esclation_policy = click.prompt('Please choose the escalation policy',
                                    type=click.Choice(esclation_policy_list),
                                    default='Default Team')
```

I would like to print each value on a separate line but by default they are printed comma separated until line wraps - which is very unreadable.

Is there any way to achieve the below ?
```
Please choose the escalation policy:
value1
value2
value3
...
valueN
```
instead of:
```
Please choose the escalation policy(value1, value2, value3, ..., valueN)
```

PS: I couldn't find in documentation support for this.

Thanks & Regards,
Constantin

**Comment by pwlandoll** [comment]
It looks like the prompt is built here: https://github.com/pallets/click/blob/c6042bf2607c5be22b1efef2e42a94ffd281434c/click/termui.py#L49

The comma-separated list looks to be hard-coded if you're using `type=click.Choice()`.

**Comment by Constantin07** [comment]
Thanks @pwlandoll for looking into this. Do you know if there is simple way to override this behavior without modifying source code ?

**Comment by pwlandoll** [comment]
You could abuse the `prompt_suffix` argument in the `prompt` method:
```
prompt_suffix = "\n".join(choice_list)
# This could be done without f-strings as well
choice = click.prompt("Choose:\n", prompt_suffix=f"{prompt_suffix}\n> ")
```
This produces:
```
$ ./test.py
Choose:
option0
option1
option2
option3
option4
> 
```
However this will not automatically validate the input against the list of choices, so I don't recommend this.

**Comment by jcrotts** [comment]
You could monkey patch ```_build_prompt``` to get the behavior you want.

```python
import os
import click
from click import Choice

def _build_prompt(text, suffix, show_default=False, default=None, show_choices=True, type=None):
    prompt = text + ":"
    if type is not None and show_choices and isinstance(type, Choice):
        prompt += "\n"
        prompt += "\n".join(map(str, type.choices))
    if default is not None and show_default:
        prompt = '%s [%s]' % (prompt, default)
    return prompt + "\n" + ">"

click.termui._build_prompt = _build_prompt

escalation_policy_list = ["value1", "value2", "value3"]

esclation_policy = click.prompt('Please choose the escalation policy',
                                type=click.Choice(escalation_policy_list))
```

You would also need to subclass or patch Choice to change the behavior of the invalid choice error message.

I believe this is the part you would need to override.
https://github.com/pallets/click/blob/2c622eed402c64e1645db3904c2410f6c05fbf19/click/types.py#L129

Feel free to continue the discussion, however I am going to close this issue because it isn't a bug/ isn't related to improving Click.

**Comment by davidism** [comment]
This might become possible with #938.
