### ISSUE TITLE
Not exactly about click

### ISSUE THREAD

**Issue by shadowrylander** [pallets/click#1252]
Hello! <br>
&nbsp;&nbsp;&nbsp;&nbsp; I apologize for disturbing you like this, however, would it be possible to tell me how you managed to get your function to be declared with arguments, but then not pass any in while calling them, as in your examples? <br>
```
import click

@click.command()
@click.option('--count', default=1, help='Number of greetings.')
@click.option('--name', prompt='Your name',
              help='The person to greet.')

###############################################################
# Defined here with arguments

def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for x in range(count):
        click.echo('Hello %s!' % name)
###############################################################

if __name__ == '__main__':

###############################################################
    # Called here with none!

    hello()
###############################################################

```
&nbsp;&nbsp;&nbsp;&nbsp; I would normally Google this, but I can't seem to come up with the correct search query! <br>
Thank you kindly for understanding! <br>

**Comment by davidism** [comment]
Because decorators aren't required to return the same thing they decorate. In this case they return a command object that wraps the function.

**Comment by shadowrylander** [comment]
Hmm... I'll have to do more research, it seems, then. Thank you!
