### ISSUE TITLE
make nargs optional 

### ISSUE THREAD

**Issue by hemanta212** [pallets/click#1254]
I want something like this:

@click.option('--add' , nargs=2, help= 'add key and value pair to a dict. If only key given, then return its value')
def cli(add):
   
    if add and len(add) == 2:
        pass
    if add:
        key = add[0]
        return my_dict[key]

However I can't seem to call this add option without specifying both args.
I want to either pass one or 2 args to add option.
Am i missing something?

**Comment by davidism** [comment]
https://click.palletsprojects.com/en/7.x/options/#multi-value-options

> Sometimes, you have options that take more than one argument. For options, only a fixed number of arguments is supported. This can be configured by the nargs parameter. The values are then stored as a tuple.

You want two options, `-k` and `-v`, or two commands, `get` and `set`.
