### ISSUE TITLE
no_args_is_help for Command: documentation vs code is wrong

### ISSUE THREAD

**Issue by ericnchen** [pallets/click#1259]
I am using Python 3.7 and have Click 7.0 installed via `pip install click`.

In the current [API documentation](https://click.palletsprojects.com/en/7.x/api/) the documentation for the `command` decorator says the following:

> Creates a new `Command` and uses the decorated function as callback. This will also automatically attach all decorated `option()`s and `argument()`s as parameters to the command.
> ...
> **All keyword arguments are forwarded to the underlying command class.**

This is my first time using click, so when I click on the link to get the `Command` class documentation, it tells me it has this option:

> `no_args_is_help` – this controls what happens if no arguments are provided. This option is disabled by default. If enabled this will add --help as argument if no arguments are passed

However when I try to add this as an option to the `command` decorator I get an error:

> `TypeError: __init__() got an unexpected keyword argument 'no_args_is_help'`

Looking into the code in `decorators` and `core` it is apparent that this error is because `Command` doesn't actually have the `no_args_is_help` argument, only `MultiCommand` does.

Why is there such a big discrepancy between the documentation and the actual implementation? I see that there are other issues here about this same option, but they are all either merged or closed as far as I can tell. As a new user this is extremely frustrating because I'm trying to 'rtfm' but that doesn't work when the manual is wrong.

**Comment by pwlandoll** [comment]
From [the changelog](https://click.palletsprojects.com/en/7.x/changelog/#version-7-1) for 7.1:
> Add no_args_is_help option to click.Command, defaults to False (#1167)

It looks like the docs may have been built from unreleased changes intended for 7.1.

**Comment by davidism** [comment]
This is why PRs need to have `.. versionadded` or `.. versionchanged` markers in the docs as well as a changelog entry.

**Comment by pwlandoll** [comment]
@ericnchen Thanks for pointing this out, I'm sure if there are other spots where the docs differ from the code (unlikely in my experience), the maintainers would be glad to hear about it.

@davidism I can put together a PR to fix this, I'll put 7.1 as `.. versionadded`. Would it also be worth expanding the contribution guidelines to detail some of these best practices?

**Comment by pwlandoll** [comment]
#1260 is merged, which fixed the documentation, and #1263 is open for adding to the contribution guidelines. I think this can be closed.
