### ISSUE TITLE
Cannot require 1 or more arguments with nargs

### ISSUE THREAD

**Issue by pombredanne** [pallets/click#1265]
If I set an argument with `nargs=-1` I accept zero or more arguments. I would like to accept 1 or more argument instead. I can do this alright with validation, but it would be nice to also support this in the declaration

**Comment by tucked** [comment]
Relevant: https://click.palletsprojects.com/en/7.x/arguments/#variadic-arguments

> ### Note on Non-Empty Variadic Arguments:
> If you come from `argparse`, you might be missing support for setting `nargs` to `+` to indicate that at least one argument is required.
>
> This is supported by setting `required=True`. However, this should not be used if you can avoid it as we believe scripts should gracefully degrade into becoming noops if a variadic argument is empty. The reason for this is that very often, scripts are invoked with wildcard inputs from the command line and they should not error out if the wildcard is empty.
