### ISSUE TITLE
Friendly __repr__ for Command

### ISSUE THREAD

**Issue by twosigmajab** [pallets/click#1267]
```python
(Pdb) pp cmd
<click.core.Command object at 0x7ff869ef1550>
(Pdb) pp cmd.name
'run-gunicorn'
```
What do you think of showing the command name in the `__repr__` string, for friendlier debugging? Could be a good beginner-friendly issue!

**Comment by jzengg** [comment]
I'm going to take a stab at this

**Comment by twosigmajab** [comment]
Thanks for fixing this, @jzengg!
