### ISSUE TITLE
When I use del as the function name, I will report a syntax error. The other names are correct.

### ISSUE THREAD

**Issue by kathr1ne** [pallets/click#1276]
[root@vm01 cli]# ./testgroup.py 
  File "./testgroup.py", line 16
    def del():
          ^
SyntaxError: invalid syntax

```
import click

@click.group()
def cli():
    pass

@cli.command()
def add():
    click.echo('add')

@cli.command()
def del():
    click.echo('del')

if __name__ == '__main__':
    cli()

```

**Comment by davidism** [comment]
This is not related to Click, it would happen with any Python program. https://docs.python.org/3/reference/lexical_analysis.html#keywords

**Comment by kathr1ne** [comment]
> This is not related to Click, it would happen with any Python program. https://docs.python.org/3/reference/lexical_analysis.html#keywords

I understand and thank you very much. I should read more documents.

**Comment by davidism** [comment]
To be clear, while `del` is a reserved word in Python and can't be used as a function name, you can use it as a command name:

```python
@click.command("del")
def del_command():
    ...
```

**Comment by kathr1ne** [comment]
> To be clear, while `del` is a reserved word in Python and can't be used as a function name, you can use it as a command name:
> 
> ```python
> @click.command("del")
> def del_command():
>     ...
> ```

Thanks. This is exactly what I want
