### ISSUE TITLE
Hotfix release needed on PyPI to replace Click-7.0

### ISSUE THREAD

**Issue by zvezdan** [pallets/click#1284]
Can someone please release a hotfix release of click-7.0.1 (notice *lowercase*) to replace the unexpected release of (uppercase) Click-7.0 on PyPI?

This name change causes issues in some build environments where during the dependency resolution click-6.7 and Click-7.0 are not treated as the same package with different versions.

Releasing click-7.0.1 with just a name-change revert would help in such environments.
I'm referring to this commit: https://github.com/pallets/click/commit/0d95fb0d234d2bfe0a29f673399b72b4b42e1fb2

**Comment by davidism** [comment]
I'm currently headed to pycon, this will probably happen during the sprints.

**Comment by zvezdan** [comment]
I'm also at PyCon.

Since this is still not done, can we please leave it open until it's actually completed? The "... probably happen ..." part does not sound like a full commitment.

**Comment by davidism** [comment]
I do not generally keep these open as they are not something I can commit to and they don't help a release happen any faster.
