### ISSUE TITLE
option with bool type

### ISSUE THREAD

**Issue by Cologler** [pallets/click#1287]
``` py
@click.command()
@click.option('--shout/--no-shout', default=False)
def info(shout):
    pass

info()
```

is ok, but

``` py
@click.command()
@click.option('--shout/--no-shout', default=False, type=bool)
def info(shout):
    pass

info()
```

will raise a TypeError: Got secondary option for non boolean flag.

**Comment by jab** [comment]
you need to use `click.BOOL` instead of `bool`, as per the docs:
https://click.palletsprojects.com/en/7.x/parameters/#parameter-types

**Comment by jab** [comment]
Oops, that's not right, sorry, deleting and will hopefully post a sensible response momentarily.

**Comment by jab** [comment]
I've tracked this down to
https://github.com/pallets/click/blob/c6042bf2607c5be22b1efef2e42a94ffd281434c/click/core.py#L1573
in this case `type` is not `None`, it's `bool`, so the condition is failing and `self.is_bool_flag` incorrectly gets set to `False`.

I can't immediately see why this is there (it just looks wrong at first glance). But [blame](https://github.com/pallets/click/blame/master/click/core.py#L1573) says that line of code is 5 years old, which suggests there's more to it...

**Comment by Cologler** [comment]
I am working on a click helper library (https://github.com/Cologler/click-anno-python), so I was did a lot of tests for click.

**Comment by davidism** [comment]
I think this is there because the `--no-` option makes this a special type of boolean flag automatically, it wouldn't make sense to assign a type to it. I guess we could check if type is none or bool.

**Comment by jab** [comment]
Huh, I’d have thought it made sense if using the `/--no-` spelling *implied* `type=bool`, so you didn’t have to add that explicitly, but if you did, it would mean the same thing.

**Comment by Ketzalkotal** [comment]
Taking a look at this

**Comment by Ketzalkotal** [comment]
Checked the Discord, it looks like KP has got it

**Comment by xingheng** [comment]
Same here. `type=click.BOOL` repros this bug, too. Temporarily remove the type and resolved.

**Comment by Xevion** [comment]
The `type` argument only supports `bool` and not `click.BOOL`, should this be changed to support both?

https://github.com/kporangehat/click/blob/c7bd8d47b44816c2999a12a0b4e52162e5c6994a/click/core.py#L1609
