### ISSUE TITLE
With `prompt=True` does not work with `click.Choice` and `multiple=True`

### ISSUE THREAD

**Issue by jcrotts** [pallets/click#1289]
With `prompt=True` this does not work with 7.0
```
@click.option('--environments', 
   prompt=True, 
   type=click.Choice(['prod','stg','dev']),
   show_default=True,
   multiple=True,
   default=('prod'))
```

### Error
> Environments (prod, stg, dev): [('prod',)]: stg
> Error: invalid choice: p. (choose from prod, stg, dev)
> Environments (prod, stg, dev): [('prod',)]: ('stg',)
> Error: invalid choice: (. (choose from prod, stg, dev)

_Originally posted by @NargiT in https://github.com/pallets/click/issues/1246#issuecomment-488970315_

**Comment by VictoryChang** [comment]
Taking a look at this issue

**Comment by VictoryChang** [comment]
It looks like a similar discussion was done in 2014 and 2016 and there is no explicit support for 
Option(prompt=True, multiple=True) today. Do we want to have this functionality supported, parsing the prompted value via a character like a whitespace?
2014 [closed with no follow up]: https://github.com/pallets/click/issues/218
2016 [closed with note]: Disallowed unless this will be properly implemented: https://github.com/pallets/click/issues/532

**Comment by jcrotts** [comment]
Nice in that case I think a docs change advising against it would be appropriate.

**Comment by jcrotts** [comment]
Going to close this because, it is actually a duplicate of #532
