### ISSUE TITLE
Spelling of click changed in release version 7.0

### ISSUE THREAD

**Issue by stwa** [pallets/click#1319]
With release version 7.0 the spelling of click changed to use an uppercase C, see:
https://github.com/pallets/click/commit/e8bf968c8f26231d7c2a6d04ac83c81199bb607f#diff-2eeaed663bd0d25b7e608891384b7298L18

These change seems to be inconsistent with publications on https://pypi.org.

While the package name still seems to be lowercase, the uploaded archives are uppercase:
https://pypi.org/project/click/#files

As an example of a package with an uppercase first letter see Werkzeug.
Even accessing https://pypi.org/project/werkzeug/ redirects to https://pypi.org/project/Werkzeug/ and getting the JSON from pypi (https://pypi.org/pypi/Werkzeug/json) gives the package name `Werkzeug` under `.info.name`. That's not the case with click (anymore).

I know this sounds like nitpicking, but this makes it really hard to guess the archive names automatically.

**Comment by davidism** [comment]
Yeah, this was my bad when I was updating the metadata for all the projects. It was changed back in master, it will be part of 7.1 when that's released.
