### ISSUE TITLE
Revert Click 6 regressions for chain and deprecate chain

### ISSUE THREAD

**Issue by mitsuhiko** [pallets/click#1323]
With Click 6.0 we landed a change that was supposed to fix chain (https://github.com/pallets/click/commit/0a2919f34fcbc635d8530b4c5b60bf119b2bcedb). In the process it got worse and broke a bunch of non chain uses.

We should back out that change and instead deprecate chain. I do not believe there is a way to make chain work with the current argument parsing and execution behavior.

The reason for this is that click really wants to delegate the parsing of subcommands with the remainder of the command line but this breaks in the light of chaining. I would need to look into the exact implementation again but last time I investigated this it looked like a fundamental issue we cannot fix with the current design.

**Comment by direnter** [comment]
Is there a way to replicate `chain` functionality using traditional Click methods?

**Comment by jtrakk** [comment]
At least in 2015 [an expert thought](https://github.com/pallets/click/blame/c16ff82166736748407c2fb00d4de34abc1a10ee/docs/commands.rst#L330) it was fixable :-)

> It is currently not possible for chain commands to be nested.  This will be fixed in future versions of Click.

**Comment by davidism** [comment]
@jcrotts did some research and determined that the changes from 6 were already reverted and released in 6.1. After looking over the issues again, we've decided not to remove chain. Putting aside the broad issue of possibly rewriting the parser or pipeline, the open issues appear to be solvable, so we'll continue to address them for now.
