### ISSUE TITLE
Include docstring in missing argument error for MultiCommands

### ISSUE THREAD

**Issue by cyeb** [pallets/click#133]
Sample code:

```
import click

@click.group()
def main():
    pass

@main.command()
@click.argument('arg1', nargs=1)
def remove(arg1):
    '''
    Removes arg1.
    '''
    click.echo("Removing %s" % arg1)

if __name__ == '__main__':
    main()
```

Would like this output:

```
Usage: asdf.py remove [OPTIONS] ARG1

  Removes arg1.

Options:
  --help  Show this message and exit.
```

Not this output:

```
Usage: asdf.py remove [OPTIONS] ARG1

Error: Missing argument "arg1".
```

---- more verbose description of problem, if needed ----
Doing something like:

> python my_code.py remove            # missing argument after 'remove'

Prints usage instructions and `Error: Missing argument "..."`, but not the docstring specifying how to use the command 'remove'. To me, it makes more sense for the default behavior to include the docstring specifying how the function should be used for the missing argument error (the text that pops up for "python my_code.py remove --help"). This is the way Git functions.

**Comment by saad-cliqr** [comment]
:+1:

**Comment by izakp** [comment]
This prompt causes some confusion when there are required options for a command.  Would like it if the full output of `--help` could be configured to display, perhaps by a flag to the `@command(context_settings={})` dict

**Comment by gitlines** [comment]
I would also love to see not just an error message, but the help page or a reference of how to get to the help page.

If I do not use arguments (e.i. only commands and options) in my click program code and simply type the name of the cli tool I get the help page. However, if an argument is included in my code only the error is shown.

**Comment by awfki** [comment]
I'd like this as well. Either show full help on missing argument or at least include something like "Use the --help option for more information.".

Another option would be to allowing adding help to arguments that could provide additional information for the error message.

**Comment by davidism** [comment]
Decision made to keep current "see --help" message in #502.
