### ISSUE TITLE
Adding option 'sort' to choice

### ISSUE THREAD

**Issue by Igorjan94** [pallets/click#1337]
What about adding sort option to choice?  
Sometimes it's better to have choices in original order (e.g. python sorts russian words in wrong order)   
https://github.com/pallets/click/blob/f537a208591088499b388b06b2aca4efd5445119/click/_bashcomplete.py#L265

**Comment by makrandr1999** [comment]
I'd love to work on this issue.

**Comment by leshnabalara** [comment]
I'd like to take this up!

**Comment by leshnabalara** [comment]
Running the program yourscript.py 
```
import click

@click.command()
@click.option('--completion',
              type=click.Choice(['AAA', 'ACA', 'ABA'], case_sensitive=False))
def cli(completion):
    click.echo(completion)
```

pressing TAB after writing 
```
yourscript --completion=A
```
results in 
```
AAA  ACA  ABA  
```

click version: 7.1.2
Thus this gives the expected behaviour without sorting the Choice

**Comment by davidism** [comment]
Yep, looks like the new completion system took care of this.
