### ISSUE TITLE
Ability to disable showing the help-documentation for ZSH completions.

### ISSUE THREAD

**Issue by Yhoorneman** [pallets/click#1341]
I'm working on a CLI tool and the tab-completion is perfect when using the Bash shell. Using the ZSH shell gives a different format because it shows the documentation based on the help parameters of options and subcommands

Is there a way of getting the same format for both shells? I was not able to find a way in the documentation.

**Comment by davidism** [comment]
Probably something you'd configure in ZSH. I don't really want to add more configuration for this, it's complicated enough as it is.

**Comment by Yhoorneman** [comment]
@davidism Thank you for responding so quickly. Just to confirm, you are saying it makes sense I didn't find any documentation, because this isn't available.

**Comment by davidism** [comment]
Going to close this as I don't plan on adding configuration to the completions provided by Click. Perhaps click-completion offers this? You can always write your own shell completion source, the one provided by Click is just a starting point, and will probably never be as good as a hand written one for these types of cases.
