### ISSUE TITLE
Complex argument processing

### ISSUE THREAD

**Issue by SoniEx2** [pallets/click#1345]
When you look at tools like ffmpeg and beep, you see an order-dependent argument processing thing.

I need something like that so I can do something like this:

`./foo add-values --weight 3 foo.txt bar.txt baz.txt --weight 2 qux.txt`

(contents of `foo`, `bar` and `baz` would have weight 3, `qux` would have weight 2, the output would have everything merged with the correct weights.)

**Comment by davidism** [comment]
This may be possible already through subclassing, but it is not a goal of click to be able to create this type of argumemt layout.
