### ISSUE TITLE
Does Click support cli options with arbitrary number of elements?

### ISSUE THREAD

**Issue by KamranMaharov** [pallets/click#1351]
Such that,
`program --optA a1 a2 a3 --optB b1 b2`.
`program --optA a1 a2 --optB b1 b2 b3`
both these invocations are valid from Click's perspective.

We can have workaround by using arguments instead of options and passing `nargs=-1`. But we can't have more than one argument with `nargs=-1`. So the only method remaining is,
`program --optA a1 --optA a2 --optA a3 --optB b1 --optB b2`,
It's working very well, but doesn't look elegant.

As an example, argparse has nargs='*' which supports this.

Maybe i missed something? Is there such a way?

**Comment by davidism** [comment]
No, this is an intentional design decision.
