### ISSUE TITLE
ProgressBar item_show_func displays the previous item

### ISSUE THREAD

**Issue by JoelEager** [pallets/click#1353]
I've noticed a bug with the `item_show_func` option for `click.progressbar` where the progress bar ends up showing the previous item instead of the current one.

The issue seems to be that `ProgressBar.generator()` will only render the progress bar _after_ the current item has been processed. As a result, the previous item is visible on screen while the current one is in processing.

I think this change to [lines 285-288](https://github.com/pallets/click/blob/7.x/click/_termui_impl.py#L285) should fix the issue:
```python
for rv in self.iter:
    self.current_item = rv
    self.render_progress()
    yield rv
    self.make_step(1)
```

**Comment by davidism** [comment]
You can just as easily argue that the current behavior is correct as it shows the last completed task. Which is correct?

**Comment by JoelEager** [comment]
The documentation, to me at least, seems to indicate that the intended behavior is to display the current item as opposed to the previous one. So I guess this is less of a bug and more of a case of the docs and implementation being out of sync.

**Comment by davidism** [comment]
Still not sure, but would you mind making a PR so I can take a look at it?

**Comment by JoelEager** [comment]
Sure, I'll try to put one up this evening.

**Comment by nip3o** [comment]
Any updates on this? I find the current behaviour quite confusing, especially when iterating over a single item (for example over a queryset which has been filtered with CLI arguments) – then the progressbar is not shown at all.

**Comment by BALaka-18** [comment]
@davidism I'm from MLH fellowship, would like to work on this Issue.

**Comment by davidism** [comment]
@BALaka-18 there is already a PR for this, but it wasn't linked for some reason. Sorry about that.

**Comment by BALaka-18** [comment]
> @BALaka-18 there is already a PR for this, but it wasn't linked for some reason. Sorry about that.

Sure ! Not a problem.

**Comment by JoelEager** [comment]
Thanks for taking the time to revive and resolve this. I'm looking forward to making use of your fix in the future.
