### ISSUE TITLE
command classes

### ISSUE THREAD

**Issue by SoniEx2** [pallets/click#1356]
I'd like to be able to build command groups from classes. I currently have lots of code similar to this:

```python
def migrations():
    @ganarchy.group()
    def migrations():
        """Modifies the DB to work with a newer/older version.

        WARNING: THIS COMMAND CAN BE EXTREMELY DESTRUCTIVE!"""

    @migrations.command()
    @click.argument('migration')
    def apply(migration):
        """Applies the migration with the given name."""
        conn = sqlite3.connect(data_home + "/ganarchy.db")
        c = conn.cursor()
        click.echo(MIGRATIONS[migration][0])
        for migration in MIGRATIONS[migration][0]:
            c.execute(migration)
        conn.commit()
        conn.close()

    @click.argument('migration')
    @migrations.command()
    def revert(migration):
        """Reverts the migration with the given name."""
        conn = sqlite3.connect(data_home + "/ganarchy.db")
        c = conn.cursor()
        click.echo(MIGRATIONS[migration][1])
        for migration in MIGRATIONS[migration][1]:
            c.execute(migration)
        conn.commit()
        conn.close()

    @click.argument('migration', required=False)
    @migrations.command()
    def info(migration):
        """Shows information about the migration with the given name."""
        if not migration:
            # TODO could be improved
            click.echo(MIGRATIONS.keys())
        else:
            click.echo(MIGRATIONS[migration][2])

migrations()
```

and ppl really don't like my use of functions for this.

instead, my ideal API would look more like this:

```python
@ganarchy.command_class()
class Migrations:
    """Modifies the DB to work with a newer/older version.

    WARNING: THIS COMMAND CAN BE EXTREMELY DESTRUCTIVE!"""

    def __init__(self):
        pass # this gets called with any class-level options and arguments and stuff, rather than using context objects.

    @click.argument('migration', required=False)
    @click.class_command()
    def info(self, migration): # note the self. it replaces context objects.
        """Shows information about the migration with the given name."""
        if not migration:
            # TODO could be improved
            click.echo(MIGRATIONS.keys())
        else:
            click.echo(MIGRATIONS[migration][2])

    # other commands omitted
```

the main benefits of this API are:

1. uses classes instead of "context objects". context objects can still be *used*, but I wouldn't use them, myself.
2. from what I can tell this is more idiomatic than the current click way.
3. it would also make my code more idiomatic because I wouldn't be using a function to create a new local scope.
4. it's more idiomatic all around? if my understanding of python is correct. which, it might not be, I'm still trying to figure this all out.

**Comment by davidism** [comment]
I'm not clear what the goal of the code you've shown is. Why not just define the group, then register it with the command later? Also, you definitely want context here, not classes, despite saying you don't like context. This doesn't seem idiomatic to Click's design.

**Comment by SoniEx2** [comment]
click's design is antipythonic. I'd much rather have classes. the benefit of the function scope is that it doesn't pollute the outer scope, and thanks to click I can still invoke the subcommands with no issues.

how do you do this with context:

```
@click.command_class()
@click.option("--bar")
class Foo:

    def __init__(self, bar):
        self.bar = bar

    @click.argument('qux', required=False)
    @click.class_command()
    def baz(self, qux):
        if qux:
            click.echo(qux % self.bar)
        else:
            click.echo(self.bar)
```

it's much more pythonic with classes.

**Comment by davidism** [comment]
I'm sorry, this doesn't fit in with our design, and seems to be mostly a matter of opinion, or could be solved by other refactoring and code practices. I disagree that Click is "antipythonic", but it's not something I really want to discuss either.

**Comment by SoniEx2** [comment]
if I could have click invoke the command group before looking up subcommands that would be okay too. then I could write:

```python
@click.group()
def foo():
    @foo.command()
    def bar():
        pass
```
