### ISSUE TITLE
help footer?

### ISSUE THREAD

**Issue by pjz** [pallets/click#1362]
Is there an easy way to add a footer line to all the --help output?  I want to add a version number to the help output so I don't have to make a full command just to output the version number.  I could also see it being used for a copyright notice or similar.

**Comment by davidism** [comment]
Yes, override `Command.format_help` to output what you want at the end of your command's help.

See https://click.palletsprojects.com/en/7.x/api/#click.HelpFormatter for how to use the formatter passed to that method.
