### ISSUE TITLE
Printing fails after command is executed

### ISSUE THREAD

**Issue by jsgoller1** [pallets/click#1365]
I am writing a tool to do ability checks for D&D. I am trying to structure my code so I have one function that parses CLI arguments and returns the parsed args, then code elsewhere that does the logic I want. I only have the CLI related function wrapped with click decorators, but for some reason after my decorated function is executed, all printing to stdout fails. Is this normal?

```


@click.command()
@click.option("--players", required=True, help="Comma-separated string list of players (case sensitive) to send message to; use \"all\" for everyone",
              type=str)
@click.option("--check", required=True, help="The type of check", type=str)
@click.option("--dc", required=True, help="Difficulty Class of the check", type=int)
@click.option("--advantage", default="", help="Comma-separated string list of players with advantage on check; use \"all\" for everyone",
              type=str)
@click.option("--disadvantage", default="", help="Comma-separated string list of players with disadvantage on check; use \"all\" for everyone",
              type=str)
@click.option("--pass-text", default="", help="Text to send if player succeeds check", type=str)
@click.option("--fail-text", default="", help="Text to send if player fails check", type=str)
def cli(players, check, dc, advantage, disadvantage, pass_text, fail_text):
    """
    Parse CLI args into simple dict and return.
    """
    with open("config.json") as json_file:
        config = json.load(json_file)
    return Parameters(config, players, check, dc, advantage, disadvantage, pass_text, fail_text)

...

if __name__ == "__main__":
    parameters = cli()
    run_check(parameters)
    print("Can't print here; this doesn't show up in stdout!")
    click.echo("This also doesn't show up in stdout!")
```

**Comment by aelbehe95** [comment]
Hello @jsgoller1 

As per the [documentation](https://click.palletsprojects.com/en/7.x/api/#click.BaseCommand.main)

> `standalone_mode` – the default behavior is to invoke the script in standalone mode. Click will then handle exceptions and convert them into error messages and the function will never return but shut down the interpreter. If this is set to False they will be propagated to the caller and the return value of this function is the return value of invoke().

An example that does not work

```py
import click


@click.group()
def cli(): pass

@cli.command()
@click.option('-s', '--string-to-echo')
def echo(string_to_echo):
    click.echo(string_to_echo)

if __name__ == "__main__":
    cli()
    click.echo("hello") # will not be printed as by default standalone_mode is set to true
```
 
But if you set the standalone mode to false 

```py
if __name__ == "__main__":
    cli(standalone_mode=False)
    click.echo("hello") # will  be printed
```

Double check the [how to contribute](https://github.com/pallets/click/blob/master/CONTRIBUTING.rst) and make sure you already checked the documentation and stackoverflow [almost same question found here](https://stackoverflow.com/questions/34286165/python-click-usage-of-standalone-mode)

Thanks

**Comment by jsgoller1** [comment]
Got it, @aelbehe95 - thanks for the clarification!
