### ISSUE TITLE
echo fails with some console configurations in Windows

### ISSUE THREAD

**Issue by aivarannamaa** [pallets/click#1367]
I'm using click as transitive dependency (Birdseye => Flask => Click) in Thonny IDE. In Windows it uses [certain tricks to allocate console so that Cmd Window is not visible to the user](https://github.com/thonny/thonny/blob/f8c02a68a69e9d22fed8777b08f56474fc658089/thonny/running.py#L591).

It looks like this confuses click -- it tries to write to non-existing stream: 
```
Traceback (most recent call last):
  File "C:\Users\Aivar\AppData\Local\Programs\Thonny\lib\site-packages\thonny\plugins\birdseye_frontend.py", line 23, in start_server
    port=get_workbench().get_option("run.birdseye_port"), debug=False, use_reloader=False
  File "C:\Users\Aivar\AppData\Local\Programs\Thonny\lib\site-packages\flask\app.py", line 985, in run
    cli.show_server_banner(self.env, self.debug, self.name, False)
  File "C:\Users\Aivar\AppData\Local\Programs\Thonny\lib\site-packages\flask\cli.py", line 670, in show_server_banner
    click.echo(message)
  File "C:\Users\Aivar\AppData\Local\Programs\Thonny\lib\site-packages\click\utils.py", line 260, in echo
    file.write(message)
AttributeError: 'NoneType' object has no attribute 'write'
```
More context here: https://github.com/thonny/thonny/issues/847#issuecomment-520728499

I tried both click 7.0 and 6.7.

It would be nice if one could somehow force click to switch to non-tty mode (eg. via an environment variable).

**Comment by aivarannamaa** [comment]
In another context, I was able to make click work by returning `False` from my fake stdout's `isatty` method. But in this situation it didn't help.

**Comment by mostaphaRoudsari** [comment]
@aivarannamaa, any solutions for this. Someone has reported the same issue on their machine. Is there any specific settings in Windows that needs to change in order to get this to work? I'm thinking to catch the error and try to simple print out the message instead. I assume that should not fail.

**Comment by aivarannamaa** [comment]
@mostaphaRoudsari , I believe in my case it was not because of some special setting, but because of special procedure for console allocation. I'll update my first post to point to correct line.

**Comment by davidism** [comment]
I'm going to close this for now. It seems to be due to an unusual terminal configuration that is not something I can investigate or debug. It seems like something that should be addressed in Thonny, since other libraries may also have the same expectations about the terminal.
