### ISSUE TITLE
Resuming script flow after KeyboardInterrupt

### ISSUE THREAD

**Issue by adl1995** [pallets/click#1374]
I have this function:
```
@click.command(name='run')
@click.option('--username', callback=username_callback)
@click.option('--group', callback=group_callback)
def run(...):
...
```

The callbacks prompt the user for an input (if they omitted passing the CLI arguments).
```
def username_callback(ctx, param, value):
    value = click.prompttext='Username: ', type=str)
    return value
```

 In Click there's a parameter called `standalone_mode` which allows users to manually handle exceptions. I would like to prompt the user for a series of CLI input, during which if they press `CTRL + C` I would like to confirm if they want to exit. If not, I would like to resume the normal program flow i.e. resume taking input for the same parameter.

I currently have this:

```
try:
    cli.add_command(run)
    cli(standalone_mode=False)
except RuntimeError:
    if click.confirm("\nPlease confirm if you want to exit"):
        print('Exiting...')
        exit(1)
```

This has two issues:
1. If the user presses `CTRL + C` twice, the interrupt is handled by Click and it shows the generic "Aborted!" message.
2. If the user wants to resume execution, they will have to provide all parameter values again. E.g. if they were previously at `--group` callback they would again have to provide the `--username` value.

Is there a workaround for this issue?

**Comment by davidism** [comment]
You'd probably need to write your own `promt_func`
