### ISSUE TITLE
open_file(…, 'w', atomic=True) sets or resets permissions to 600, ignoring umask

### ISSUE THREAD

**Issue by andersk** [pallets/click#1376]
Files are normally created with permission `666 & umask` as expected:

```pycon
>>> click.open_file('/tmp/test1', 'w').close()
>>> oct(os.stat('/tmp/test1').st_mode)
'0o100644'
```

However, opening a new or existing file with `atomic=True` sets or resets its permissions to `600` unconditionally:

```python
>>> click.open_file('/tmp/test2', 'w', atomic=True).close()
>>> oct(os.stat('/tmp/test2').st_mode)
'0o100600'
>>> click.open_file('/tmp/test1', 'w', atomic=True).close()
>>> oct(os.stat('/tmp/test1').st_mode)
'0o100600'
```

I’d expect a new file created with `atomic=True` to be created with the usual permission `666 & umask`, and an existing file opened with `atomic=True` to have the previous permissions preserved. (There’s probably no way to preserve permissions atomically; taking the previous permissions at the time of the initial open is fine.)

**Comment by iwhiz** [comment]
Could you please tell me the operating system you working with??

**Comment by Minkey27** [comment]
> Could you please tell me the operating system you working with??

I'm running OS X, the problem also occurs on Debian
