### ISSUE TITLE
Option to edit how name of the option shows in help

### ISSUE THREAD

**Issue by jack1142** [pallets/click#1380]
When I create on/off flags, I usually just add `no-` to off version and it would be nice if help could show it as `--[no-]option-name` instead of `--option-name / --no-option-name`.

While click could just support this specific use case, it most likely is better to just add manual editing of how the option name shows in help to support some other scenarios instead of adding support for specific use case so I figured I'll make the issue for that :)

**Comment by davidism** [comment]
I don't plan on adding options for this type of display customizing.
