### ISSUE TITLE
Setuptools and Values from Environment Variables

### ISSUE THREAD

**Issue by edusantana** [pallets/click#1384]
In [docs](https://click.palletsprojects.com/en/7.x/) it only says how to usem with the `__name__` fuction, but I'm using Setuptools.

Can you document how do we do this?

**Comment by jcrotts** [comment]
I'm not sure 100% what you are asking for.

The documentation on environment variables is here:
https://click.palletsprojects.com/en/7.x/options/#values-from-environment-variables

The documentation for using setuptools and click is here:
https://click.palletsprojects.com/en/7.x/setuptools/?highlight=setuptools

Something like this should work with setuptools.
```python
@click.command()
@click.argument('src', envvar='SRC', type=click.File('r'))
def echo(src):
    """Print value of SRC environment variable."""
    click.echo(src.read())
```

**Comment by edusantana** [comment]
Sorry, I wasn't clear. How to use `auto_envvar_prefix` with a project with Setuptools:

```python
@click.command()
@click.option('--username')
def greet(username):
    click.echo('Hello %s!' % username)

if __name__ == '__main__':
    greet(auto_envvar_prefix='GREETER')
```

I don't have this `if __name__ == '__main__'` on my project.

How could we use that on the [setuptools example](https://click.palletsprojects.com/en/7.x/setuptools/#introduction)? I think that's missing on the docs.

**Comment by jcrotts** [comment]
I see what you mean. I don't think that particular scenario is shown anywhere explicitly outside the api docs.

auto_envar_prefix is a parameter under context in the api docs, so it could be passed in a context dictionary.  https://click.palletsprojects.com/en/7.x/api/?highlight=context%20settings#context

**Comment by edusantana** [comment]
I have tried something like this:

```python
CONTEXT_SETTINGS = dict(
    help_option_names=['-h', '--help'],
    auto_envvar_prefix='COZER'
)

# ...

@click.group(cls=DYMGroup, context_settings=CONTEXT_SETTINGS)
@click.version_option()
def cli():
#...


@click.option('-r','--recipiente','recipiente',metavar='<recipiente>', envvar="RECIPIENTE", show_envvar=True, required=True)
@click.option('--como', 'como', metavar='<descricao>', help='descrição de como deve ser realizado a operação, ex: --como "com cuidado para não quebrar"')
#...
```

I have tried:

```
export COZER_RECIPIENTE=oiooo
export COZER_COMO="que bom"
export COZER_DESCRICAO="que bom"

export RECIPIENTE=oi  # only this one works... but doesn't have the prefix
```

I don't know how to call it. Is there an example somewhere?

**Comment by edusantana** [comment]
I made a small code, can you help with this one?

https://gist.github.com/edusantana/dd484f492c3310745ae51a409bb2810a

**Comment by davidism** [comment]
```python
def main():
    greet(auto_envvar_prefix='GREETER')
```

Point the entry point at `main`.
