### ISSUE TITLE
new release or pre-release before last one's anniversary 

### ISSUE THREAD

**Issue by ssbarnea** [pallets/click#1386]
Not having any kind of release since the last year one is not a good sign. While master code may not be ready for a release there is no danger on making pre-release to pypy (0.0a0, or 0.0b1,...) so we can consume them if we need them.

I guess that explains why someone took the effort to fork and publish https://pypi.org/project/click8/ --- something that probably nobody wants.

**Comment by davidism** [comment]
This type of issue is not helpful. Please avoid making them in open source projects.
