### ISSUE TITLE
Flask click SystemError when used with pySimpleGUI output redirect

### ISSUE THREAD

**Issue by ruky87** [pallets/click#1390]
I have a problem using Flask, that uses click echo method, with pySimpleGUI that permits the redirect of the standard output to a text field in the GUI. I get the following error:
`SystemError: built-in method replace of str object at returned a result with an error set`
I got a solution using the last answer of https://stackoverflow.com/questions/55677165/python-flask-as-windows-service
The modified code in `lib\site-packages\click\utils.py`, line 260:
```python
if message:
    try:
        file.write(message)
    except SystemError:
        print(message)
```
internal python print has been substituted with another print function that redirects the output to the pySimpleGUI text field (output).

I don't know if this is the best solution to solve this problem, for now it just works. 
If there is a better solution let me know. Please add the code to the next version of the library if possible.

**Comment by jcrotts** [comment]
This seems like an issue with pySimpleGUI, not with Click. I think we would need more context on what what you are trying to do with your Flask or click code, before changing Click.
