### ISSUE TITLE
Using --help on a subcommand does not show group options

### ISSUE THREAD

**Issue by thedrow** [pallets/click#1391]
It is very common to display all options for both the subcommand and the group.
Click does not display the entire set of options available when invoking the command which is both unfortunate and potentially confusing for end users.
Is it possible to display the entire set of options available for the user for a subcommand?

**Comment by davidism** [comment]
This is intended behavior. It is possible to override the methods that output the help if you want other behavior.

**Comment by thedrow** [comment]
How? There's no access from a sub command to its group.
