### ISSUE TITLE
Multiple envvar Check for Option

### ISSUE THREAD

**Issue by erayerdin** [pallets/click#1396]
We can set the value of an option with `envvar` argument on `Option` as below.

```
@click.option(
    # ...
    envvar="FOO"
    # ...
)
# ...
```

I would like to update my terminal application to use `FOO_BAR` instead, yet I also would like to keep `FOO` for backwards compability for a while. What I would like to, in short:

```
@click.option(
    # ...
    envvar=["FOO_BAR", "FOO"]
    # ...
)
# ...
```

This will check in order, first `FOO_BAR`, then `FOO` and set the `Option` when one is available.

**Comment by davidism** [comment]
This is something you should handle in your code.

```python
if "FOO" in os.environ:
    os.environ["FOO_BAR"] = os.environ["FOO"]
    warnings.warn("FOO is deprecated, use FOO_BAR")

cli()
```
