### ISSUE TITLE
Options and Arguments should support multiple types

### ISSUE THREAD

**Issue by thedrow** [pallets/click#1398]
I have an option which accepts either a string or a float.
While I can create a new parameter type for it, it's rather inconvenient.
There should be an API to specify that this option accepts either type A or type B.
For example:
```python
@click.option('-a', type=click.Either(str, float))
@click.command
def foo(a):
  pass
```

**Comment by davidism** [comment]
Interesting idea, but I think this belongs as a custom type in your code, or in an extension.

**Comment by thedrow** [comment]
Why? It should be common enough for people to have such a use case.
The argument in question is a datetime or the time in seconds until expiry...
Naturally both a string and a float are applicable.
