### ISSUE TITLE
Feature request: timeout for click.confirm

### ISSUE THREAD

**Issue by kshpytsya** [pallets/click#1401]
My application, which uses `click`, locks some global resource, and uses `click.confirm` before proceeding with action. Sometimes something distracts a user, leaving the application at the prompt in some forgotten window and locking out other team members from performing actions on the resource. The confirmation cannot be moved outside the scope of the lock. It would be great to have a way to time-out the `click.confirm`. This could possibly be also useful for `click.prompt` as well but my specific use case only needs `click.confirm`.

**Comment by davidism** [comment]
There are plenty of solutions for adding timeouts to Python code. Is there something Click-specific that needs to happen here?

**Comment by kshpytsya** [comment]
Could you recommend any specific one which would work well with `click` on all the supported platforms? To me, most generic time-out solutions I have seen seem to be somewhat hackish (use of signals or dedicated threads to asynchronously raise an exception in the thread to be interrupted on timeout). To me, a cleaner solution would be having a proper timeout support that would essentially boil down to an equivalent of `select` syscall with timeout on the tty fd (or similar for Windows).

**Comment by kshpytsya** [comment]
Oh, and definitely click-specific would be some visualization of count-down of remaining time.

**Comment by davidism** [comment]
Those aren't hacks, those are necessary parts of handling blocking and cancelling input. And a countdown would be outside the scope of click. This would probably be better as a project-specific thing or a separate Click extension.
