### ISSUE TITLE
Inherit group class

### ISSUE THREAD

**Issue by albireox** [pallets/click#1407]
When you have multiple nested groups I think there is no way for the child group to inherit the class of the parent, so you have to do something like

```python
@click.group(cls=MyGroupClass)
def parent_group()
    pass

@parent_group.group(cls=MyGroupClass)
def child_group()
    pass
```

It would be useful if `child_group` automatically inherited the parent class without having to specifically define it each time.

**Comment by davidism** [comment]
You can do this with partial, but it's not clear that this is always desirable, so I don't think the default should change.
