### ISSUE TITLE
Choice and docs consistency

### ISSUE THREAD

**Issue by fepegar** [pallets/click#1409]
This is my script `test.py`, adapted from the [Choice docs](https://click.palletsprojects.com/en/7.x/options/#choice-options):

```python
import click

@click.command()
@click.option('--hash-type',
              type=click.Choice(['MD5', 'SHA1'], case_sensitive=False))
def digest(hash_type):
    click.echo(hash_type)

digest()
```

If I run `python test.py --hash-type=md5`, the output is `md5`. According to the link above, it should've printed `MD5`. Am I doing anything wrong? I'm using click 7.0.

**Comment by davidism** [comment]
Might be part of 7.1, which hasn't been released yet. Does this work as expected on master?

**Comment by fepegar** [comment]
Yes, I just tried. In this case, I guess the docs for 7.0 should be modified.

**Comment by davidism** [comment]
There are no docs for 7.0, only 7.x. We'll hopefully realease 7.1 soon, but if you want to add a ``.. versionchanged:: 7.1`` note to that section that would be helpful.

**Comment by fepegar** [comment]
I think I did something wrong in the PR. Maybe I should have created my branch from the 7.x branch? Sorry, I don't have much experience with this.
