### ISSUE TITLE
Optional argument after multi-value argument do not work

### ISSUE THREAD

**Issue by mathiasbrito** [pallets/click#1412]
Click Version: 7.0
Platform: MacOS Catalina
Python Version: Python 3.6.2

Problem Description: Maybe the behaviour described is expected, however I expect the `mod` argument to be optional. By positioning it after 'list_', the las argument is always identified as a `mod`. `list_` type is explicitly set as string and mod as Integer. If I list a set of values no mater if `mod` decorator is declared before or after `list_` it will always get a value, and will never be optional. 

Sample Code:
```python
import click


@click.group()
def grp():
    pass


@grp.command(name='cmd', help='Roll one or a set of dices.',
              context_settings={"ignore_unknown_options": True})
@click.argument('list_', type=click.types.STRING, nargs=-1, required=True)
@click.argument('mod', type=click.types.INT, required=False)
@click.option('--message', '-m', help='an optional message')
def cmd(list_, mod, message):
    click.echo(list_)
    click.echo(mod)
    click.echo(message)


if __name__ == '__main__':
    grp()
```

Output:
```
$ python tclick.py cmd xyz xzy yxz
Usage: tclick.py cmd [OPTIONS] LIST_... [MOD]
Try "tclick.py cmd --help" for help.

Error: Invalid value for "[MOD]": yxz is not a valid integer
```

What I Would Expect: That click would not set `mod` if it was not a valid integer type since I set the types, leaving the argument to `list_`, by doing so it would skip the `mod` argument.

**Comment by jcrotts** [comment]
This doesn't seem to be a bug, but an odd interaction between required and nargs=-1. If you have a suggested improvement/fix please submit a PR.

 If you do need this particular setup for your application, you could remove the type of 'mod', and do custom validation inside the cmd function.

**Comment by mathiasbrito** [comment]
If there is at least one case that the required=False doesn't work, seems to me that allowing to flag it as required is misleading. I spend a lot of time trying to figure out what was going on. My solution was to use a custom validation. But this is really an odd behavior, I would suggest documenting it or  not allowing `required=False` for arguments if using it along with another one using `nargs=-1`.

**Comment by davidism** [comment]
> if it was not a valid integer type since I set the types, leaving the argument to list_

It's not possible to make this decision during parsing, which is when nargs is handled.

> not allowing required=False for arguments if using it along with another one using nargs=-1.

While this might be possible to check during parsing (in the same code that handles nargs), the statement above still applies, so it wouldn't really solve anything and might be a false positive.

Docs PRs welcome if you can write some docs that would have helped you in this case, but closing this as wontfix.
