### ISSUE TITLE
No way to mask default for password type prompts

### ISSUE THREAD

**Issue by jiveman** [pallets/click#1419]
Following the documented example

```
@click.option('--password', prompt=True, hide_input=True,
              confirmation_prompt=True, default='MySecretIsOut')
```

while adding a default demonstrates the issue. It just displays sensitive data in plaintext, maybe it could mask most of the letters or something like that.

**Comment by carc1n0gen** [comment]
Why would you pass a default to a password input? That means you have the password in plain text in the script anyway

**Comment by davidism** [comment]
I don't understand the use case here. Passwords don't have a programatic default. If you want to specify them without entering, perhaps use Click's `autoenvvar` or otherwise make the option optional and load a value from some secure location if it's not given.

**Comment by jiveman** [comment]
Hi guys, thanks for the quick response and the awesome library! The use case is this. I’m reading a bunch of settings, some of which are sensitive. They are defaults so the end user doesn’t have to retype them. hide_input helps when the user types in a new secret, however if the secret is not to be changed accepting the default does work, minus the fact it was just displayed on the screen. I feel like hide_input gets me half way there. 

I’m not familiar with autoenvvar.. I’ll look it up When I get a minute. Thanks!

**Comment by sh4nks** [comment]
If you already have a secret you could just check if the password input is empty, and if it is, use the pre-generated secret key.

**Comment by jiveman** [comment]
I ended up masking it before supplying to default, then unmasking when using it on the other side. It was quick and easy, just thought other's might like this.
