### ISSUE TITLE
[BUG] When using multiple option names, the first one is used as param

### ISSUE THREAD

**Issue by jaklan** [pallets/click#1420]
In Click docs you can read:
> The naming rules can be found in Parameter Names. In short, you can refer the option implicitly by the longest dash-prefixed argument:

and:

> If all names for a parameter contain dashes, the internal name is generated automatically by taking the longest argument and converting all dashes to underscores.

Actually it's not true - the chosen one is the first argument with double dashes, not the longest one. 

E.g. this one works:
```
@click.option("-i", "--input-file", "--input")
def fun(input_file):
```

but this one - doesn't:
```
@click.option("-i", "--input", "--input-file")
def fun(input_file):
```
Error message is quite obvious:
```
TypeError: fun() got an unexpected keyword argument 'input'
```
So we just have a bug in code or a bug in docs 🙂

**Comment by AlbertUlysses** [comment]
i created a pr for documentation. @davidism and I discussed it in person today, that the feature probably shouldn't change.

**Comment by davidism** [comment]
https://github.com/pallets/click/blob/466d0add86f48502db9c02c32e30287d39ab866b/click/core.py#L1751

seems to indicate that option names are intended to be sorted by length, so I might need to look at this a little more.

**Comment by davidism** [comment]
Never mind, that line I pointed to above is (as the comment says) grouping long options before short options, not sorting by name length. Looking back through the history of that line makes it clear that preferring the first long option, not the longest option, was an intentional change. #1482 makes the documentation match the implementation.
