### ISSUE TITLE
Generated help with aliased group shows abbreviated command in usage

### ISSUE THREAD

**Issue by dvstans** [pallets/click#1422]
The typical AliasGroup class overrides the get_command method and returns a matching sub command; however, when help is displayed, the usage information shows the matched abbreviated subcommand instead of the full subcommand name. After debugging, I found that the context.info_name contains the the abbreviated sub command name. I think when a sub-command context is being created, it should use the full command name for this field rather than what the user typed.

**Comment by dvstans** [comment]
I believe line 1280 in core.py should be:

        return cmd.name, cmd, args[1:]

instead of:

        return cmd_name, cmd, args[1:]

**Comment by ovezovs** [comment]
In an attempt to reproduce this issue, I have tried the following example:
``` python
# main.py
class AliasedGroup(click.Group):
    def get_command(self, ctx, cmd_name):
        rv = click.Group.get_command(self, ctx, cmd_name)
        if rv is not None:
            return rv
        matches = [x for x in self.list_commands(ctx)
                   if x.startswith(cmd_name)]
        if not matches:
            return None
        elif len(matches) == 1:
            return click.Group.get_command(self, ctx, matches[0])
        ctx.fail('Too many matches: %s' % ', '.join(sorted(matches)))

@click.command(cls=AliasedGroup)
def cli():
    pass
@cli.command()
def push():
    click.echo('this is push')
@cli.command()
def pop():
    click.echo('this is pop')

if __name__ == '__main__':
    cli()
```
``` bash
$ python main.py pu --help
Usage: main.py push [OPTIONS]

Options:
  --help  Show this message and exit.
```
Based on the above input/output, I am getting the full name of the `push` subcommand in the Usage part. Therefore, I was not able to reproduce the issue, @davidism.

**Comment by davidism** [comment]
After triple checking, the example does reproduce the issue, there was some confusion over a few things being worked on at the same time.

**Comment by davidism** [comment]
Reverted in #1915, see #1895
