### ISSUE TITLE
Question: get order of parameters (not arguments)

### ISSUE THREAD

**Issue by benboeck** [pallets/click#1427]
An application modifies text files by applying a chain of functions to each line. The _order of the parameters_ (not arguments) matters.

`filterapp input.txt -a +b -c -d...`

**How is it possible to get the order of the supplied parameters (-a, +b, -c, -d) as supplied on the command line?**

I tried `click.get_current_context().params` but the dictionary is not an OrderedDict so the positions change each run (older Python3 where standard dictionaries are still unordered).

Thank you
kind regards

Ben

**Comment by davidism** [comment]
Click intentionally does not support the ordered option style shown here. There are existing discussions on this such as #567.
