### ISSUE TITLE
Have option to not add space to autocompletion suggestions

### ISSUE THREAD

**Issue by schollii** [pallets/click#1431]
Currently if an option has autocompletion function that returns a list of paths (reachable from current working directory), then when there is only one path left in list so TAB accepts it, click automatically appends a space after the slash. Say you type ("|" represents the cursor):
```
mycommand.py some/path|TAB
```
and the TAB allows for completion because there is only one option `["some/path_to_file/"]`, you get a space before the cursor:
```
mycommand.py some/path_to_file/ |
```
Needless to say this is non-standard and almost never what user expects or desires. Is there a way to configure a click option to not append space, or to patch click so there is no space inserted after the completion?

**Comment by dimbleby** [comment]
cf #1403

**Comment by davidism** [comment]
I don't think this is the right solution to the issue, and want to avoid adding more switches for things. That said, #1622 redesigns the completion system and makes it much easier to customize how completions are returned.
