### ISSUE TITLE
Invoking group without options and arguments order

### ISSUE THREAD

**Issue by timofurrer** [pallets/click#1432]
I'm using the following simplified code to make a `click.group` callable:

```python
@click.group(invoke_without_command=True)
@click.option(
    "--debug",
    "is_debug_mode",
    is_flag=True,
    help="Enable debug mode",
)
@click.argument(
    "some_path",
    type=click.Path(exists=True, dir_okay=False),
)
def cli(is_debug_mode, some_path):
    pass

@cli.command()
def cmd():
    pass
```

Eventually I want to be able to make the following calls to the cli:

```bash
tool -d my/path  # works  
tool my/path -d  # doesn't work
tool cmd   # doesn't works
```

However, only the first works.
For the second call it'll always complain that `some_path` is missing.
For the third call it'll always complain that `cmd` is not an existing file - so, click thinks it's for `some_path`.

I understand that the interface is kinda ambiguous, but wouldn't it be possible for click to prefer commands over arguments of the group? 
Or is that impossible because the group options and arguments are always evaluated no matter of the command?

Would it be a better option to have a default command being called? Instead of using the group directly as default command? (see https://github.com/click-contrib/click-default-group)

**Comment by davidism** [comment]
This is designed this way on purpose and won't change.
