### ISSUE TITLE
Add help shorthand (-h) without boilerplate

### ISSUE THREAD

**Issue by GammaGames** [pallets/click#1433]
I think that allowing the help message to be shown with both `-h` and `--help` is common enough that a basic boolean keyword argument that provides the functionality would be welcome. Currently the easiest way is to [pass custom `context_settings`](https://click.palletsprojects.com/en/7.x/documentation/#help-parameter-customization) like so:

```python3
CONTEXT_SETTINGS = dict(help_option_names=['-h', '--help'])

@click.command(context_settings=CONTEXT_SETTINGS)
def cli():
    pass
```

I admit that it is not much, but something like the following would be nice to remove the boilerplate needed to get the functionality:

```python3
@click.command(help_shorthand=True)
def cli():
    pass
```

**Comment by davidism** [comment]
Thanks for the suggestion! I don't think it's worth the custom option right now, just to reduce one line of config. This isn't significantly shorter, and opens up further requests for inlining context settings, which I don't want to commit to.

```python
@click.command(context_settings={"help_option_names": ["-h", "--help"]})
def cli():
    ...
```
