### ISSUE TITLE
`CliRunner.invoke` takes `mix_stderr` which does nothing

### ISSUE THREAD

**Issue by adamtheturtle** [pallets/click#1435]
`mix_stderr` is a parameter of `CliRunner.invoke`.
This is not documented in the docstring as a `:param`.
Simply reading the code (which I did after trying this and seeing no output) shows that this parameter is not used.

`mix_stderr` works on `CliRunner.__init__`.

The `mix_stderr` parameter should be removed, or changed to work and get documented.

**Comment by davidism** [comment]
Fairly sure this is fixed in master

**Comment by adamtheturtle** [comment]
@davidism I believe that it is not.

See on `master` the parameter list includes `mix_stderr`:

https://github.com/pallets/click/blob/6944450c5331f2d652d342650b6d9b3b52404baa/click/testing.py#L280-L281 

The parameter documentation does not include `mix_stderr`:

https://github.com/pallets/click/blob/6944450c5331f2d652d342650b6d9b3b52404baa/click/testing.py#L296-L311

And the function code does not include `mix_stderr`:

https://github.com/pallets/click/blob/6944450c5331f2d652d342650b6d9b3b52404baa/click/testing.py#L312-L357

**Comment by jcrotts** [comment]
I think this is at least partially fixed here:
https://github.com/pallets/click/pull/1194

**Comment by adamtheturtle** [comment]
> I think this is at least partially fixed here:
> #1194

@jcrotts I don't think that #1194 relates to this issue - this issue concerns `CliRunner.invoke` and that PR concerns `CliRunner.__init__`.

**Comment by jcrotts** [comment]
Some behavior is changed in CliRunner.invoke, the docstring isn't changed though.
https://github.com/pallets/click/pull/1194/files#diff-637edab3f8e0763a9874d17879193dc9R350

**Comment by adamtheturtle** [comment]
I still don't understand how that in any way addresses this issue, which is that the `mix_stderr` parameter to `CliRunner.invoke` does nothing.

**Comment by davidism** [comment]
Hi Adam, you seem to have a specific idea in mind that we're having trouble understanding. If this is important to you and you have the time, it would probably be easier to create a PR fixing the issue rather than going back and forth more.

**Comment by adamtheturtle** [comment]
Good idea @davidism . I have created #1442 . I'm happy to back port / change this if you are happy with the general idea.

**Comment by adamtheturtle** [comment]
@jcrotts @davidism - I hope that the linked PR makes it clear what this issue is.

**Comment by miker985** [comment]
I also just ran into this issue and was confused why stderr and stdout were mixed.

Since it's easy to set this on the CliRunner object I endorse the #1442
