### ISSUE TITLE
Choice options do not get normalized for case

### ISSUE THREAD

**Issue by beowulfenator** [pallets/click#1436]
In the [options doc page](https://click.palletsprojects.com/en/7.x/options/#choice-options) there's an example of case normalization of choice options. I've created the file `digest.py` with the following contents:

```
import click


@click.command()
@click.option('--hash-type',
              type=click.Choice(['MD5', 'SHA1'], case_sensitive=False))
def digest(hash_type):
    click.echo(hash_type)

if __name__ == "__main__":
    digest()
```

The only difference from the example in the docs is that I'm not using setup Setuptools.

So I am running my command like this: `python digest.py --hash-type=md5`. According to the docs I should see `MD5`, the originally passed choice. In reality I am getting `md5`. Am I doing something wrong, or is this a bug?

Click version is 7.0.

**Comment by davidism** [comment]
From those docs:

> Changed in version 7.1

This has not been released yet.
