### ISSUE TITLE
Current working directory of CliRunner.invoke

### ISSUE THREAD

**Issue by danilobellini** [pallets/click#1437]
I found no way to control the "current working directory" when calling `click.testing.CliRunner.invoke` inside tests, and I think that it can be a keyword parameter (accepting a string or a `pathlib.Path` object) of either `CliRunner.invoke` or `CliRunner.__init__`.

```python
runner = CliRunner()
result = runner.invoke(main, ["filename.ext"], cwd=Path(__file__).parent)
```

I can try to create something like a context manager or a fixture (for setup/teardown) that sets it (e.g. with `os.chdir`, like what happens in `CliRunner.isolated_filesystem`) before calling the test, getting back to the previous working directory after running that specific test, however that will make it quite difficult to run tests in multiple threads at once, unless everything can be done from the same single current working directory.

Perhaps `CliRunner.isolated_filesystem` should include some note in its docstring telling that it must not be called more than once at the same time (multi-thread or concurrently/async) in a single process.

I need something like that because the current working directory is part of the result of the application I'm trying to test.

**Comment by davidism** [comment]
Use PyTest's (or something like it) [`tmp_path`](https://docs.pytest.org/en/latest/tmpdir.html) and [`monkeypatch.chdir`](https://docs.pytest.org/en/latest/monkeypatch.html) fixtures to manage this.
