### ISSUE TITLE
Bug in invoke() method: mix_stderr argument does nothing

### ISSUE THREAD

**Issue by amaciel81** [pallets/click#1438]
Hello,

The method `invoke()` on the class `CliRunner` has the argument `mix_stderr` that is actually not doing anything:

https://github.com/pallets/click/blob/6944450c5331f2d652d342650b6d9b3b52404baa/click/testing.py#L281

Also, it seems the documentation includes the argument but is missing the description: http://click.palletsprojects.com/en/7.x/api/#testing.

Thanks!

**Comment by jcrotts** [comment]
Thanks for opening the issue, I believe this is addressed in [this PR](https://github.com/pallets/click/pull/1194)
