### ISSUE TITLE
Feature Request: Allow `click.launch()` to specify the application to launch the url

### ISSUE THREAD

**Issue by ravsimar-sodhi** [pallets/click#1439]
Currently, `click.launch()` uses `xdg-open` to launch applications (On Linux). This is not always desirable, for example, I'd like to open a file with a specific PDF viewer which is not the default. 

Looking at the code, launch() further calls the `open_url` method. Is it possible to add another argument to the method specifying which application to use to open the URL? I'd be willing to contribute if this seems useful to others as well.

**Comment by davidism** [comment]
In that case you should use your own function. The idea of `launch()` is to let each user's operating system decide. If you know the file and application you want ahead of time, use `subprocess.run()` directly.
