### ISSUE TITLE
Determine if called by another command

### ISSUE THREAD

**Issue by schollii** [pallets/click#1440]
So with current behavior of click, my command has to check whether it is being called directly or from another command, in order to do the right thing: return a value if called from other command, raise `click.ClickException` if called directly. Doesn't make much sense IMO but ok, per #747 that's the way it is.

So what is a robust way to check this? I can't find anything in ctx that jumps out. There is no "is_invoked" property/method. One difference I found between the 2 types of invocations is that if command is called directly, then `ctx.parent.invoked_subcommand` is itself, whereas if it is called via `ctx.invoke`, this property is `None`. But is this defined behavior or could this change in the future?

**Comment by davidism** [comment]
Your suggestion seems fine.
