### ISSUE TITLE
Question: subcommands of subcommands

### ISSUE THREAD

**Issue by seebi** [pallets/click#1443]
This is a question regarding if its possible or not:

I am currently planning a bigger CLI and would like to know if there is a way to have a 2 level cli interface such as:

> cli typeX commands_for_typeX

so as an example 

> cli graph export --options
> cli graph delete --options
> cli graph import --options

and similar to another resource type:
> cli space export --options
> cli space delete --options
> cli space import --options

I looked into the example but was not aware of such a structure.

**Comment by davidism** [comment]
Yes, add groups to groups.

**Comment by seebi** [comment]
ok, thanks - as a reference for others, here a working example:

```
#!/usr/bin/env python

import click

@click.group()
def cli():
    pass

@click.group()
def graph():
    pass

@click.group()
def workspace():
    pass

@click.command()
def cmd1():
    """Command1 on cli1"""
    click.echo('cmd1')

@click.command()
def cmd2():
    """Command2 on cli2"""
    click.echo('cmd2')

@click.command()
def cmd3():
    """Command3"""
    click.echo('cmd3')

@click.command()
def cmd4():
    """Command4"""
    click.echo('cmd4')


graph.add_command(cmd1)
graph.add_command(cmd2)
workspace.add_command(cmd3)
workspace.add_command(cmd4)
cli.add_command(graph)
cli.add_command(workspace)


if __name__ == '__main__':
    cli()

```
