### ISSUE TITLE
Message on KeyboardInterrupt handling

### ISSUE THREAD

**Issue by daskol** [pallets/click#1447]
Is it possible to change [this message](https://github.com/pallets/click/blob/master/click/core.py#L823) to something much less misleading? I have spent two days on debugging C extension since I think there is memory leackage in the extension or internal assertion in CPython or libc. I would preffer to see `Interrupted!` instead of `Aborted!`. Another point is that the original message hints to `SIGABRT` but `SIGINT`. This is a bit annoying too.

**Comment by davidism** [comment]
You could run in non-standalone mode and handle exceptions yourself. I'm sorry this caused issues with debugging, but I don't see this as a big enough issue to make configurable.

**Comment by daskol** [comment]
Well, my point actually is to prevent any possible obstacles others could face with. Message `Aborted!` is a bit counter intuitive and unexpected reason to produce the message.
