### ISSUE TITLE
Jump back into calling function

### ISSUE THREAD

**Issue by Zethson** [pallets/click#1450]
Dear developers,

I would like to use a function that may look like:
```
@click.command()
@click.option('--language',
              type=click.Choice(['python', 'c++', 'kotlin'], case_sensitive=False),
              prompt="Choose between the following options:")
def handle_cli(language):
    do_something

    cli_options()

    do_something_else
```

As you can see cli_options() is called.

```
@click.command()
@click.option('--parameter')
def cli_options(parameter):
    do_something
```

My issue is that 'do_something_else' is never called, since cli_options returns exitcode 0 and terminates the program. How can I force it to jump back into the original calling function?
I could make some hacks work with exit codes, but this is really not the way it should be done.

Thank you very much and happy new year!

**Comment by davidism** [comment]
Use invoke with standalone mode disabled to call other cli commands without exciting. Calling the command directly it's not doing what you expect here.

Or, preferably, extract the common code to a separate function and call it from both commands.

**Comment by Zethson** [comment]
"Use invoke with standalone mode disabled to call other cli commands without exciting."
Perfect. Exactly what I was looking for. Thanks!
