### ISSUE TITLE
Using inspect and type annotations [New Feature]

### ISSUE THREAD

**Issue by tianhuil** [pallets/click#1456]
Hi -- this project looks like what I've been trying to find for a while.

One suggestion: rather than using decorators to specify arguments, consider using Python 3 type annotations and `inspect.getfullargspec` to get the argument names, types, and default values.  You can then more succinctly describe a click command.

**Comment by davidism** [comment]
Thanks for the suggestion. We don't plan to add or use annotations at this time. That would be a pretty large departure from the existing API, or would require way more supporting code to maintain both simultaneously. Perhaps an extension could do this.

**Comment by dsully** [comment]
Check out https://github.com/tiangolo/typer - which is built on top of Click.
