### ISSUE TITLE
color output is not working in command prompt on windows

### ISSUE THREAD

**Issue by mkinney** [pallets/click#1458]
I do not get color output when I run from windows, I get escape sequences:

```
PS C:\Users\vagrant> cd one
PS C:\Users\vagrant\one> virtualenv.exe venv
Using base prefix 'c:\\users\\vagrant\\appdata\\local\\programs\\python\\python37'
New python executable in C:\Users\vagrant\one\venv\Scripts\python.exe
Installing setuptools, pip, wheel...
done.
PS C:\Users\vagrant\one> .\venv\Scripts\activate
(venv) PS C:\Users\vagrant\one> pip install click
Collecting click
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Installing collected packages: click
Successfully installed click-7.0
(venv) PS C:\Users\vagrant\one> cp ..\mike.py .
(venv) PS C:\Users\vagrant\one> type mike.py
import click

print(click.style('hello', 'yellow'))
(venv) PS C:\Users\vagrant\one> python mike.py
[33mhello[0m
```

<img width="345" alt="Screen Shot 2020-01-20 at 2 46 10 PM" src="https://user-images.githubusercontent.com/2219838/72762206-a2748d00-3b93-11ea-9abf-11aad8be1ecb.png">

Any ideas?

**Comment by mkinney** [comment]
Using examples from https://click.palletsprojects.com/en/7.x/utils/#printing-to-stdout :

```
(venv) PS C:\Users\vagrant\one> type mike2.py
import click

click.secho('Hello World!', fg='green')
click.secho('Some more text', bg='blue', fg='white')
click.secho('ATTENTION', blink=True, bold=True)
(venv) PS C:\Users\vagrant\one> python .\mike2.py
Hello World!
Some more text
ATTENTION
```

<img width="378" alt="Screen Shot 2020-01-20 at 2 51 35 PM" src="https://user-images.githubusercontent.com/2219838/72762435-65f56100-3b94-11ea-90fc-7f59facdef1e.png">

**Comment by mkinney** [comment]
Ah. RTFM. Need to have colorama installed.

```
(venv) PS C:\Users\vagrant\one> pip install colorama
Collecting colorama
  Using cached https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
Installing collected packages: colorama
Successfully installed colorama-0.4.3
(venv) PS C:\Users\vagrant\one> python .\mike2.py
Hello World!
Some more text
ATTENTION
```

<img width="843" alt="Screen Shot 2020-01-20 at 2 54 40 PM" src="https://user-images.githubusercontent.com/2219838/72762542-d43a2380-3b94-11ea-839b-7977cccbe3e3.png">

The `print(click.style('hello', 'yellow'))` works really well on mac.

Any way to get that to work the same in Windows? Or do I need to convert all `print` statements to `click.echo` and/or `click.secho` command?

**Comment by davidism** [comment]
You need to install colorama and use Click's functions.
