### ISSUE TITLE
Force tool filename in --help output

### ISSUE THREAD

**Issue by darkvertex** [pallets/click#1461]
I have a case where I have a little entrypoint bash script:

A file called `mytool`:
```
#!/usr/bin/env bash
python3 -m mymodule.cli "$@"
```

And all my Click-based CLI stuff happens in my module's cli.py file.

However, when I run `mytool --help` I get:

```
$ mytool --help
Usage: cli.py [OPTIONS] COMMAND [ARGS]...
```

How do I force another string instead of "cli.py"? I vaguely recall that there is a way, but I scoured the docs to no avail. :thinking:

**Comment by davidism** [comment]
Set an environment variable with the correct name, pass that as prog_name when calling main.

**Comment by darkvertex** [comment]
That works; thanks! :+1:
