### ISSUE TITLE
app_name and prog_name are both used for the same thing

### ISSUE THREAD

**Issue by bkreider** [pallets/click#1464]
A minor issue, but maybe standardize on one name instead of both app_name and prog_name?

 * `click.get_app_dir(app_name...)`
 * `click.version_option(...)`: "prog_name – the name of the program (defaults to autodetection)"

**Comment by davidism** [comment]
They're different though. `prog_name` ideally matches the name of the executable you run. `app_name` is the name of the application regardless of how it was run.
