### ISSUE TITLE
dynamically add Options to Command through callback of an eager option

### ISSUE THREAD

**Issue by jyscao** [pallets/click#1483]
### Example (not yet working)
I posted [a question on SO](https://stackoverflow.com/q/60469503/5437918) with a simplified code example of my try at implementing the behavior described in the title. I shall re-post it below for convenience:

```python
import click


def std_cb(ctx, param, standardize):
    if standardize:
        opt = click.Option(param_decls=['-a'],
                           help='this option only exists when -S is set')
    else:
        opt = click.Option(param_decls=['-b'],
                           help='this option only exists when -S is not set')
    ctx.command.params.append(opt)
    return standardize


@click.command()
@click.option('-S', '--standardize/--no-standardize', is_eager=True,
              is_flag=True, default=False, callback=std_cb)
def get_options(standardize, **extra_opts):
    print(locals())


if __name__ == '__main__':
    uis = get_options.main(standalone_mode=False)
```

### Explanation of Desired Behavior
What I'm trying to achieve is to be able to dynamically create different options for a given command depending on the value of an eager flag option to the same command using the click library.

When I execute the above command on the CLI as `$ python cli_test.py`, this is printed to stdout `{'standardize': False, 'extra_opts': {}}`, as expected. Similarly `$ python cli_test.py -S` prints `{'standardize': True, 'extra_opts': {}}`, also expected.

And when I invoke the built-in `--help` option with `$ python cli_test.py --help`, I get:

```bash
Usage: cli_test.py [OPTIONS]

Options:
  -S, --standardize / --no-standardize
  -b TEXT                         this option only exists when -S is not set
  --help                          Show this message and exit.
```

Which seems to suggest that the attachment of the `--no-standardize` specific option via the `std_cb` callback for the `-S` flag is working as well.

Similarly, `$ python cli_test.py --help -S`, produces:

```bash
Usage: cli_test.py [OPTIONS]

Options:
  -S, --standardize / --no-standardize
  -a TEXT                         this option only exists when -S is set
  --help                          Show this message and exit.
```
Now with the `-a` option appearing due to the presence of the `-S` flag.

However, if I were to try and do `$ python cli_test.py -b hello`, I'd get the error: `click.exceptions.NoSuchOption: no such option: -b`.

And similarly, `$ python cli_test.py -S -a world` produces `click.exceptions.NoSuchOption: no such option: -a`, despite them showing up in the help page under their applicable `-S` flag value.

What I had expected to see from the given code example is of course, `$ python cli_test.py -b hello` printing `{'standardize': True, 'extra_opts': {'b': 'hello'}}`.

And `$ python cli_test.py -S -a world` printing `{'standardize': True, 'extra_opts': {'a': 'world'}}`.

### Ideas on the Cause of the Error
Originally, I thought that it might have been some subtle difference in behavior between using the `click.option` decorator and manually appending the `Option` to the `Command.params` list like I was doing via `ctx.command.params.append(opt)`. But after trying to do it by using the decorator like so `ctx.command = click.option(*param_decls, **attrs)(ctx.command)`, the same misbehavior, the dynamically added option are documented with `--help`, but still unavailable and raises `NoSuchOption` exception when trying to use, still remains.

So now I've come to realize this is likely an inherent limitation in the way Click works. Presumably because all options passed on the CLI are parsed before any of their callbacks are fired, so adding additional options via the callback of an already added option (even if it's eager) results in the `NoSuchOption` exception.

### Motivation
Two use cases that motivated this proposed feature are:
- being able to dynamically add different sets of options based on the value of some eager flag
- being able to dynamically set different defaults to a shared set of options based on the value of some eager flag

Please let me know what you think of this feature request, and if it's possible to implement. If so, I'm willing to give it a shot at implementing it if you could provide some high level direction.

Alternatively, if there is an existing way to achieve what I want already, please let me know.

### Environment
* Python version: 3.8.1
* Click version: 7.0

**Comment by davidism** [comment]
There are a few phases to Click's processing. The parser is constructed, parses the command line, then the results of that are passed through all the option and parameter callbacks. By the time you get to callbacks, the parsing is already done.

While I understand the use case, it seems like it's trying to be too clever. Instead, you probably want to always document all options, but provide clear help text about when the options are used. Possibly, you want to make different subcommands instead.

There are various methods you could override on a custom `Command`/`Group` class to implement this. For example, you could override `Command.parse_args` to look at the passed in raw `args` and add options before calling `super().parse_args`, which creates and calls the parser.
