### ISSUE TITLE
Regarding the availability of features related to ParameterSource

### ISSUE THREAD

**Issue by jyscao** [pallets/click#1487]
### Expected Behavior

Be able to use something like the following callback for an option parameter:

```python
def process_xmin_args(ctx, param, xmin_args):
    print(ctx.get_parameter_source(param.name))
```

### Actual Behavior

Get `AttributeError: 'Context' object has no attribute 'get_parameter_source'`

### Environment

* Python version: 3.8.1
* Click version: 7.0

I have the head of the source cloned, so I do see that methods for `Context` like `set_parameter_source` and `get_parameter_source` are in the codebase as of around June of 2019, however these are not yet in the latest 7.0 release. So guess I'm just wondering approximately when the next release will be, which presumably will include this among other new feature additions.

(apologies if this question sounds impatient and pushy, not my intention at all, just curious)

**Comment by davidism** [comment]
I'm sorry, we can't make predictions about release schedules. Click is under active development. I will release 7.1 when I am able to.
