### ISSUE TITLE
ClickException message goes to stdout instead of stderr with version 7.1

### ISSUE THREAD

**Issue by greschd** [pallets/click#1495]
Thanks a lot for ``click`` - absolutely fantastic project. 

I've noticed the following change when upgrading to 7.1, and am not sure if it's intentional or not:

### Expected Behavior

When raising ``click.ClickException``, the corresponding ``Error: <message>`` goes to ``stderr`` using click version 7.0.

Minimal reproducing code:

```python
import click

@click.command()
def run():
    raise click.ClickException('exception message')

if __name__ == '__main__':
    run()
```
```bash
python <filename>.py 1> stdout 2> stderr
```

### Actual Behavior

With version 7.1, the ``Error: exception message`` ends up in ``stdout`` instead of ``stderr``.

### Environment

* Python version: Python 3.7.5
* Click version: 7.1
* OS: Ubuntu 18.04 [through WSL1]
* Shell: GNU bash, version 4.4.20

### Additional comments

As mentioned above I'm not sure if this is an intended change, but I couldn't find any mention on the [Changelog](https://click.palletsprojects.com/en/7.x/changelog/#version-7-1), and [this part](https://click.palletsprojects.com/en/7.x/exceptions/#which-exceptions-exist) of the docs still referes to ``show`` being printed to ``stderr``.

Happy to do some more digging if this happens only on my system.

**Comment by greschd** [comment]
I believe the cause for this is that ``file`` is passed to ``format`` instead of ``echo`` here: https://github.com/pallets/click/blob/master/src/click/exceptions.py#L42

**Comment by davidism** [comment]
Wow, that's my bad, misplaced a paren. Fix coming soon.

**Comment by greschd** [comment]
No worries, and thanks again for the awesome project.

**Comment by davidism** [comment]
7.1.1 is on PyPI

**Comment by greschd** [comment]
Awesome, thanks for the quick turnaround.
