### ISSUE TITLE
Support for NO_COLOR proposal

### ISSUE THREAD

**Issue by seebi** [pallets/click#1498]
### Expected Behavior

As described at https://no-color.org/, setting NO_COLOR to any value should disable color output at all.

### Actual Behavior

Every application need its own solution for color disabling.

I think this behavior should be added to Click itself because its a reasonable default.

**Comment by jcrotts** [comment]
See this [issue](https://github.com/pallets/click/issues/1090) for discussion on a similar request. 
This may have more of a rationale behind it, but in general I don't think click benefits from this sort of customization.

**Comment by davidism** [comment]
I find myself agreeing with https://github.com/ggreer/the_silver_searcher/pull/1207#issuecomment-395316172, it's not clear that this standard is a standard or that it's the correct thing to do.

As Jay points out, this has already been discussed in #1090 and we reached similar conclusions then. If an application wants to support controlling the color with an env var, it's straightforward to add.

```python
if __name__ == "__main__":
    color = os.environ.get("CLICK_COLOR")
    color = color in {"1", "true"} if color is not None else None
    cli(color=color)
```
