### ISSUE TITLE
Changes introduced to string quoting in responses

### ISSUE THREAD

**Issue by kriolyth** [pallets/click#1499]
First of all, thank you for maintaining this wonderful project!

We've been running CI tests on our product that uses click, and tests for command-line [stumbled](https://gitlab.com/tessia-project/tessia/-/jobs/467901400#L478) upon a change in output representation [introduced](https://github.com/pallets/click/commit/718485be48263056e7036ea9a60ce11b47e2fc26#diff-fb2a32ceb27b1c3d30b386fbae56f34eR9) in "manual cleanup" commit.

I do not see this as an issue in click, but it took some time to find the origin, and so I suggest to mention effects of this change in documentation or changelog.

Thank you!

---

### Expected Behavior

Previously a missing option string was displayed with double-quotes:

```
Error: Missing option "--os".
```

### Actual Behavior

Now a missing option string is displayed with single-quotes, as per repr() implementation:

```
Error: Missing option '--os'.
```

### Environment

* Python version: 3.8
* Click version: 7.1.1

**Comment by WhyNotHugo** [comment]
This change broke a bunch of tests for me, and it took quite a while to figure out what was wrong. Looks like there's no changelog entry for this, even though it's very breaking. Is the intention to keep it this way? Can this be added to the logs?

**Comment by brianv0** [comment]
Running across this. I can't find out if this was a permanent behavior change or is a bug which will be fixed in a subsequent release.

**Comment by davidism** [comment]
43e40c05a4b94c6aa497dc7bba62b7d69b7e35ec

**Comment by WhyNotHugo** [comment]
Thanks!

--
Hugo Osvaldo Barrera
