### ISSUE TITLE
Order of commands in help is unreliable in Python <3.6

### ISSUE THREAD

**Issue by andy-maier** [pallets/click#1505]
### Expected Behavior

The order in which commands are shown in the help should be reliable across Python versions.

### Actual Behavior

For Python >= 3.6, the order shown in the help text is the order in which the commands are added to the group. That is how it should be.

For Python <3.6, the order shown in the help text is not the order in which the commands are added to the group, and appears to be unpredictable (but pretty much repeatable).

The unpredictability and the changes across Python versions make it hard for users of Click to define testcases for the produced help.

Analysis shows that the use of a standard dictionary is the reason for this behavior. The standard Python dicttionaty became order-preserving with Python 3.6. We could show that replacing the `dict` in the following code with `OrderedDict` (minimally for Python < 3.6) solves the issue:

In `click/core.py`:
```
class Group(MultiCommand):
    . . .

    def __init__(self, name=None, commands=None, **attrs):
        MultiCommand.__init__(self, name, **attrs)
        #: the registered subcommands by their exported names.
        self.commands = commands or {}     # <- Use of standard Python dict causes the issue
        # self.commands = commands or collections.OrderedDict  # <- Addresses the issue
```

### Environment

* Python version: 2.7, 3.4, and higher
* Click version: 7.1.1

**Comment by davidism** [comment]
See previous discussion in #672 and #513. Commands are ordered alphabetically, see `Group.list_commands`, so I'm not sure why you're seeing an inconsistent order. If you do want a different order, `Group` can be subclassed and overridden.

We're dropping support for Python < 3.6, as those versions are unsupported upstream. I don't really want to add more compat code at this point, especially since there are workarounds if your project needs that.

**Comment by andy-maier** [comment]
I forgot to mention that we do use an approach similar to the one in https://github.com/pallets/click/issues/513#issuecomment-301046782 for maintaining the original order. Sorry for that. The implementation of it overwrites `self.commands` after calling the super init, which I think is ugly, and that spawned my comment. We will change that to pass the commands list to the super init, as in the example from #513.

On "Python not supported upstream":
* Python 3.5 is still supported for security fixes, EOL is 2020-09-13.
* Python 2.7 and 3.4 are still in wide use, even after their EOL.
* If we package owners believe we can remove support for EOL Python versions on the day it occurs, we are not doing the Python community a good service, overall. At least my view.
