### ISSUE TITLE
Shell completion for command groups

### ISSUE THREAD

**Issue by SamSchott** [pallets/click#1506]
### Expected Behavior

Shell tab completion works perfectly well for regular commands but does not seem to work for sub-commands which are part of a group. This is the case at least for zsh on macOS. But maybe this is the intended behaviour?

### Actual Behavior

Tab completion does not work for commands which are part of a group.

### Environment

* Python version: 3.7.6
* Click version: 7.1.1

**Comment by davidism** [comment]
I can't reproduce this issue. Tab completion works for command names in groups and subgroups on ZSH.

**Comment by SamSchott** [comment]
Hm, strange. I'll have a look if this is something which I caused and if I can reproduce it for a different shell.
