### ISSUE TITLE
Search on click website does not function.

### ISSUE THREAD

**Issue by tokuchan** [pallets/click#1513]
I didn't know where to report this issue, so here it is!

---

### Expected Behavior

When I search for, say "option" on the website, by entering "option" into the search box and clicking "Go", the search results page includes relevant results.

### Actual Behavior

The search results page provides almost no functional links. Instead, the vast majority, if not all results are "Page not found".

https://click.palletsprojects.com/en/7.x/search/?q=option
https://click.palletsprojects.com/en/7.x/options.html?highlight=option

**Comment by davidism** [comment]
This is an issue with certain Sphinx versions and Read the Docs. Working with them to figure it out, but no timeline for a fix.

cc @davidfischer

**Comment by davidfischer** [comment]
After quite a delay, there's now a feature flag to use the regular Sphinx builders on Read the Docs. If you're interested in using it, I can set it up for you.

**Comment by davidism** [comment]
Worked with David to fix this. Search works correctly now.
