### ISSUE TITLE
echo_via_pager broken on Windows in 7.1

### ISSUE THREAD

**Issue by Chadiaw** [pallets/click#1514]
Calls to `click.echo_via_pager` are failing on Windows since upgrading to 7.1 

### Expected behavior (7.0)
```
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import click
>>> click.__version__
'7.0'
>>> text = [f"hello {i} \n" for i in range(1000)]
>>> click.echo_via_pager(text)
hello 0
hello 1
hello 2
hello 3
hello 4
-- MORE --
```

### Actual behavior (7.1)
```
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import click
>>> click.__version__
'7.1.1'
>>> text = [f"hello {i} \n" for i in range(1000)]
>>> click.echo_via_pager(text)
The system cannot find the file specified.
>>>
```

## Notes
- Only seems broken on Windows: tested with Ubuntu WSL and click 7.1, works as expected

### Environment

* Python version: 3.7, 3.8 (same results)
* Click version: 7.1.1

**Comment by thorstenkampe** [comment]
Same issue as [here](https://github.com/dbcli/pgcli/issues/1167) - and same root cause:
```python
>>> os.environ['PAGER'] = 'less -SRXF'
>>> import click
>>> text = [f"hello {i} \n" for i in range(1000)]
>>> click.echo_via_pager(text)
The system cannot find the file specified.

>>> os.environ['PAGER'] = 'less'
>>> click.echo_via_pager(text)
  hello 0
  hello 1
  hello 2
  hello 3
[...]
```

**Comment by thorstenkampe** [comment]
`click.edit()` exhibits the same problem

**Comment by davidism** [comment]
Due to #1470. I'll see about reverting that or fixing it on Windows.

**Comment by davidism** [comment]
Click 7.1.2 is available on PyPI.

**Comment by ivankravets** [comment]
@davidism could you take a look at https://github.com/pallets/click/issues/1501? We reverted back @platformio to 7.0. Click is broken on Windows.

**Comment by davidism** [comment]
Missed that issue, but it's due to the same thing, so that's should be fixed too.
