### ISSUE TITLE
Bash completion of strings containing colons is incorrect

### ISSUE THREAD

**Issue by dandavison** [pallets/click#1515]
### Expected Behavior

Click should be able to perform tab completion over a set of strings containing colons.

To reproduce this problem, apply the following diff to the click repo, and run the `bashcompletion` example following the instructions in `examples/bashcompletion/README.md`. Here's a session that goes wrong

```
$ bashcompletion group subcmd bob<TAB>
bob:1  bob:2  bob:3  # OK
$ bashcompletion group subcmd bob:<TAB>
bob:1  bob:2  bob:3
$ bashcompletion group subcmd bob:bob:  # <-- Oh no!
```

```diff
diff --git a/examples/bashcompletion/bashcompletion.py b/examples/bashcompletion/bashcompletion.py
index 0502dbc..42f4915 100644
--- a/examples/bashcompletion/bashcompletion.py
+++ b/examples/bashcompletion/bashcompletion.py
@@ -30,7 +30,7 @@ def group():
 def list_users(ctx, args, incomplete):
     # You can generate completions with descriptions by returning
     # tuples in the form (completion, description).
-    users = [("bob", "butcher"), ("alice", "baker"), ("jerry", "candlestick maker")]
+    users = [("bob:1", "butcher"), ("bob:2", "baker"), ("bob:3", "candlestick maker")]
     # Ths will allow completion matches based on matches within the
     # description string too!
     return [user for user in users if incomplete in user[0] or incomplete in user[1]]
```

### Actual Behavior

Completion over a set of strings containing a colon character is correct until the partial user input contains a colon. At that point, something happens that is wrong, but a bit hard to describe. It seems to involve incorrectly duplicating the user input so far.

(This means that, for example, click cannot correctly complete python nose test names.)

### Environment

* Python version: 3.8.1
* Click version: current master at the time of writing: c3eac6b887ecc2012b28356c229c443a50523f7f

**Comment by dandavison** [comment]
It looks like this might be solved by something along the lines of https://stackoverflow.com/a/12495480/583763

**Comment by kx-chen** [comment]
Still an issue in the new autocomplete system (https://github.com/pallets/click/pull/1622). 
With colons: 
![Screen Shot 2020-08-10 at 11 16 08 AM](https://user-images.githubusercontent.com/22359229/89816233-098b6c00-dafb-11ea-9eb5-0fc68ad94dc3.png)

Without colons: 
![Screen Shot 2020-08-10 at 11 16 55 AM](https://user-images.githubusercontent.com/22359229/89816252-11e3a700-dafb-11ea-99cb-f77577addf68.png)

Occurs in both bash and zsh. 

The hope for the new autocomplete system is to drop support for bash versions older than 4.4, which hopefully should make it easier to fix.

**Comment by ricksentam** [comment]
elif return ~/ .

**Comment by davidism** [comment]
This doesn't happen for me in Zsh or Fish, only Bash. @dandavison would you be able to make a pull request with your suggested changes?

**Comment by dandavison** [comment]
@davidism the change I investigated is here: https://github.com/pallets/click/compare/master...dandavison:fix-colon-completion

However, this didn't quite fix it, so I didn't open a PR. Copying the comment from https://github.com/dandavison/click/commit/0f33bebdb542c7adc509ef086bcbbd6de947498d, here's the evidence that it is still not quite right with that change:

```
$ bashcompletion group subcmd bob<TAB>
bob:1  bob:2  bob:3  
$ bashcompletion group subcmd bob:<TAB>
1  2  3  
```

You are welcome to use 0f33bebdb542c7adc509ef086bcbbd6de947498d, with attribution or not. I can of course open the PR but I don't have time to work on it more at the moment.

**Comment by davidism** [comment]
It seems that `_get_comp_words_by_ref` is provided by the bash-completion package, not built-in to Bash. Despite the name, the bash-completion package is not required for Bash completion, and is not always installed. Using it in Click would make that package required.

I'm going to call this an issue with Bash's completion system in general, although there do seem to be legitimate reasons for it too. I don't think this is something Click can solve, although if a Bash expert comes along later with a PR and an explanation, I won't object. The nice thing about the new completion system is that if a project is ok with making it a requirement, they can apply this fix to their own completion script fairly easily now.
