### ISSUE TITLE
objects.inv of click documentation moved?

### ISSUE THREAD

**Issue by ltalirz** [pallets/click#1523]
[`aiida-core`](https://github.com/aiidateam/aiida-core) is an avid `click` user and we've been taking advantage of the [`intersphinx`](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) extension to link the documentation of `aiida-core` to the one of `click`, where appropriate.

This works using the `objects.inv` file generated by sphinx, which used to be hosted at
https://click.palletsprojects.com/objects.inv

However, this link no longer seems to work - has this file moved?

![Screenshot 2020-04-11 at 19 08 02](https://user-images.githubusercontent.com/1053245/79050064-ce9a2a00-7c27-11ea-97f6-cd872bdf0689.png)

**Comment by ltalirz** [comment]
Sorry, I guess it was indeed a glitch to a signup to cloudflare. Working again!

**Comment by ltalirz** [comment]
We still occasionally get 502 errors when fetching the `objects.inv` file.
This issue is not limited to `click` but also applies to other documentations hosted on palletsprojects.com, such as `flask` (https://github.com/pallets/flask/issues/3472)

**Comment by davidism** [comment]
The link in the original post seems to work.
