### ISSUE TITLE
Make ParameterSource an Enum

### ISSUE THREAD

**Issue by davidism** [pallets/click#1530]
`core.ParameterSource` was implemented as fake enum for compatibility with Python 2. Replace this with a simple `enum.Enum` now that we support Python >= 3.6. Can remove the `ParameterSource.validate` method too, it was just for ensuring the enum values were used.

**Comment by alanbato** [comment]
I'd like to work on this!

**Comment by davidism** [comment]
Go for it, no need to comment first! :-) I just merged a big PR, so make sure your repo is up to date before you start.
