### ISSUE TITLE
[Testing] Passing env through invoke() does not work

### ISSUE THREAD

**Issue by LucasVanHaaren** [pallets/click#1533]
### Explanation

I'm building a multi-commands cli with persistent configuration stored in `~/.config/myapp`
Each time cli runs, it parses this file and passes it to context to be available to sub-commands.
The init command builds and writes configuration on disk.
For testing I want to use [isolated_filesystem()](https://click.palletsprojects.com/en/7.x/api/#click.testing.CliRunner.isolated_filesystem) and write config on it, using [invoke()](https://click.palletsprojects.com/en/7.x/api/#click.testing.CliRunner.invoke) with env var.

_src/config.py_
```python
if 'TMP_DIR' in environ:
    CONFIG_DIRECTORY = Path(environ['TMP_DIR'])
else:
    CONFIG_DIRECTORY = Path.home().joinpath(".config/myapp")

CONFIG_FILE = CONFIG_DIRECTORY.joinpath("config.json")
```

_test/init_test.py_
```python
def test_init(runner):
    with runner.isolated_filesystem() as fs:
        # Adding config location to env
        env = environ.copy()
        env['TMP_DIR'] = fs
        # Running init cmd with env
        res = runner.invoke(cli, ['--verbose', 'init', '.'], env=env)
        assert res.exit_code == 0
        assert fs in res.output
```

### Expected Behavior

Init command should exit successfully and print to stdout the directory where config file was created like this: 

`working directory initialized in /tmp/tmplmw_fea6`

### Actual Behavior

`TMP_DIR` env is not passed to init command, so config is loaded from `~/.config/myapp` even in testing.

### Environment
I use virtualenv with: 
* Python version: 3.6.9
* Click version: 7.1.1
* Pytest version: 5.4.1

Thank you in advance :smile:

**Comment by jcrotts** [comment]
Hi thanks for opening the issue could you post an example of what your cli function looks like.

What platform are you running click on?

**Comment by LucasVanHaaren** [comment]
Hi, I'm running click on Ubuntu 18.04 Bionic.

Here is my cli function which I import from `src/main.py` in `test/init_test.py`

_src/main.py_
```python
...
class CommandContext():
    """Global options object"""
    def __init__(self, verbose=False):
        self.config = read_config()
        self.verbose = verbose


@click.group(cls=CLI, help="Show myapp help.")
@click.pass_context
@click.option('--verbose', is_flag=True, help="Show more information during command processing.")
def cli(context, verbose):
    """Pass context object to subcommands"""
    context.obj = CommandContext(verbose)
```

**Comment by LucasVanHaaren** [comment]
I've juste created an online pad to reproduce the bug easily.
Here is the link: https://repl.it/@LucasVanHaaren/click-testing-invoke-bug-reproduce

We can see the env wasn't overrided, and so config was loaded from user config folder instead of temporary folder provided by isolated_filesystem().

Thanks for your time

**Comment by IamCathal** [comment]
Looking into this at the moment

**Comment by davidism** [comment]
This might be related to #1610, cc @amy-lei.

**Comment by amy-lei** [comment]
Seems the issue was that the value of `CONFIG_FILE` was already set the moment you imported from config, and this happened before the env was updated. So although the value was indeed there (can check by printing `environ.get("TMP_DIR")` inside of `read_config`), the actual value of `CONFIG_FILE` used inside of the function body was evaluated before this update. 

I made some changes to `read_config` so that it updates the value of `CONFIG_FILE` before evaluating the rest of the body, and the output is now `DEBUG config file loaded from /tmp/tmpjn_b9xq8/config.json`. Does this match the behavior you were expecting? Here is the code forked from your replit: https://repl.it/join/ljsynukg-amylei3

**Comment by davidism** [comment]
Good catch, the config is only evaluated once, and is presumably imported before the test case runs. Closing as this doesn't seem to be something that Click can address.

**Comment by LucasVanHaaren** [comment]
> I made some changes to `read_config` so that it updates the value of `CONFIG_FILE` before evaluating the rest of the body, and the output is now `DEBUG config file loaded from /tmp/tmpjn_b9xq8/config.json`. Does this match the behavior you were expecting? [...]

Yes, it's definitely the expecting behavior :ok_hand: 
Thank you all for your time.
