### ISSUE TITLE
[console_scripts] is not recognized using windows store version of python

### ISSUE THREAD

**Issue by grantka** [pallets/click#1536]
### Expected Behavior
I am using python as installed from the [windows store](https://www.microsoft.com/en-us/p/python-38/9mssztt1n39l)
My project is set up as recommended in [help docs](https://click.palletsprojects.com/en/7.x/setuptools/#setuptools-integration)

```
setup.py
mypackage/
    __init__.py
    scripts/
        __init__.py
        myscript.py
```

```python
from setuptools import setup

setup(
    name='myscript',
    version='0.1',
    py_modules=['myscript'],
    install_requires=[
        'Click',
    ],
    entry_points='''
        [console_scripts]
        myscript=mypackage.scripts.myscript:cli
    ''',
)
```

### Actual Behavior
The install looks like it goes through successfully and I can see my package in `pip list` but trying to run `myscript` results in `myscript is not recognized as an internal or external command,
operable program or batch file` 

When I install it with python downloaded via chocolatey or from the python website it works as expected.

### Environment

* Python version: 3.8.2
* Click version: 7.1.1

**Comment by davidism** [comment]
I'm sorry, this isn't something that Click controls. You'll need to report this to either whoever builds the Windows store version of Python, or setuptools.
