### ISSUE TITLE
Use of Setuptools' "extras_require" for colorama?

### ISSUE THREAD

**Issue by bsolomon1124** [pallets/click#1546]
Might it make sense to use Setuptools' ["extras"](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) feature for automatically installing colorama on Windows?

Currently the docs contain fragments to the effect of "_if_ colorama is installed," and advise the user to install colorama if they wish to lend click extra functionality on Windows.

So, might a

```python
extras_require={"wincolors":  ["colorama"]}
```

allowing users to `pip install click[wincolors]` be a better option?

**Comment by davidism** [comment]
I think in this case I'd like to just make it an automatically installed dependency on Windows.
