### ISSUE TITLE
show_default and default_map don't play nice together

### ISSUE THREAD

**Issue by ewjoachim** [pallets/click#1548]
```python
#!/usr/bin/env python
import click

@click.command(context_settings={
    "show_default": True, "default_map": {"a": "b"}
})
@click.option("-a", default="c")
def func(a):
    print(a)

if __name__ == "__main__":
    func()
```
```console
$ # This is expected
$ ./cli.py
b
$ # This is not (default should be b)
$ ./cli.py --help
Usage: cli.py [OPTIONS]

Options:
  -a TEXT  [default: c]
  --help   Show this message and exit.  [default: False]
```

### Expected Behavior

I expect the default shown to be identical to the one being used.

### Actual Behavior

The default shown was the value provided as `default`, without taking the `default_map` into account

### Environment

* Python version: 3.7
* Click version: ``click==7.1.2``

**Comment by ewjoachim** [comment]
I may be able to make a failing test or a PR if you point me to the right direction. Would calling `lookup_default` instead of `.default` in this line be enough ?

https://github.com/pallets/click/blob/bce4ea4ba54e15959cb412d6793634e0c9b24491/src/click/core.py#L1936

**Comment by davidism** [comment]
Seems plausible, happy to review a PR.

**Comment by ewjoachim** [comment]
Ok, I'll try to remember to communicate here whether it happens or not. If I have neither said nor committed anything by May 17th, assume I have forgotten about it and you're free to go :)

**Comment by ewjoachim** [comment]
Yay, done :)
