### ISSUE TITLE
AttributeError: 'int' object has no attribute 'lower'

### ISSUE THREAD

**Issue by DavidKatz-il** [pallets/click#1553]
Hi,  

When i run the following code:   `click.types.BOOL(1)`    i get this error: 
>AttributeError: 'int' object has no attribute 'lower'  

The simple solution is to change  `value = value.lower()` to  
```
if not isinstance(value, (int, str)):  
    raise TypeError("value must be a string or integer")  
value = str(value).lower()
```
[in the 'BoolParamType' class](https://github.com/pallets/click/blob/master/src/click/types.py#L389)

### Environment

* Python version: 3.7.6
* Click version: 7.1.2
  
  
I will be happy to submit a PR.

**Comment by davidism** [comment]
I don't understand why you're using `BOOL(1)`, that isn't how Click types are used. Besides that, input data should always be strings, because that's what comes in on `sys.argv`.

**Comment by DavidKatz-il** [comment]
I didn't use BOOL, i just wanted to explain the bug.
The problem is that some projects are using 'click' not with sys.argv (e.g.
'black'), which causes issues like this issue
https://github.com/dagster-io/dagster/issues/2446
So It may be better to protect the function from mal inputs

בתאריך יום ג׳, 12 במאי 2020, 20:32, מאת David Lord ‏<
notifications@github.com>:

**Comment by DavidKatz-il** [comment]
I didn't use BOOL, i just wanted to explain the bug.
The problem is that some projects are using 'click' not with sys.argv (e.g. 'black'), which causes issues like this [issue ](https://github.com/dagster-io/dagster/issues/2446 
).
So It may be better to protect the function from mal inputs.

**Comment by davidism** [comment]
That sounds like an issue with how they're using Click, not with Click. ;-)

**Comment by DavidKatz-il** [comment]
Ok tnx, i'm closing the issue.
