### ISSUE TITLE
click.launch(wait=True) does not appear to work

### ISSUE THREAD

**Issue by leducvin** [pallets/click#1557]
### Expected Behavior

When calling `click.launch(wait=True)`, if I interpret the documentation correctly, `click.launch(wait=True)` should wait (block) for the user to close the launched program.

From https://click.palletsprojects.com/en/7.x/api/#click.launch:
> wait – waits for the program to stop.

In fact, whatever the value of `wait`, the behavior does not change.

What I'm trying to accomplish is to generate a temp file in my CLI app, let the user look at it using `click.launch`, then have the temp file deleted once the viewing program is closed.

```python
# test.py
# Assume exisiting ./test.txt file

import click
 
@click.command()
def main():
    print('Entering main.')
    click.launch('./test.txt', wait=True)
    print('Leaving main.')
 
if __name__ == '__main__':
     main()
```

```
> python test.py
> Entering main.
(file opens in program)
(user closes program)
> Leaving main.
```

### Actual Behavior
```
> python test.py
> Entering main.
> Leaving main.
(file opens in program)
```

### Environment

* Python version: 3.7.5 (default, Nov  7 2019, 10:50:52) 
* Click version: 7.1.2

Had a look in the source. I'm on linux, so xdg-open is being called, and that never blocks. click always returns `0` if `wait == False`, and the return code of xdg-open if `wait == True`.

**Comment by davidism** [comment]
There's nothing we can do for this. If xdg-open is non-blocking, then it sounds like the only thing wait can do is what it does: ignore the return if it's False, or get the return as soon as it's returned and pass that on if it's True.

**Comment by leducvin** [comment]
Hmm, too bad, I was hoping there was a fix possible, if there was a blocking alternative to xdg-open.

One way would be to get the mimetype with `xdg-mime filetype /path/to/file`, then use` xdg-query default <mimetype>` to get the default application `.desktop` file name.

Find the file in XDG_DATA_DIRS (/applications subfolder). The `.desktop` file would then have to be parsed to find the command for the application, then launch a blocking subprocess with the application using the proper command.

But this is complicated, and I think it's probably not in click's scope.

Maybe a small change in the docs to clarify will do.
