### ISSUE TITLE
Extra empty line added for options with long description

### ISSUE THREAD

**Issue by psss** [pallets/click#1559]
Since version `7.1` there seems to be an extra empty line added after each option with longer description which has to be wrapped. Works nice with `7.0`.

### Reproducer

```python
import click

@click.command()
@click.option(
    '-v', '--verbose', is_flag=True, multiple=True,
    help='Please, show more details. Use multiple times to raise verbosity.')
@click.option(
    '-d', '--debug', is_flag=True, multiple=True,
    help='Provide debugging information. Repeat to see more details.')
def show(verbose, debug):
    """ Show something """
    print(f"verbose: {verbose}\ndebug: {debug}")

if __name__ == '__main__':
    show()
```

### Expected Behavior

There should be no empty lines between option descriptions.

```
Options:
  -v, --verbose  Please, show more details. Use multiple times to raise
                 verbosity.
  -d, --debug    Provide debugging information. Repeat to see more details.
  --help         Show this message and exit.
```

### Actual Behavior

Extra lines after the `verbose` option.

```
Options:
  -v, --verbose  Please, show more details. Use multiple times to raise
                 verbosity.

  -d, --debug    Provide debugging information. Repeat to see more details.
  --help         Show this message and exit.

```

### Environment

* Python version: 3.8.2
* Click version: 7.1.1

**Comment by davidism** [comment]
This was an intentional change, it's listed in the changelog. https://github.com/pallets/click/issues/1075

**Comment by psss** [comment]
I see, thanks for the pointer. Will add a comment there.

**Comment by psss** [comment]
As there was no feedback in #1075, pasting the comment here.

Adding extra new lines only for some options looks to me quite inconsistent and can be very confusing. Here's a real-life example from my project:

    -i, --id ID                  Run id (name or directory path).
    -l, --last                   Execute the last run once again.
    -a, --all                    Run all steps, customize some.
    -u, --until STEP             Enable given step and all preceding steps.
    -s, --since STEP             Enable given step and all following steps.
    -A, --after STEP             Enable all steps before the given one.
    -B, --before STEP            Enable all steps after the given one.
    -S, --skip STEP              Skip given step(s) during test run execution.
    -e, --environment KEY=VALUE  Set environment variable. Can be specified
                                 multiple times.

    -v, --verbose                Show more details. Use multiple times to raise
                                 verbosity.

    -d, --debug                  Provide debugging information. Repeat to see
                                 more details.

    -q, --quiet                  Be quiet. Exit code is just enough for me.
    -f, --force                  Overwrite existing files and step data.
    -n, --dry                    Run in dry mode. No changes, please.
    --help                       Show this message and exit.

This creates an impression of multiple sections but very poorly organized (especially as `verbose`, `debug` and `quiet` belong together but are artificially separated).

If the extra empty line is added, it should be probably added to all options to get a consistent look. But then you get so much space wasted. I'd say that the previous behaviour was much better.

If it's really needed, what about making this feature configurable? It could be something like `separate=[True|False|Auto]`. What do you think?

**Comment by davidism** [comment]
No, I do not plan to add configuration options for things like this. There are way, way, way too many opinions about exactly how different things should look and function, and adding options for all of them becomes way too complex. The general philosophy of Click is to makes decisions where it can rather than providing configuration for everything, although there is a general desire to refactor the formatting system to allow projects to override these sorts of things without having to add options for everything in #561.
