### ISSUE TITLE
Undefined behaviour when ctx.obj is renamed ctx.args

### ISSUE THREAD

**Issue by ashwinvis** [pallets/click#1570]
I was trying to implement the `pass_context` feature as given in:

> https://click.palletsprojects.com/en/7.x/commands/#nested-handling-and-contexts

and I renamed the `obj` dictionary attribute of context with `args`. 

### Expected Behavior
I expected it to work smoothly or throw an error at least.

```python
import click


@click.group()
@click.option('--debug/--no-debug', default=False)
@click.pass_context
def cli(ctx, debug):
    ctx.ensure_object(dict)
    ctx.args['DEBUG'] = debug


@cli.command()
@click.pass_context
def sync(ctx):
    click.echo('Debug is %s' % (ctx.args['DEBUG'] and 'on' or 'off'))


if __name__ == '__main__':
    cli(args={})
```

Here is the traceback if I used `argv` instead:

```pytb
$ python mycli.py sync
...
  File "/usr/lib/python3.8/site-packages/click/core.py", line 698, in make_context
    ctx = Context(self, info_name=info_name, parent=parent, **extra)
TypeError: __init__() got an unexpected keyword argument 'argv'
```

Ideally, it should throw such an error or something more meaningful. 

### Actual Behavior

No error at all. It simply displays the help message, and thus it was hard to debug.

```pytb
$ python mycli.py sync
Usage: mycli.py [OPTIONS] COMMAND [ARGS]...

Options:
  --debug / --no-debug
  --help                Show this message and exit.

Commands:
  sync
```

### Environment

* Python version: 3.8.3
* Click version: 7.1.2

**Comment by davidism** [comment]
I'm sorry this caused you confusion, but I don't think this is common enough to warrant any more specific error handling. This is not undefined behavior, this is using various parts of Click incorrectly.

* `args` is a parameter to `cli()`, it's the list of command line args to process: https://click.palletsprojects.com/en/7.x/api/#click.BaseCommand.main
* `Context` exposes the list of leftover arguments after processing as `args`: https://click.palletsprojects.com/en/7.x/api/#click.Context.args
* Treating `ctx.args` as a dict raises `TypeError: list indices must be integers or slices, not str`, it's not clear why you didn't see that with the code you've shown.

**Comment by ashwinvis** [comment]
Thanks @davidism for the explanation. 

> Treating ctx.args as a dict raises TypeError: list indices must be integers or slices, not str, it's not clear why you didn't see that with the code you've shown.

I get that only if I make this change on my example:

```diff
 
 if __name__ == '__main__':
-    cli(args={})
+    cli(obj={})
```

Perhaps its worth pointing out in the documentation that `ctx.obj` has special meaning, which was not obvious to me.
