### ISSUE TITLE
Is there a way to use wildcard arguments when using CliRunner

### ISSUE THREAD

**Issue by dhhagan** [pallets/click#1578]
### Expected Behavior

If given a wildcard argument when testing using CliRunner, the wildcard is not expanded and instead is sent as a string.

```python
@click.command("concat")
@click.argument("files", nargs=-1, type=click.Path())
@click.option("-o", "--output", default="output.csv", help="The filepath where you would like to save the file", type=str)
@click.option("-v", "--verbose", is_flag=True, help="Enable verbose mode (debugging)")
def concat(files, output, verbose, **kwargs):
    """Concatenate FILES together.
    """
    for f in files:
        click.echo(f)

```

### Test Code

```python
class SetupTestCase(unittest.TestCase):
    def setUp(self):
        self.test_files_dir = os.path.join(os.getcwd(), "tests/files")

    def tearDown(self):
        pass

    def test_concat_files(self):
        runner = CliRunner()
        result = runner.invoke(concat, [os.path.join(self.test_files_dir, "*.csv")])

```

### Actual Behavior

Instead of printing out all csv files in the directory, it prints out `<path-to-directory>/*.csv` as a string which raises an error with the unittest because it expects a valid filepath (i.e. without the wildcard). Is there a way to test wildcards using CliRunner?

### Environment

* Python version: 3.6.10
* Click version: 7.1.2

**Comment by davidism** [comment]
Expansion is done by your shell, not Click. Since you're building this invocation in Python, you can use the built-in `fnmatch` or `glob` module.
