### ISSUE TITLE
when @click.option('-s', '--string-to-echo') used , by mistake if i give -string-to-echo it will consider the option as -s and followed by the value passed to it. is there validation for options as well?

### ISSUE THREAD

**Issue by girishprabhu7** [pallets/click#1588]
```python
@click.command()
@click.option('-s', '--string-to-echo')
def echo(string_to_echo):
    click.echo(string_to_echo)
```

```
> python test.py -string-to-echo
  tring-to-echo
```

expectation:
Error: no such option:  -string-to-echo

```
> python test.py -sassdf
assdf
```

option does not need space separator for value to be passed  

expectation:
Error: no such option:  -sassdf

### Environment

* Python version: 2.7
* Click version:  7.1.2

**Comment by davidism** [comment]
Not requiring a space after a short option is fairly standard CLI behavior. I understand how this potential typo is confusing, but I don't think this is something we want to change. Unless we significantly change the parser, I don't think there's a good way to disable this, or to detect that you meant to type a long option.

**Comment by girishprabhu7** [comment]
Any work around or how can it be handled this in the code, any alternative ways print the error message when its typo in option .

**Comment by davidism** [comment]
No, there is no customization or override points related to that.
