### ISSUE TITLE
Question: How do you remove the f-strings in the wheel on Pypi?

### ISSUE THREAD

**Issue by andy-maier** [pallets/click#1592]
I ran into an install issue with click on Python 2.7 when installing it as editable from the repo's working directory. I then found that it uses f-strings, which explains the behavior.

The source files in the wheel archive on Pypi however do not have the f-strings; that seems to have been converted from the repo source.

I am aware of the pre-commit hook in click that does a pyupgrade, which creates f-strings, but this is the opposite direction.

Two questions on that:
1. How do you create the weehl that gets uploaded to Pypi, such that its source does not have the f-strings?
2. The setup.cfg has `python_requires = >= 3.6`, but on Pypi, the latest version is indicated as `Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*`. How is that done?

**Comment by davidism** [comment]
Python 2.7 is not supported in the next version.
