### ISSUE TITLE
@click.command() decorator does not preserve __name__ attribute

### ISSUE THREAD

**Issue by taranlu-houzz** [pallets/click#1612]
### Expected Behavior

I have some code that uses the `__name__` attribute. I would expect the decorator to preserve this value on the decorated function that it produces. I can see that a new `name` attribute is added, but this is a modified name that has underscores replaced with dashes.

```python
import click

def test_func_1():
    print("test_1")

@click.command()
def test_func_2():
    print("test_2")

dir(test_func). # This will list __name__
print(test_func.__name__).  # This will print "test_func"

dir(test_func_2)  # This will not list __name__
print(test_func_2.__name__). # This will raise an AttributeError
```

### Actual Behavior

The `__name__` attribute is missing on the decorated function that is produced.

### Environment

* Python version: 3.7.7
* Click version: 7.1.2

**Comment by davidism** [comment]
The decorators don't produce functions, they produce `Command` objects. If you need to access the original function you can use `test_func2.callback`. While the most common type of decorator usually returns a modified or wrapped function, there is no requirement that a decorator do so, and Click takes advantage of this pattern.
