### ISSUE TITLE
click.argument ignores default value of None

### ISSUE THREAD

**Issue by sammko** [pallets/click#1625]
### Expected Behavior

The `click.argument` decorator should be able to distinguish a `default=None` parameter from not specifying a default value at all.

```python
@click.command()
@click.argument("arg", default=None)
def cmd(arg):
    print(arg)
```
```
λ py c.py
None
```
### Actual Behavior

The `default=None` parameter is ignored.

```
λ py c.py 
Usage: c.py [OPTIONS] ARG
Try 'c.py --help' for help.

Error: Missing argument 'ARG'.
```

### Workaround

Use a different value, which is guaranteed not to appear as legitimate user input e.g. of a different type, or a sentinel object.

```python
_sentinel = object()

@click.command()
@click.argument("arg", default=_sentinel)
def cmd(arg):
    if arg is _sentinel:
        arg = None
    print(arg)
```

### Environment

* Python version: any
* Click version: 7.1.2

**Comment by davidism** [comment]
Use `required=False`.

**Comment by sammko** [comment]
@davidism And wouldn't it be better to fix the issue instead of suggesting the same workaround as I did?

**Comment by davidism** [comment]
There's no issue to be fixed. The default `default` is already `None`, but arguments are also required by default. Pass `required=False` to the argument if you want the default to be `None`. That's not a workaround, that's the intended behavior. Setting `default` to a non-`None` value just does that automatically.

I'm not sure why you think that's the same as the workaround you suggested of using a sentinel value. Please remember to be kind when asking for help from others. Demanding we fix something that doesn't appear to be an issue isn't going to get you far.
