### ISSUE TITLE
wrong default shown when envvar set on an option and show_default=True

### ISSUE THREAD

**Issue by schollii** [pallets/click#1651]
### Expected Behavior

When `envvar` and `default` both set on an option and `show_default=True`, the `--help` output should show the envvar value if the env var exists: 

```python
import click

@click.group()
def cmd_top():
    pass

@cmd_top.command('example')
@click.option('--option', default='default-val', envvar='SOME_ENV_VAR', show_default=True)
def cmd_mycommand(option):
    """some help"""
    pass

cmd_top()
```

Then 
```bash
python main.py example --help
```
correctly shows the default for `--option` as being `default-val` BUT
```bash
SOME_ENV_VAR=other-default-var python main.py example --help
```
should show `other-default-var` as default since that is what will be used if run `SOME_ENV_VAR=other-default-var python main.py example`. 

I also expected click to give a hint that default is from an env var eg 
```
Usage: test.py example [OPTIONS]

  some help

Options:
  --option TEXT  [default (from SOME_ENV_VAR): other-default-val]
  --help         Show this message and exit.
```

### Actual Behavior

```bash
SOME_ENV_VAR=other-default-var python main.py example --help
```
still shows `default-val`, eventhough calling `SOME_ENV_VAR=other-default-var python main.py example` will (correctly) use `other-default-var`

### Environment

* Python version: 3.7
* Click version: 7.1.2

**Comment by davidism** [comment]
But the default is still the same. The env var sets the value just like passing on the command line, it has nothing to do with the default value.
