### ISSUE TITLE
Date ParamType

### ISSUE THREAD

**Issue by enricobarzetti** [pallets/click#1655]
Similar to DateTime there should be a Date parameter type

**Comment by davidism** [comment]
This can be added by a project that needs it. In my experience date on it's own is not that useful, as it cannot account for timezones.

**Comment by enricobarzetti** [comment]
In my experience `date`'s usefulness has nothing to do with time zones.  A date represents a day on a calendar which is a totally legitimate data value used by programs.

I'm adding this because I just had a project where I needed to accept dates on the command line.

It's not rational to say that programs don't need dates unless they also have a time zone.

> Note that one of the default formats accepted by DateTime is only the date.

Wrong, it takes the date format but returns a `datetime`.  My program needs a `date` not a `datetime`.  By the same argument you should remove the `int` type because you can express integers as strings.

Can you either just merge this change or provide an actual rational reason why you know that no command line program will ever want to use a date value as input unless there is a time zone?

I'm not the first person asking about this.  There are 3 other tickets going back 6 years on this subject.  Obviously people want it and it doesn't make sense for you to have `datetime` but not `date`.

**Comment by enricobarzetti** [comment]
@thbourlove @numbsafari @ddaws @devforfu @rsyring @jonatasleon @0x2b3bfa0 @testvinder

@davidism all 9 of us have over the last 6+ years expressed a need for `date` as a parameter type in 5 tickets.  I think this is enough support to justify adding this code.  If `datetime` is an appropriate parameter type then so is `date`.  `datetime` is not `date` and it doesn't make sense to use it in that kludgy that way because it is a different type.

**Comment by davidism** [comment]
> In my experience `date` on it's own is not that useful, as it cannot account for timezones.

> If `datetime` is an appropriate parameter type then so is `date`.

I'm sorry that this implied a value judgement on your preference for and use of `date`, that was not my intention. My experience is that it causes issues that may not be immediately obvious, including (but not limited to) dealing with dates across timezones, and that a `datetime` with a zeroed time (`%Y-%m-%d`) accomplishes the same thing as a date value. You're welcome to use `date` as appropriate for your project.

>  By the same argument you should remove the `int` type because you can express integers as strings.

There are a myriad useful types in the standard library that do not have a direct implementation as a Click `ParamType`. It is not Click's goal to provide an implementation for every conceivable type. Instead, a framework is provided for adding whatever validation and parsing is needed, either through custom types or with callbacks.

If your project needs a `date` type, you could add a callback with a `DateTime` type:

```python
def as_date(value: datetime) -> date:
    return value.date()

@click.command()
@click.option("--start", type=click.DateTime(["%Y-%m-%d]), callback=as_date)
def cli(start):
    ...
```

Or you could implement a dedicated type, such as your PR. If you feel that this would be useful to users outside your own project, I encourage you to release it as an extension package on PyPI.
