### ISSUE TITLE
Autocomplete does not work with incomplete in fish

### ISSUE THREAD

**Issue by mrmeszaros** [pallets/click#1660]
### Expected Behavior

Autocomplete should be usable with incomplete parts in fish.

```python
#!/usr/bin/env python
import click
from sys import stderr
from glob import glob
from os.path import expanduser, splitext, basename


def _complete(ctx, args, incomplete):
	# print(incomplete, file=stderr)
	words = ['bar', 'baz', 'foo', 'fux']
	return [w for w in words if w.startswith(incomplete)]


@click.command()
@click.option('test', '--test', autocompletion=_complete)
def main(test):
	print(test)


if __name__ == '__main__':
	main()
```

### Actual Behavior

The autocomplete did not trigger properly.
On the input `foo-bar --test <TAB>`, the whole word list is shown as suggestions (`bar  baz  foo  fux`).
On the input `foo-bar --test b<TAB>`, nothing was printed as suggestions.
Upon debugging into a log-file, it seems to me that the `incomplete` parameter is not passed to the callback.
On the input `foo-bar --test=b<TAB>`, nothing was printed as suggestions.
Upon debugging, it seems that the `incomplete` gets populated properly, and the function returns values, however, fish does not print anything.

Tested in bash, it worked properly.

### Environment

* Python version: `Python 3.8.2`
* Click version: `7.1.2`

PS. This is a simplified case - what I want is for the option to autocomplete to the names of files in a directory.

**Comment by davidism** [comment]
See #1484 and #1622
