### ISSUE TITLE
Out-of-order output from click.echo on windows when mixing byte output with string output

### ISSUE THREAD

**Issue by ehaas** [pallets/click#1663]
### Expected Behavior

Below program should output:
`123This happens last`

(that is the output on MacOS and Linux)

```python
import click

@click.command()
def hello():
    for byte in [b'1', b'2', b'3']:
        click.echo(byte, nl=False)
    click.echo('This happens last')

if __name__ == '__main__':
    hello()
```

### Actual Behavior

On windows, program outputs:
```
This happens last
123
```
As a workaround, adding `sys.stdout.flush()` after the `click.echo` call within the loop fixes the issue.

### Environment

* Python version: 3.8.5
* Click version: 7.1.2
* Windows version: Windows 10 Pro r1909

**Comment by parabolize** [comment]
> Depending on if unicode values or byte strings are passed the control flow goes completely different places internally which can have some odd artifacts if data partially ends up being buffered. Click attempts to protect against that by manually always flushing but if you are mixing and matching different string types to stdout or stderr you will need to manually flush.

https://click.palletsprojects.com/en/7.x/wincmd/#unicode-output-and-input

**Comment by davidism** [comment]
Thanks for finding that, @parabolize. Going to close this as it's a documented limitation of mixed output on Windows.
