### ISSUE TITLE
click always shows completion options for the first argument which I pressed tab to complete

### ISSUE THREAD

**Issue by kortina** [pallets/click#1667]
### Expected Behavior

A script, `ck`, with the following groups / commands:

```
g1 / boo
g1 / boo2
g2 / touch
```

Should show the completion options `boo` `boo2` when typing:

```
ck g[tab]
... complete to:
ck g1 b[tab]
boo
boo2
```

Sort of like this:

![image](https://user-images.githubusercontent.com/5924/92676525-92521f00-f2d6-11ea-9db2-fbc4d2a6d82b.png)

### Actual Behavior

Instead, when I complete `ck g` and it show the options `g1`, `g2`, and then I type ` b[tab`, the completion options for `g1` `g2` still show:

![image](https://user-images.githubusercontent.com/5924/92676282-1526aa00-f2d6-11ea-8215-e3f882c4d9d0.png)

I *can* get the correct behavior if I type `ck g1 b[tab]` (and DO NOT first use tab to complete the first argument).

### Environment

* Python version: 3.7.0
* Click version:  7.1.2
* zsh 5.8 (x86_64-apple-darwin19.3.0)

- Gist with example python file: https://gist.github.com/kortina/31bb6efc0cc2eca8be1e0c9ea4444182
- my full zshrc: https://github.com/kortina/dotfiles/blob/master/.zshrc

**Comment by davidism** [comment]
Probably solved by #1622

**Comment by kortina** [comment]
ohhhhhh, actually, this was a zsh thing for me: https://github.com/kortina/dotfiles/commit/79ce31b6ecfd0cedeacad102f666313fbe70a636

I *think* the key change was adding:

```
unsetopt always_last_prompt
```

**Comment by kortina** [comment]
Actually, spoke too soon, just to update this, https://github.com/kortina/dotfiles/commit/79ce31b6ecfd0cedeacad102f666313fbe70a636 did fix part of my issue, but typing

`ck g1 b[tab]` still immediately completes to `ck g1 boo` (whereas `git c` (correctly) shows all the options for git commands that begin with `c` but does not complete any of them).

Will wait for #1622 (and maybe checkout the code and try it to see if it fixes)
