### ISSUE TITLE
ZSH autocompletion print help

### ISSUE THREAD

**Issue by jGsch** [pallets/click#1669]
### Expected Behavior

ZSH autocomplete do not print help 

### Actual Behavior

The `clicktest.py`:
```python
import click

@click.group()
def cli():
    """A simple command line tool."""

@click.group()
def start():
    """Start a thing."""

@start.command()
def service():
    """Start a service."""
    print("service")

@click.group()
def stop():
    """Stop a thing."""

@cli.command()
def process():
    """Stop a process."""
    print("process")

if __name__ == "__main__":
    cli()
```
The `setup.py` file:
```
from setuptools import setup

setup(
    name='clicktest',
    version='0.1',
    install_requires=[
        'Click==8.0.0dev0',
    ],
    entry_points='''
        [console_scripts]
        clicktest=clicktest:cli
    ''',
)
```
Installation:
```
pip install -e . && cd && eval "$(_CLICKTEST_COMPLETE=source_zsh clicktest)"
```
And after `clicktest <TAB>`:
```
[jgsch@SERVER]~% clicktest process:Stop\ a\ process. 
```

But it is working in bash:
```
[jgsch@SERVER]~% bash
[jgsch@SERVER ~]$ eval "$(_CLICKTEST_COMPLETE=source_bash clicktest)" 
```
And after `clicktest <TAB>`:
```
[jgsch@SERVER ~]$ clicktest process 
```

### Environment

* Python version: `3.8.5`
* Click version:` 8.0.0dev0` (also tested with `7.1.2`)
* Zsh version: `5.0.2` (`$HOME/.zshrc` removed to use the base one)

**Comment by amy-lei** [comment]
I am not able to reproduce the error from your code snippet (testing with Click version `7.1.2`). Are you still having this issue?

**Comment by davidism** [comment]
Probably a duplicate of #1321

**Comment by jGsch** [comment]
The problem came from zsh version (`5.0.2`), upgrade to the latest one (`5.7.1`) solved the problem!
