### ISSUE TITLE
Allow for testing.Result to be booleanized

### ISSUE THREAD

**Issue by thejcannon** [pallets/click#1671]
It's nice to be able to `assert` the result of an invoke command (instead  of having to `assert` the exit code _isn't_ zero.
This is easily accomplished by adding a `__bool__` method to `Result`.

```python
assert my_invocation()
# vs.
assert my_invocation().exit_code == 0
```

**Comment by jab** [comment]
Thanks for the interesting idea. However, those semantics seem non-obvious and counter to the explicit-is-better-than-implicit principle enough that I’d want to think carefully about this before accepting.

**Comment by jab** [comment]
In the meantime, you can of course write a helper function for your tests to avoid any code duplication.

**Comment by davidism** [comment]
You almost never want to be using the status code as the main test that your command succeeded, so giving it special behavior doesn't seem right. Instead, you should be testing that the output/side effects of the command are what you expect.

**Comment by thejcannon** [comment]
Perhaps booleanizing isn't the right way about it, as it is implicit. Essentially I want to assert that the result was successful (in addition to other asserts as @davidism pointed out), and right now the `Result` object doesn't _quite_ help you with that.

Should I look at the `exit_code` or the `exception` attribute? Both? The `__repr__` leads me to believe that the `exception` attribute holds the source of truth.

How would y'all feel about some sort of "success" method/property, as essentially that's what I want. Some way of asserting success.

**Comment by davidism** [comment]
You should look at whatever you want to test. If you care about the exit code being zero, look at that. If you want to know what exception was raised (if any), look at that. If you want to know the command actually did the thing it was supposed to do, look at its output or other side effects.
