### ISSUE TITLE
Using conflicting feature switches should raise an error

### ISSUE THREAD

**Issue by saroad2** [pallets/click#1672]
Consider the following code from [this example](https://click.palletsprojects.com/en/7.x/options/#feature-switches)

```python

import click
import sys


@click.command()
@click.option("--upper", "transformation", flag_value="upper", default=True)
@click.option("--lower", "transformation", flag_value="lower")
def info(transformation):
    click.echo(getattr(sys.platform, transformation)())
```

And consider the following commands calls:
```
info
info --lower
info --upper
info --lower --upper
info --upper --lower
```

While the first 3 lines are valid, the last 2 are not.

### Expected Behavior
In my opinion, this kind of invalid commands should raise an exception.

### Actual Behavior
At the moment, *Click* takes the last flag inserted (upper in the first case and lower in the second).

### Environment

* Python version: 3.7.9
* Click version: 7.1.2

**Comment by davidism** [comment]
This is as intended. Click prefers the last value given for an option, to allow overriding aliases, env vars, etc. This is documented.
