### ISSUE TITLE
Integrating alias functionality in Click's core

### ISSUE THREAD

**Issue by ldealmei** [pallets/click#1674]
Hi, yet another issue about aliases.

I went over all the proposed solutions discussed (notably [this project](https://github.com/click-contrib/click-aliases) which comes closest to what I look for), however none really fit what I was looking for.

And I'm not sure I understand why this functionality is not part of Click itself.

[This comment](https://github.com/pallets/click/issues/1346#issuecomment-507308404) in issue #1346 gives a first response:
> Thanks for your interest. I don't plan to add this feature to Click itself at this time, as it is already covered by overridable APIs. If you'd like to add to the documentation, PRs are welcome.

However for a nice integration, I found that overriding the available APIs becomes messy quite quickly (more details on this below). It also requires to have a good understanding of the codebase itself to successfully add the functionality. It feels a bit counter-intuitive to have to follow an advanced pattern (as seen [here](https://click.palletsprojects.com/en/7.x/advanced/)) for a use-case that seems rather common.

Here is an example of what I am looking for:
```
$ cli lama list --help
Usage: cli lama [OPTIONS] COMMAND [ARGS]...

  Manage lamas

Aliases:
  lama, la

Options:
  --help          Show this message and exit.

Commands:
  list   List all lamas

$ cli lama list --help
Usage: cli lama list [OPTIONS]

  List all lamas

Aliases:
  list, ls

Options:
  --help          Show this message and exit.
```
> Note here that `Aliases` are an integral part of the help output, at the same level as options

This would be coded as follow:
```py
@click.group()
def cli():
    pass

@click.group(help="Manage lamas", alias="la")
def lama():
    pass

@lama.command(help="List all lamas", alias="ls")
def list():
    click.echo("Listing lamas")

cli.add_command(lama)
```
> Note that here `alias` is not a list as often suggested, this could be the case and supporting it too is trivial

I find that supporting this pattern allows for powerful and discoverable CLIs. New users can easily explore functionality and veterans can just use aliases to speed up their work. 
The reasoning behind this is actually the same as for short and long flag names, which Click supports natively.

There are quite a few CLIs that make use of this pattern already. Examples are the digital ocean CLI (`doctl`) or the CLIs from the `iproute2` package.

There also has been quite some interests in the last years about that feature and it would be convenient not to  have to rely on an extra dependency.

I added the functionality directly into Click's core, and all in all it amounts for 13 lines of code (without the tests). The implementation supports specifying aliases for both commands and groups and includes showing the aliases in the help output.

I also tried doing it by overriding the provided APIs, seeing that this feature had been rejected a few times. However I did not manage to allow setting aliases to a group (without starting to override all classes), I have more than 5 times more lines of code and I have to import and pass my custom class to every decorator.

I think including this into Click would save a lot of time to all those that would like the feature and would, IMO, integrate quite naturally into the whole project.

I'm submitting a PR with a first basic implementation, I would love to know what you think about it and if you would consider integrating it into Click.

Cheers!

**Comment by davidism** [comment]
Thanks for putting in the time on this, but the comment about not integrating this still applies.

**Comment by ldealmei** [comment]
The issue is also about why this is considered a "complex behavior" in the first place.

It is something often requested, it is often seen in CLIs and serves a clear purpose...

Could you elaborate more on why you don't consider this as an integral part of building a CLI?

**Comment by ldealmei** [comment]
@davidism would you care to answer?

Thank you very much
