### ISSUE TITLE
Minor docs update - boolean flags

### ISSUE THREAD

**Issue by lrjball** [pallets/click#1696]
I've found myself a few times double checking what the default option is when a boolean flag is use i.e. does `default=False` refer to the first flag or the second flag.  Thought adding an example of the calls without any flags to the docs would make this a bit clearer.

**Comment by davidism** [comment]
This makes sense, but it looks like you made a PR against your fork instead of submitting it here.

**Comment by lrjball** [comment]
Good point, my bad! Updated now
