### ISSUE TITLE
Can't pass string with spaces as an argument

### ISSUE THREAD

**Issue by BrendanSimon** [pallets/click#1699]
I can't seem to pass a string as an argument, and I've quoted the string.

Surely this is a very common use case.  What am I doing wrong?  Or is it really a bug ???

```
python foo..py --text="hello there"
```

### Expected Behavior

I expect the the program to be able to accept a single argument which contains spaces  e.g. "hello there"

```python
import click

@click.command()

@click.option( '-t', '--text', default = '' )

def cli( text : str ) :
    click.echo( f"text = {text!r}")

cli()
```

### Actual Behavior

Only the first word of the string is captured, and then click produces an error as the remaining part of the string is unexpected.

The error reported is:

```pytb
Usage: foo.py [OPTIONS]
Try 'foo.py --help' for help.

Error: Got unexpected extra argument (there)
```

### Environment

* Python version: 3.7.3 (Debian Buster)
* Click version: 7.1.2

**Comment by BrendanSimon** [comment]
I think I finally found a solution.  Passing `nargs=1` to the option seems to help.

Is that the "correct" way of doing this?  Is there any reason that it is not the default for strings?

**Comment by ThiefMaster** [comment]
Does `--text "hello world"` work? It's your shell's job to parse quotes, so as long as the shell passes everything properly in a single argument I'd expect click to handle it correctly...
