### ISSUE TITLE
Getting: failed to exec 'man': No such file or directory

### ISSUE THREAD

**Issue by acivitillo** [pallets/click#1700]
### Expected Behavior

Tell us what should happen.

Loading the click script in `/usr/local/bin` with name `git-s3`

```bash
cp git_s3.py /usr/local/bin/git-s3
```

All the click commands work extending my git command line. For instance I can do `git s3 list` which would give me a list of s3 folders as expected from my program.

The --help flag doesn't work.

```bash
git s3 --help
```

I don't get the help page.

### Actual Behavior

Instead I gest this error message

```
git s3 --help
warning: failed to exec 'man': No such file or directory
fatal: no man viewer handled the request
```

### Environment

* Python version: 3.7
* Click version: 7.1.2

**Comment by davidism** [comment]
That's presumably git's help system, not Click. In git, all the commands are separate behind the scenes and use man for their help. Seems that's applied to custom commands too.
