### ISSUE TITLE
Invoke a command manually with unparsed arguments

### ISSUE THREAD

**Issue by Spriithy** [pallets/click#1705]
I would like to be able to run a click command on an unparsed string. For instance from a text input, from a file...

----

I am building a tool which uses a REPL and would like to leverage Click's syntax and efficient interfaces to parse user inputs.

Maybe something like

```python
import click

@click.command('foo')
@click.option('-b', '--bar')
def command(bar):
    print(bar if bar else 'baz')

click.invoke(command, "foo --bar baz") # parses the string and passes the results to the command
```

Are there any plans on supporting this ? Am I missing something in Click's API ? I have been through the code already and haven't found anything substantial in that direction besides `click.testing.CliRunner` which, first doesn't suit my needs (input/ouput is buffered) and is a testing tool which should be used for testing, not production.

Thanks in advance for your kind replies

**Comment by davidism** [comment]
The first parameter when calling a command as an entry point is a list of args to use instead of `sys.argv`. https://click.palletsprojects.com/en/7.x/api/#click.BaseCommand.main

See https://github.com/click-contrib/click-repl for a repl for Click commands.
