### ISSUE TITLE
Reducing overhead by including typing info in method signature's parameter annotations

### ISSUE THREAD

**Issue by ClaymasterJ** [pallets/click#1706]
# Motivation
To reduce the overhead of including imports and potentially spelling out parameters twice like the following:

```python
import click

@click.command()
@click.argument(
    "arg_path",
    type=click.Path(exists=True),
)
@click.option("option_count", type=int)
@click.option("option_flag", is_flag=True)
@click.option("option_range", type=click.IntRange(min=0))
def main_old(
    arg_path,
    option_count,
    option_flag,
    option_range=30,
):
    """Docstring"""

    print(f"Count: {option_count}; flag: {option_flag}; path: {arg_path}")
```

As seen, `arg_path`, `option_count`, etc. are all spelled out twice, and in addition, decorators can quickly confuse the developer and make code hard to manage.

# Example Implementation

Something like the following could be used to specify click's parameter checking in a succinct way that would be discovered using introspection when the command is created with the  `@click.command()` decorator:

```python
import click

@click.command()
def main_new(
    arg_path: click.Path(exists=True),
    option_count: int = 2,
    option_flag: click.Option(is_flag=True) = False,
    option_range: click.IntRange(min=0) = 30,
):
    """Docstring"""

    print(f"Count: {option_count}; flag: {option_flag}; path: {arg_path}")
```

For click to discover the type for each argument, the following code would be used:

```python
# Within click.command() method:
import inspect

click_type = inspect.signature(self.callback).parameters["<whatever_parameter_name_here>"].annotation
```

**Comment by davidism** [comment]
Thanks for the suggestion. I don't plan to add this to Click. You may be interested in [Typer](https://typer.tiangolo.com/).
