### ISSUE TITLE
standalone prompt() repeats prompt string on the same line after empty input

### ISSUE THREAD

**Issue by MarcSchmitzer** [pallets/click#1714]
### Expected Behavior

When the `prompt` function is used directly (not via `option`) and the user hits the return key without entering a value, the next prompt string should appear on a new line. 

```
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import click
>>> click.prompt("input")
# Press return multiple times before entering text and pressing return again.
input:
input:
input:
input:
input:
input: a
'a'
```

### Actual Behavior

The prompt string is repeated on the same line.

```
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import click
>>> click.prompt("input")
# Press return multiple times before entering text and pressing return again.
input: input: input: input: input: input: a
'a'
```
This does _not_ happen for options with `prompt=True`. 

### Environment

* Python version: 3.8.5
* Click version: 7.1.2

**Comment by makrandr1999** [comment]
I'd love to take this one up.

**Comment by amy-lei** [comment]
I'm unable to reproduce this bug both locally and on [replit](https://repl.it/@amylei3/testPrompt)
