### ISSUE TITLE
Shell completion documentation does not match code behavior

### ISSUE THREAD

**Issue by ssbarnea** [pallets/click#1717]
Using latest stable version of click  7.2.1 and documentations from  https://click.palletsprojects.com/en/7.x/bashcomplete/#activation-script

Opposed to what documentation says, the only command that seams to produce the shell script seams to be
`_FOO_COMPLETE=source foo`

But documentation indicates to run `_FOO_COMPLETE=source_zsh foo` (or bash), which do not produce anything, even worse returning success code all the time.

I know that there is some work done to rewrite the completion for 8.x release but that future release is already known to break lots of users, making impossible to adopt even if it would released today.

### Expected Behavior

Be able to rely on documentation.

### Actual Behavior

Zero output when running commands from documentations.

### Environment

* Python version: 3.8 (any)
* Click version: 7.1.2

**Comment by davidism** [comment]
I can't reproduce this issue. All four source commands for the 7.x release (`source` / `source_bash`, `source_zsh`, `source_fish`) behave as expected.
