### ISSUE TITLE
8.x pre-release breaks plugins

### ISSUE THREAD

**Issue by ssbarnea** [pallets/click#1721]
The recent pre-release of 8.0.0a1 proved that it breaks at least https://github.com/click-contrib/click-help-colors/issues/12 as I had jobs testing pre-releases.

### Expected Behavior

* even pre-releases need release notes, https://github.com/pallets/click/releases has no description -- as a hint, you could make use of release-drafter which populates the description on merges building really useful release notes without extra human help

* if breaking changes are made, you should better deprecate them first, or it will alienate most click users and plugin writers making much harder to upgrade.

### Actual Behavior

Tell us what happens instead.

```pytb
  File "/home/runner/work/molecule/molecule/.tox/eco/lib/python3.8/site-packages/click_help_colors/decorators.py", line 6, in <module>
    from click._compat import iteritems
ImportError: cannot import name 'iteritems' from 'click._compat' (/home/runner/work/molecule/molecule/.tox/eco/lib/python3.8/site-packages/click/_compat.py)
ERROR: InvocationError for command /home/runner/work/molecule/molecule/.tox/eco/bin/molecule --version (exited with code 1)```

### Environment

* Python version:
* Click version: 8.0.0a1

**Comment by davidism** [comment]
The changelog can always be found in the docs: https://click.palletsprojects.com/en/master/changelog/#version-8-0

It looks like that extension was relying on something in `_compat`. That module was never public and was never intended to be used by external code. It has been removed now that Python 2 support has been removed, as the code is no longer used. In general for Pallets projects, don't assume anything that isn't documented in the API docs to be public.
