### ISSUE TITLE
optparse replacement

### ISSUE THREAD

**Issue by a1rohner** [pallets/click#1728]
This would be more of a discussion topic, but I would like to know, if you are aware that [optparse is deprecated](https://docs.python.org/3/library/optparse.html) - which you probably are - and if you plan to use `argparse` instead or if there are other plans in this regard. 
I've already quite a bunch of tools depending on the great functionality of `click` and I hope the dev. continuous also without `optparse`.

**Comment by ThiefMaster** [comment]
The only place where I see optparse is in a unit test... https://github.com/pallets/click/search?q=optparse&type=code

**Comment by davidism** [comment]
I swear this has already come up, but I can't find a duplicate, maybe it was on Discord.

Click's parser is *based on* optparse, it doesn't *depend on* optparse. Click is deliberately *not* based on argparse. https://click.palletsprojects.com/en/7.x/why/

That said, optparse itself is only deprecated in the sense that it will not receive more development, not that it will be removed. https://docs.python.org/3/library/optparse.html
