### ISSUE TITLE
Multiple types

### ISSUE THREAD

**Issue by ThatXliner** [pallets/click#1729]
I would like a way to define mutiple input types (a.k.a. `Union[type1, type2]`)

For example, `pip` can install from the index or from a sdist or wheel.

```python
import click
@click.command()
@click.argument("package", type=click.Union(click.Path(exists=True, file_okay=True, dir_okay=False)))
def install_package(package):
    if isinstance(package, str):
        # Get it from the index
        ...
    else:
        # Read data
        ...
```

**Comment by davidism** [comment]
That's a great use for a custom type. https://click.palletsprojects.com/en/7.x/parameters/#implementing-custom-types
