### ISSUE TITLE
Types are not properly handled for multiple options with the same argument name

### ISSUE THREAD

**Issue by jwodder** [pallets/click#1730]
I'm trying to create a command-line interface with several options that set the same argument "slot", but each one converts its argument using a different class.  (In the event that more than one option is given, the last one should take precedence.)  Here's a toy example that I expected to work:

```python
from   collections import namedtuple
import click

Apple = namedtuple('Apple', 'value')
Banana = namedtuple('Banana', 'value')
Coconut = namedtuple('Coconut', 'value')

@click.command()
@click.option('-a', '--apple', 'option', type=Apple)
@click.option('-b', '--banana', 'option', type=Banana)
@click.option('-c', '--coconut', 'option', type=Coconut)
def main(option):
    click.echo(option)

if __name__ == '__main__':
    main()
```

### Expected Behavior

```
$ python3 script.py --apple Foo
Apple(value='Foo')
$ python3 script.py --banana Foo
Banana(value='Foo')
$ python3 script.py --coconut Foo
Coconut(value='Foo')
```

### Actual Behavior

```
$ python3 script.py --apple Foo
Coconut(value='Foo')
$ python3 script.py --banana Foo
Coconut(value='Foo')
$ python3 script.py --coconut Foo
Banana(value='Foo')
```

### Environment

* Python version: 3.9.0
* Click version: 7.1.2

**Comment by jcrotts** [comment]
I'm not sure what you are trying to do is supported directly click.
The following code works on my end.
```python
from collections import namedtuple
import click
Apple = namedtuple('Apple', 'value')
Banana = namedtuple('Banana', 'value')
Coconut = namedtuple('Coconut', 'value')

@click.command()
@click.option('-a', '--apple', type=Apple)
@click.option('-b', '--banana', type=Banana)
@click.option('-c', '--coconut', type=Coconut)
def main(apple,banana,coconut):
    click.echo(apple)
    click.echo(banana)
    click.echo(coconut)
```

To get the behavior i think you are looking for you could manually validate the different options in the function body.
Alternatively you could try using [choice](https://click.palletsprojects.com/en/7.x/parameters/?highlight=custom%20types#implementing-custom-types)

If you need to dynamically instantiate classes from an option you could make custom types by sub-classing `click.ParamType`
[docs](https://click.palletsprojects.com/en/7.x/parameters/?highlight=custom%20types#implementing-custom-types)

Let me know if i misunderstood what you were asking.

**Comment by jwodder** [comment]
That code does something different from what I want.  If the user specifies `--apple foo --banana bar` on the command line, I want the `--apple foo` to be ignored and for the function to only be passed `Banana("bar")`.  As an additional wrinkle, in my actual use case, there are also flag options that should set `option` to a constant, discarding any previous `--apple` etc. options on the command line, and these flag options should themselves be ignored if another `option` option occurs after them.

I figured out a way to do what I want using callbacks, but it still seems like a bug that the code in the original post does not do what I intuitively expect it to do.

**Comment by jcrotts** [comment]
Thanks for clarifying, I think i see what you mean now, but the behavior you are describing is probably best handled in callbacks/custom types, and not something click supports directly. Docs PRs are always welcome.
