### ISSUE TITLE
Custom default label ignored if default is None

### ISSUE THREAD

**Issue by ziima** [pallets/click#1732]
I found out that custom default label is not shown when `default` is `None`. In some cases `default = None` is intentional, but custom default label would be still helpful.

An example with `--limit` option, with `None` as `default` meaning no limit:
```python
import click

@click.command()
@click.option('--limit', type=int, show_default='unlimited')
def main(limit: int):
    print('Limit: {}'.format(limit))

if __name__ == '__main__':
    main()
```

### Expected Behavior
Tell us what should happen.

```sh
$ python3 /tmp/foo.py --help
Usage: foo.py [OPTIONS]

Options:
  --limit INTEGER  [default: unlimited]
  --help           Show this message and exit.
```

### Actual Behavior
Tell us what happens instead.

```sh
$ python3 /tmp/foo.py --help
Usage: foo.py [OPTIONS]

Options:
  --limit INTEGER
  --help           Show this message and exit.
```
Default is not shown, making the description less useful.

### Environment

* Python version: 3.9.1
* Click version: 7.1.2

**Comment by b3n4kh** [comment]
`show_default` is supposed to be a Boolean, triggering to show the value in `default`. Since there is no default set I think the best would be to just set `help='[default: unlimited]'`.

Otherwise you could achive your result with:
```
import click

@click.command()
@click.option('--limit', type=int, show_default='unlimited', default=-1)
def main(limit: int):
    if limit >= 0:
      print('Limit: {}'.format(limit))

if __name__ == '__main__':
    main()
```

**Comment by ziima** [comment]
According to docs, string is a perfectly valid value for a `show_default`, see https://click.palletsprojects.com/en/7.x/api/?highlight=show_default#click.Option.

Yes, I found out it works, when I change the default value to something else, but that's not something I want to do. It makes code less readable.
