### ISSUE TITLE
Allow +toolchain style positional options

### ISSUE THREAD

**Issue by flying-sheep** [pallets/click#1734]
Some options are so centrally important that they shouldn’t need a flag name, just a prefix to the value.

This allows them to optionally go before positional arguments or commands, without potential for ambiguity:

```bash
cargo +dev build ...
cargo +stable build ...
cargo build
```

The example above is the way to [override the default Rust toolchain](https://rust-lang.github.io/rustup/overrides.html#toolchain-override-shorthand).

**Comment by davidism** [comment]
This is already possible, options can have any prefix you want.

**Comment by flying-sheep** [comment]
Sorry, seems like I wasn’t clear enough:

When specifying the commandline, everything after the `+` is the value, not the name. It would be defined something like:

```py
@click.???('+toolchain', default=None, action=click.Choice(['dev', 'stable']))
def main(toolchain: Optional[str]):
    ...
```

And invoking it like

```py
python -m mymod +dev
```

would result in `main(toolchain='dev')` being called.

It’s of course possible to use several options for this, but I can’t find a way to make `--help` show them as one option/argument:

```py
import click

def plus_option(name, vals, default=None):
    vals = list(vals)
    assert default is None or default in vals
    def decorator(fn):
        for val in vals:
            dec = click.option(f'+{val}', name, flag_value=val, default=val == default)
            fn = dec(fn)
        return fn
    return decorator


@click.command()
@plus_option('toolchain', ['dev', 'stable'])
def main(toolchain: str):
    print(toolchain)
```

Results in help like:

```py

Options:
  +stable 
  +dev
  --help   Show this message and exit.
```

instead of

```py
Options:
  +[stable|dev]  Toolchain to use.
  --help         Show this message and exit.
```

**Comment by flying-sheep** [comment]
@davidism so should I open a new bug or will you reopen this one?

**Comment by davidism** [comment]
I don't plan to make the changes described here. If the existing solutions (multiple options, argument with `Choice` type) don't cover this, it is unlikely to be possible without an extensive rewrite to the underlying parser. I don't plan to do that at this time.
