### ISSUE TITLE
Resource tracker warning on zsh completion

### ISSUE THREAD

**Issue by idantavor** [pallets/click#1738]
### Expected Behavior

No warning should be printed on zsh autocompletion.
Warning only appears on python 3.8/3.9
No warning on python 3.7

### Actual Behavior

The warning below is showing upon completion.
the same error is printed when generating the autocompletion script.
seems like its related to the fast_exit implementation (core.py:53)
```python
_MY_TOOLS_COMPLETE=source_zsh my-tools
```
```pytb
warnings.warn('resource_tracker: There appear to be %d '
/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
```

### Environment

* Python version:3.8/3.9
* Click version:7.1.2

**Comment by davidism** [comment]
I can't reproduce this. Are you perhaps unconditionally setting up some multiprocessing code outside a CLI function? This seems to point to an issue with your code, not with Click.

**Comment by davidism** [comment]
See #2030
