### ISSUE TITLE
Ability to wrap lines when directly calling 'echo'

### ISSUE THREAD

**Issue by yannickperrenet** [pallets/click#1750]
#### Request
Wrap lines when using `echo`, example:
```python
click.echo("A paragraph.", wrap=72)
```
This would result in the paragraph getting wrapped at the given width (in the case of the example `72`).

> A very very very
very very very 
long paragraph.

Instead of (if specified):

> A very very very very very very long paragraph.

Ideally, I want the ability to specify a maximum width for the lines since I don't want lines to be printed across the entire width of the terminal.

A look at the codebase would suggest adding (in `click.utils.py`):
```python
import textwrap

def echo(message=None, file=None, nl=True, err=False, color=None, wrap=0):
    # ...
    if wrap:
        message = textwrap.fill(message, width=wrap)
```
#### Alternative
The alternative is of course to wrap the lines before passing it to `echo` (or write a wrapper function). This request is to include this ability in `echo` instead.

#### Extra context
I came from https://github.com/tiangolo/typer and am using `typer.echo` a lot to display helpful messages. `typer.echo` is just `click.utils.echo` and so I figured this would be the place to discuss the change first.

**Comment by davidism** [comment]
While I see how this can be useful, I want to avoid adding more formatting options to functions, as it makes it harder to test the multiple paths in the function. Both your suggested alternatives seem acceptable to me in this case.
