### ISSUE TITLE
Use of deprecated & insecure tempfile.mktemp()

### ISSUE THREAD

**Issue by MIS-Alex** [pallets/click#1752]
### Expected Behavior

_tempfilepager() in _termui_impl.py uses a depreciated function that is considered insecure by the core [Python team](https://docs.python.org/3/library/tempfile.html#tempfile.mktemp). It is recommended to use mkstemp() instead. 

```python
import tempfile
filename = tempfile.mkstemp()  # Suggested replacement
```

### Actual Behavior

Python's warning: 

> Use of this function may introduce a security hole in your program. By the time you get around to doing anything with the file name it returns, someone else may have beaten you to the punch.

```python
import tempfile
filename = tempfile.mktemp()  # Depreciated and insecure
```

### Environment

* Python version: 3.8.5
* Click version: 7.1.2

**Comment by davidism** [comment]
Please see our guidelines for responsibly reporting security issues: https://github.com/pallets/click/security/policy
