### ISSUE TITLE
Config file support

### ISSUE THREAD

**Issue by NotAnyMike** [pallets/click#1753]
Configuration file support. Having a file holding all the parameters values instead of passing them in terminal. 

Once the projects grow (e.g. ML models), the parameters increase a lot and managing them using CLI does not scale well. Having a file where we store those values and just pass the file as argument to click to read all the values sounds very beneficial. 

I know there is something similar in click contrib, but that is not part of click and highly experimental, moving project configs to use it is something I am not willing to take. I prefer to use parsearg file options instead which is not my favorite. Even Hydra does not look clean enough as click. Are you considering implementing something like this in the near future?

**Comment by davidism** [comment]
Thanks for your interest. This is not something we're interested in implementing. It's up to the user to choose a configuration scheme appropriate for their project.
