### ISSUE TITLE
Can't edit file with " quotation mark in name

### ISSUE THREAD

**Issue by fpob** [pallets/click#1760]
Looks like `filename` in `click.edit` is not escaped or quoted which causes exception or weird behavior when filename contains `"`.

Exception when filename contains odd number of `"`

```python
click.edit(filename='foo"bar')
```

```pytb
/bin/sh: 1: Syntax error: Unterminated quoted string
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fpob/tmp/.direnv/python-3.9.1/lib/python3.9/site-packages/click/termui.py", line 588, in edit
    editor.edit_file(filename)
  File "/home/fpob/tmp/.direnv/python-3.9.1/lib/python3.9/site-packages/click/_termui_impl.py", line 466, in edit_file
    raise ClickException("{}: Editing failed!".format(editor))
click.exceptions.ClickException: vim: Editing failed!
```
Expected is file named `foo"bar` opened in the editor.

And when filename contains even number of `"`, then the editor opens multiple files. For example when I tried to edit filename `foo "bar baz"` first file was named `foo "bar` and second `baz`. I would expect one file named `foo "bar baz"` to be open in the editor

```python
click.edit(filename='foo "bar baz"')  # opened 2 files
click.edit(filename='foo "bar baz", "foo bar"')  # opened 3 files
```

**Comment by davidism** [comment]
I don't know what the exact quoting rules for quotes are, but you'll need to do that, it's not something Click can do. I think it's something like `foo'"'bar`. Work it out in your terminal, as whatever you use there is what it should be, it's not specific to Click.

**Comment by fpob** [comment]
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html -- shell quoting rules.

I believe it is bug in Click. I tried to look into code and changed https://github.com/pallets/click/blob/master/src/click/_termui_impl.py#L480 to `c = subprocess.Popen(f'{editor} {shlex.quote(filename)}', env=environ, shell=True)`. That fixed the problem. Python docs is saying that `shlex.quote` is quoting compatible with UNIX shell.

**Comment by davidism** [comment]
We can't call `shlex.quote` because it does the wrong thing on Windows. It's up to you for now to do that.

**Comment by fpob** [comment]
Something like 
```python
            if WIN:
                c = subprocess.Popen(f'{editor} "{filename}"', env=environ, shell=True)
            else:
                c = subprocess.Popen(f'{editor} {shlex.quote(filename)}', env=environ, shell=True)
```
would work?

**Comment by davidism** [comment]
Then the behavior is different on Windows, so someone else will report that weird filenames don't work consistently. We've had a bunch of issues recently when we tried to switch to `shlex.quote`. The robust solution is to use `subprocess.Popen` instead of `os.system`, see #1476.
