### ISSUE TITLE
CliRunner fails to capture stderr as a separate stream

### ISSUE THREAD

**Issue by dnicolodi** [pallets/click#1761]
Given the following code

```python
import sys
import click
import click.testing

@click.command()
def foo():
    sys.stderr.write('Foo!\n')

runner = click.testing.CliRunner(mix_stderr=False)
result = runner.invoke(foo)
assert result.stdout == ''
assert result.stderr == 'Foo!\n'
```

I would expect the asserts to pass. However, `CliRunner` fails to capture `stderr`. I think this is due to a missing `sys.stderr.flush()` in the `CliRunner.invoke()` method (somewhere close to where `sys.stdout.flush()` is invoked. Addind the `flush()` on line 356 of `click/testing.py` so it reads

```python
...
                sys.stdout.flush()
                stdout = outstreams[0].getvalue()
                if self.mix_stderr:
                    stderr = None
                else:
                    sys.stderr.flush()
                    stderr = outstreams[1].getvalue()
...
```

solves the issue for me, but it seems to be a too trivial solution and I am wondering whether I am missing something.

* Python version: CPython 3.9.0
* Click version: 7.1.2

**Comment by davidism** [comment]
It's your code that's missing the flush, not Click. `stderr` is not buffered in the same way `stdout` is, if you call `write` on it directly you need to call `flush` as well. This is a Python thing, not a Click thing.

**Comment by dnicolodi** [comment]
The behavior is the same is I use `print()`:

```python
import sys
import click
import click.testing

@click.command()
def foo():
    print('Foo!', out=sys.stderr)

runner = click.testing.CliRunner(mix_stderr=False)
result = runner.invoke(foo)
assert result.stdout == ''
assert result.stderr == 'Foo!\n'
```

**Comment by davidism** [comment]
This is one of the things that `click.echo` takes care of, by the way. ;-)

**Comment by dnicolodi** [comment]
I argue that there is no need in my application to call `sys.stderr.flush()` as whatever the buffering of `sys.stderr` is, all what is written to it will be flushed before the application terminates. However, this is not true with the interposition of `CliRunner`. I need to modify the application to make testing work.

If stderr is not captured because it is differently buffered, why does `CliRunner` need to explicitly flush stdout as well?
