### ISSUE TITLE
`CliRunner.isolation()` incompatible return type with usage in `invoke()`

### ISSUE THREAD

**Issue by ezdac** [pallets/click#1773]
I did not encounter a problem due to this, but I found inconsistencies in the code.

### Actual Behavior

The tuple yielded by the `CliRunner.isolation()` contextmanager is incompatible with the 
usage in the `CliRunner.invoke()` method.
In the latter, a `BytesIO` object is assumed, while the actual return value is a boolean (literal).

https://github.com/pallets/click/blob/fbe33bac440d0edef50fc980fb638d2dbbf96b5e/src/click/testing.py#L265

https://github.com/pallets/click/blob/fbe33bac440d0edef50fc980fb638d2dbbf96b5e/src/click/testing.py#L370

I guess the intent was to only return the BytesIO when `self.mix_stderr` is True,
So I'd rather bind bytes_error as None before and just pass it 

```python
bytes_error = None
if self.mix_stderr:
    sys.stderr = sys.stdout
else:
    bytes_error = io.BytesIO()
    ...
...
yield (bytes_output, bytes_error)
```
But I'm unsure of what is expected behaviour here, otherwise I would simply fix it.

```
### Environment
* Click version: 7.0

**Comment by davidism** [comment]
Sure, that change makes sense.

**Comment by thisisamardeep** [comment]
i am picking this up.Will get back.

**Comment by Saif807380** [comment]
Hey, I'm a fellow from MLH. I'd like to work on this issue.
