### ISSUE TITLE
Poor response time in progressbar and concatenated outputs on use with multithreading

### ISSUE THREAD

**Issue by t0xic0der** [pallets/click#1776]
When `progressbar` is used in multithreading operations, the poor response time leads to concatenated and unrefreshed outputs. Could you please let me know what is the average response time of refreshing the console when the `progressbar` is used and how can it be reduced in multithreading operations?

Environment:

- Python version: 3.9.1
- Click version: 7.1.2

**Comment by davidism** [comment]
Use tqdm for better progress bars. I don't plan to dig into our implementation more.
