### ISSUE TITLE
Total duration and speed in progressbar.

### ISSUE THREAD

**Issue by jorgeecardona** [pallets/click#1777]
Hi, it would be great to be able to fully replace `tqdm` with `click`. I am particularly missing the information of current duration and speed (depending on units) as the bar progresses, and the total duration at the end of the run.

I am sure I can do this by adding info parts manually, but I feel many of us would get very happy to see this two fields added by default to the progressbar. Neither the total duration nor the speed need to know the length of the iterator, this should be relatively easy to implement.

I just forked the code, and I am up to add this and create a PR. But I would like to know if you have some strong comments against this, or previous ideas on how to implement it.

**Comment by jcrotts** [comment]
I don't think we are interested in making the progress bar implementation more complicated. In fact, I think David recommends `tqdm` when people are looking for progress bar features that Click doesn't have. That being said, if your PR doesn't add too much complexity it might be considered.

**Comment by davidism** [comment]
Yes, please use tqdm, I don't plan to add more to our implementation.
