### ISSUE TITLE
Readable and ergonomic way to create a command from a function

### ISSUE THREAD

**Issue by alexeymuranov** [pallets/click#1780]
Suppose i have a function that takes some arguments and then reads from `stdin` or a file and writes to `stdout` or a file. Suppose i want to keep it as a part of the API, and i do not want its definition to depend on `click`, but i want to make a command-line application from it using `click` to parse and validate the command line.

According to #1054, it is suggested to do something like this:
```python
import click

def hello_fun(name):
    print("Hello {}".format(name))

@click.command()
@click.option( '--name',
               prompt='Your name',
               help='The person to greet.' )
def hello_cmd(name):
    return hello_fun(name)

if __name__ == '__main__':
    hello_cmd()
```

However, i do not feel like adding an extra wrapper and an extra call stack frame just to make the code look neat, for no functional benefit. I would rather do this:
```python
import click

def hello_fun(name):
    print("Hello {}".format(name))

hello_cmd = hello_fun
for d in ( click.option( '--name',
                         prompt='Your name',
                         help='The person to greet.' ),
           click.command() ):
    hello_cmd = d(hello_cmd)

if __name__ == '__main__':
    hello_cmd()
```

I would have liked however if this could be done in a more readable and ergonomic way.

**Comment by davidism** [comment]
```python
hello_cmd = click.Command(
    "hello",
    params=[click.Option(["--name"], prompt="...", help="..."),
    callback=hello_fun,
)
```

**Comment by alexeymuranov** [comment]
Thanks.
