### ISSUE TITLE
Support not running group body when subcommand is asked for help

### ISSUE THREAD

**Issue by jwodder** [pallets/click#1789]
Consider the code below:

```python
import click

@click.group()
def main():
    """ Run code """
    click.echo("Code is running.")

@main.command()
def foo():
    """ Do foo """

if __name__ == '__main__':
    main()
```

When this script is run with `python script.py --help`, just the help for the main command is displayed, as expected.  When the script is run with `python script.py foo --help`, however, the body of the `main()` function is run before the help text for `foo` is displayed, and the line "Code is running." is printed out above the help text.  I would like to request some built-in method to prevent the `main()` function from running when a subcommand is asked for help.

As far as I am aware, the best way to currently get what I want is via [this SO answer](https://stackoverflow.com/a/54163623/744178), which moves the body of `main()` into a wrapper around `Command.invoke()`.  This strikes me as needlessly complicated, and I expect there should be a better way.

**Comment by davidism** [comment]
Click is dynamic, there's no generic way for it to know what `foo` is without executing everything before it. There are other related issues open about this regarding `--help` and completions.
