### ISSUE TITLE
 Differentiating between an option being unset via environment variables, and being set to an empty string

### ISSUE THREAD

**Issue by underyx** [pallets/click#1790]
I'm not confident in my proposal, because I'm sure that setting the env var `STRING_OPTION=""` results in `string_option is None` by an intentional design decision. But perhaps string options' values could be set to `""` when the environment variable is set to an empty string.

However, we have two common failure cases in https://github.com/returntocorp/semgrep-action: either people don't set a required API token option at all (`API_USERNAME="foo" cli-command`), or people try to set it via a GitHub Actions secret, but this secret is unavailable for any number of reasons, and thus ends up rendering as an empty string (`API_USERNAME="foo" API_TOKEN="" cli-command`). We'd like to be able to differentiate between these two cases so we can print more useful error messages. In both cases currently, `api_token` will be set to `None`. It would be nice to tell the difference without our code having to understand what environment variable name click will generate for a given option.

**Comment by davidism** [comment]
The behavior is deliberate, see #1304.

> Empty environment variables are ignored rather than taking the empty string value. This makes it possible for scripts to clear variables if they can't unset them.

**Comment by ulope** [comment]
This is a really unfortunate change since it's breaking backwards compatibility.

The rationale for this change IMO doesn't hold water. There are many ways to remove variables from the environment. The `env` command being the easiest for example.
