### ISSUE TITLE
filename_to_ui is not defined [FileError, Python(3.8.2), Click(7.1.2)]

### ISSUE THREAD

**Issue by mpetrinidev** [pallets/click#1802]
I'm receiving the following error when I try to raise click.FileError exception:

> NameError: name 'filename_to_ui' is not defined

Code:

```
def read_credentials():
    bnc_config_file_path = get_bnc_config_file_path()

    if not os.path.isfile(bnc_config_file_path):
        raise FileError(filename=bnc_config_file_path, hint='Credentials file does not exists')

   .....
``` 

Same in the following test

``` 
def test_read_credentials_file_not_found(mocked_bnc_config_path):
    with pytest.raises(FileError, match='Credentials file does not exists'):
        read_credentials()
``` 

Thoughts?

Environment:

- Python version: Python 3.8.2
- Click version: 7.1.2

**Comment by davidism** [comment]
I can't reproduce this issue. Sounds like there's an issue with your virtualenv or installation of Click.
