### ISSUE TITLE
Move iterable checks from type_cast_value to __init__

### ISSUE THREAD

**Issue by davidism** [pallets/click#1806]
Both the errors raised in `type_cast_value` should be in `__init__` instead. The composite error should be removed from `type_cast_value`, it makes no sense at runtime. Both places that `value` is iterated in `type_cast_value` should raise a `BadParameter` error instead of `TypeError`.

_Originally posted by @davidism in https://github.com/pallets/click/issues/1805#issuecomment-791522850_

**Comment by davidism** [comment]
@Saif807380 want to work on this?

**Comment by Saif807380** [comment]
Sure. I'll have a go at it.
