### ISSUE TITLE
Allow for command "mixins" for better customizability

### ISSUE THREAD

**Issue by thejcannon** [pallets/click#1810]
For `click.command` and `click.group` decorators, they allow for a `cls` param which means the user can use classes which inherit from `Command` or `Group` and add some custom functionality (which is great because then people can author their own customizations instead of bugging y'all).

However this breaks down for two reasons:
1. You have to subclass at least `click.Command` and `click.Group` to ensure clients get the right behavior. (and make sure they choose the right one)
2. Mixing multiple custom behaviors means declaring a new type that's only use is for its bases.

Allowing clients to specify a list of mixins helps alleviate these issues.

As an example:

```python
import click

class FromFilePrefixChars(click.BaseCommand):
    """Adds argparse's fromfile_prefix_chars to the command."""
   
    def parse_args(self, ctx, args):
       # ...
       super().parse_args(ctx args)
   

class NoisyInvocation(click.BaseCommand):
    """Adds a print statement to the command."""

    def invoke(self, *args, **kwargs):
       print("IDK something")
       super().invoke(*args, **kwargs)

@click.command(mixins=[FromFilePrefixChars, NoisyInvocation])
# ...
def cli(...):
    pass
```

Not only is this super easy to implement, but I think this behavior would make extending `click` much easier.

Let me know if you'd like a RFC PR.

**Comment by thejcannon** [comment]
(this should be extended for Parameters as well)

**Comment by thejcannon** [comment]
I was hoping that my comment might spark follow-up discussion about the merits of such a feature, but after a week I assume that isn't going to happen.

As a note, editing your comment to fix the bug and _not_ acknowledging its existence or respond to my points about how easy it is to get this pattern wrong (and how to make it very easy to get it right with a one-or-two-line addition to `click`) turns me off to contributing to this project. I'm quite demotivated to open additional issues/feature requests/PRs and if asked by my peers will like forward that sentiment. It's a shame too, because I quite like `click` and have been advocating for it to be our "one true CLI toolkit".

CC: @mitsuhiko

**Comment by davidism** [comment]
I was on my phone when writing that code, so the fact that it was well formatted at all was impressive. ;-) However, your further comments didn't sway me, so I'm still not planning to make the proposed change in Click. You're describing an issue you have with subclassing / dependency injection in Python in general, which is not something Click specifically will fix. Thank you for your bringing up the idea.
