### ISSUE TITLE
resolve_path differs on Windows depending on Python version

### ISSUE THREAD

**Issue by daddycocoaman** [pallets/click#1813]
Hi. There was an issue filed under [Typer](https://github.com/tiangolo/typer/issues/244#issuecomment-792455309) that gives a full explanation, but basically the use of `os.path.realpath` in the `resolve_path` logic for click.Path differs between Python 3.7 and 3.8 on Windows. Prior to 3.8, `os.path.realpath` did not resolve symlinks. Therefore Click users on Windows using Python 3.7 or lower are getting the wrong results for resolve_path.

More info: https://docs.python.org/3/library/os.path.html#os.path.realpath

**Comment by davidism** [comment]
I'm not sure what you're proposing click should do here.

**Comment by daddycocoaman** [comment]
Sorry...I probably should have specified the solution. 

[This resolve path logic](https://github.com/pallets/click/blob/master/src/click/types.py#L736) needs to account for symbolic links, particularly for the Windows issue.

The way to do this is to check if the path is a link with `os.path.islink`, and if it is, then get the path with `os.readlink`.  That seems like the best cross-platform solution, and I don't think it should break anything. 

I would normally submit a PR but currently super occupied this month. 🤔

**Comment by BALaka-18** [comment]
@davidism , @jab I'm an MLH Fellow, I am working on this issue.

**Comment by davidism** [comment]
This is causing issues: #1921, #1958. I'm going to revert this change. Update your Python version if you want the behavior offered in a later Python version.
