### ISSUE TITLE
No such option error when an argument starts with "-"

### ISSUE THREAD

**Issue by orlevii** [pallets/click#1817]
Argument cannot  start with `-`

Let's take a simple example:

`main.py`
```python
import click


@click.command()
@click.argument('params', nargs=-1)
def cmd(params):
    print(params)


if __name__ == '__main__':
    cmd()
```

When running: `python main.py a b c` we get the expected result
```
$ python main.py a b c
('a', 'b', 'c')
```

But when one of the arguments starts with `-` we get `Error: no such option`:
```
$ python main.py a b -c
Usage: main.py [OPTIONS] [PARAMS]...
Try 'main.py --help' for help.

Error: no such option: -c
```

I made it work with the following syntax:
```
$ python main.py -- a b -c
('a', 'b', '-c')
```
But I'm not sure this is how it should behave.

I want to accept everything, that's why I'm using `nargs=-1`.
Is there a way to make that work? 

Environment:

- Python version: 3.7
- Click version: 7.1.2

**Comment by davidism** [comment]
Use `--` to separate options from argument values that look like options. Using `allow_interspersed_args=False` might help as well.
