### ISSUE TITLE
Support for styling with rich

### ISSUE THREAD

**Issue by rlanyi** [pallets/click#1824]
Hello, would it be possible to use [rich](https://github.com/willmcgugan/rich) in help outputs? It would be a nice addon and if it's not installed Click could fallback to the current behavior with `echo`.

This way it would be possible to print colorized and formatted help for the commands like `A [red]complex[/red] command line interface.`.

**Comment by davidism** [comment]
I don't know exactly how rich works, but presumably it already has functions to format a string. So `click.echo(rich.style(...))` is all you need.

**Comment by rlanyi** [comment]
Sorry, maybe I was not clear enough about my goal here. What I'd like to achieve is to use the same default output from Click, but run it through rich, so if it contains any special formatting strings then those would be applied.

It is not that easy because the `--help` invokes `Command.get_help()` which after all will invoke `HelpFormatter.write()` which writes only to a memory buffer, and after all the whole thing will be flushed from a `TextIOWrapper` in `utils.echo()`.

I couldn't find the place where this could be captured into a variable.

**Comment by davidism** [comment]
You can override `Command.format_help` if you want to change how help is presented.

**Comment by willmcgugan** [comment]
There is an ongoing discussion about integrating Rich with Click [here](https://github.com/willmcgugan/rich/discussions/1121).
