### ISSUE TITLE
Document argument callbacks

### ISSUE THREAD

**Issue by injust** [pallets/click#1826]
Callbacks for options are [documented](https://click.palletsprojects.com/en/7.x/options/#callbacks-for-validation). Similar functionality is available for arguments, but is not documented.

The main difference is that the 2nd parameter (passed to the callback function) is of type `click.Argument` instead of `click.Parameter`. If reusing the example from the Options page, the example code should be adjusted so the function signature is `validate_rolls(ctx, arg, value)`.

The other issue I encountered is that the types in [typeshed](https://github.com/python/typeshed/tree/master/stubs/click) are incompatible.

```
Argument "callback" to "argument" has incompatible type "Callable[[Context, Argument, str], str]"; expected "Optional[Callable[[Context, Union[Option, Parameter], Any], Any]]"  [arg-type]
```

**Comment by davidism** [comment]
Sounds like typeshed needs to be fixed. Note that they are a third party library, not official type annotations.

**Comment by davidism** [comment]
The second parameter is the parameter calling the callback. Options and Arguments are both Parameter, with some parsing differences.
