### ISSUE TITLE
Address public CVE PRISMA-2021-0020 on 7.x patch

### ISSUE THREAD

**Issue by axsaucedo** [pallets/click#1833]
A CVE has been reported on 7.1.2 via PRISMA-2021-0020, this has been reported fixed in 8.0.0 but 8.x is still pre-release. Is there a timeline to either release 8.x, or perhaps to do a patch release (eg 7.1.3) with the CVE fix so we can upgrade.

**Comment by davidism** [comment]
No one has reported anything to us via security@palletsprojects.com, and I can't find any information about the CVE.

Please follow https://github.com/pallets/click/security/policy to report security issues. Do not post them in public issues.
