### ISSUE TITLE
urllib.unquote() no longer exists

### ISSUE THREAD

**Issue by nagelp-bosch** [pallets/click#1838]
In [_termui_impl.py](https://github.com/pallets/click/blob/972becff259e4ffcd220a6cad5096f36a89fdd6d/src/click/_termui_impl.py#L556) `urllib.unquote()` is called. But [urllib](https://docs.python.org/3/library/urllib.html) is a package now. Equivalent functionality is available in the urllib.parse module.

**Comment by davidism** [comment]
Happy to review a PR.
