### ISSUE TITLE
Help us avoid repeating help/prompt text :)

### ISSUE THREAD

**Issue by spioter** [pallets/click#1841]
Allow us to use the same string for both [prompt] and [help] options.

Example, my current code: 
`@click.option('--project_name', '-n', help='the project name (it will be part of its path)', required=True, prompt='the project name (it will be part of its path)')
`

My preferred code would be to only put the help/prompt string once, something akin to:
`@click.option('--project_name', '-n', required=True, prompthelp='the project name (it will be part of its path)') #a new option that would send the string to both prompt and help`

or either of the below, just allow us to refer to the prompt/help string as needed

`@click.option('--project_name', '-n', required=True, help='the project name (it will be part of its path)', prompt=help)
`
or
`@click.option('--project_name', '-n', required=True, prompt='the project name (it will be part of its path)', help=prompt)
`

**Comment by davidism** [comment]
```
message = "..."

@click.option(... help=message, prompt=message
```

**Comment by spioter** [comment]
I thought of this workaround but it doesn't strike me as very click-like - we no longer have self-documenting code with "a place for everything and everything in its place". Instead, we have two places :-/

**Comment by spioter** [comment]
I did a bit more due diligence and found the show_default option mentioned in another issue.

The analogous fix would be to allow the help message to include the prompt: 
show_prompt=True
