### ISSUE TITLE
add a `first_col_width` argument to `HelpFormatter.write_dl`

### ISSUE THREAD

**Issue by janLuke** [pallets/click#1851]
## What problem does it solve?
It allows clients of `HelpFormatter` to align multiple definition lists.

### My specific problem
I'm the author of [Cloup](https://github.com/janLuke/cloup) and I need to format option groups as multiple help sections with aligned definition lists. 

I resorted to a smart hack that makes use of padding, but I'm going to subclass `HelpFormatter` and add this and other changes since the hack has several drawbacks (that might not be evident at first).

Since this change is very simple, I thought it'd be nice to include it in click as well.

## Implementation
Currently, the width of the first column is computed inside `write_dl`. I propose to allow the clients to provide it as argument:
```python
    def write_dl(
        self, rows, ..., 
        first_col_width: Optional[int] = None
    ) -> None:
        if first_col_width is None:
            first_col_width = self.compute_first_col_width(rows, col_max)
```

In this way, the client of `HelpFormatter` can compute the `first_col_width` based on all rows of all sections to align.

`compute_first_col_width` is an optional. It allows subclasses to override the default behavior. For example, I'm excluding the strings longer than `col_max` from the computation, since those rows will have the first column on their own rows anyway.

If you approve this, I can open a PR.
Thank you.

**Comment by davidism** [comment]
Going forward, you know my stance on what I want to focus on with formatting, I'm not particularly inclined to make small changes along the way as there's no guarantee they'll be relevant or compatible in a larger refactor.

You can probably already do this in a subclass without any changes on Click's part, considering you're probably already overriding `write_dl`:

```python
class Formatter:
    def __init__(self, ...):
        self.first_width = None

    def write_dl(...):
        if self.first_width is None:
            self.first_width = compute_default()
        ...
```

That said, if you feel this change will make a meaningful difference in how you write cloup, and can get an easy-to-review PR in today, I can add it, although depending on when I make a release candidate it may not be present until the final release.

**Comment by janLuke** [comment]
No, I agree. If a major refactoring is coming, it's probably useless to add this now. I'm going to subclass HelpFormatter anyway in Cloup. Maybe, you can keep this use case in mind for when you design :)

> you know my stance on what I want to focus on with formatting

Actually, I know very little.
