### ISSUE TITLE
URLs into Clickable Links

### ISSUE THREAD

**Issue by mrjatinchauhan** [pallets/click#1857]
It would be easily noticeable to have Clickable links instead of complete URL for webpages.
Using `[Webpage](link url)`

For Example:
```markdown
Links
-----

-   [Documentation](https://click.palletsprojects.com/)
-   [Changes](https://click.palletsprojects.com/changes/)
-   [PyPI Releases](https://pypi.org/project/click/)
-   [Source Code](https://github.com/pallets/click)
-   [Issue Tracker](https://github.com/pallets/click/issues)
-   [Website](https://palletsprojects.com/p/click)
-   [Twitter](https://twitter.com/PalletsTeam)
-   [Chat](https://discord.gg/pallets)
```

We can also use [Shields.io](https://shields.io/), for legible badges. It can be used for badge of twitter, discord, etc.

**Comment by davidism** [comment]
Thanks, but the format is deliberate, and the links are already clickable.
