### ISSUE TITLE
Pass global parameters without context

### ISSUE THREAD

**Issue by chrisroat** [pallets/click#1868]
The recommended way to pass a global option is to pass a context in to your functions, and store/retrieve information with that context object.

```
import click

@click.group()
@click.option('--database')
@click.pass_context
def cli(ctx, database):
    ctx.ensure_object(dict)
    ctx.obj['database'] = database

@cli.command()
@click.pass_context
def initdb(ctx):
    click.echo('Init db %s' % ctx.obj['database'])

@cli.command()
@click.pass_context
def dropdb(ctx):
    click.echo('Drop db %s' % ctx.obj['database'])

if __name__ == '__main__':
    cli()
```

I see several drawbacks to this approach:
- Its a bit verbose
- Care must be taken to document what the context object must contain.
- Testing seems difficult. Unit testing would more naturally a signature like `initdb(database)` rather than `initdb(ctx)`, with the effective signature stored as a dictionary.

I find myself resorting to the following and testing `initdb_internal` instead.

```python
@cli.command()
@click.pass_context
def initdb(ctx):
    initdb_internal(**ctx.obj)

def initdb_internal(database):
    click.echo('Init db %s' % database)
```

Would a pattern like the following be possible, where options can be passed to commands based on the signature?

```python
import click

@click.group()
@click.option('--database', command_usable=True)
def cli(database):
    pass

@cli.command()
def initdb(database):
    click.echo('Init db %s' % database)

@cli.command()
def dropdb(database):
    click.echo('Drop db %s' % database)


if __name__ == '__main__':
    cli()
```

**Comment by davidism** [comment]
You're looking for `@pass_object` https://click.palletsprojects.com/en/7.x/api/#click.pass_obj or `@make_pass_decorator`. Beyond that, I don't plan to have parameters automatically forwarded to subcommands.
