### ISSUE TITLE
Allow ANSI escapes codes in metavar hints

### ISSUE THREAD

**Issue by AdrienPensart** [pallets/click#1869]
Hello,

little quirk when printing metavar hint : 
`
Error: Missing argument '\x1b[95mREGION\x1b[0m'.
`

region argument was declared like this : 
`
region_argument = click.argument('region', metavar=click.style('REGION', fg='bright_magenta'))
`

It should be printed with magenta color : 

`
Error: Missing argument 'REGION'.
`

Environment:

- Python version: 3.6
- Click version: > 8.0 / master

**Comment by davidism** [comment]
I don't think this was ever intended to work.
