### ISSUE TITLE
Click 8.0 does not support mypy's no_implicit_reexport

### ISSUE THREAD

**Issue by tucked** [pallets/click#1879]
Looks like 8.0.0 started shipping type annotations (yay!): https://github.com/pallets/click/commit/0103c9570650daa59560baf42ad0a27e57b3157f

Something doesn't seem to be clicking (no pun intended 😁) with `mypy` , though:
```
error: Name 'click.Context' is not defined
error: Name 'click.Option' is not defined
error: Module has no attribute "command"; maybe "Command"?
error: Module has no attribute "option"; maybe "Option"?
error: Module has no attribute "IntRange"
error: Module has no attribute "Choice"
error: Name 'click.Context' is not defined
error: Module has no attribute "argument"; maybe "Argument"?
error: Module has no attribute "pass_context"
error: Module has no attribute "secho"; maybe "echo"?
error: Module has no attribute "echo"; maybe "secho"?
```

Anyone else seeing this or know what's up?

**Comment by davidism** [comment]
Please provide a minimal reproducible example. It's not clear that this is an issue with Click vs MyPy vs typeshed.

**Comment by tucked** [comment]
``` py
# foo.py
import click

def foo(option: click.Option) -> None:
    pass
```
``` sh
python3 -m venv venv
venv/bin/pip install --upgrade 'click>=8' mypy
venv/bin/mypy --strict foo.py
```
```
foo.py:3: error: Name 'click.Option' is not defined
Found 1 error in 1 file (checked 1 source file)
```

**Comment by tucked** [comment]
I've updated the title because that repro ☝️ doesn't seem to happen without `--strict`.

**Comment by JelleZijlstra** [comment]
This is about the `--no-implicit-reexport` flag: https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport. Click's `__init__.py` has a bunch of lines like `from .module import Name`. With that flag on, mypy doesn't treat such names as being re-exported, and to make it accept the code you need to do `from .module import Name as Name`.

That said this seems a bit too strict in this case, so maybe mypy should change its behavior to be more permissive here.

**Comment by tucked** [comment]
Workaround is to pin `click<8` so that `mypy` falls back to using `typeshed`.

**Comment by davidism** [comment]
I don't know why you're confused over this. This is a configuration you add to your own project.

```
[mypy-click]
no_implicit_reexport = False
```
