### ISSUE TITLE
cli not working when freezing into an executable using cx_freeze

### ISSUE THREAD

**Issue by buckettt** [pallets/click#1883]
My simple app works nicely as an exectuable when calling from the command line with arguments e.g. `myscript.exe --fpth_docx args` however when running without arguments the cli does not work. Running using `python myscript.py` is fine. 

myscript.py:
```
@click.command()
@click.option('--fpth_docx',
              default=FPTH_DOCX_DEFAULT,
              prompt='fpth_docx',
              help='insert filepath (or list of filepaths) of docx file to convert to pdf')
def click_command(fpth_docx, fpth_pdf, update_toc, openfile, repeat_table_headings):
    """
    click command line tool for running docx_to_pdf
    """
    docx_to_pdf(fpth_docx=fpth_docx,
                fpth_pdf=fpth_pdf,
                update_toc=update_toc,
                openfile=openfile,
                repeat_table_headings=repeat_table_headings)

if __name__ == '__main__':
    click_command()
```

Is this a known issue when freezing to an executable?

Environment:

- Python version: 3.9
- Click version: 7.1.2
- cx_freeze: 6.6

**Comment by davidism** [comment]
I'm sorry, I don't know anything about cx_freeze, so I can't help you with this.
