### ISSUE TITLE
Callback behavior has changed in 8.0.0 and raises exception now

### ISSUE THREAD

**Issue by p5a0u9l** [pallets/click#1888]
My CLI application has started raising an exception which wasn't happening in the previous release. Image of traceback below
![image](https://user-images.githubusercontent.com/4721335/118023907-ebb19880-b312-11eb-858a-71cfe5ce42ba.png)

Here is minimal repro code
```python
import socket
import click


def cb_validate_ipaddr(_, value):
    """Click callback to validate IP addresses"""

    # allow not setting ipaddr
    if value is None:
        return value

    try:
        socket.inet_aton(value)
    except socket.error:
        raise socket.error from click.BadParameter(
            f"Option must be valid IPv4 address. Got '{value}'"
        )

    return value


@click.group()
def cli():
    """App CLI"""


@click.option(
    "--ipv4",
    "-i",
    type=str,
    callback=cb_validate_ipaddr,
    default=None,
    help="IPv4",
)
@cli.command("app")
def app(ipv4):
    """App CLI"""
    print(ipv4)


if __name__ == "__main__":
    cli()
```

with `click==7.1.2`, executing this code prints the `ipv4` argument, with 8.0.0, I get the traceback above

Environment: x86 Linux, Ubuntu18.04, virtualenv

- Python version: 3.7.10
- Click version:8.0.0

**Comment by davidism** [comment]
The 2-arg format has raised a warning for quite a long time (since 2.0 I think), and has finally been removed in 8.0. Be sure to run your tests with warnings turned into errors so you can see what you need to update sooner.

The supported format is:

```python
def callback(ctx: click.Context, param: click.Parameter, value: Any) -> Any: ...
```
