### ISSUE TITLE
mypy error on progress bar usage

### ISSUE THREAD

**Issue by decaz** [pallets/click#1892]
xxx.py:
```python
import click

with click.progressbar([1, 2, 3]) as bar:
    for x in bar:
        pass
```

mypy error:
```
$ mypy xxx.py 
xxx.py:4: error: "Iterable[<nothing>]" has no attribute "__next__"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

Environment:

- Python version: 3.9.5
- Click version: 8.0.0
- mypy version: 0.812

**Comment by jcrotts** [comment]
Changing the return type in `ProgressBar.__iter__` https://github.com/pallets/click/blob/9da166957f5848b641231d485467f6140bca2bc0/src/click/_termui_impl.py#L104 from `t.Iterable[V]` to `t.Iterator[V]` fixes the mypy error, but it requires that you declare the type of x. 
I'm also not sure if it's the correct thing to do type wise.

**Comment by davidism** [comment]
I'm working in this, going to use generics since it shouldn't affect performance in this case
