### ISSUE TITLE
Click 8.0.0 do not infer bool type anymore from default value

### ISSUE THREAD

**Issue by vallsv** [pallets/click#1897]
Hi, while reaching regression on `coilmq` package runner, i found this behaviour change between click 7 and 8

It looks like `click` 7 was infering bool type from the `default` value, but it is not the case anymore.

Which looks to fail the `coilmq` package, wich was not updated for a while.

Is that something you would like to support back on your side?

# Sample code
```
import click

@click.command()
@click.option("--bool_test", default=False, help="Test bool")
def main(bool_test):
    print("click", click.__version__)
    for n, v in locals().items():
        print(n, v, type(v))

if __name__ == '__main__':
    main()
```

# Click 7
```
$ pip install click==7
$ python test.py
click 7.0
bool_test False <class 'bool'>
```

# Click 8
```
$ pip install click==8
$ python test.py
click 8.0.0
bool_test False <class 'str'>
```

**Comment by vallsv** [comment]
Most probably duplication of #1886 ?

**Comment by jcrotts** [comment]
Related to https://github.com/pallets/click/issues/1886, same behavior with different types. You can work around this by specifying the type in the option.

**Comment by vallsv** [comment]
I am not sure i understand. Could you answer if you want to fix this regression?
Cause i can't work around. I am not the owner of the library i talk about.
