### ISSUE TITLE
Arguments may break `--help`

### ISSUE THREAD

**Issue by terencehonles** [pallets/click#1899]
Using `click.Path` for an argument may prevent the `--help` from showing up. A simple example is the following:

```
@click.command()
@click.option(
    "-f",
    type=click.Path(exists=True, file_okay=True),
    default="this does not exist",
    help="Output file name",
    show_default=True,
)
def cli():
    pass
```

When trying to print the `--help` the default argument will be checked for validity and instead print an error that `-f` is an invalid value.

Environment:

- Python version: Python 3.8.9
- Click version: 8.0.0

**Comment by davidism** [comment]
Hard to say whether this should be an issue. If you're going to give a default to `Path(exists=True)` that doesn't exist, you're going to have to address that anyway, as it will fail when not using `--help` too.

**Comment by terencehonles** [comment]
@davidism as an end user if you're not using `--help` it's still going to print what you need to fix. If you still don't understand the message, the current behavior blocks even looking at the `--help` to see if there's anything more that would be helpful or look at what all the arguments mean.

I understand the value will need to be addressed by the developer and potentially the end user, but how should a developer handle catching the error in the `--help` path and allow or unset defaults that might be problematic / allow printing the default as given as I did in the PR?

Regarding your comment (mentioning here just to keep the discussion in one place):

> I don't think it's the correct fix, `call=False` is used for more than generating help, ignoring errors in that case has wider potential effects.
https://github.com/pallets/click/pull/1900#issuecomment-843673138

It didn't look to be the case when I scanned the code, but I may have missed something and I understand this may be overloading the `call` argument more than is desired.

Is the only option moving either the default or the existence check into the beginning of the command? I couldn't tell if this code was new as I was simply contributing to a library which already used `click` and I was upgrading it to `click` 8 to allow it to use the typing that is provided, but I would have expected since `click` is auto-generating the `--help` it's `click`'s responsibility to _try_ to render the help as much as it can. Falling back to the default as given doesn't seem like a very big ask, but I understand it may need to be done in a different manner than I had implemented in #1900.

**Comment by davidism** [comment]
The problem shouldn't be seen by an end user. You shouldn't be shipping code that has a default that doesn't actually work with the given type.

**Comment by davidism** [comment]
OK, so the issue is that you want to provide a default value that may or may not exist and show that in help text. The problem is that the processing pipeline changed to apply type casting consistently to parameter values, including when getting defaults.

**Comment by terencehonles** [comment]
Thanks for the change.
