### ISSUE TITLE
Allow disabling pattern expansion on Windows

### ISSUE THREAD

**Issue by ofek** [pallets/click#1901]
## TL;DR

Essentially, make this optional: https://github.com/pallets/click/pull/1830

## Use case

We have a command that passes arbitrary arguments to be executed in other contexts such as Docker containers, servers over SSH, etc.

On Windows since Click 8.0 this breaks (depending on files in cwd, etc.) and unlike on Linux we can't just escape special characters

## Implementation

Setting could be called `disable_pattern_expansion`, e.g.:

```python
import click


@click.command(
    context_settings={'help_option_names': [], 'ignore_unknown_options': True, 'disable_pattern_expansion': True},
)
@click.argument('args', required=True, nargs=-1)
@click.pass_obj
def run(app, args):
    environment = app.get_environment()
    environment.send_command(args)
```

**Comment by ofek** [comment]
I looked into the code and it appears nested commands will have already received expanded arguments so `disable_pattern_expansion` will need to be of type `t.Optional[t.Union[bool, t.List[str]]]` and if nesting then defined on the group as a list of sub-command names to ignore.

**Comment by davidism** [comment]
Can you provide an example of what goes wrong, so we can explain better in the changelog? Also, there was some discussion of escaping in the original issue, maybe it can help?

**Comment by ofek** [comment]
Basic example:

```cli run external-tool *.log```

now would run `external-tool` on the other system with expanded args if there are any log files in the current directory.

On Linux we can do:

```cli run external-tool \*.log```

but on Windows the Click args become `('external-tool', '\\*.log')`

**Comment by davidism** [comment]
Not ideal, I understand, but the original feature request discussed escaping https://github.com/pallets/click/issues/1096#issuecomment-415892327

> Python's glob module lets you use `[]` for quoting. (E.g., the pattern `[*].txt` matches the literal filename `*.txt`.) Not very intuitive, but it is possible, and I guess Windows users are used to weird edge cases when trying to use the cli to refer to files with `*` in the name?

**Comment by ofek** [comment]
> Windows users are used to weird edge cases when trying to use the cli to refer to files with `*` in the name

Actually, us Windows users are accustomed to CLIs not supporting expansion by default 😉 

> Python's glob module lets you use `[]` for quoting

What about `~` and env vars?

I guess the point I'm trying to stress is that certain inputs can no longer be achieved in a cross-platform way

**Comment by davidism** [comment]
Pinging @njsmith and @asweigart for their thoughts since they participated in the original discussion.

Due to the way the processing pipeline works, the expansion has to be done at the beginning, before any parsing of the command line is done. This would be an all or nothing toggle, either no expansion happens for any command, or it happens for every command.

**Comment by ofek** [comment]
Thank you!!!

**Comment by davidism** [comment]
A follow up to this is #2195, which points out that we could assume any error in glob expansion on Windows could be treated the same as no glob expansion: keep that arg as-is. So in that case you might be able to leave expansion enabled for your app.
