### ISSUE TITLE
Completion behaviour for options/arguments with empty incomplete

### ISSUE THREAD

**Issue by DEvil0000** [pallets/click#1907]
### Trying to explain current state
As one can experiance using click scripts or can also see in the test cases the completion behavior for "empty incomplete strings" is not consistent and sometimes unexpected (- for bash at least).
Commands and groups get shown as possible input on an empty incomplete string.
Options and arguments do not get shown as possible input on an empty incomplete string.
There is however a exeption for arguments with defaults if I got that correct.

example from test cases as it is today - option on command with empty incomplete string
```
def test_command():
    cli = Command("cli", params=[Option(["-t", "--test"])])
    assert _get_words(cli, [], "") == [] 
```

### Difference to most command completions - using bash
For most bash commands it it normal to provide a list of possible options/arguments on double tab as completion list "on an empty incomplete string". (Basically the normal bash completion shows all options or at least the most important ones on empty incomplete.) I would like to see this behavior beeing changed in click.

### Suggested change/improvement
Maybe it would be best to add a context config option and/or config per option/argument if this should be the behavior/default behavior.
For options providing a short and long name (and flags maybe) it might be best to implement an additional context config option if the short name or the long name should be prefered to be shown as completion option - or both should be shown by default resulting in a potential long list.

suggested expectation change according to this test case:
```
def test_command():
    cli = Command("cli", params=[Option(["-t", "--test"])])
    assert _get_words(cli, [], "") == ["--test"] 
```

**Comment by davidism** [comment]
This is deliberate, options are only completed if at least the the option prefix `-` is given.

**Comment by DEvil0000** [comment]
@davidism Ahm, yes this is what I see in the test cases as well but this is not a normal behaviour (at least for bash commands). In my eyes is is also more convinient to show all options in such a case instead of none.
Since this may not be what everyone wants I thought a config value to change the behaviour in the Context would be nice.

overriding `Command.shell_complete` is exactly what I will do but I considered this more a workaround so I opened this issue.
