### ISSUE TITLE
Parameter.name is of type Optional[str]. Shouldn't it be str?

### ISSUE THREAD

**Issue by janLuke** [pallets/click#1911]
The type of `name` seems to be inferred from the return type of `_parse_decl()`, but as far as I can see:
- all parameters should have a name
- concrete implementations of `_parse_decl` raise `TypeError` if they can't assign a value to `name`. 

(I'm getting several MyPy errors for this reason in Cloup.)

Thank you.

**Comment by davidism** [comment]
Unfortunately discovered this while adding type annotations myself, I had to deal with a bunch of errors too. I left a detailed note in #1856 regarding it, I think we could definitely try to refactor this, but we can't change the type until then.

**Comment by janLuke** [comment]
What about either:
1. always requiring a name, even for unexposed parameters
2. or just changing `name` type to str and set `name` to the empty string in case it is not provided and `expose_value is False`.

Either solutions would work for my specific issues.
