### ISSUE TITLE
Allow overriding exception text

### ISSUE THREAD

**Issue by fubuloubu** [pallets/click#1917]
Inheriting from `ClickException` has a small problem: It always appends `Error: ` to the front of the exception text.

https://github.com/pallets/click/blob/9da166957f5848b641231d485467f6140bca2bc0/src/click/exceptions.py#L43

Overriding that would be useful if you are trying to maintain a consistent style and/or color scheme with log messages and warnings/errors

---

Could easily make a somewhat backwards-compatible update to allow overriding the prepended string via the following:

```python
    def format_message(self) -> str:
        return f"Error: {self.message}"

    ...

    def show(self, file: t.Optional[t.IO] = None) -> None:
        if file is None:
            file = get_text_stderr()

        echo(_(self.format_message()), file=file)
```

**Comment by fubuloubu** [comment]
> we now wrap everything with gettext, which means that could be used to substitute the string.

Can you explain more what this means?

**Comment by davidism** [comment]
Yes, set up translations with gettext and you can substitute whatever you want, for multiple languages even.
