### ISSUE TITLE
Running a cli with pytest inside runner.isolated_filesystem with an arg default=os.getcwd() defaults to pytest cwd, instead of the tmp_path wd

### ISSUE THREAD

**Issue by Smattacus** [pallets/click#1922]
I have a cli that has an argument of type `click.Path()` that defaults to `os.getcwd()`. It seems that the `os.getcwd()` in the default part of the argument decorator runs in the pytest invocation cwd, rather than the temp directory of my fixture.

# CLI Program:

```
import click
import os
from pathlib import Path

@click.command()
@click.argument('path_from_arg', type=click.Path(), required = False, default=os.getcwd())
def hello(path_from_arg):
    """Simple program that prints the input path."""
    click.echo(f'Path from arg default: {path_from_arg}')
    cwd = os.getcwd()
    print(f"cwd from os.getcwd() in body is {cwd}")
    (Path(cwd) / 'test.none').touch()

if __name__ == '__main__':
    hello()
```

# Test program:

```
from click.testing import CliRunner
import os
from my_cli import hello

def test_hello_world(tmp_path):
  runner = CliRunner()
  with runner.isolated_filesystem(temp_dir = tmp_path):
    result = runner.invoke(hello, [])
    assert result.exit_code == 0
    assert result.output == 'Hello path!\n'
```

With the debugger and putting a breakpoint at the line `click.echo(f'Path from arg default: {path_from_arg}')`, here is the `path_from_arg` and `os.getcwd()`:

![image](https://user-images.githubusercontent.com/8194512/119037385-86475280-b977-11eb-8660-bb6826cfab8b.png)

## Expected Behavior:

The path from os.getcwd() in the `default=` parameter to @click.argument is the tmp_path directory from the pytest fixture tmp_path.

## Actual Behavior:
The path from os.getcwd() in the `default=` paramter to @click.argument is the pytest invocation directory. os.getcwd() called inside the function works normally it appears.

# Environment:

- Python version: 3.7.4
- Click version: 8.0.1

**Comment by davidism** [comment]
Because `os.cwd()` is executed at import time, not when the test runs. You can use dynamic defaults if you want: `default=os.cwd`.
