### ISSUE TITLE
Progress bar doesn't overwrite correctly on Bash on Windows 7

### ISSUE THREAD

**Issue by cool-RR** [pallets/click#1924]
When using a long-enough label, the progress bar goes crazy and fills the shell, instead of overwriting itself

Video: https://www.dropbox.com/s/1wrfm5tsnhirmts/VID_20210521_203118.mp4?dl=0

Environment:
- MSYS Bash on Windows 7
- Python version: 3.8.1
- Click version: 8.0.1

Code:

```
import click
import time

label = 'This is a long label that causes a bug on Bash / Windows'

with click.progressbar(range(100), length=100, label=label) as progress_bar:
    for item in progress_bar:
        time.sleep(0.1)
```

**Comment by davidism** [comment]
We're no longer working on the progress bar implementation. Use a dedicated library like tqdm to render progress bars.
