### ISSUE TITLE
point to tqdm as an alternative progress bar in the docs

### ISSUE THREAD

**Issue by cool-RR** [pallets/click#1926]
I just spent time changing my program to use `click.progressbar` and then [submitted a bug about it](https://github.com/pallets/click/issues/1924). It was closed with the message "We're no longer working on the progress bar implementation. Use a dedicated library like tqdm to render progress bars."

I wish I knew that in advance. I suggest that the section about `progressbar` in the docs would say that it's deprecated, and to use `tqdm` instead.

**Comment by cool-RR** [comment]
I think that the docs should also say that the progress bar is deprecated, since that seems to be the official position.

**Comment by davidism** [comment]
It's not deprecated.

**Comment by cool-RR** [comment]
I thought that "We're no longer working on the progress bar implementation" means it's deprecated, but I guess we'll agree to disagree.
