### ISSUE TITLE
Shell autocompletion doesn't work for the click 8.0.1

### ISSUE THREAD

**Issue by sio13** [pallets/click#1933]
The shell autocompletion stopped working for me after upgrading the version of click from 7.1.2 to 8.0.1. The shell autocompletion seems not to be present in the latest documentation. Are you planning to implement the feature for the latest click or you have dropped the shell completion feature at all? 

Environment: zsh, bash, fish

- Python version: 3.8.6
- Click version: 8.0.1

**Comment by davidism** [comment]
The system was rewritten, and the command to activate it in your shell config has changed slightly. See https://click.palletsprojects.com/en/8.0.x/shell-completion/ for the documentation.

**Comment by sio13** [comment]
Thank you @davidism
