### ISSUE TITLE
Prompt invokes value_proc on default value (click >= 8.0)

### ISSUE THREAD

**Issue by cjolowicz** [pallets/click#1943]
In #870 the decision was taken that `value_proc` should not be invoked on the default value.

@davidism :

> The default should be the final value, not an intermediate value. value_proc seems intended for user input only.

In #1517 this decision was reverted with the goal to ensure that the default value is converted to the requested type. However, this PR does not mention #870. Previously, this had already been partially reverted as a special case to support the `Path` type (#1020).

It's not quite clear to me if this was an intended change in behavior or a bug. I don't necessarily disagree with the current state. But it does break client code, for example Cookiecutter (see https://github.com/cookiecutter/cookiecutter/issues/1558). If this was an intended change, these projects can probably adapt, although they will likely need to keep some compatibility layer if they wish to continue support for click < 8.0.

Is this change intentional and permanent? Or should we expect click's behavior to change further here? (Sorry in advance if I missed an existing discussion about this on the PRs leading up to click 8.0.)

**Comment by davidism** [comment]
Having a hard time diving into this once again, so I'm going to say that I'm happy with #1517 as-is.
