### ISSUE TITLE
bug or behaviour change in version 8

### ISSUE THREAD

**Issue by aenima-x** [pallets/click#1952]
I'm not sure if its a bug or an expected behaviour change.

```
@click.option(
    '--password', type=str, default=False)
```
In version 7 if no ```--password``` parameter was supplied the value was False (bool).
Now in version 8 the value es "False" as a string.

Environment:

- Python version: 3.9
- Click version: 8.0.1

**Comment by davidism** [comment]
The type isn't actually string if `False` is also a valid value. So either you need to pick a different default, or use a custom type that returns a string or passes through `False`.
