### ISSUE TITLE
Add documentation site redirect from "bashcomplete" to new completions page

### ISSUE THREAD

**Issue by zbentley** [pallets/click#1955]
The google top result for "click shell completions" is https://click.palletsprojects.com/en/7.x/bashcomplete/. However, when I click from that page on the "show me the 8.x/latest version of this doc" link I'm given a 404.

Give that this link is quite popular, it'd be great if the "bashcomplete" page on the 8.x docs existed, and redirected to the main [shell completions doc](https://click.palletsprojects.com/en/8.0.x/shell-completion).

**Comment by davidism** [comment]
Seems to be impossible, Read the Docs won't redirect `/bashcomplete/`, only `/bashcomplete` (no trailing slash), but Sphinx generates links with trailing slashes. I'll report it to RTD, but this should eventually solve itself as Google starts preferring results for the newer version.

**Comment by davidism** [comment]
Never mind, it does seem to be working now.

**Comment by zbentley** [comment]
Thanks for the update @davidism!
