### ISSUE TITLE
IndexError in format_bar()

### ISSUE THREAD

**Issue by obfusk** [pallets/click#1957]
One of my [CI builds](https://gitlab.com/obfusk/fdroiddata/-/jobs/1342670690#L3506) failed with:

```
File ".../site-packages/click/_termui_impl.py", line 176, in format_bar
    chars[
IndexError: list assignment index out of range
```

I've never seen this before. It seems to be a bug that's only triggered in very rare circumstances and hard to reproduce.

Environment:

- Python version: 3.9.5
- Click version: 8.0.1

**Comment by jcrotts** [comment]
Do you have click code from your project/ci build that is causing the issue that you could post?

**Comment by obfusk** [comment]
Sure. But I'm not doing anything interesting :)

```py
with open(file) as f:
  with click.progressbar(f, width = 0, label = "...") as bar:
    for line in bar:
      ...
```

This has worked fine 100% of the time. Except for that single CI build.

**Comment by davidism** [comment]
Closing as there's nothing to reproduce with.

**Comment by obfusk** [comment]
> Closing as there's nothing to reproduce with.

I agree that lacking the ability to reproduce this is a problem. And currently I can't rule out that this was the result of a random bit flip.

But *if* the problem is that the math used to calculate the index has a weird edge case, we could still either fix the math or coerce the value to the appropriate range.

**Comment by obfusk** [comment]
> But if the problem is that the math used to calculate the index has a weird edge case

I'm not convinced that's the case, but I'm certainly not convinced it isn't either :)
