### ISSUE TITLE
Param decorators assume `attrs[key] is not None` just because `key in attrs`

### ISSUE THREAD

**Issue by janluke** [pallets/click#1959]
The following lines cause a `TypeError` if one provide `help=None`:

https://github.com/pallets/click/blob/8b48450d5d63c747600e069d4c3e2274f41c8360/src/click/decorators.py#L244-L245

By the way, why is `cleandoc` called by the decorator and not by `Option` itself? The docstring says "all keyword arguments are forwarded unchanged (except ``cls``)".

The same problem appears when passing `cls=None` (also with `@argument`):

https://github.com/pallets/click/blob/8b48450d5d63c747600e069d4c3e2274f41c8360/src/click/decorators.py#L246-L247

I encountered this problem while writing a wrapper for the above decorators that explicitly list arguments for a better IDE support.

**Comment by davidism** [comment]
> By the way, why is `cleandoc` called by the decorator and not by `Option` itself? The docstring says "all keyword arguments are forwarded unchanged (except `cls`)".

Good question, I've noticed this before as well. Let's make that a separate PR for 8.1.0.

**Comment by janluke** [comment]
> I think it's because cleandoc is mostly useful when getting the doc from a decorated function's docstring, not for manually written strings

But `option.help` is never taken from the docstring. Probably it was put there for similarity with `@command`.

> Let's explore changing that with an 8.1.0 PR, to see if there are any unexpected side effects.

There shouldn't be any problem in moving this processing into `Option`. I'll check it out.

> Can you open a separate issue for that?

Yep.
