### ISSUE TITLE
flag_value paramters are cast with the wrong type 

### ISSUE THREAD

**Issue by tozka** [pallets/click#1960]
Since click 8.0 passing flag_value enum value , it is converting it to string which breaks the CLI.  (7.x works fine)

For example

```
@unique
class Operation(Enum): 
    CREATE = "create"
    UPDATE = "update" 

@click.option(
    "--update",
    "operation",
    flag_value=Operation.UPDATE
)
@click.option(
    "--create",
    "operation",
    flag_value=Operation.CREATE
)
def my_cli(operation)
   if operation == Operation.CREATE: 
       print("create")
  
 if operation == Operation.UPDATE: 
       print("UPDATE")
  ```

if are run it with `cli --create `

**Expected behavior** 

operation is Operation.CREATE of type Operation and the cli prints "create" 

**Actual behavior** 
operation is a string with value "Operation.CREATE"  and the cli prints nothing 

Environment:

- Python version: 3.7+
- Click version: 8.0

**Comment by davidism** [comment]
The default param type for types that Click does not have special handling for is `str`. Click does not have special handling for `Enum`. The processing pipeline was updated to apply type casting to all data sources consistently. Either use `type=click.UNPROCESSED` or write a custom type to handle enum members.
