### ISSUE TITLE
Allow for the ability to check whether a Path has an executable bit set

### ISSUE THREAD

**Issue by sielicki** [pallets/click#1961]
It would be nice to be able to use click in the scenario where the user might pass in a path to an executable. In the case that a binary is produced in a folder of the same name, this would catch the scenario where the user passes the directory containing the executable instead of the correct `/some/long/path/programname/programname`

This is very straightforward to add: https://github.com/sielicki/click/commit/9cd5150da149fa2bff21208811deac6938acfece

**Comment by sielicki** [comment]
When you rebased, I'm afraid you dropped a `!r` modifier on the format string that came in between when I opened this issue/pr and when it landed. Phone posting so apologies if this is incorrect.

**Comment by davidism** [comment]
Oops, I'll fix that. I've been meaning to switch from `value!r` to `'value'` in general, instead of relying on the implict behavior that strings get single quotes, but I got sidetracked halfway through this rebase.

**Comment by davidism** [comment]
fixed
