### ISSUE TITLE
Clarify whether click-contrib/click-completion is deprecated or not

### ISSUE THREAD

**Issue by zbentley** [pallets/click#1966]
See https://github.com/click-contrib/click-completion/issues/41

Given the inclusion of completions into the main Click codebase, and the relatively high position of the `click-completions` repo in the Google results for completion-related results about Click, it seems prudent to clarify whether or not that repo is deprecated.

**Comment by davidism** [comment]
It is an extension, not maintained by Pallets. We don't have say over whether the maintainer decides it's deprecated.

**Comment by zbentley** [comment]
Thanks @davidism, sorry for the silly question!
