### ISSUE TITLE
flag_values get converted to str representation if they are set to a class object instead of an instance in Version 8.0.1

### ISSUE THREAD

**Issue by Torilla** [pallets/click#1973]
New in Version 8.0.1. Before, the behaviour was as expected.
This is a dublicate of the question on stackoverflow: https://stackoverflow.com/questions/68131423/py-click-8-0-flag-value-gets-converted-to-str

When creating a flag with a flag_value set to a class object, for example int, it get implicitly converted to a string
```python
import click

@click.command()
@click.option("--yes", flag_value=int)
def test(yes):
    print("yes=", yes, "type(yes)=", type(yes))

if __name__ == "__main__":
    test()
```
```bash
$ ./test.py --yes
yes= <class 'int'> type(yes)= <class 'str'>
```
Is this behavior intended? If so, why? I couldn't find anything related to the behaviour of flags in the change log. This obviously break backwards-compatibility. Before switching to click 8.0 it returned the object just fine.
Environment:

- Python version: 3.6.13
- Click version: 8.0.1

**Comment by davidism** [comment]
Please see existing issues regarding this.
