### ISSUE TITLE
missing documentation for DateTime type

### ISSUE THREAD

**Issue by ricekab** [pallets/click#1974]
The click.DateTime documentation is missing from the [API reference page](https://click.palletsprojects.com/en/8.0.x/api/#types).

There is documentation for the type on the [parameter types page](https://click.palletsprojects.com/en/8.0.x/parameters/#parameter-types) however.

(I wasn't sure what type of issue to file this under, sorry if this is the incorrect one)

**Comment by davidism** [comment]
PR welcome
