### ISSUE TITLE
Regression: ParamType.convert() being called twice for default params in Click 8.0.1

### ISSUE THREAD

**Issue by chriskeeser** [pallets/click#1980]
# Summary
When specifying a parameter custom type, the convert() function is being called twice on default param values in Click 8.0.1.  This causes the conversion to fail the second time since the value is already converted from a string to an integer (in the example provided below).  The convert() function is correctly called once for custom type default param values in Click version 7.1.2.

# Replicating the bug

Minimal example code provided at the end

## Setup and showing expected output (Click v7.1.2)

- Create a new virtual enviornment and activate it
- Install Click version 7.1.2
- Install the example program using the provided setup.py
- Execute `paramtest`
```
user@machine ~/Desktop/paramtest
$ python3 -m venv venv
user@machine ~/Desktop/paramtest
$ . venv/Scripts/activate
(venv)
user@machine ~/Desktop/paramtest
$ pip3 install click==7.1.2
...
Successfully installed click-7.1.2  colorama-0.4.4
(venv)
user@machine ~/Desktop/paramtest
$ pip3 install -e .
...
Successfully installed paramtest
```

**Expected output:**
```
user@machine ~/Desktop/paramtest
$ paramtest
value: 0x50, type: <class 'str'>
num: 80
(venv)
user@machine ~/Desktop/paramtest
$
```

## Failure case (Click v8.0.1)

- Install Click version 8.0.1
- Execute `paramtest`

```
user@machine ~/Desktop/paramtest
$ pip3 install click==8.0.1
...
Successfully installed click-8.0.1
(venv)
```

**Failure output:**
```
user@machine ~/Desktop/paramtest
$ paramtest
value: 0x50, type: <class 'str'>
value: 80, type: <class 'int'>
Traceback (most recent call last):
  File "C:\Users\chriskeeser\Desktop\paramtest\venv\Scripts\paramtest-script.py", line 11, in <module>
    load_entry_point('paramtest', 'console_scripts', 'paramtest')()
  File "c:\users\chriskeeser\desktop\paramtest\venv\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\chriskeeser\desktop\paramtest\venv\lib\site-packages\click\core.py", line 1061, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "c:\users\chriskeeser\desktop\paramtest\venv\lib\site-packages\click\core.py", line 923, in make_context
    self.parse_args(ctx, args)
  File "c:\users\chriskeeser\desktop\paramtest\venv\lib\site-packages\click\core.py", line 1379, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "c:\users\chriskeeser\desktop\paramtest\venv\lib\site-packages\click\core.py", line 2364, in handle_parse_result
    value = self.process_value(ctx, value)
  File "c:\users\chriskeeser\desktop\paramtest\venv\lib\site-packages\click\core.py", line 2320, in process_value
    value = self.type_cast_value(ctx, value)
  File "c:\users\chriskeeser\desktop\paramtest\venv\lib\site-packages\click\core.py", line 2307, in type_cast_value
    return convert(value)
  File "c:\users\chriskeeser\desktop\paramtest\venv\lib\site-packages\click\types.py", line 75, in __call__
    return self.convert(value, param, ctx)
  File "c:\users\chriskeeser\desktop\paramtest\param_test_cli.py", line 14, in convert
    return int(value, 0)
TypeError: int() can't convert non-string with explicit base
```

# minimal code example

**param_test_cli.py**
```
#!/usr/bin/env python3

import click

class BasedIntParamType(click.ParamType):
    name = 'integer'

    def convert(self, value, param, ctx):
        print("value: {}, type: {}".format(value, type(value)))
        try:
            return int(value, 0)
        except ValueError:
            self.fail('%s is not a valid integer' % value, param, ctx)

BASED_INT = BasedIntParamType()

@click.command()
@click.option('--num', '-n', default="0x50", show_default=True, type=BASED_INT, help="A based (hex / decimal) integer for conversion")
def cli(num):
    """Test the ParamType.convert"""
    print(f"num: {num}")

if __name__ == "__main__":
    cli()
```

**setup.py**
```
from setuptools import setup

setup(
    name = "paramtest",
    version = "0.1.0",
    py_modules = 
    [
        'paramtest',
    ],
    install_requires = 
    [
        "click",
    ],
    entry_points =
    '''
        [console_scripts]
        paramtest=param_test_cli:cli
    ''',
    )
```

Environment:

- Python version: 3.8.5
- Click version: 7.1.2 / 8.0.1

**Comment by davidism** [comment]
Please see existing closed issues about this.

**Comment by chriskeeser** [comment]
most relevant closed issue: https://github.com/pallets/click/issues/1898
fix: test the type in convert(), if its already the correct type, return it

other filed issues I had to read through to get to the fix
https://github.com/pallets/click/issues/1976
https://github.com/pallets/click/issues/1951

I really like this tool, but man, I can't tell you how frustrating it is to spend hours tracking this down, replicating it, writing minimal code, testing the minimal code, writing up a clear bug report, and then receiving a terse and unhelpful comment (not even a link) and an immediate close.

**Comment by davidism** [comment]
Yes, unfortunately the frustration can be mutual, as people keep opening almost identically worded issues. I was on my phone at the time, so didn't have a convenient way to find the previous issues. I don't plan to delay closing things that should be closed, so I'm not sure what I can do there. I appreciate that you wrote the issue well, that helps identify that it is a duplicate.

**Comment by chriskeeser** [comment]
I understand it both ways too.  In retrospect, I could have looked through closed issues (there were a few identical ones), it was a major version number change so I should expect some things to break, and you did say please ;)  Thanks for the prompt response on both counts.
