### ISSUE TITLE
`@option` processing help argument despite docstring saying that it forwards arguments unchanged

### ISSUE THREAD

**Issue by janluke** [pallets/click#1985]
https://github.com/pallets/click/blob/8b48450d5d63c747600e069d4c3e2274f41c8360/src/click/decorators.py#L244-L245

This code should be moved into `Option` or the docstring should be updated.

**Comment by davidism** [comment]
I'm going to extend this to other places that process blocks of text. I initially thought of `@command`, with `help`, `epilog`, and `short_help`, but I'll look for others as well.
