### ISSUE TITLE
`click.secho` is shown during unittest

### ISSUE THREAD

**Issue by kennylajara** [pallets/click#1996]
**Description**
If the function `click.secho` is called during the execution of a unittest, the message in de function is shown.

**Describe how to replicate the bug.**
1. Create a function that implements `click.secho`
1. Create a unittest to test the function.
1. Run the test
1. See the message

**Expected behavior**
I expect the `click.secho` function to work just like the `click.echo` function during the test. That is: not to show any message.

**Environment:**

- Python version: 3.9.5
- Click version: 8.0.1
- Test library: Unittest (native). 

**Note:** Tested with Pytest 6.2.4 and works OK.

**Comment by davidism** [comment]
Use Click's test runner to capture running cli commands. See the Click docs on testing.

**Comment by kennylajara** [comment]
Oh! I am sorry, I see what is happening here...

I normally use Click's test runner for my click's test but in this particular case I am trying to test an internal function (a function not directly called by command line), so... for this function I didn't use the Click's test runner and confused the behavior with a bug.

But in this specific case, when I am testing a "private" function and is not practical to create a command just for this function, what can I do? Is there a way for me to know if the code is being executed by the testsuite?

**Comment by davidism** [comment]
Mock stdout yourself if you don't want to use the runner. Again, this is not specific to Click.

**Comment by kennylajara** [comment]
Good idea. Thanks and sorry for the misunderstanding.
