### ISSUE TITLE
Inconsistent display of default values in help output

### ISSUE THREAD

**Issue by gaudenz** [pallets/click#2000]
If the default value text for the help output is given with a string value in the `show_default` option of the `click.Option` class it is shown with parenthesis around the value. If the it's taken from the `default` option directly no parenthesis are shown. Both ways of defining the default value shown in the help text should use the same formatting. If parenthesis are desired they can be added to the `show_default` string value directly.

This is caused by this code block in `src/click/core.py`:
```
2736             if show_default_is_str:
2737                 default_string = f"({self.show_default})"
2738             elif isinstance(default_value, (list, tuple)):
2739                 default_string = ", ".join(str(d) for d in default_value)
2740             elif callable(default_value):
2741                 default_string = _("(dynamic)")
2742             elif self.is_bool_flag and self.secondary_opts:
2743                 # For boolean flags that have distinct True/False opts,
2744                 # use the opt without prefix instead of the value.
2745                 default_string = split_opt(
2746                     (self.opts if self.default else self.secondary_opts)[0]
2747                 )[1]
2748             else:
2749                 default_string = str(default_value)
```

Environment:

- Python version: 3.9.2
- Click version: 8.0.1

**Comment by davidism** [comment]
The parentheses are to indicate that it's not the actual value but a message, see `(dynamic)` as well.

**Comment by gaudenz** [comment]
IMHO this is only one possible use of this setting. And if the parentheses are desired they can always be added to the `show_default` string. In my use case I wanted to show the actual value but in a different "formatting". See #1999. While this is a bug I think there might be other cases where it's not so clear that this is a bug. Adding the parenthesis in the code removes this flexibility.
