### ISSUE TITLE
Julia port?

### ISSUE THREAD

**Issue by orome** [pallets/click#2003]
Perhaps off topic, but bear with me (I don't know where else to ask): Is there any chance of a Julia port of `click`? Sadly, `argparse` has been [ported to Julia](https://argparsejl.readthedocs.io/en/latest/argparse.html), where it does untold damage (as `argparse` did for years), and the language is badly in need of a fantastic replacement like `click`!

**Comment by ThiefMaster** [comment]
I think this would be more something for a Julia dev - which AFAIK none of us are ...

**Comment by orome** [comment]
> I think this would be more something for a Julia dev - which AFAIK none of us are ...

Yeah I guess that's what it boils down to: Does anyone on this also have sufficient Julia skills (not me).

**Comment by davidism** [comment]
Someone's welcome to use Click as inspiration for a project in Julia, but we won't be developing that. I'd ask anyone who decides to do that to avoid using the name "Click" in the library name, as it implies an official relationship that will not exist. Mentioning our name in docs, such as "inspired by Click", or including our license, would be appreciated though.
