### ISSUE TITLE
Systemwide shell autocompletion doesn't seem to work for the click 8.0.1

### ISSUE THREAD

**Issue by Exidex** [pallets/click#2007]
New documentation https://click.palletsprojects.com/en/8.0.x/shell-completion/ only describes ways to add completion for single user on a system, in our case system is a server and it is infeasible to add completion for every new user separately.

Tested for single user and completion works as expected but for global system configuration i haven't managed to make version 8 to work.

I tried both ways of adding completion described in docs: one by adding `eval` and one by generating file and sourcing it. I have tried `/etc/profile`, separate file in `/etc/profile.d/`, `/etc/bash.bashrc` and even file in `/usr/share/bash-completion/completions` directory

Not sure if this is a bug in Click or just a documentation issue.

Environment:

- Python version: 3.6.9
- Click version: 8.0.1
- OS: Ubuntu 18.04.5 LTS

**Comment by davidism** [comment]
The scripts and install process are essentially unchanged, only a bit of how the scripts interpret the response from Click has changed. So this sounds like a system problem, not a Click problem.

**Comment by davidism** [comment]
I ran the `eval` line system-wide and it added completions for the command successfully. Sounds like this issue is elsewhere for you.
