### ISSUE TITLE
Absent parameters change behavior when typed

### ISSUE THREAD

**Issue by Mitmischer** [pallets/click#2010]
I ran into the following corner case when translating argparse code.

Consider the following code:
```
import click

@click.option("-a", "a")
@click.option("-b", "a")
@click.command()
def main(a):
    print(a)

if __name__ == "__main__":
    main()
```

In lack of a better description, note that these two options have the same "parameter name" (or whatever it is that corresponds to `dest` in argparse).
That gives the following, intuitive output:
```
> python3 click_bug.py  -a "hello"
hello
> python3 click_bug.py  -b "hello"
hello
```

Now I wanted to assign a type to one of the objects:

```
import click


def SomeType(ParamType):
    def convert(self, value, param, ctx):
        return value


@click.option("-a", "a")
@click.option("-b", "a", type=SomeType)
@click.command()
def main(a):
    print(a)

if __name__ == "__main__":
    main()
```

Now that is a problem:
```
> python3 click_bug.py  -b "hello"
hello
> python3 click_bug.py  -a "hello"
None
```

Although option "-b" is missing in the latter case, click supposedly still attempts to do the type conversion, yielding None. That overrides the option "-a" that is effectively lost.

Seeing that `SomeType.convert` is effectively an identity function, I'd have expected the output to be "hello" in all those examples.

Environment:

- Python version: 3.6.9
- Click version: 8.0.1

**Comment by davidism** [comment]
Don't use the same name for different options.
