### ISSUE TITLE
Parameters with identical names must not have different type

### ISSUE THREAD

**Issue by Mitmischer** [pallets/click#2011]
Another corner case that I ran into - maybe that is also related to #2010.

Consider the following example:

```
import click


@click.option("-a", "a", multiple=True)
@click.option("-b", "a")
@click.command()
def main(a):
    print(a)

if __name__ == "__main__":
    main()

```

That gives the following output:
```
> python3 click_bug.py -a "hello"
['hello']
> python3 click_bug.py -b "hello"
Usage: click_bug.py [OPTIONS]
Try 'click_bug.py --help' for help.

Error: Invalid value for '-a': Value must be an iterable.
```

Specifying both at the same time (which is _not_ my use case) would be even worse:
```
> python3 click_bug.py -a "hello" -b "hello"
Usage: click_bug.py [OPTIONS]
Try 'click_bug.py --help' for help.

Error: Invalid value for '-a': Value must be an iterable.
> python3 click_bug.py -b "hello" -a "hello"
Traceback (most recent call last):
  File "<SNIP>/lib/python3.6/site-packages/click/parser.py", line 514, in _process_opts
    self._match_long_opt(norm_long_opt, explicit_value, state)
  File "<SNIP>/lib/python3.6/site-packages/click/parser.py", line 398, in _match_long_opt
    raise NoSuchOption(opt, possibilities=possibilities, ctx=self.ctx)
click.exceptions.NoSuchOption: No such option: -a

```

When only -a or -b was specified, I'd have expected to just work as if the other option wasn't there.

Environment:

- Python version: 3.6.9
- Click version: 8.0.1

**Comment by davidism** [comment]
I don't think I want to go down the path of this much validation. It's not really possible, as Click is completely dynamic. Don't write code like that.

**Comment by Mitmischer** [comment]
I respect your response, although I'm disappointed with it.
I want to stress that
> The CLI I got is working code in argparse, with the option mapping working as intended. "Don't write code like that" is not an option when porting code and wanting to sell it.
> Although I don't like options that map to a single one, I don't find such a choice unreasonable. Keeping those options separate leads to many options that remain empty, and puts the merging logic on the user, which is okay but also avoidable.

I'll go for the workaround of differently named options and that will do it.
Still, closing this and #2010 was not the right call.
