### ISSUE TITLE
Return value of CliRunner.invoke is not the return value of the called command

### ISSUE THREAD

**Issue by Mitmischer** [pallets/click#2015]
In the documentation to [CliRunner::invoke](https://click.palletsprojects.com/en/8.0.x/api/#click.testing.CliRunner), it says that
```
The result object has the return_value attribute with the value returned from the invoked command.
```
However I don't see this reflected, see this example:
```
import click

from click.testing import CliRunner

@click.command()
@click.argument("arg")
def main(arg):
    return(arg)

runner = CliRunner()
result = runner.invoke(main, "arg")
print(result.return_value)
```
```
> python3 main.py
None
```

I expected result.return_value to be "arg".

The fix should be calling cli.main with standalone_mode == False [here](https://github.com/pallets/click/blob/main/src/click/testing.py#L408). I don't know if that would break other use cases though. So maybe it would also make sense to mimic the `standalone` flag in `CliRunner.invoke`.

Environment:

- Python version: 3.6.9
- Click version: 8.0.1

**Comment by davidism** [comment]
The runner is also used to test the default "standalone mode", so it can't disable it unconditionally. Therefore, if you want to write tests that look at the return value, you have to tell the runner that by passing `invoke(standalone_mode=False)`. We do this in Click's tests too.
