### ISSUE TITLE
Verbose flag for secho

### ISSUE THREAD

**Issue by shaharjacob** [pallets/click#2016]
**Description**: add verbose flag which will be True by default.
If the user don't want to print, just call it with verbose=False

Today, I send verbose flag to my function, and everytime asked `if verbose: secho(...)`
For example:
```
from click import secho

def foo(verbose: bool):
    if verbose: 
        secho("hello world")
```

It could be much more easy if it will be:
```
from click import secho

def foo(verbose: bool):
    secho("hello world", verbose=verbose)
```

**Comment by davidism** [comment]
You cam write this function in your coffee if you need it, but it's not something I think needs to be added to Click.
