### ISSUE TITLE
click.prompt(..., err=True) produces a single space on stdout

### ISSUE THREAD

**Issue by nils-werner** [pallets/click#2018]
Using the following script

```python
import click

click.prompt("asd", err=True)
```

and running it like

```
python test.py 1> stdout 2> stderr
```

The file `stderr` should receive all output from the script, and `stdout` should remain empty. However we can see that the file `stdout` receives a single space for each round that `click.prompt()` does (i.e. when entering nothing, it keeps re-asking).

This is unexpected and should not happen.

I believe [this comment](https://github.com/pallets/click/blob/main/src/click/termui.py#L141) is related to this issue.

Environment:

- Python version: 3.7.10
- Click version: 8.0.1

**Comment by nils-werner** [comment]
One solution might be to replace

```python
visible_prompt_func: t.Callable[[str], str] = input

def hidden_prompt_func(prompt: str) -> str:
    import getpass

    return getpass.getpass(prompt)
```

with

```python
def visible_prompt_func(prompt: str, err=False) -> str:
    out = sys.__stderr__ if err else sys.__stdout___
    try:
        sys.stdout = out
        return input(prompt)
    finally:
        sys.stdout = sys.__stdout___

def hidden_prompt_func(prompt: str, err=False) -> str:
    import getpass

    out = sys.__stderr__ if err else sys.__stdout___
    try:
        sys.stdout = out
        return getpass.getpass(prompt)
    finally:
        sys.stdout = sys.__stdout___
```

**Comment by davidism** [comment]
See discussion in #2019. We cannot patch `sys.stdout` as proposed, Click deliberately avoids doing that outside tests.
