### ISSUE TITLE
No documentation on options' default values

### ISSUE THREAD

**Issue by wvxvw** [pallets/click#2028]
#1618 says that it solved the problem. But there's no documentation, not even an example in the comments... Does this even work? How one would know if it works?

To be more specific. I'm not interested in prompting users. I'm interested in the equivalent of `const` argument in `ArgumentParser`.

**Comment by davidism** [comment]
That PR includes new documentation. If you have a question about your own code, please as on our [Discord server](https://discord.gg/pallets).

**Comment by wvxvw** [comment]
Where is this documentation? There is a list of about 10 different PRs linked in multiple tickets, but I couldn't find documentation on this feature. Not to mention it hasn't been published on the documentation website.

**Comment by jab** [comment]
https://github.com/pallets/click/pull/1618/files#diff-fcf77d5d210d0bb583fe53868f7897681f307a7b99e6397cce8028a8add6ed75

**Comment by jab** [comment]
And it has been published on the documentation website. 

https://click.palletsprojects.com/en/8.0.x/options.html

> By default, the user will be prompted for an input if one was not passed through the command line.

**Comment by wvxvw** [comment]
The link in your comment is broken. The correct link was probably https://click.palletsprojects.com/en/8.0.x/options/#optional-value .

Otherwise, thanks. The confusing part here is mentioning the promoting. It's the feature that is so undesirable, that I didn't realize that the useful documentation would be behind it.
