### ISSUE TITLE
Auto create documentation/swagger

### ISSUE THREAD

**Issue by jochman** [pallets/click#2029]
The auto-swagger/documentation will create a webpage that can be similar to swagger UI with the command, input, outputs, and other documentation. 

In my case, I'm working on [demisto-sdk](https://github.com/demisto/demisto-sdk/). We've using readmes in each command directory. I would prefer something like `pydoc` that will take care of the commands and the documentation site.

**Comment by davidism** [comment]
This would be a separate tool. See for example sphinx-click.
