### ISSUE TITLE
click.Path() breaks with recent versions of click

### ISSUE THREAD

**Issue by gtristan** [pallets/click#2037]
When trying to test fresh versions of click in our tox environment, we encountered stack traces when accessing the public `path_type` member of the `click.Path()` object.
 

Write code which accesses the `click.Path.path_type` member.

In our case, we have a custom bash completion algorithm which overrides click's implementation (dating back to #780, I think click has added new functionality in master by now and I still have to check if it covers all the use cases we need).

Environment:

- Python version: I tested with python 3.9, but it will obviously happen with any version
- Click version: I tested with 8.0.1, but the problem will go back to when the API was broken (I don't have a local checkout on hand, `git blame` will tell...)

**Comment by davidism** [comment]
Sorry, you haven't provided enough information to describe or reproduce the problem.

**Comment by gtristan** [comment]
> Sorry, you haven't provided enough information to describe or reproduce the problem.

Sorry I followed the form you have some kind of template in your github, but it doesn't leave any sections only comments, so it looks hard to tell what the steps to reproduce are.

The steps to reproduce the problem is very simple:

> Write code which accesses the click.Path.path_type member.

It's **that** simple.

Take this code for instance which accesses the `path_type` public API member of the `Path` object:

```python
param = click.Path(file_okay=False, writable=True)

# Access the `path_type`
click.echo(param.path_type)
```
Before the breakage, this will print *"Directory"* to the console.

After the breakage, the code which used to work, now throws an `AttributeError` instead.

**Comment by davidism** [comment]
That attribute was not a public API. We consider things in the docs the public API. It looks like I removed that variable while making some type-related changes, as it was redundant and was confusing with the `path_type` init parameter. You probably should not be keying off a display string anyway, you can look at `self.file_okay` and `self.dir_okay`, but note that those are technically not public either, so it's up to you to monitor and maintain compatibility with any future changes.
