### ISSUE TITLE
`fzf` choice support

### ISSUE THREAD

**Issue by nikochiko** [pallets/click#2047]
`fzf` is a popular fuzzy finder tool that can do fuzzy matching within a list of strings (https://github.com/junegunn/fzf)
There should be an easy way to use `fzf` to display `choices` for a prompt if it is available (installed by the user).

When there is a large number of choices, the up and down arrows are inconvenient. With fuzzy matching you can type the part of the option that you remember and it will keep narrowing it down. It is not possible to integrate it with `click.prompt`. It is possible to do it with some other libraries (https://github.com/nk412/pyfzf) - like this one.

I am willing to contribute the code for this

**Comment by davidism** [comment]
As interesting as that library may be, we do not use third party libraries in Click. Are you referring to refactoring part of Click to make it possible to extend? I'm not really clear what you're proposing.

**Comment by nikochiko** [comment]
Sorry, I wasn't clear. What I meant was that, it would be really handy to have something like

```python3
click.prompt("Please make a choice", choices=get_choices(), use_fzf=True)
```

That will route the output to fzf if it is there on the system. In that way the CLI will get a neat UI to see the choices and choose one. Similar to opening something in a pager (`click.echo_with_pager`).

> we do not use third party libraries in Click

What I mean is, if `use_fzf` is true, then click will look for a `fzf` binary locally. Use it if it exists, or just continue on with normal behaviour if not.

**Comment by davidism** [comment]
Well, we definitely won't have a `use_fzf` parameter, since as I said we don't typically add random third part functionality. I do want to allow the developer to override things such as what `prompt` does, so maybe that will help with your case eventually.

**Comment by nikochiko** [comment]
> allow the developer to override things such as what prompt does, so maybe that will help with your case eventually.

That will help, thanks!

Was typing this before your reply, I think this is similar to what you mentioned:

But I understand that it might not be ideal for click to be this tightly coupled with another library. I am not that familiar with how click's code is written, but it would be possible to have a generic way of passing the choices to some other shell command. Something like

```python3
click.prompt("Please make a choice", choices=get_choices, transform=transform_func)

# where transform_func is something like
def transform_func(choices):
    return "fzf ...."
```

**Comment by kdeldycke** [comment]
A FAQ entry covering the completion of prompts in Click has been proposed in https://github.com/pallets/click/pull/3826
