### ISSUE TITLE
Consider exporting ParameterSource from Click

### ISSUE THREAD

**Issue by janluke** [pallets/click#2048]
... so that one can access it as `click.ParameterSource`.

**Comment by davidism** [comment]
As a general policy I'm not really adding things to the top level for Pallets projects. Is there a reason you don't want to import it directly?

**Comment by janluke** [comment]
Not a compelling one, actually. In my wrapper/extension library (Cloup) I tend to use only the click namespace to avoid confusion. Most stuff in click.core is exported, I expected it to be exported too. But it's not a big deal given that I don't redefine ParameterSource in Cloup.
