### ISSUE TITLE
Parse environment variables when invoking a different command

### ISSUE THREAD

**Issue by nue-melexis** [pallets/click#2050]
Hi,

I like Click and would like to have one feature about parsing the env vars when invoking commands.
This would be handy when having kind of independent commands, which you wanna invoke and they take default values (or the ones from command line)

Short example:
```
#!/usr/bin/env python3

import click

@click.group()
def cli():
    pass

@cli.command(help="print envvar")
@click.option("--test", envvar="TESTENVVAR")
def test(test):
    print(test)

@cli.command(help="print and invoke")
@click.option("--test2", envvar="TESTENVVAR2")
@click.pass_context
def test2(ctx, test2):
    print(test2)
    ctx.invoke(test)
```

Calling it with test2 command will not parse the values from env for test command.
```
TESTENVVAR2=2222 TESTENVVAR=111 python test.py test2
> 2222
> None
```

I don't know if this is for invoke (as a flag?) or there should be another click way to do this elegantly like `ctx.launch`

I currently work around this with a function that creates a context with `c = cmd.make_context(cmd.name, [], resilent_parsing=True, parent=click.current_context())`
Then I invoke from original context `click.current_context().invoke(cmd, **c.params)`.

Please feel free to drop your ideas about this.

**Comment by nue-melexis** [comment]
Ass addition:
creating the sub context with cmd.make_context and invoking from this is generally possible but it adds a context layer in between.

**Comment by davidism** [comment]
See https://github.com/pallets/click/issues/1124#issuecomment-653238970 for an explanation on the distinction between running the CLI and invoking another command during the run.
