### ISSUE TITLE
`default_map` uses internal names to override default values of options

### ISSUE THREAD

**Issue by yashrathi-git** [pallets/click#2055]
click default_map uses internal names to set(override) default values

## Problem
`--from`, internal name `from_internal` I cannot override default using `{"from":"newvalue"}`, I have to use `{"from_internal": "new value"}`

In my use case, the user would be overwriting the values, so it would make sense to use option names instead of internal names. Is there any workaround for this?

## Example snippet
From [docs](https://click.palletsprojects.com/en/8.0.x/commands/#overriding-defaults)
```py
import click

CONTEXT_SETTINGS = dict(
    default_map={'runserver': {'port': 5000}}
)

@click.group(context_settings=CONTEXT_SETTINGS)
def cli():
    pass

@cli.command()
@click.option('--port', 'port_internal_name', default=8000)
def runserver(port_internal_name):
    click.echo(f"Serving on http://127.0.0.1:{port_internal_name}/")

if __name__ == '__main__':
    cli()
```
This doesn't override the default, for `--port` option
```sh
$ python test.py runserver
Serving on http://127.0.0.1:8000/
```

Environment:

- Python version: 3.9.6
- Click version: 8.0.1

**Comment by davidism** [comment]
An option only has one name. In this case, you named the option `port_internal_name`, so that's the name that Click knows to look for. An option can have multiple *flags*, and by default uses the name of a flag as the name of the option, but Click doesn't consider each possible flag when looking at `default_map` or `allow_from_autoenv`.

**Comment by yashrathi-git** [comment]
Thanks for response,
What I did, is I changed all internal names to either be the same name as the option or have the suffix `_`, like `from_`. And then I took dict from user input and added repetitive values with suffix `_`. 
Ex:
```py
{"from": "value"}
# turns to 
{"from": "value", "from_":  "value"}
```

It's hacky but that's the best way I found.
