### ISSUE TITLE
CliRunner does not support process substitution

### ISSUE THREAD

**Issue by mikepqr** [pallets/click#2056]
Given this click application:

```
## cat.py (i.e. the unix cat utility)

import click


@click.command()
@click.argument("fname")
def cat(fname):
    with open(fname) as f:
        print(f.readlines())


if __name__ == "__main__":
    cat()
```

you get the following (correct) behavior in the shell

```
$ python cat.py foo
['1\n', '2\n', '3\n']

$ python cat.py <(echo -ne '1\n2\n3\n')
['1\n', '2\n', '3\n']
```

The second command makes use of [process substitution](https://tldp.org/LDP/abs/html/process-sub.html).

It seems, however, that CliRunner cannot invoke the process substitution command correctly:

```
## test_cat.py

from cat import cat
from click.testing import CliRunner

runner = CliRunner(mix_stderr=False)

data = "1\n2\n3\n"


def test_file():
    with open("foo", "w") as f:
        f.write(data)
    result = runner.invoke(cat, ["foo"])
    print(f"file: {result.exit_code=}")
    print(f"file: {result.stdout=}")
    print(f"file: {result.stderr=}")


def test_psub():
    result = runner.invoke(cat, [f'<(echo -ne "{data}")'])
    print(f"psub: {result.exit_code=}")
    print(f"psub: {result.stdout=}")
    print(f"psub: {result.stderr=}")


test_file()
test_psub()

```

The `invoke` in `test_psub` fails: there is a non-zero exit code, and stdout or stderr:

```
$ python -m test_cat
file: result.exit_code=0
file: result.stdout="['1\\n', '2\\n', '3\\n']\n"
file: result.stderr=''
psub: result.exit_code=1
psub: result.stdout=''
psub: result.stderr=''
```

I assume this is something to do with `f'<(echo -ne "{data}")']` not being a real "argument". Is this a bug in click, a bug in understanding of click and the shell, or something else?

**Comment by davidism** [comment]
Process substitution is a Bash (and probably other shell) feature. You linked to the "Advanced Bash Scripting Guide". That happens in Bash, not in Python. Your second attempt is just a Python string.

**Comment by mikepqr** [comment]
So how do I test my app's interaction with shell features? Is there an equivalent of `subprocess.run(..., shell=True)` to allow that?
