### ISSUE TITLE
CliRunner.mix_sderr has no effect

### ISSUE THREAD

**Issue by wvxvw** [pallets/click#2060]
When `click` testing isn't able to read from `stderr` (the program actually prints to `stderr`, but `click` doesn't notice neither `stdout` nor `stderr`), even though `CliRunner.mix_stderr == False`, attempting to access `click.testing.Result.stderr` results in an error: `ValueError: stderr not separately captured`.

I believe that `click` is unable to capture any output because it runs inside `pytest`, which screws up all output. But this is irrelevant, because even if `pytest` replaced `stderr` with something else, the expected behavior of accessing `result.stderr` is that it returns an empty string... or, even better, byte-string. It shouldn't throw error if `stderr` turned out to be empty for some reason.

**Comment by davidism** [comment]
I can't reproduce this issue with the information given.
