### ISSUE TITLE
Allow passing 'command_class' to group() or Group()

### ISSUE THREAD

**Issue by dlax** [pallets/click#2061]
Currently, the only way to use a custom command class for a group is to set the `command_class` attribute on custom `Group` subclass or an existing `Group` object. E.g.:

```python
class MyCommand(click.Command):                                                           
    ...                                          

@click.group()
def cli():                                                                        
    ...                                                                                  
                                          
cli.command_class = MyCommand
```

It might be handy to be able to create the group with the `command_class` attribute set in `__init__`:
```python
@click.group(command_class=MyCommand)
def cli():                                                                        
    ...           
```
The same probably applies to `group_class`.

Happy to work on a PR if the suggestion is accepted.

**Comment by davidism** [comment]
It's an interesting idea, but I don't think it fits with how I want to handle overriding behavior. It's an extra layer of injection beyond injecting the class itself, which would require creating subclasses internally (to avoid modifying globals (class vars) as a side effect.
