### ISSUE TITLE
mypy raises errors when using `click.prompt()` due to `type` argument having incompatible type

### ISSUE THREAD

**Issue by andrewlangemann** [pallets/click#2062]
I have a project that uses the latest version of mypy (0.910) and click (8.0.1). I am attempting to use `click.prompt()` and pass in the `type` argument but this is always causing mypy (with default settings) to find errors.

Here is an example:
```python
import click
name = click.prompt('What is your name?', type=str)
age = click.prompt('What is your age?', type=int)
```

When I run mypy against this file, I get two errors:
```
main.py:2: error: Argument "type" to "prompt" has incompatible type "Type[str]"; expected "Optional[ParamType]"
main.py:3: error: Argument "type" to "prompt" has incompatible type "Type[int]"; expected "Optional[ParamType]"
```

To address these, I tried passing in some different values for `type` but to no avail (same issues all happen for `int` as well):
```python
name = click.prompt('What is your name?', type=Optional[str])
# Returns error: Argument "type" to "prompt" has incompatible type "object"; expected "Optional[ParamType]"

name = click.prompt('What is your name?', type=StringParamType)
# Returns error: Argument "type" to "prompt" has incompatible type "Type[StringParamType]"; expected "Optional[ParamType]"

name = click.prompt('What is your name?', type=Optional[StringParamType])
# Returns error: Argument "type" to "prompt" has incompatible type "object"; expected "Optional[ParamType]"
```

Is this a bug or should I be providing something different to `type`?

Environment:

- Python version: 3.7.10
- Click version: 8.0.1
- mypy version: 0.910

**Comment by davidism** [comment]
It's half a bug with typing, and half a bug with your attempted workarounds.

The type of `type` should be `Optional[Union[str, ParamType]]`. Happy to review a PR that fixes this.

The reason `StringParamType` didn't work for you is that's a class, not an instance of it. The singleton instance of `StringParamType` that you should use is `click.STRING`. Additionally, passing `typing` things like `Optional[StringParamType]` doesn't make sense, that's a type annotation not a parameter value.

**Comment by andrewlangemann** [comment]
Thank you @davidism - by using `click.STRING` and `click.INT` I have now appeased mypy :)

```python
import click
name = click.prompt('What is your name?', type=click.STRING)
age = click.prompt('What is your age?', type=click.INT)
```
