### ISSUE TITLE
Possibility to output tool metadata in JSON

### ISSUE THREAD

**Issue by shpigunov** [pallets/click#2063]
Click already provides automatic help text generation. Would it be possible to use the same internal properties and attributes to generate a JSON object like:

```
{
  "name": "my_tool",
  "params": [
    {"flag": "input", "type": "str", ...},
    {"flag": "pvalue", "type": "flat", "help": "p-value adjustment", ...},
    ...
  ]
}
```

The use case for this functionality is to automatically generate machine-readable command line tool metadata to include these tools in various workflows and pipelines (which would require validation of inputs/outputs for each tool).

I wonder if this could be better resolved in via subclassing or adding a method, or could the community benefit from this functionality so that it can be included in Click?

**Comment by davidism** [comment]
Every core object has a `to_info_dict()` method. For example, `my_tool.to_info_dict()`.

**Comment by shpigunov** [comment]
Thanks, this is just what I needed! And since `typer` depends on `click`, it works in `typer`, too!
