### ISSUE TITLE
Use flake8 4.0.x

### ISSUE THREAD

**Issue by angus-lherrou** [pallets/click#2102]
As discussed [here](https://github.com/pallets/click/pull/1896#discussion_r632668344), `flake8` did not properly detect imports of the `typing` module when aliased like `import typing as t`, which is a pattern used in this repository. Detection of `typing` is needed for `flake8` to understand (and ignore with respect to F811) function redefinitions using the `@typing.overload` decorator, so where this decorator is used, `click` imports the module twice:

```python
import typing
import typing as t
```

With PyCQA/pyflakes#632 merged, `pyflakes` 2.4.0 properly detects aliased `typing` imports, and `flake8` 4.0.x uses `pyflakes >= 2.4.0, < 2.5.0`. If we upgrade to using this newer version of `flake8`, we can remove the duplicate imports.

As far as I can tell it's as simple as changing one line in `.pre-commit-config.yaml`, but I'm not sure if there's more needed under the hood to update the CI pipeline. I'm ready to open a PR for this if people agree on the update.

**Comment by davidism** [comment]
Happy to review a pr. Make it off the 8.0.x branch.
