### ISSUE TITLE
Command in completion mode exits with non-zero exit code even if the completion instructions have been retrieved correctly

### ISSUE THREAD

**Issue by rubendibattista** [pallets/click#2123]
When enabling complete mode. The CLI exits with non-zero code

1. Create a simple CLI command (e.g. `mycmd`.py)
2. Install the CLI command as console_script (e.g. named `mycmd`)
3.  Run `MYCMD_COMPLETE mycmd`
4. echo $?

The script should should exit with a 0 exit code if the completion script was retrieved correctly. I think the relevant part of the code is [here](https://github.com/pallets/click/blob/1784558ed7c75c65764d2a434bd9cbb206ca939d/src/click/_bashcomplete.py#L368) 

Environment:

- Python version: 3.9.6
- Click version: 7.1.2

**Comment by davidism** [comment]
Click 7 is no longer supported. The completion system has been almost entirely rewritten in Click 8. If this is still an issue with Click 8, please update the issue.

**Comment by rubendibattista** [comment]
This indeed is fixed in version 8.x. Thanks!
