### ISSUE TITLE
`count=True` default format for option is differently depending on OS

### ISSUE THREAD

**Issue by Besler** [pallets/click#2128]
### Clear outline of what the bug is.
When using an `option` with the `count=True`, such as in the case of different levels of verbosity, the default help format is OS dependent. This is a pain for me since I write unit tests for my CLI help functionality to keep it consistent between operating systems.

### Describe how to replicate the bug.
`main.py`
```python
import click

# Set up context setting for all children
CONTEXT_SETTINGS = dict(
    help_option_names=['-h', '--help'],
    show_default=True,
)


@click.command(context_settings=CONTEXT_SETTINGS)
@click.option(
    '--verbose', '-v',
    count=True,
    default=int(0),
)
def main(verbose: int):
    print(f'{verbose}')


if __name__ == '__main__':
    main()
```

```bash
# OSX
$ python main.py -h
Usage: testing.py [OPTIONS]

Options:
  -v, --verbose  [default: 0;x>=0]
  -h, --help     Show this message and exit.  [default: False]
```
```bash
# Unix
$ python main.py -h
Usage: testing.py [OPTIONS]

Options:
  -v, --verbose  [default: 0]
  -h, --help     Show this message and exit.  [default: False]

```
The difference is the output `[default: 0;x>=0]` vs `[default: 0]`.

### Describe the expected behavior that should have happened but didn't.
The default help should print the same independent of operating system.

### Environment

- Python version: `Python 3.8.11`
- Click version: `click 8.0.1`

**Comment by davidism** [comment]
It's different based on the Click version you've installed, not based on OS. Upgrade to 8.0.3 consistently and you'll see the fix for https://github.com/pallets/click/issues/2072.

**Comment by Besler** [comment]
Much appreciated!
________________________________
