### ISSUE TITLE
Default usage of "-h" for "--help"

### ISSUE THREAD

**Issue by zachriggle** [pallets/click#2132]
I've noticed that Click does not register `-h` → `--help` as `argparse` does.  This is unfortunate.

Most command-line tools\* support `-h` and `--help` so it's not unreasonable for users to expect `foo -h` to work. 

\* *And I was very close to running every executable in `$PATH` with `-h` and `--help` and diff'ing the output to see how many do -- but realized there's surely some random binary or script I wrote that when invoked as `some_cmd -h` will manage to  
`$ sudo rm -rf --no-preserve-root /`*

## Feature Suggestion

It would be nice if we could get any (or all) of the following:

1. *Default behavior change*  
  `-h` invokes `--help` if the `-h` would otherwise throw `Error: No such option: -h`
2. *Global configuration*  
  `click.command.short_help = True`  
  Allows a package to set it once and forget it (again, being overridable if a `-h` flag is declared)
3. *User controllable via environment*  
  By default, `click.command.short_help = os.environ.get('CLICK_SHORT_HELP', False)` per above

The specific naming doesn't matter, but these features would be nice for my (and presumably others') muscle memory and consistency with `argparse`.

Since I'm only proposing opt-in behavior (2, 3) and only changing the default behavior (1) should `NoSuchOption` be raised for `-h`, this should not be a breaking change.

### Implementation

For (1), I'm not sure the best way to do this, since I'm not familiar with the interaction of the classes in `core.py`.

For (2), the `Context` class could be given a class property, `default_help_option_names`.  
Then, the below line could be changed to `... = list(self.default_help_option_names)`.

https://github.com/pallets/click/blob/6411f425fae545f42795665af4162006b36c5e4a/src/click/core.py#L370

For (3), we can just add a few lines after the change (2) suggested above:

```py
default_help_option_names = ['--help]'

if os.environ.get('CLICK_SHORT_HELP', False):
  default_help_option_names.append('-h')
```

## Prior Art

This has been raised before in #1433, but I think it's worth discussion of the above points.

In the other issue, these three approaches were compared, and I agree none are particularly better than the other.

### A

```py
CONTEXT_SETTINGS = dict(help_option_names=['-h', '--help'])

@click.command(context_settings=CONTEXT_SETTINGS)
def cli():
    pass
```

### B

```py
@click.command(help_shorthand=True)
def cli():
    pass
```

### C

```py
@click.command(context_settings={"help_option_names": ["-h", "--help"]})
def cli():
    ...
```

In particular, it would be nice if this were configurable

**Comment by davidism** [comment]
Thanks for that write up. However, I still stand by my decision in the previous linked issue.

>  -h invokes --help if the -h would otherwise throw Error: No such option: -h

This is not possible.

> click.command.short_help = True

Not only does `short_help` already have a meaning, but this is what `Command.context_settings` does.
