### ISSUE TITLE
Install with Poetry fails with: 'Link' object has no attribute 'name'

### ISSUE THREAD

**Issue by ingvaldlorentzen** [pallets/click#2133]
# Outline
When trying to install `click` with `poetry` it fails with the following error:
```
• Installing click (8.0.3): Failed
  AttributeError
  'Link' object has no attribute 'name'
  at /usr/local/Cellar/poetry/1.1.11/libexec/lib/python3.9/site-packages/poetry/installation/executor.py:632 in _download_link
      628│                 raise RuntimeError(
      629│                     "Invalid hashes ({}) for {} using archive {}. Expected one of {}.".format(
      630│                         ", ".join(sorted(archive_hashes)),
      631│                         package,
    → 632│                         archive.name,
      633│                         ", ".join(sorted(hashes)),
      634│                     )
      635│                 )
      636│ 
```

I guess this could be an issue with Poetry, but it doesn't seem like it. Seems like `click` is missing some information in the package that Poetry expects? Install with `pip` works fine. 

# Replicate
1. [Install Poetry](https://python-poetry.org/docs/#installation) (or simply, `brew install poetry` on macOS if you have Homebrew).  
2. In a virtual environment, run `poetry add click` 

# Expected Behaviour
Click should be installed without issues. 

Environment: macOS
- Python version: 3.9
- Click version: 8.0.3

**Comment by davidism** [comment]
This sounds like an issue with Poetry.

**Comment by davidism** [comment]
I searched poetry's issue tracker for "archive name" and immediately found this: https://github.com/python-poetry/poetry/issues/4701

**Comment by ingvaldlorentzen** [comment]
I was searching around in the Poetry issues before submitting this, but didn't find that issue 🤦‍♂️

Seems like Poetry caches some stuff that isn't cleared with the `poetry cache` command.  
Removing `~/Library/Caches/pypoetry` did the trick on macOS. 

Sorry for the incorrect issue, and thanks for the help!
