### ISSUE TITLE
Hidden commands

### ISSUE THREAD

**Issue by gitpushdashf** [pallets/click#2134]
It's easy to hide options in Click, but there's no way to hide commands that I'm aware of. This would be handy for launching beta features.

This could look like: `@click.command("some-command", hidden=True)`

**Comment by davidism** [comment]
This already exists.

**Comment by gitpushdashf** [comment]
I was just going to close this. My bad!

https://click.palletsprojects.com/en/8.0.x/api/?highlight=click%20group#click.Command
