### ISSUE TITLE
feat: `.add_group()` method

### ISSUE THREAD

**Issue by leungyauming** [pallets/click#2141]
AFAIK `.add_command(<func>)` can achieve the same effect as `@click.command()` and `@group.command()` directly, but there is no function to achieve the same effect as `@group.group()` (nested group) directly, I can only achieve nested group by using `.add_command(click.group()(<func>)` which is kind of too verbose.

I could work on this and open a pull request but I want to see if anyone wanted this feature before I put my hands on.

**Comment by davidism** [comment]
A group is a special command. An `add_group` method wouldn't do anything different than `add_command`.

**Comment by leungyauming** [comment]
I surely know that it is a special command but the problem is my IDE is not happy with it. And if there is `click.group`, why not one more `.add_group`.
