### ISSUE TITLE
Support union types

### ISSUE THREAD

**Issue by saroad2** [pallets/click#2147]
Description
=======
More than once you want an an argument or an option to be able to get multiple types of variables.

While this ability *has been suggested* previously in #1729, and it was closed, I do think that it should be a built-in feature of `click` because of the followings:

* It is a **very common** use-case that I'm sure almost everybody faced some time.
* It is really easy to implement (I believe).
* It allow us to write more elaborated behaviors with less code.

Example
======
The most common example I can think of is when you need an argument to be able to get both numbers and strings.

For example, let us think about a CLI that can run on multiple cores. You might want to specify how many cores to run the CLI on.
So, we add a `-j` flag that excepts integers to specify the number of cores to run.

Now, one might want to tell the CLI to run on **all** of the cores or **half** of the cores. One might do that as follows

```python
import click

@click.command()
@click.option('-j', '--jobs', type=click.Union(int, click.Choice(["all", "half"]))
def run_cli(jobs):
   ...
   # Run on cores as stated
```

Features
======

A few features I believe should be implemented:

* Support of union default types such as `click.Union(int, float)`
* **Order should matter** - `click` should try to parse the flag according to the order of the components of `click.Union`. So when having `click.Union(int, float)`, `click` would try to parse `int` first and then `float`.

If you think this ability should be added (which I strongly do), I'll take a chance trying to develop it.

**Comment by davidism** [comment]
Thanks for the details. However, this still sounds like a better fit for a custom param type. I'm going to close this with the same recommendation as #1729.

**Comment by saroad2** [comment]
Even though custom types is a valid solution, I kindly disagree.

Hope you'd change your mind.
