### ISSUE TITLE
When use 'user' as envvar and auto_envvar_prefix, it can not return the correct user value

### ISSUE THREAD

**Issue by fred214** [pallets/click#2153]
Environment:
- System: MacOS Monterey 12.0.1
- Python version: 3.9.9
- Click version: 8.0.3

```
@click.option('-u', '--user', envvar='USER', help='Database username')
......
def extract(host, port, user, password, database, skip):
......
extract(auto_envvar_prefix='EXTRACT')
```
when use `env EXTRACT_HOST=1.2.3.4 EXTRACT_USER=db EXTRACT_PASSWORD='123456' EXTRACT_DATABASE=db python main.py --skip extract`, the args is:
```
(Pdb) args
host = '1.2.3.4'
port = 3306
user = MY_USER_NAME
password = '123456'
database = 'db'
skip = ('extract',)
```
The user value is `MY_USER_NAME`, not the `db`, but when I change option `user` to `username` and `USERNAME` as envvar, it works well

**Comment by davidism** [comment]
Explicitly defining an env var overrides/does not combine with an auto prefix.
