### ISSUE TITLE
`click.echo_via_pager` does not use pager when stdin is not tty. Why is this the case?

### ISSUE THREAD

**Issue by paw-lu** [pallets/click#2159]
## Issue

`click.echo_via_pager` does not output via a pager when stdin is not a tty—such as when something is piped to app. This is due to this line:

https://github.com/pallets/click/blob/6411f425fae545f42795665af4162006b36c5e4a/src/click/_termui_impl.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L347

where `not isatty(stdin)` is explicity checked.

## How to replicate

```python
"""main.py"""
import click

click.echo_via_pager("Hello world")
```

```sh
% python main.py
# Pager is called here

% echo 'Lorep' | python main.py
Hello world  # Not pager, just printed to stdout
```

## Expected behavior

I completely understand why `not isatty(stdout)` is checked before chosing whether to call a pager, but why is `not isatty(stdin)` checked? I would think that if input is piped or redirected into the command, I would still like click to output as a pager when possible. Are there some cases that I'm missing here? If there is, could we add an argument in `echo_via_pager` to override the check?

## Environment

- Python version: 3.10
- Click version: 8.0.3

**Comment by davidism** [comment]
If it's not a TTY, it's not possible to guarantee that it's executing interactively, it could be part of a scripted pipeline, which would cause it to hang or fail unexpectedly.

**Comment by paw-lu** [comment]
Thanks for the response! And thanks for helping maintain the library.

> If it's not a TTY, it's not possible to guarantee that it's executing interactively

Yeah I get you there. But isn't this general case covered by the second check—`isatty(sys.stdout)`? What extra edge cases does checking `isatty(sys.stdin)` bring? What would happen if we dropped the `stdin` check but kept the `stdout` check?

**Comment by davidism** [comment]
Whether stdout is piped to a file doesn't tell us about the interactivity of stdin. They are both separate conditions where a pager doesn't work.

**Comment by paw-lu** [comment]
Okay, I think I misunderstood. So you're saying there are cases where `isatty(sys.stdout) == True` and `isatty(sys.stdin) == False` that calling a pager would break? I didn't know this was the case. I thought we would only need to care about the output state.

Closing the issue then. Is there any way here to deal with this edge case?
