### ISSUE TITLE
Option ordering wrong in the documentation

### ISSUE THREAD

**Issue by daviddavis** [pallets/click#2169]
If you read [the click documentation](https://click.palletsprojects.com/en/8.0.x/) the first thing you'll see is an example with two options (count and name):

```python
@click.command()
@click.option('--count', default=1, help='Number of greetings.')
@click.option('--name', prompt='Your name',
              help='The person to greet.')
def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for x in range(count):
        click.echo(f"Hello {name}!")
```

I know that the order probably doesn't matter since click is passing the options as keywords but shouldn't the order of the options technically be reversed since python executes the decorators in reverse order (inner one first)?

```python
@click.command()
@click.option('--name', prompt='Your name',
              help='The person to greet.')
@click.option('--count', default=1, help='Number of greetings.')
def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for x in range(count):
        click.echo(f"Hello {name}!")
```

**Comment by davidism** [comment]
Click is implemented in such a way that its decorators can be read top to bottom.
