### ISSUE TITLE
Multiple values not parsed at prompt

### ISSUE THREAD

**Issue by skieffer** [pallets/click#2172]
It seems like there's no way to enter values at the interactive prompt, for an option having `multiple=True`.
I searched for help on this, but couldn't find any.

# Example

With this script:

```python
import click

@click.command()
@click.option('--names', multiple=True, prompt='Names')
def foo(names):
    print(names)

if __name__ == "__main__":
    foo()
```
I tried every way I could think of to enter two names:
```shell
Names: foo bar
Error: Value must be an iterable.
Names: foo, bar
Error: Value must be an iterable.
Names: [foo, bar]
Error: Value must be an iterable.
Names: (foo, bar)
Error: Value must be an iterable.
Names: 'foo' 'bar'
Error: Value must be an iterable.
Names: 'foo', 'bar'
Error: Value must be an iterable.
Names: ['foo', 'bar']
Error: Value must be an iterable.
Names: ('foo', 'bar')
Error: Value must be an iterable.
```

but none of the obvious options seems to work.

## Possible Solutions?

It looks like [input parsing is supported when the value is drawn from an environment variable](https://click.palletsprojects.com/en/8.0.x/options/#multiple-values-from-environment-values). Maybe the same parsing should be applied to strings entered at an interactive prompt?

The exception is raised here:

https://github.com/pallets/click/blob/41f5b7a7967bb65910e8837bd4e8542a18feec6c/src/click/core.py#L2250-L2259

## Environment:

- Python version: 3.8.12
- Click version: 8.0.3

**Comment by jcrotts** [comment]
See these issues for context: https://github.com/pallets/click/issues/218 https://github.com/pallets/click/issues/1289

PRs are welcome, but it would probably require a significant change to the parser.
The easiest thing to do is prompt interactively, alternatively you could do your own parsing in a callback.

Closing this for now, but if you are interested in changing this behavior we can re-open.

**Comment by skieffer** [comment]
Thanks very much for the feedback. I did search for open issues containing the word `multiple`, but I forgot to search for closed ones!

I would _tentatively_ be interested in working on this (not necessary soon though). Would it be possible to give a rough idea of what about the parser would have to change?
