### ISSUE TITLE
Option(prompt=True, multiple=True)

### ISSUE THREAD

**Issue by kolypto** [pallets/click#218]
Click's support for 'prompt' is great! And many thanks for the excellent library :)

However, `prompt=True` does not play well with `multiple=True`.

Playing with this example:

``` python
import click

@click.command()
@click.option('-v', '--value', 
              prompt=True, multiple=True)
def cli(value):
    print value  # just print the value

if __name__ == '__main__':
    # supporing env vars
    cli.main(auto_envvar_prefix='TEST')
```

Let's first pass multiple options (it works):

``` console
$ python cli.py -v1 -v2 -v3
(u'1', u'2', u'3')
```

Great, now let's test the prompt:

``` console
$ python cli.py
Value [()]: 1 2 3
(u'1', u' ', u'2', u' ', u'3')
```

Hmm, the input is not split using spaces!

Okay, maybe environment variable does it better?

``` console
$ TEST_VALUE="1 2 3" python cli.py
(u'1', u'2', u'3')
```

Yes, it does!

---

I suggest to inherit the `auto_envvar_prefix` behavior by default, and also introduce a keyword that can preprocess a value _only_ if it was taken from the prompt. 

Or even better, support a callable `prompt` keyword which accepts the same keyword arguments as `prompt=True` would set: it will enable the user to pass `click.prompt` with any custom settings:

``` python
@click.option(prompt=lambda **kwargs: click.prompt(**kwargs))
def cli(value):
    #...
```

Or at least prevent it from splitting the string as an iterable :)

**Comment by testn** [comment]
has there been some improvement to this problem? I would like to explore the option of sentinel such as blank line to stop accepting more values.

**Comment by mitsuhiko** [comment]
The proper solution is to prompt in the function interactively instead of outside.  This is just too complex to handle at that layer.
