### ISSUE TITLE
Show help for all commands (follow-up)

### ISSUE THREAD

**Issue by bittner** [pallets/click#2183]
This is a follow-up on #1449.

> To get an overview of a program's usage, it would be helpful to print help for all commands at once rather than having to run, e.g. `script.py command1 --help`, `script.py command2 --help`, etc.
> 
> This feature is important because the default top-level help doesn't indicate which commands have options, so it doesn't give a good overview of the program's functionality.

Counting the related questions and answers on the Web, there is significant interest to provide a solution for this problem.

## Solution Example

Based on the [approach from SO](https://stackoverflow.com/questions/57810659/), this could be a fully working solution:

```python
def help(ctx, param, value):
    """Show usage for all commands and exit."""

    def collect_help(cmd, parent=None):
        ctx = click.core.Context(cmd, info_name=cmd.name, parent=parent)
        if parent:
            click.echo()
        click.echo(cmd.get_help(ctx))
        commands = getattr(cmd, 'commands', {})
        for sub in commands.values():
            collect_help(sub, ctx)

    if value:
        collect_help(ctx.command)


@click.group(click.utils._detect_program_name(), invoke_without_command=True, no_args_is_help=True)
@click.option("--help", is_flag=True, expose_value=False, callback=help, help=help.__doc__)
def main():
    """CLI application starts here."""
```

The above implementation shows the simple help screen (group help) when invoked w/o arguments and the full help screen with `prog_name --help`.

To reduce the clutter of the resulting screen, the individual `--help` options may be suppressed using `help_option` decorators on each command like this:

```python
@click.help_option(hidden=True)
```

## Criticism

- [ ] The verbose argument list in the `@click.group(...)` decorator is ugly, but it's unfortunately needed to:

   - suppress an `Error: Missing command.` when using `--help` on the main group, and
   - display the correct `prog_name` for all commands in the help screen (the name of the group _function_ is used, otherwise).

- [ ] It would be nice to suppress the verbose, recurring, redundant `--help` options _programmatically_ in the `help` function above.

- [ ] The output still says, `Usage: prog_name foo ...` for each command, repeatedly, which may be nice to simply replace by `Command: foo ...` (as already remarked in #1449). – _OTOH, usage instructions remain complete when it stays like it is._

## Proposal

Probably the simplest thing to do would be to add the above code sample to the Click documentation. Potential places:

- [Options](https://click.palletsprojects.com/en/latest/options/) chapter
- [Commands and Groups](https://click.palletsprojects.com/en/latest/commands/) chapter
- [Examples](https://click.palletsprojects.com/en/latest/quickstart/#screencast-and-examples) in Quickstart

Alternatively, we turn the above code into a decorator and add it to the Click code base.

Would you be open for a PR on either extending the docs or adding a decorator as explained?

**Comment by davidism** [comment]
Thanks, however I don't plan to change my decision at this time. As you've pointed out, the proposed code snippet doesn't really create nice output, and has other issues. See https://github.com/pallets/click/issues/1449#issuecomment-642044041.

**Comment by bittner** [comment]
Can someone give indications on how to improve the situation with the group annotation in the snippet? Is there a better way?

```python
@click.group(click.utils._detect_program_name(), invoke_without_command=True, no_args_is_help=True)
```

If I understand your closing comment in #1449 correctly, the objection all refers to adding a feature to the code base. But given the popular interest, would it be okay to add a solution to the documentation? It would certainly help to avoid future frustration and more questions on the topic.

**Comment by bittner** [comment]
I have attempted to further improve the code, thus reducing some of my own solution criticism. Would the solution now be good enough for inclusion in the Click documentation?

Alternatively, I'd be happy if we could collaboratively try to improve the approach, maybe make minor adjustment to the Click code base to allow simpler, more elegant solutions before adding the code sample as a solution to the docs. Specifically, the call to the "protected" member above catches my eye.

FYI @alphapapa
