### ISSUE TITLE
[Feature] Set progressbar ETA manually

### ISSUE THREAD

**Issue by saroad2** [pallets/click#2186]
Description
========
One should be able to set `click.progressbar` ETA (estimated time of arrival) **manually**.

Why?
====
Sometimes you want to use `click.progressbar` when you know that processing each element in this bar can be done in very different time spans (some elements take shorter time to process while others take a long time). You still want to show ETA, but you know that the automatic way *Click* is calculating this ETA is inaccurate.

In my personal use case, I have statistics on each task on how long it normally takes, so I can calculate ETA **historically** pretty easy.

Proposed Syntax
===========
```python
import click


@click.command()
def my_command():
    with click.progressbar(length=20) as bar:
        for i in bar:
            time.sleep(0.5)
            bar.eta = eta_in_seconds
```

**Comment by davidism** [comment]
I don't plan to make further changes to Click's progress bar implementation. Use tqdm or rich instead if you need additional features.
