### ISSUE TITLE
Add click.Path option that allows checking for executable flag

### ISSUE THREAD

**Issue by blsqr** [pallets/click#2192]
[`click.Path`](https://click.palletsprojects.com/en/8.0.x/api/#click.Path) already allows checking whether a path points to a directory ( `dir_okay`) or a file ( `file_okay`) and whether it is `readable` and/or `writeable`. I would suggest to add an additional `executable` flag that would check if the executable bit is set for the file or directory the path points to.

This surely can be achieved via a custom type, but it seems to me that this would be a valuable extension of `click.Path` as it would lead to all three access modes being checkable via click.  
I am happy to contribute to an implementation, if there is any interest in this.

**Comment by davidism** [comment]
Duplicate of #1961

**Comment by blsqr** [comment]
Ah, I missed that one, sorry! 👍
