### ISSUE TITLE
Incorrect type hint when @command uses a custom class

### ISSUE THREAD

**Issue by matejcik** [pallets/click#2211]
The `@command` decorator is annotated as always returning `Command`.

This is a problem when supplying custom class, e.g.:
```python
@click.command(cls=MyClass)
def foo():
     ...

reveal_type(foo)  # revealed type is `Command`
foo.my_property = 6  # error: `Command` does not have a member `my_property`
```

Environment:

- Python version: any
- Click version: 8.x

**Comment by davidism** [comment]
This is causing issues, please see #2227 and #2233.
