### ISSUE TITLE
`Group` code is executed when subcommand is invoked with `--help` but not through `click.testing.CliRunner`

### ISSUE THREAD

**Issue by sphuber** [pallets/click#2222]
Consider the following minimal script:
```python
import click

@click.group()
def cli():
    raise RuntimeError()

@cli.command('sub')
def sub():
    click.echo('all good')

if __name__ == '__main__':
    cli()
```
When calling the `--help` for the main command all is fine:
```
(aiida_dev) sph@citadel:~/code/aiida/env/dev/ro-crate-py$ python test_cli.py --help
Usage: test_cli.py [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  sub
```
But when calling the `--help` for the `sub` command, the `RuntimeError` is hit:
```
(aiida_dev) sph@citadel:~/code/aiida/env/dev/ro-crate-py$ python test_cli.py sub --help
Traceback (most recent call last):
  File "/home/sph/code/aiida/env/dev/ro-crate-py/test_cli.py", line 12, in <module>
    cli()
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.9/site-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sph/.virtualenvs/aiida_dev/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sph/code/aiida/env/dev/ro-crate-py/test_cli.py", line 5, in cli
    raise RuntimeError()
RuntimeError
```
Is this intended behavior? Should the body of the `cli` `Group` be executed if a sub-command receives the `--help` option?
And if this is the intended behavior, how can we properly test for this.
If we invoke `sub` through the `click.testing.CliRunner` the exception is not hit:
```python
In [1]: import click
   ...: 
   ...: @click.group()
   ...: def cli():
   ...:     raise RuntimeError()
   ...: 
   ...: @cli.command('sub')
   ...: def sub():
   ...:     click.echo('all good')
   ...: 

In [2]: from click.testing import CliRunner

In [3]: CliRunner().invoke(sub, ['--help'])
Out[3]: <Result okay>
```

Environment:

- Python version: 3.9.11
- Click version: 8.0.4

**Comment by davidism** [comment]
Yes, this is expected, and has been discussed and explained multiple times before. Click's processing pipeline is completely dynamic and nested, each command has to run before the next is processed because a prior command can affect subsequent ones.

**Comment by sphuber** [comment]
Apologies for the noise then. But could you perhaps point me where in the documentation this is explained? I read the [testing documentation](https://click.palletsprojects.com/en/8.0.x/testing/) but could not find anything on this subject. If it doesn't exist yet, I would be happy to contribute a PR with added docs to explain this, if you like. Would seem useful especially given that apparently this has been discussed and explained multiple times before as you said.
