### ISSUE TITLE
ImportError: cannot import name '_unicodefun' from 'click'

### ISSUE THREAD

**Issue by karthiknadig** [pallets/click#2225]
Environment:

- Python version: 3.10.2
- Click version: 8.1.0

This used to work fine with previous version, now I get this error when running tools like `black`:
```
ImportError: cannot import name '_unicodefun' from 'click' (/lib/python3.10/site-packages/click/__init__.py)
```

**Comment by davidism** [comment]
This internal module is no longer needed for any supported version of Python, and has been removed.

**Comment by karthiknadig** [comment]
when will the fixed version be out?

**Comment by ThiefMaster** [comment]
https://github.com/psf/black/blob/f239d227c003c52126239e1b9a37c36c2b2b8305/src/black/__init__.py#L1430-L1434

looks like you just need to use a recent black version.

**Comment by Sillocan** [comment]
@karthiknadig This is an issue with black, not with click. https://github.com/psf/black/issues/2964

**Comment by karthiknadig** [comment]
@Sillocan Thanks for info and Sorry for missing the details on this.

**Comment by arogozhnikov** [comment]
It is an issue with click too. Namely, very short notices on deprecations.

> Black 22.3.0 has already been released to address this.

There are multiple other packages affected: to me those are typer and prefect.

I've updated black and changed formatting of projects. 
Now I see other parts are not working and I probably need to downgrade black and revert formatting again. 

I have previously suffered from click not being able to maintain relatively stable API (7 vs 8), but these immediate deprecations in minor versions are over my understanding.

**Comment by ThiefMaster** [comment]
A module starting with an underscore was always internal and never meant to be relied upon / used by anyone else. so while you may have a strong opinion about removing/deprecating anything that was part of a public API, this certainly cannot applied to `_unicodefun`...

**Comment by arogozhnikov** [comment]
typer and prefect are broken because of change in **public** API and yes, I do have strong opinion on this.

And I have strong opinion on that function from public API that you deleted - it could be there for years in deprecated mode and nothing would break, but it was deleted.
