### ISSUE TITLE
Choice.convert should use `get_missing_message`

### ISSUE THREAD

**Issue by kevinastone** [pallets/click#223]
Was trying to use `get_missing_message` to offer spelling correction suggestions, but the fail message is hard-coded:
https://github.com/mitsuhiko/click/blob/master/click/types.py#L148-L149

**Comment by dawran6** [comment]
See: https://github.com/pallets/click/blob/master/click/types.py#L161-L162. I'm not sure when was this changed but `Choice.conver` uses `self.choices` instead of hard-coded:

```python
    def convert(self, value, param, ctx):
        ...
        self.fail('invalid choice: %s. (choose from %s)' %
                  (value, ', '.join(self.choices)), param, ctx)
```
