### ISSUE TITLE
Regression: Type errors caused by untyped decorator

### ISSUE THREAD

**Issue by Dreamsorcerer** [pallets/click#2231]
With 8.1 we are now getting errors in mypy due to the `.command()` decorator.

Looking at the code (https://github.com/pallets/click/blob/main/src/click/core.py#L1814), it appears to have been changed to a `Union` while adding support for not calling the decorator before the function.

As per the mypy documentation, this should be represented with overloads, rather than a union:
https://mypy.readthedocs.io/en/stable/generics.html?highlight=decorator#decorator-factories

**Comment by davidism** [comment]
Happy to consider a PR that updates the type annotations.

**Comment by Dreamsorcerer** [comment]
Sorry, duplicate of #2227.
