### ISSUE TITLE
Click 8.1 changed the parameter order in click.Path

### ISSUE THREAD

**Issue by timj** [pallets/click#2235]
In #1962 (released as 8.1.x) the writable and readable parameters for the `click.Path` constructor changed order (and the executable parameter was not added at the end of the parameter list). This breaks code that was not using kwargs in the constructor.

See for example the breakage from lsst/daf_butler#669.

We have switched to kwargs. The API is not requiring that it only be used with kwargs and so we had not used kwargs previously.

Please consider using the `*` parameter in the APIs that are assumed to be kwargs only as this would enforce the policy.

Environment:

- Python version: 3.8
- Click version: 8.1.1

**Comment by davidism** [comment]
This was in the middle of a long list of arguments with no clear order, and with a clear fix. Using `*` consistently across the API required a minimum version of Python, and also requires a lot more compat code to migrate people over, so it's a longer term thing.

**Comment by davidism** [comment]
Hmm, I'll just put the parameter at the end until I can figure a better way to migrate to keyword-only args.

**Comment by davidism** [comment]
Click 8.1.2 is available: https://pypi.org/project/click/8.1.2/
