### ISSUE TITLE
What is security vulnerability 47833 about?

### ISSUE THREAD

**Issue by leberknecht** [pallets/click#2242]
Sorry for selecting "Feature Request", this is obviously a "Question" but it also obviously doesnt belong on stackoverflow...

So `saftey` started reporting that click is vulnerable. As im depending on flask, which requires click <8.0.0, i need to know if its safe for me to ignore this, so i need to know what exactly this is about and/or how to mitigate.

**Comment by leberknecht** [comment]
![image](https://user-images.githubusercontent.com/1165177/161510720-ab604d53-fd86-439b-ae9d-69f4b6bf9adb.png)

**Comment by ThiefMaster** [comment]
I have no idea what that tool is, but I don't think we have any CVEs and Snyk doesn't show anything either: https://snyk.io/advisor/python/click#security

Considering that the site you screenshotted (https://pyupio.github.io/safety-db/ so others don't have to type the URL manually) doesn't show any details when clicking on `<8.0.0` and have a bunch of nonsense for other package names, I wouldn't give it a second thought...

![image](https://user-images.githubusercontent.com/179599/161511363-c9316584-099a-4676-9c05-dd7b1b611ae0.png)

**Comment by leberknecht** [comment]
Uh, my apologies, i understood that pyup works in a way that they sync with the vendors.. Nevermind, i will ping them then and see if we somehow can find out what this is about.

**Comment by vincent-prz** [comment]
it seems that the reported error is legit, see https://github.com/pyupio/safety-db/issues/2354

Is there any plan to fix this in the version 7 ? It would be nice to be forced to migrate to v8. Thanks!

**Comment by davidism** [comment]
Only the latest feature release receives fixes. Currently, that's the 8.1.x branch.
