### ISSUE TITLE
decorator 'version_option' throws TypeError

### ISSUE THREAD

**Issue by chr7** [pallets/click#2250]
Adding the [version_option decorator](https://click.palletsprojects.com/en/8.1.x/api/#decorators) and specifying `param_decls` throws a `TypeError`.

```python
import click


@click.command()
@click.version_option(version='alpha', param_decls='-V')
def app():
    pass


if __name__ == '__main__':
    app()
```

![image](https://user-images.githubusercontent.com/7242780/162200455-77ab48ba-0ffa-42c8-bb57-c9d61a7998a5.png)

Environment:

- Python version: 3.10.3
- Click version: 8.1.2

**Comment by chr7** [comment]
I still get a `TypeError`:

```python
import click


@click.command()
@click.version_option('-V', version='alpha')
def app():
    pass


if __name__ == '__main__':
    app()
```

throws `TypeError: version_option() got multiple values for argument 'version'`

**Comment by davidism** [comment]
Please compare your code to the signature from the docs: https://click.palletsprojects.com/en/8.1.x/api/#click.version_option

**Comment by chr7** [comment]
Ok, the following line works: `@click.version_option('alpha', '-V')`

But the documentation is misleading because it says:
`click.version_option(version=None, *param_decls, package_name=None, prog_name=None, message=None, **kwargs)`

thus at the first glance it looks like `version` is a keyword argument which is actually not the case, it's positional. Improving the documentation here would help to avoid this trap.
