### ISSUE TITLE
incompatibility python 3.7.* and click 8.1.2

### ISSUE THREAD

**Issue by qoffee** [pallets/click#2257]
Hello everyone, my code crashes on [this](https://github.com/pallets/click/blob/14472ffcd80dd86d47ddc08341168152540ee6f2/src/click/types.py#L165) line.
I think this is due to [this](https://bugs.python.org/issue34422) error.
When I changed the `__name__` to `_name`, the code started working fine.
The error was the following:
![image](https://user-images.githubusercontent.com/23388221/164721651-baea9276-48b7-4dce-94d6-7d1979e1b3eb.png)

**Comment by davidism** [comment]
I can't reproduce this error with the information provided. Be sure to follow the issue template when opening an issue.

I'm not clear why you would be decorating a `typing` object with `@click.command`. That's not an intended use case.
