### ISSUE TITLE
Nested option values

### ISSUE THREAD

**Issue by Elysium1436** [pallets/click#2258]
Include a way to create nested option values like the example below

The script execution
`myscript --parent.child=hello`

The script
```python
@cilck.group
def cli():
    return

@cli.command()
@click.option("--parent.child")
def command(parent):
    assert isinstance(parent,dict) #True
    print(parent["child"]) #hello
```

**Comment by ThiefMaster** [comment]
That seems like something very rarely used; I don't think such functionality should be part of click. But maybe it's possible as a separate package (written and maintained by someone else who actually needs this of course) extending click...?

**Comment by Elysium1436** [comment]
I see, i'll look into how to extend click and see if I can take a shot on it. Thanks!
