### ISSUE TITLE
Mark parameter as deprecated

### ISSUE THREAD

**Issue by stmlange** [pallets/click#2263]
Thanks for this great project!
Perhaps it's just me who feels that it is rather cumbersome mark a single parameter as deprecated (the closet I found was https://stackoverflow.com/a/50402799). Is there perhaps a more official method to mark a single parameter as deprecated?
That would somewhat be similar to https://github.com/pallets/click/issues/1507.

Possible scenarios:
- the parameter was renamed (e.g. a previous version was using `--name` as option, but now a dev want's to make sure it's the `--sur-name`.
- the parameter is not needed anymore

Perhaps as an example consider:
```
import click

@click.command()
@click.option('--count', default=1, help='Number of greetings.')
@click.option('--name', prompt='Your name',
              help='The person to greet.')
def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for x in range(count):
        click.echo(f"Hello {name}!")

if __name__ == '__main__':
    hello()
```
and I want to rename `--count` to `--greetings-count`.
However I don't want to remove  `--count`  instantly, instead when users use `--count` prompt a message that they should use the new `--greetings-count`. The usage of `--count` and `--greetings-count` should be forbidden.

Thanks.

**Comment by peacock0803sz** [comment]
I'll work on this

**Comment by peacock0803sz** [comment]
@davidism I just implemented to show the message with `--help`.
Is it better to show same message running without `--help`?

**Comment by adam-tokarski** [comment]
Hi, @peacock0803sz, what's the status of this issue? 

You've linked that PR which has to fix the issue, but it's not clear how exactly - I mean the PR is rather about printing the thing out in `help`, right?

Is the more appropriate PR maybe already merged? Or it's not created yet?

**Comment by wpietri** [comment]
Just wanted to share an example of the second use case, the one where an option is being removed. I changed the option line to look like this:

```
@click.option("--parallel", default=False, help="Obsolete flag, soon to be removed")
```
and then added this at the top of the command function:

```
    if parallel:
        click.echo("--parallel option unnecessary; benchmarks are now always run in parallel")
```

If click were to add a `deprecated` flag for options, I'd want to use it like this:

``
@click.option("--parallel", default=False, deprecated="--parallel option unnecessary; benchmarks are now always run in parallel")
````

That would a) remove the option from the help listing, and b) print the text I give it if somebody tries to call it. It should also skip as much validation as possible, so that users don't get negative feedback that doesn't really matter.

**Comment by AndreasBackx** [comment]
Those that are interested in having this added to Click. I've updated #2271 to make it cover hopefully everything that is desired. The only thing I think of still adding is allowing the customisation of the deprecation message as highlighted by @wpietri. Any feedback on the PR is welcome.
