### ISSUE TITLE
invoked_subcommand is always None in option callback on group with given subcommand

### ISSUE THREAD

**Issue by ulope** [pallets/click#2274]
When defining an option with a callback on a `Group` the `invoked_subcommand` attribute in the `Context` passed to the callback is always `None` even if a subcommand was indeed passed.

Minimal example:

```python
import click

def cb(ctx, param, value):
    print(f'callback {ctx.invoked_subcommand=}')


@click.group()
@click.option('-o', callback=cb)
@click.pass_context
def main(ctx, o):
    print(f'group {ctx.invoked_subcommand=}')


@main.command()
def cmd():
    ...

if __name__ == "__main__":
    main()
```

Run with `python file.py cmd`

Actual output:
```
callback ctx.invoked_subcommand=None
group ctx.invoked_subcommand='cmd'
```

Expected output:
```
callback ctx.invoked_subcommand='cmd'
group ctx.invoked_subcommand='cmd'
```

Environment:

- Python version: 3.9.2
- Click version: 8.1.3

**Comment by davidism** [comment]
That's because a command is not being invoked yet, the options are processed before the group callback, and then the subcommand. `invoked_subcommand` will be available once the group callback processing starts, which is after the option processing ends. Perhaps you're looking for a `result_callback`?

**Comment by ulope** [comment]
No, I'm indeed looking for option callbacks.

My use case is for options on a group to change behaviour (e.g. change required status) depending on which subcommand was invoked.

**Comment by davidism** [comment]
That's not possible with the way the pipeline works. Option processing happens before group and subcommand processing.
