### ISSUE TITLE
Shell completion - could not detect bash version

### ISSUE THREAD

**Issue by mkb79** [pallets/click#2276]
Adding shell completion does not work with my OS. I got the RuntimeError `Couldn't detect Bash version, shell completion is not supported.`.

`shell_completion.py:306` will run the command `bash -c echo ${BASH_VERSION}` to get the bash version. This command gives me a blank line. But if I run `echo ${BASH_VERSION}` I got `5.1.4(1)-release`.

Environment:

- Python version: 3.9.2
- Click version:
- OS: Debian 11

**Comment by davidism** [comment]
`bash -c 'echo ${BASH_VERSION}'` returns a version for me. You need to use single quotes around the command so that the variable is expanded in the subcommand.

**Comment by mkb79** [comment]
> `bash -c 'echo ${BASH_VERSION}'` returns a version for me. You need to use single quotes around the command so that the variable is expanded in the sub

Yes, this work. But click does not use single quotes [here](https://github.com/pallets/click/blob/c96545f6f4ba0eab99de6ec8b4ceb77c9bdb2528/src/click/shell_completion.py#L306), so the command failed with a RuntimeError!

**Comment by mkb79** [comment]
Updating click from 8.0.2 to 8.1.3 solves the issue.

**Comment by davidism** [comment]
`subprocess.run` is not the same as typing in the shell, each individual list item is quoted automatically.
