### ISSUE TITLE
Support custom shell behaviors for autocompletion

### ISSUE THREAD

**Issue by msarahan** [pallets/click#2277]
Bash supports two custom behaviors that are helpful to our application: 

* the ability to change what defines a word break
* the ability to not emit a space when a matching completion is found

We add this behavior to the click-generated bash script like so:

```
    local IFS=$'\n'
    local response

    response=$(env COMP_WORDS="${COMP_WORDS[*]}" COMP_CWORD=$COMP_CWORD _GUILD_COMPLETE=bash_complete $1)

    COMP_WORDBREAKS='"'"'"'><=;|&(: '  # Reset as can be modified below.
    for completion in $response; do
        IFS=',' read type value <<< "$completion"
        if [ "$value" = "!!nospace" ]; then
            compopt -o nospace
            continue
        elif [ "$value" = "!!no-colon-wordbreak" ]; then
            # Dangerous as this effects other completions. The damage
            # is mitigated by resetting COMP_WORDBREAKS above but this
            # is still not ideal.
            COMP_WORDBREAKS='"'"'"'><=;|&( '
            continue
        fi
        if [[ $type == 'dir' ]]; then
            COMPREPLY=()
            compopt -o dirnames
        elif [[ $type == 'file' ]]; then
            COMPREPLY=()
            compopt -o default
        elif [[ $type == 'plain' ]]; then
            COMPREPLY+=($value)
        fi
    done
```

We then use custom shell_complete functions in python to emit these values (`!!nospace` or `!!no-colon-wordbreak`) where we want to enable those behaviors. We use psutil to detect the parent shell, and when that is bash, we emit these strings.

Would this be of interest to include in click? If so, I'd be happy to add it and document it. I'm just not sure if it is too bash-specific to be in click, and also pretty sure the psutil dependency would be too much to ask.

**Comment by davidism** [comment]
You've done exactly what is intended by the completion mechanism in Click. Create a subclass of `ShellComplete` with your script and handling for your custom messages. Emit custom `CompletionItem` messages from `shell_complete` callbacks. I don't plan to add complexity to the built-in completion, but you can always publish an extension on PyPI if you want to make this available to others.
