### ISSUE TITLE
Documentation of decorators should should show where to look for arguments' reference  

### ISSUE THREAD

**Issue by MrMino** [pallets/click#2280]
I've just started exploring click, and wholeheartedly love it. Thanks!

One thing that made the experience a bit frustrating was the API reference. Currently, in some places, it omits descriptions of the arguments of some of the decorators. For example, with [`click.argument`](https://click.palletsprojects.com/en/8.1.x/api/#click.argument), it just says the type is `Any` without telling where to look for the actual description:

![image](https://user-images.githubusercontent.com/6691643/167310684-18074b81-3932-4bc8-b7e4-5af48cf8f8b2.png)

I guess it's because the underlying argument class is customizable, but for the default usecase it would be nice to have a reference to the default.

Clicking on the reference to [`click.Argument`](https://click.palletsprojects.com/en/8.1.x/api/#click.Argument) doesn't reveal much either:

![image](https://user-images.githubusercontent.com/6691643/167310805-d624ec5c-728a-4f73-9f72-43c7a86ee9c9.png)

It would be nice if the description of `attrs` pointed to their actual reference: [`click.Parameter`](https://click.palletsprojects.com/en/8.1.x/api/#click.Parameter) in case of `argument` and `option` decorators.

There's already a precedent for this in the docs - [`click.Group`](https://click.palletsprojects.com/en/8.1.x/api/#click.Group):
![image](https://user-images.githubusercontent.com/6691643/167312103-295a3eee-42c7-436a-a2e0-cbbaebb001b0.png)

**Comment by Rowlando13** [comment]
Closing. Attached PR is merged.
