### ISSUE TITLE
Shell completion dependent on arguments already given (follow-on)

### ISSUE THREAD

**Issue by alexreg** [pallets/click#2290]
This follows on from the [previous issue](https://github.com/pallets/click/issues/2283) that was closed. I suspect I was not clear enough about the issue. Perhaps my [StackOverflow question](https://stackoverflow.com/questions/72252072/shell-completion-dependent-on-arguments-already-provided?noredirect=1#comment127652593_72252072) is clearer; I don't know. The one commenter on that question suggested it is *not* possible from "within the script", and the lack of other respondents suggests to me, at the very least, that the solution is non-trivial.

On the other hand, @davidism (whom I gather is a maintainer) responded briefly to the previous issue indicating that this *is* possible. I have double-checked the [documentation on shell completion](https://click.palletsprojects.com/en/8.1.x/shell-completion/?highlight=completion), and as far as I can tell, there is nothing about how to make shell completion of a given param depend on the values of params *already given* on the command line. So, it seems that either there was a miscommunication/misunderstanding here, or else it would be very useful to expand the documentation.

Thank you in advance.

**Comment by davidism** [comment]
I can't reproduce this issue with the information provided. Within a `shell_complete` callback, `ctx.params` contains values for already processed parameters.

**Comment by alexreg** [comment]
@davidism Okay, I will investigate further, and create an MRE if it doesn't work still.
