### ISSUE TITLE
Unintuitive argument capturing behavior 

### ISSUE THREAD

**Issue by woodruffw** [pallets/click#2307]
First of all, thanks for maintaining `click`! 

Consider the following CLI:

```python
@click.group()
def main() -> None:
    pass


@main.command("test")
@click.option(
    "output_signature",
    "--output-signature",
    metavar="FILE",
    type=Path,
    help="With a value, write a single signature to the given file; conflicts with --output",
)
@click.option(
    "output_certificate",
    "--output-certificate",
    metavar="FILE",
    type=Path,
    help="Write a single signing certificate to the given file; conflicts with --output",
)
def test(output_signature, output_certificate):
    print(f"{output_signature=}, {output_certificate=}")
```

Expected behavior:

When run as `foo.py --output-signature --output-certificate`, I expect one of two behaviors:

* Ideal: Ideally, `click` would raise an error, as neither option has a default value set and the semantics of default-constructing a path aren't clear.
* Less ideal, but understandably: `foo.py` should print `output_signature=None, output_certificate=None`, since neither option has a value on the argument vector

Actual behavior:

The actual output is `output_signature=PosixPath('--output-certificate'), output_certificate=None`, indicating that `--output-signature` has consumed the `--input-signature` option as its value. This is pretty unintuitive to me, as `--output-signature` is definitely known to Click's parser (via `click.option`).

Environment:

- Python version: `Python 3.10.0`
- Click version: `8.1.3`

**Comment by davidism** [comment]
Unfortunately, this is not something we can change. It may change if I ever have time to finished rewriting the entire parser and processing pipeline.

**Comment by woodruffw** [comment]
That's fair. Thanks for the rapid response!
