### ISSUE TITLE
Add show_envvar as global setting via context_settings (like show_default)

### ISSUE THREAD

**Issue by gertvdijk** [pallets/click#2313]
The context_settings / Context object allows for global setting of some option/command variables. For example, to show the default for all options and setting an auto-envvar-prefix, one can do this via `context_settings`:

```python
@click.command(context_settings=dict(show_default=True, auto_envvar_prefix="MYAPP"))
@click.option("--host", default="127.0.0.1")
@click.option("--port", default="1234")
```

Now, to also show the environment variable for each option in the `--help` output, it's required to add `show_envvar=True` for each `option`:
```python
@click.option("--host", default="127.0.0.1", show_envvar=True)
@click.option("--port", default="1234", show_envvar=True)
```

I'd like to have this available as global setting as well, ie., I wish this would work:

```python
@click.command(context_settings=dict(show_default=True, auto_envvar_prefix="MYAPP", show_envvar=True))
@click.option("--host", default="127.0.0.1")
@click.option("--port", default="1234")
```

**Comment by davidism** [comment]
If you have a default set of arguments you want to use repeatedly, use `functools.partial`.

```python
import functools

option = functools.partial(click.option, show_envvar=True)

@option("--host")
```

I could have sworn we've had a discussion about `show_envvar` before, but can't find it. In general, I'm against adding a context arg for every possible command/option arg.

**Comment by gertvdijk** [comment]
I know about `functools.partial` and it's my current work-around. Feels odd to have most of these settings available via context args, but then this one isn't. 😅

Perhaps either remove all of them or add all of them, but the current state feels weird to me.

**Comment by davidism** [comment]
Closing for now. There's a general goal to update the help formatter system to be more customizable in general, that's where I'd like to focus for these types of changes.
