### ISSUE TITLE
Copyright Notice Needs to be Updated in the Docs

### ISSUE THREAD

**Issue by navneethc** [pallets/click#2319]
The Click documentation still shows 2014.

Visit https://click.palletsprojects.com/en/8.1.x/  and scroll down to the bottom of the page and notice the year, it says 2014. 

It's 2022.

Environment:

- Python version: N/A
- Click version: N/A

**Comment by davidism** [comment]
That's not how copyright works. The copyright would be valid even if there was no date at all (and even if there was no notice at all), therefore keeping it at the year the work was created is fine.
