### ISSUE TITLE
Use arbitrary set of input/output streams throughout the sources

### ISSUE THREAD

**Issue by happz** [pallets/click#232]
Hi,

my use case is this - I use click to power simple CLI I use in a custom REPL, available over current terminal (stdin/stdout/stderr). Now I'd like to extend this functionality to work over networked streams, which would require click to became aware of world where arbitrary input/output streams exist, not just stdin/stdout.

The Perfect Solution for me would be to pass pair (or triplet) of IO streams to Command when I call it in my internal loop, using context or any other way available. I'd also like to use the very same Command structure I have already created for my stdin/stdout CLI to serve for network streams - code is same, the only difference is just another set of streams the code works with.

I might be able to update sources myself and create pull request, but this requires someone more familiar with internals - e.g. function like prompt, confirm, etc. call echo directly and I have no idea how to teach them about ^^^ without their API getting modified which I think needs more careful planning than just "hey, I did this, accept it."

**Comment by davidism** [comment]
I'm not really clear what the requirements are based on the description. Given the age and lack of activity, going to close this for now.
