### ISSUE TITLE
Support for localization of messages

### ISSUE THREAD

**Issue by mmdbalkhi** [pallets/click#2320]
For ease of reading messages in different languages, I think it's great that Click uses po for **localization**. I don't mean the Click itself, but the programs that are **made** by the **Click**.

**Comment by ThiefMaster** [comment]
what exactly are you asking for though? if an application wants to use i18n it needs to wrap its own strings in gettext calls... they're nothing click can do for that.

**Comment by mmdbalkhi** [comment]
> what exactly are you asking for though? 

I mean that the Click internally uses po files for localization, if locales were available

**Comment by davidism** [comment]
Click already wraps internal strings with gettext.  This allows any project that wants to offer a different language to translate Click's messages along with their own.
