### ISSUE TITLE
strip "_command" suffix when generating command name

### ISSUE THREAD

**Issue by davidism** [pallets/click#2322]
You often want a command to have the same name as a function it is wrapping. However, this will cause a name collision, if your command is going to call `init_data` its function can't also be called `init_data`. So instead it's written as `init_data_command`, and then the command name has to be specified manually `@command("init-data")`. Click should remove a `_command` suffix when generating the command name from the function name.

```python
def init_data(external=False):
    ...

@cli.command
@click.option("--external/--internal")
def init_data_command(external):
    init_data(external=external)

```

Currently this command would be named `init-data-command`. After the change, it would be `init-data`.

**Comment by bebleo** [comment]
Hi @davidism, Am I right in assuming the expected behaviour would be that both `_command` and `_cmd` suffixes are dropped?

An example using `_cmd` as a suffix:

https://github.com/pallets/click/blob/fb4327216543d751e2654a0d3bf6ce3d31c435cc/examples/imagepipe/imagepipe.py#L74-L98

**Comment by davidism** [comment]
I'm going to stick with `_command` and `_group` only. Style guides usually suggest avoiding shorthand variable names in favor of complete words, so I'd rather encourage that.
