### ISSUE TITLE
Zsh completion: executable missing in $commands

### ISSUE THREAD

**Issue by tomasr8** [pallets/click#2328]
Hi all,
I'm using click with zsh autocomplete and I've noticed a slight issue with the way the zsh script checks for the existence
of the command you want to execute. This is the line in question: https://github.com/pallets/click/blob/main/src/click/shell_completion.py#L132

It currently checks if the command you want to autocomplete is in the `$commands` hash table. Now, I don't exactly know why, but zsh does not always update this table. To reproduce this, create a virtual env and install some python package. Let's say the package has an entrypoint called `foo-bar`. Even if you execute `foo-bar`, zsh won't update the `$commands` table which means that the check fails and thus autocomplete does not work. I can force zsh to update with `rehash` after which everything works fine.

To avoid this unexpected behaviour, I think it would be better instead of checking `$commands` directly, to use `command -v $progName` i.e.
```diff
- (( ! $+commands[%(prog_name)s] )) && return 1
+ (! [ $(command -v %(prog_name)s) ]) && return 1
```
This would provide a more robust solution for the zsh completion. Thoughts?

Environment:

- Python version: 3.8
- Click version: 8.1
- zsh version: 5.8

**Comment by davidism** [comment]
Shells (not just zsh, bash has the similar `hash -r`) cache commands for performance, and some tools like don't know to update this after altering `$PATH`. That's a problem with shells/tools in general, not with Click. It doesn't seem correct to bypass that cache by running an extra command on every invocation.
