### ISSUE TITLE
@cli.command without the () sometimes works, sometimes doesn't

### ISSUE THREAD

**Issue by simonw** [pallets/click#2338]
I just spent a few hours confused by a VERY weird bug. Running `s3-ocr --help` sometimes listed all of the sub-commands I had registered... and sometimes didn't! Depending on installation criteria that I couldn't quite nail down, but I suspect was related to the specific dot-release of Click that was installed.

My long-winded investigations of this issue (not particularly interesting reading) are here:

- https://github.com/simonw/s3-ocr/issues/25
- https://github.com/simonw/s3-ocr/issues/26

Given how much work it took me to spot my mistake, I think it would be useful if Click could raise an error if you attempt to use the `@cli.command` decorator without including the `@cli.command()` parenthesis.

**Comment by simonw** [comment]
Here's my diff that finally fixed the bug for me: https://github.com/simonw/s3-ocr/commit/c67949aeb8ca916e358ff01551ec754e63896e13

**Comment by davidism** [comment]
We just made it possible to use without the parens. I don't plan to change that again. What was the actual thing that was failing? A reproducible example would be helpful.

**Comment by simonw** [comment]
I think that explains my mystery! Just found this here: https://click.palletsprojects.com/en/8.1.x/changes/#version-8-1-0

> The `command` and `group` decorators can be applied with or without parentheses. [#1359](https://github.com/pallets/click/issues/1359)

My mistake: I pinned to `click>=8.0` and thought that would fix the bug I was seeing. As a result, if my software was installed on a machine that already had Click 8.0 the following bug would exhibit itself:

```
% s3-ocr --help
Usage: s3-ocr [OPTIONS] COMMAND [ARGS]...

  Tools for running OCR against files stored in S3

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.
```
Where a machine with `8.1.0` or higher would do the correct thing, which is this:

```
% s3-ocr --help
Usage: s3-ocr [OPTIONS] COMMAND [ARGS]...

  Tools for running OCR against files stored in S3

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  dedupe       Scan every file in the bucket checking for duplicates -...
  fetch        Fetch the OCR results for a specified file
  index        Create a SQLite database with OCR results for files in a...
  inspect-job  Show the current status of an OCR job
  start        Start OCR tasks for PDF files in an S3 bucket
  status       Show status of OCR jobs for a bucket
  text         Retrieve the text from an OCRd PDF file
```

**Comment by simonw** [comment]
So I don't think Click has done anything wrong here: you added a new feature in `8.1.0` (minor version bump) and documented it in the changelog.

The point of confusion is that if you USE this new feature (`@cli.command` instead of `@cli.command()`) and fail to pin to `click>=8.1.0` in your requirements your software will work fine on some installs but will fail in a very confusing way (rather than throwing an error) on others.

Hopefully I've made enough noise about this in enough places that are indexed by search engines that people who run into this problem in the future will spend less time debugging it than I did!

**Comment by simonw** [comment]
For a reproducible example:

    pip install s3-ocr==0.6

That version doesn't pin Click - so if you then run:

    s3-ocr --help

You will see a list of commands if you happened to end up with click 0.8.1, but you will get an empty list if you already have a prior version of click installed.

Initially I ran into trouble because on older versions of Fedora and Ubuntu there's a `python3-click` operating system package which provides Click 7.0 - so if that was present an un-pinned `click` dependency would leave the user with that older version.

**Comment by simonw** [comment]
To anyone who sees this and has experienced the same bug: add the following to your requirements or `setup.py` dependencies to fix it:

    "click>=8.1.0"

**Comment by davidism** [comment]
8.1 is a feature version, we are not semver.
