### ISSUE TITLE
Raise a notification when an option is provided twice by the user

### ISSUE THREAD

**Issue by elyas20** [pallets/click#2340]
Hello, 
We are using  Click, and we would like Click to notify the user when an option is provided more than once.

For example, if a user enter this:
`command --count 2 --name xxx  --count 3`
it will raise an Exception or notification.

Thanks!

**Comment by davidism** [comment]
This is intended behavior so that it's possible to override values already set by env vars, or set in an alias. I'm fairly sure there are existing issues discussing this as well.
