### ISSUE TITLE
Misleading usage string for subcommands

### ISSUE THREAD

**Issue by reitzig** [pallets/click#2347]
Consider this small example of a command group:

```python
#!/usr/bin/env python3
import logging

import click


@click.group
@click.option('--global', '-g', 'glob', help='something relevant to all subcommands')
@click.pass_context
def foo(ctx, glob: str):
    logging.debug(f"global={glob}")


@click.command
@click.option('--local', '-l', help='something relevant only to this subcommand')
@click.pass_context
def bar(ctx, local: str):
    logging.debug(f"local={local}")


foo.add_command(bar)

if __name__ == '__main__':
    foo()
```

### Expected

```
❯ ./foo.py bar --help
Usage: foo.py [FOO OPTIONS] bar [BAR OPTIONS]
```

The syntax is less important than documenting clearly that _two_ distinct blocks of options are what's happening.

NB: It _might_ be useful to list the "global" options on the subcommands as well, in a separat section; precedence includes `helm`. I'm uncertain how that scales with deeply nested (sub)command structures, though. And that would be a feature request, anyway. (end of derail)

### Actual

```
❯ ./foo.py bar --help
Usage: foo.py bar [OPTIONS]
```

This is misleading; In particular, users tried to run `./foo.py bar --global Oh --local Well` -- completely in line with the help output, but fails.

To be clear: I'm not asking for this input to _work_ (as previous issues did) but for the help output to make clear it won't.

### Environment

- Python version: 3.8.10
- Click version: 8.1.3

**Comment by davidism** [comment]
Happy to review a PR. However, I don't think this is generally possible given Click's dynamic nature.
