### ISSUE TITLE
DateTime adds %H:%M:%S to output when format is %Y-%m-%d

### ISSUE THREAD

**Issue by kyrylogy** [pallets/click#2357]
### Description
Passing ['%Y-%m-%d'] with date in the same format as `format` parameter  to click.Datetime causes output to be `%Y-%m-%d %H:%M:%S`. This goes for default format as well.
### Reproduce
```
import click

@click.command()
@click.option("--date", required=False, type=click.DateTime(['%Y-%m-%d']))
def main(date):
    print(date)
```
```
> python main.py --date 2022-09-21
2022-09-21 00:00:00
```
### Environment:

- Python version: 3.9.7
- Click version: 8.1.3

**Comment by davidism** [comment]
It's parsing in that format, to give you a datetime object. What you output it as is up to you.
