### ISSUE TITLE
add functools wraps to decorators to create __wrapped__ original function access

### ISSUE THREAD

**Issue by ITJamie** [pallets/click#2358]
I would really like the decorators to also use functools wraps decorator to create a `__wraped__` copy of the original function.

This would be really useful for calling functions written for the click cli in other python library's without user input

functools wraps doco: https://docs.python.org/3/library/functools.html#functools.wraps

specific example where this would be useful, being able to call the original function https://github.com/sonic-net/sonic-utilities/blob/master/config/main.py#L4951 without the decorators, the function could then be used in standard automation tools (eg ansible / salt)

**Comment by davidism** [comment]
There are two strategies for this. Either call the function associated with the command object you created.

```python
@click.command
def example():
    pass

example()  # call it as a CLI command (which it is)
example.callback()  # call the callback associated with the command (the decorated function in this case)
```

Or create the command separately from the function.

```python
def example():
    pass


@click.command("example")
def example_command():
    example()

example()  # the original function
example_command()  # the CLI
```
