### ISSUE TITLE
[feature request] Mixin for easy (standardized) logging verbosity args

### ISSUE THREAD

**Issue by mshafer-NI** [pallets/click#2363]
I've seen a lot of projects that use click either don't provide an option to increase/decrease verbosity of the logging, or differ from each other. While freedom is great, I would like to be able to make a "use Click with x args" recommendation to developers within my company to have consistent logging args available. (-v/-q, default warning).

This can be achieved via an extension that provides a mixin (extending the BaseCommand) as is. My thought was to check if the core maintainers would like to (/or be open to) mainlining such a mixin before publishing an additional tool.

**Comment by davidism** [comment]
I don't plan to add this to the core library at this time.

**Comment by mshafer-NI** [comment]
And to be clear - not open to this as a contribution?
