### ISSUE TITLE
New decorator for automatic click options/arguments

### ISSUE THREAD

**Issue by odoublewen** [pallets/click#2371]
Implementation of PEP [484](https://peps.python.org/pep-0484/) and [585](https://peps.python.org/pep-0585/) in recent Python versions (3.8 and 3.9) provide a convenient way to annotate variable types.  It would be neat if click could somehow introspect these annotations to permit automatic CLI configuration.  For example, instead of:

```
@click.command()
@click.argument('name', type=str, help='The person to greet.')
@click.option('--count', default=1, help='Number of greetings.')
def hello(name, count):
    ...
```

One could write something like:
```
@click.auto_command()
def hello(name: str, count: int = 1):
    """
    ...
```

* args with no default value become click.arguments, while args with a default value become click.options.
* types could come from type hints
* help messages, if needed, could come from docstrings

Just a thought.  I don't even know if it is technically possible to introspect type hints at run time.

**Comment by davidism** [comment]
You're looking for [Typer](https://typer.tiangolo.com/), a wrapper around Click.
