### ISSUE TITLE
Is detection of bash version really necessary when installing shell completions

### ISSUE THREAD

**Issue by hmaarrfk** [pallets/click#2378]
Thank you for the great tool!

I'm wondering if it is necessary to detect the bash version when trying to generate the bash shell completions. 

Generally speaking, I may be trying to maximize compatibility with an older system, where bash may be older than 4.4

I understand that it will only "work" with newer bash. but does the "generation" of the shell completions need newer bash?

Maybe a warning is more appropriate?

https://github.com/pallets/click/blob/ef11be6e49e19a055fe7e5a89f0f1f4062c68dba/src/click/shell_completion.py#L302

**Comment by hmaarrfk** [comment]
As a comparison, fish and zsh do not check for version (or as it seems, existence)

**Comment by davidism** [comment]
We previously had issues with different versions, and requests for features that did not work on older versions. Given that we are not Shell Completion programmers, we opted to limit the maintenance surface we were taking on. You're welcome to add a custom completion provider with a script that works for other shell versions.

**Comment by hmaarrfk** [comment]
thank you for your response.
