### ISSUE TITLE
Be able to advance progress bar with arbitrary progress

### ISSUE THREAD

**Issue by Kentzo** [pallets/click#238]
Imagine I want to print a progress bar of extracting a TarFile.
The natural way to do that would be to create custom FileObject and advance progress bar in the read method.
Unfortunately I do not know size of chunks implementation will use in advance therefore I cannot pre-calculate length for progress bar and advance by +1 steps.

**Comment by RonnyPfannschmidt** [comment]
another use-case would be progress callbacks from Paramiko file transfers

**Comment by untitaker** [comment]
I am unsure what API you want. OP, you could instantiate the bar at the first read().

**Comment by Kentzo** [comment]
I need API to advance progress bar by my own value, not by +1.

**Comment by untitaker** [comment]
Oh, I misunderstood then... I thought you asked for one that would allow you to **set** the percentage to any value, greater or lower than the current one.

In that case, PRs are welcome. :-)

**Comment by Kentzo** [comment]
This issue seems to be partially addressed since 4.0

However, now I need exactly the ability to set exact steps to an arbitrary position.

Consider the following example: I'm downloading a file from HTTP. In the middle of the process it breaks and I attempt to resume downloading by using the Range header. However, server for any reason replies with Content-Range header that contains slightly different range. At this point I'd like to move progress bar back.

**Comment by desrod** [comment]
I've hacked up something quick-and-dirty, but does give me what I'm looking for... 

Basically, I'm calculating how many '#' marks are equivalent to the bytes downloaded, then pre-pending those to my bar_format on the next run. Change bar_width, and the calculation is changed to accommodate.  

>             bar_width = 40
>             progress = '#' * int(os.path.getsize(local_path) / (file_length / bar_width))
>             bar_template = f"'%(label)s [{progress}%(bar)s] %(info)s'"
> 
>             with click.progressbar(kernel.iter_content(1024),
>                                    bar_template=bar_template,
>                                    info_sep='|',
>                                    label=click.style(local_path.rjust(35), fg='green'),
>                                    show_pos=True,
>                                    length=file_length,
>                                    show_eta=True,
>                                    show_percent=True,
>                                    width=(bar_width - int(os.path.getsize(local_path) / (file_length / bar_width))),
>                                   ) as bar:
>                 for chunk in bar:
>                     output_file.write(chunk)
>                     bar.update(1024)

Not exactly a PR, but it is a workaround for the current scope.

**Comment by davidism** [comment]
You can modify `bar.pos` before iterating to set an arbitrary position. For more advanced use cases, I recommend using tqdm, I don't plan to add more complexity to Click's progress bar at this point.

```python
with click.progressbar(...) as bar:
    bar.pos = resume_position

    for item in bar:
        ...
```
