### ISSUE TITLE
On Windows click.Path(writable=True) isn't reliable

### ISSUE THREAD

**Issue by jules43** [pallets/click#2390]
When declaring an option that is for some kind of output file:

@click.option("--logfile", type=click.Path(dir_okay=False, writable=True), default="", help="Name of output file to write to")

The writable option is intended to guarantee that the file can be opened and successfully written to.

Unfortunately, on Windows, this can fail, as if the file is open/locked by another process or access rights are violated then the current os.access(rv, os.W_OK) will return True but the actual open will fail.

This problem is discussed in more detail here:
https://github.com/python/cpython/issues/46780

It would be possible to fix this by replacing the os.access calls with attempts to open the file, which will throw an exception, though care may be needed to avoid side effects from the open.

It appears that Python may fix this for Windows in some future version.

Replication:

On Windows open a file with something that takes a lock on the file, for example Excel. Alternatively create a file and changes ACL permissions to be inaccessible by current user.

Run this code <cmd> -f filename
```
@click.command()
@click.option("-f", 'myfile', type=click.Path(dir_okay=False, writable=True), default="test.csv")
def cli(myfile: str):
    fd = open(myfile, "w")
    fd.write("This,is,a,test")
    fd.close()

if __name__ == "__main__":
    cli()
```

If the file is locked we get a PermissionError exception from the open, if the file is not locked it writes to it. If the file is readonly we get an error message from click.

We should get a click error message when the file is locked saying it is not writable as we do if it is readonly.

Environment:

- Python version: 3.10.4
- Click version: 8.1

**Comment by davidism** [comment]
I'm not aware of any other way to test if a file is writable. `open` has the side effect of possibly creating/truncating the file, which `Path` must not do. It sounds like this needs to be fixed in Python's `os.access`. You can always use a custom type if you need specific checks for your use case.
