### ISSUE TITLE
CliRunner with mix_stderr=False does not capture stderr

### ISSUE THREAD

**Issue by martinfthomsen** [pallets/click#2392]
I'm trying to capture stderr separately, but using the "mix_stderr=False" option for the CliRunner only removes the stderr, it is not captured!

See Example below:

```
>>> import sys, click
>>> from click.testing import CliRunner
>>> print('Click Version: {}'.format(click.__version__))
Click Version: 8.1.3
>>> print('Python Version: {}\n'.format(sys.version))
Python Version: 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28) 
[Clang 6.0 (clang-600.0.57)]

>>> 
>>> @click.command()
... def cli_stderr():
...     sys.stdout.write("stdout")
...     sys.stderr.write("stderr")
... 
>>> runner = CliRunner(mix_stderr=False)
>>> result = runner.invoke(cli_empty_stderr)
>>> 
>>> assert result.output == 'stdout\n'
>>> assert result.stdout == 'stdout\n'
>>> assert result.stderr == 'stderr\n'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
>>> result.stderr
''
```

I expect the following asserts to succeed in the above code example:
assert result.output == 'stdout\n'
assert result.stdout == 'stdout\n'
assert result.stderr == 'stderr\n'

The last assert with stderr results as shown in an assertion error. And the result.stderr does not contain the text written to stderr in the run function.

Environment:
Click Version: 8.1.3
Python Version: 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 03:13:28)

**Comment by davidism** [comment]
This is not an issue with Click. `sys.stderr` is not line buffered, you must call `sys.stderr.flush()` after writing to it. Add that (and remove the newlines from the asserts) and this passes.
