### ISSUE TITLE
Use of multiple=True flag without repeatedly speciying the argument name [interested in implementing]

### ISSUE THREAD

**Issue by JoeZiminski** [pallets/click#2394]
Currently if using the multiple=True flag, if I understand correctly the CLI command must repeat the flag e.g.

```
python -m my_cli --arg ele1 --arg ele2 --arg ele3
```
It would be very nice to pass multiple arguments without having to re-specify the argument e.g.
```
python -m my_cli --arg1 ele1 ele2 ele3
```
similar to argpase functionality. Is this possible in click? Would definately be happy to work on a PR for this as it would be very important for our project.

**Comment by davidism** [comment]
This is not possible without creating ambiguous and confusing parsing situations. You can use `nargs=positive number` to accept a number of values, or use a custom type an split on spaces, like `--name "one two three"`.
