### ISSUE TITLE
Type hints: public API uses generic hints without parameters

### ISSUE THREAD

**Issue by mjpieters** [pallets/click#2398]
There are several methods in the click API that uses generic types that  leave out the parameter. To name two specific examples:

```
# click/decorators.py
def make_pass_decorator(
    object_type: t.Type, ensure: bool = False
) -> "t.Callable[[F], F]":
```

```
# click/utils.py
class KeepOpenFile:
    def __init__(self, file: t.IO) -> None:
```

`Type` and `IO` are generic types here, both take a single parameter.

Anyone using the pyright type checker _in strict mode_ can't easily use these functions or classes as the type hints are incomplete:

```
import click

class Foo:
    pass

pass_foo = click.make_pass_decorator(Foo)
# Type of "make_pass_decorator" is partially unknown
# Type of "make_pass_decorator" is "(object_type: Unknown, ensure: bool = False) -> ((F@make_pass_decorator) -> F@make_pass_decorator)"
```

Please fill in generic parameters wherever possible, even if it is just `Any`.

Environment:

- Python version: 3.10
- Click version: 8.1.3

**Comment by davidism** [comment]
To be honest, I'm pretty much over trying to support pyright and mypy in strict mode based on the support I've gotten when I've reported issues doing that. And what's weird is we run mypy with a very strict set of options in our own tests, and those pass.

I'm happy to accept a PR that fixes this, but it's not a priority for me to look into personally.

**Comment by mjpieters** [comment]
> I'm happy to accept a PR that fixes this, but it's not a priority for me to look into personally.

I already have a commit I can throw up as a PR right now; my worry is how to test for this. I'm hoping there's a mypy configuration that lets you find these.

I don't really have the bandwidth right now to figure out why mypy is okay with these. It's not as if there are default values for the parameters, after all.

**Comment by davidism** [comment]
Don't worry about typing tests for now. In Flask, we started testing type annotations by adding files with known valid uses of the library and checking that mypy passes them. But that's a good task for a sprint (or other contributor), no need to do that yourself.

**Comment by mjpieters** [comment]
I found `disallow_any_generics`, setting that to True lets me find the same issues with mypy:

```
src/click/_compat.py:53: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/_compat.py:156: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/_compat.py:165: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/_compat.py:178: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/_compat.py:196: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/_compat.py:244: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/_compat.py:247: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/_compat.py:248: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/_compat.py:290: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/_compat.py:306: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/_compat.py:370: error: Missing type parameters for generic type "PathLike"  [type-arg]
src/click/_compat.py:374: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/_compat.py:388: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/_compat.py:459: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/_compat.py:463: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/_compat.py:497: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/_compat.py:505: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/_compat.py:579: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/utils.py:123: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/utils.py:144: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/utils.py:186: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/utils.py:343: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/utils.py:373: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/utils.py:378: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/utils.py:384: error: Missing type parameters for generic type "PathLike"  [type-arg]
src/click/utils.py:461: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/exceptions.py:39: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/exceptions.py:62: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/_termui_impl.py:96: error: Missing type parameters for generic type "ProgressBar"  [type-arg]
src/click/types.py:400: error: Missing type parameters for generic type "t.Type"  [type-arg]
src/click/types.py:705: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/types.py:706: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/types.py:797: error: Missing type parameters for generic type "t.Type"  [type-arg]
src/click/types.py:947: error: Missing type parameters for generic type "t.Type"  [type-arg]
src/click/core.py:1844: error: Missing type parameters for generic type "t.Callable"  [type-arg]
src/click/core.py:1892: error: Missing type parameters for generic type "t.Callable"  [type-arg]
src/click/core.py:2263: error: Missing type parameters for generic type "Iterator"  [type-arg]
src/click/core.py:2280: error: Missing type parameters for generic type "t.Tuple"  [type-arg]
src/click/core.py:2285: error: Missing type parameters for generic type "t.Tuple"  [type-arg]
src/click/decorators.py:44: error: Missing type parameters for generic type "t.Type"  [type-arg]
src/click/testing.py:82: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/testing.py:86: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/testing.py:209: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/testing.py:304: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/testing.py:353: error: Missing type parameters for generic type "IO"  [type-arg]
src/click/testing.py:452: error: Missing type parameters for generic type "PathLike"  [type-arg]
Found 46 errors in 8 files (checked 16 source files)
```

(this is with `platform = linux` added too, as otherwise there are a few `unreachable` errors too where a `sys.platform` test ends the function early when running mypy on a Mac).

**Comment by mjpieters** [comment]
I was closer than I thought; I'll add a changelog entry tomorrow.

**Comment by mjpieters** [comment]
I naturally dove in far deeper than I intended to and addressed a few more type hint improvements that I could see.

There are quite a few places type hinting could be further improved but that'd require making various core click types _generic_, which means that users of the library that are already using type hints are going to be affected. Plus, that's a lot more work to get right, and I don't have the time to follow through on that right now.

Then there are what look to me outright bugs being papered over by `# type: ignore` in the codebase (places where a variable can be `None`, but the callable won't accept None are the most common), and one place where the return value of `sys.exc_info()` (`tuple[None, None, None]` or `tuple[type[BaseException], BaseException, TracebackType]`) is being treated as `Optional[tuple[type[BaseException], BaseException, TracebackType]]`. I'm not sure how much those are actual bugs or bugs in the type hints, so I'm leaving those.

**Comment by DanielNoord** [comment]
Would it be possible to do a patch release with some of the fixes from this issue already? There are some nice fixes on `master` (specifically for `progressbar`) that we'd like to use in our projects. The last release is (almost) one year ago.
