### ISSUE TITLE
'WindowsPath' object has no attribute 'lstrip'

### ISSUE THREAD

**Issue by fabiokfouri** [pallets/click#2408]
When I tried passing an address and check that the file existed in OS Windows 10, the following error apears:

**'WindowsPath' object has no attribute 'lstrip'**

```
@click.command()
@click.argument('input_filepath', type=click.Path(exists=True))
def main(input_filepath):
    pass

if __name__ == '__main__':
    main("C:/Development/test.csv")
```

I debugged the click code and the error have raised in line 611 at core.py. I tried to apply str() function but other erros have raised.

Environment:

- OS: Windows 10
- Python version: 3.8
- Click version: 8.1.3

**Comment by davidism** [comment]
Calling a CLI takes a list of parameters, not a string. `main(["test.csv"])`.
