### ISSUE TITLE
Autocomplete support?

### ISSUE THREAD

**Issue by breerly** [pallets/click#241]
Would love to enhance my various commands with tab/auto completion.

Thoughts?

**Comment by rymndhng** [comment]
Yes, this would be awesome. My current workaround has been to loop and create multiple commands -- but this approach is not as flexible, i.e. supporting wildcard arguments

**Comment by ShahriyarR** [comment]
[Documentation](http://click.pocoo.org/4/bashcomplete/) states, that for activating bash completion i must edit .bashrc file manually. Is there any way to automize this process using setuptools setup.py?

I wrote a command line script , where i want to activate click bash completion while installing it.

**Comment by cbandera** [comment]
+1 
I would love this feature too. Is anybody working on this or is planning to?

**Comment by stopthatcow** [comment]
Hey guys, I know this is an old thread, but I have implemented something that may fufill your needs:
Check out this PR: https://github.com/pallets/click/pull/755
Feedback is welcome!

**Comment by stopthatcow** [comment]
Also, for zsh support this thread has a solution: https://github.com/pallets/click/issues/323

**Comment by jcrotts** [comment]
#755 looks like it solves this for bash, and #323 has a workaround for zsh, closing this issue.
