### ISSUE TITLE
Click command line errors don't log to syslog or allow custom error handling

### ISSUE THREAD

**Issue by parlays** [pallets/click#2418]
When a command line error occurs such as:
Error: No such command 'xxxxxxx'.
Error: No such option: --xxxx

Click outputs to standard error on the console.  But if a click command is being run by an automated process (such as cron), it will die silently with no trace of the error.

There is not a simple way to tie into the error handling and add logging or send the error to Sentry.  Please can a feature be added to have Click allow the user to add logic to the error handling.

Thank you!

**Comment by davidism** [comment]
I don't think this is a common behavior of cli error messages, not do I know how we'd do this.

**Comment by parlays** [comment]
All good, thanks for the comment.  Probably would only happen rarely if there was a typo in the cron file.  I appreciate this library, great work.
