### ISSUE TITLE
Enhanced `auto_envvar_prefix` support

### ISSUE THREAD

**Issue by alexreg** [pallets/click#2424]
This request really has two parts, with the goal of allowing for simpler auto-generated env var names. (I consider this to be desirable in certain cases.)

1. Support `auto_envvar_prefix=""`. This works already, but results in environment variables like `_FOO`, which is hard to imagine being desirable. I think it the sensible and natural thing to do in this case would just be to eliminate the leading underscore, resulting in an env var like `FOO`. This may even be considered a bug fix, perhaps.
2. Provide an option to turn off "inheritance" of `auto_envvar_prefix` by child contexts (`auto_envvar_prefix_inheritable`?). Right now, if you have a command `bar` with an option `foo` and a root `auto_envvar_prefix` of `MYCLI`, the auto-generated env var for this option will be `MYCLI_BAR_FOO`. This feature would allow the user to have env vars named like `MYCLI_FOO` generated – and when combined with the previous adjustment, env vars named simply like `FOO`.

Any thoughts would be appreciated.

**Comment by davidism** [comment]
The current behavior is intentional. Enable it, and every param of every command is addressable as an env var in a standard format. If you need different behavior, you can process the command tree and set `param.envvar` as needed.

**Comment by alexreg** [comment]
@davidism Thanks for getting back to me. That's fair enough. What about just point #1 though? Since an empty `auto_envvar_prefix` is currently allowed, it might be better to refine this behaviour to something more natural.
