### ISSUE TITLE
"Got unexpected extra arguments" when using a star

### ISSUE THREAD

**Issue by gpxricky** [pallets/click#2431]
Hi,

I'm using something like the following command in my python application:

```
import click
from pathlib import Path

@click.command()
@click.argument("pattern")
def search(pattern):
    # pattern may be a fnmatch pattern and allows wildcards like * or ?
    for file in Path.cwd().glob(pattern):
        click.echo(str(file))

if __name__ == "__main__":
    search()
```

Unfortunately when running the application and apply "*" as value for the pattern (e.g. `python my_script.py "*"`) I get the following error on my Windows operating system:

```
Error: Got unexpected extra arguments (<list of files>)
```

While `<list of files>` contains all file and folder names that are in my current working directory (first file or folder is ignored).
Does anyone know what I'm doing wrong? Or is this a Click bug?

Many thanks and best regards,
Markus

Environment:

- Python version: 3.8.5
- Click version: 8.0.4
- Operating system: Windows 10 20H2

**Comment by davidism** [comment]
Use single quotes to prevent shell expansion. This is shell behavior, not something click can address.

**Comment by WernerWessely** [comment]
@davidism Sry to be a bother but something is not right here. I am getting the same strange behavior. PS and CMD under Windows do NOT expand wildcards. Compare these two samples:

test_argv.py:
```python
import sys

if __name__ == "__main__":
    print(sys.argv[1])

```
Under CMD or PS:
```
C:/argtest ➜ py .\test_argv.py *
*
C:/argtest ➜ py .\test_argv.py '*'
*
C:/argtest ➜ py .\test_argv.py "*"
*
```
test_click.py:
```python
import click


@click.command()
@click.argument("pattern", default="")
def hello(pattern):
    print(pattern)


if __name__ == '__main__':
    hello()
```
Under CMD or PS:
```
C:/argtest ➜ py .\test_click.py *
Usage: test_click.py [OPTIONS] [PATTERN]
Try 'test_click.py --help' for help.

Error: Got unexpected extra argument (test_click.py)
C:/argtest ✗ py .\test_click.py '*'
Usage: test_click.py [OPTIONS] [PATTERN]
Try 'test_click.py --help' for help.

Error: Got unexpected extra argument (test_click.py)
C:/argtest ✗ py .\test_click.py "*"
Usage: test_click.py [OPTIONS] [PATTERN]
Try 'test_click.py --help' for help.

Error: Got unexpected extra argument (test_click.py)
```

I read that there is something called setargv.obj or wsetargv.obj which you can link an executable to under Windows to ENABLE automatic expansion. Could it be that this is somehow happening when using Click under Windows?

**Comment by davidism** [comment]
See `windows_expand_args` https://click.palletsprojects.com/en/8.1.x/api/#click.BaseCommand.main

**Comment by WernerWessely** [comment]
@davidism Thanks!

**Comment by WernerWessely** [comment]
@davidism Sry to be a noob, but how would I enable this behavior in a simple app, like test_click.py? I don't want to call that main function manually...

**Comment by davidism** [comment]
Please use [our Discord](https://discord.gg/pallets) for discussion about your own code. This tracker is for issues related to the project itself.

**Comment by davidism** [comment]
Also, please don't `@` mention people on every single message. Pings are intended for very important messages, not for every reply.
