### ISSUE TITLE
how to disable or remove command options

### ISSUE THREAD

**Issue by odigity** [pallets/click#2434]
Is there a way to disable or remove an option from a command - specifically, an automatically inherited one like "--help"?

I'm working on a dev tool (`dc`) that we will use to invoke Django and Celery (instead of their respective pre-packaged CLIs), and am using `ignore_unknown_options` to tell Click to ignore all args so I can pass them on to Django and Celery to process.  For example, instead of:

    $ python manage.py runserver -p 80

We would use:

    $ python dc.py django runserver -p 80

Everything works except this:

    $ python dc.py django --help

Because Click recognizes and reacts to that option instead of ignoring it.

**Comment by odigity** [comment]
Just wanted to note a simple hack that solves the problem for me - I added an explicit `--help` option to override the automatically-provided one, then handle that case explicitly in the command handler.

```
import click
from dc.utils import django as runner

@click.command(context_settings={"ignore_unknown_options": True})
@click.argument("args", nargs=-1)
@click.option("--help", is_flag=True)
def django(args, help):
    """forwards all args to Django's CLI (like manage.py)"""
    if help:
        runner("--help")
    else:
        runner(*args)
```

Unfortunately, I have to repeat this pattern in nearly a dozen places.

**Comment by davidism** [comment]
Click stops processing tokens as options after seeing a `--` token. This is a common idiom in command line tools. `python dc.py django -- --help` or `python dc.py -- django --help` will both work.
