### ISSUE TITLE
Documentation not rendering well

### ISSUE THREAD

**Issue by Gerardwx** [pallets/click#2435]
https://click.palletsprojects.com/en/8.1.x/api/#click_group doesn't render well on web browser.

Tried Chrome and Safari on Mac OS X, Chrome and Firefox on Ubuntu 20.04
![click](https://user-images.githubusercontent.com/2816043/213177332-58f8a836-3b7c-4f0a-919e-1b0aae4ba396.jpg)

**Comment by davidism** [comment]
Duplicate on the theme repo

**Comment by Gerardwx** [comment]
What does that mean?
