### ISSUE TITLE
short option does not parse "=" and recognizes it as part of the option string

### ISSUE THREAD

**Issue by likewei92** [pallets/click#2436]
If we have an option that can called with `-x`, using `-x=test` will give `=test` as `x` instead of `test`.

Using example from https://click.palletsprojects.com/en/8.1.x/options/#name-your-options

test.py:
```
import click

@click.command()
@click.option('-s', '--string-to-echo')
def echo(string_to_echo):
    click.echo(string_to_echo)

if __name__ == "__main__":
    echo()
```

try running `python test.py -s=test_string`, the output is `=test_string`. Using the long name `python test.py --string-to-echo=test_string` gives the right output of `test_string`.

Environment: MacOS

- Python version: 3.11
- Click version: 8.1.3

**Comment by davidism** [comment]
That's correct, that's the semantics of short option values. = is only a separator for long options.
