### ISSUE TITLE
Transition docs from setup.py to pyproject.toml

### ISSUE THREAD

**Issue by BrennanBarker** [pallets/click#2444]
Is there any issue transitioning the "Setuptools Integration" doc section from referencing a notional `setup.py` to instead reference a `pyproject.toml`?  I can submit a PR if there's no objection.

**Comment by swills1** [comment]
Just an FYI, @BrennanBarker is referring to this - https://github.com/pallets/click/blob/main/docs/setuptools.rst.

Which probably is antiquated at this point like they say.
