### ISSUE TITLE
Dynamic Click app generation

### ISSUE THREAD

**Issue by dmytro-afanasiev** [pallets/click#2451]
Currently, I can export the whole Click structure to JSON by using `to_info_dict` method. Something like this does it well:
```python
with click.Context(cli) as ctx:
    info = ctx.to_info_dict()
with open('info.json', 'w') as file:
    json.dump(info, file, default=str)
```
Now I've bumped into a case when I need to be able to make a reversed action - to generate CLI from such info JSON (or maybe another info JSON). Is there a native way to do it, or I just need to go through the info dict manually and create corresponding Click's objects?

**Comment by davidism** [comment]
You need to write code to do what you want.
