### ISSUE TITLE
Output styling for more generic input (string and bytes)

### ISSUE THREAD

**Issue by rgryta** [pallets/click#2464]
# Intro
At the moment click>=8.0 no longer throws exceptions when used with bytes as input. However, it now doesn't try apply style at all when used with bytes - instead recommending to first decode bytes into str.

While this isn't really any issue, I do think that it could be possible to use both: bytes and strings. Reason: why not? This would require more testing obviously, but the initial idea is to not use echo with msg being string, but bytes instead. That also means a change in `style` (so maybe it'd require additional flag `force_bytes`).

Rough idea that I've implemented and tested (note that I've only used it with secho, so haven't tested any other functionalities):
In `style` method, before returning from function, I'm changing all elements of `bits` into bytes using `.encode('utf-8')` (if they're not already). Then in return statement: `return ''.encode(...).join(bits)`. Such implementation returns bytes string back to `secho`, which is then provided to `echo`. Result? Terminal has stylized output even when byte strings are used.

One difference that I've noticed so far is when piping output from a program to a file. When you pipe it using current implementation, content of the file is unstylized string `cat testfile` basically returns white text. But with this implementation, the file also contains styling information, so when using `cat testfile` you are also getting the same stylized output (dunno if that'd be considered a bug or feature actually, maybe it would be possible to implement this differently without piping style bits into file).

# What does it "resolve"
For me, it's styling for multithreaded/multiprocessing programs. I'm already using my implementation in production in one of services that we're using to diagnose databases (basically copied that one function, changed it in the way I described and monkey-patching it on runtime). This program used to be run serially, taking A LONG time to execute. click.secho helps us visually identify errors and warnings and is used throughout the diagnosis execution.

Parallelizing this logic was a bit of a challange as the order of echo statements had to be somewhat maintained. My solution to this was to create `io.BytesIO` objects that act as a buffer per thread (providing it as file argument to secho). Each thread would then `secho` it's own stylized messages in order into it's own buffer. Then saves that buffer into the shared list. Once all child threads are closed, main process grabs that list, joins all `io.BytesIO` objects and performs one final `secho` with all the output information combined.

This way I have multiprocessing and secho styling with no issues. I tried this with `io.StringIO` as a buffer, but using this approach makes the program lose the styling infomation and the entire output is default white.

**Comment by rgryta** [comment]
Wouldn't mind submitting a PR, but the doc said to submit a request first.
Moreover, if that is something that was agreed to - should I also investigate options for that "issue" with styling bytes being piped from output to files?

**Comment by davidism** [comment]
I'm having trouble understanding exactly what you're requesting, because you've attempted to describe code concepts with prose without showing any concrete code examples.

I am deliberately moving away from supporting both str and bytes everywhere. What you're describing is adding a lot of complexity to an already complex implementation, all to avoid having to call `encode/decode` before or after some call. I don't plan to go in that direction.

**Comment by rgryta** [comment]
Ok, so I dug a bit deeper into the code right now to familiarize with newer click 8.1 (at work we were still using version 7 not that long ago, and a bit has changed obviously).

I'm applying click.secho in multiple threads simultaneously. I need it to be stylized. And I need the threads to print in order. This means that I have to use some sort of buffer. On top of that I also need styling. And so, the easiest way is to use io objects.

Now, as I wrote in initial submition, I'm using BytesIO. But from what I see, I should be able to make it work with new click using StringIO object. However, I'll also have to set `color` argument flag to True. While this isn't an issue obviously, more like a convenience thing. This comes down to the purpose of `should_strip_ansi` function. In it's current form, my understanding is that it's purpose is to: "check if output is a terminal, if not then strip ANSI". Wouldn't it make sense for StringIO to be considered as a terminal mock though - I mean, user has put this styling on purpose there, so it doesn't make much sense to me to later strip it anyway.

**Comment by rgryta** [comment]
If that's not something that is wanted then I can work with workaround, like I did before. This is just suggestion as I've seen some questions on stackoverflow with whether click supports multithreading, and this would open it up for that concept a bit more.

**Comment by davidism** [comment]
I have absolutely no idea what threading has to do with whether `click.secho` accepts bytes. You seem to have constructed an XY problem while trying to solve your actual issue. It's not a "workaround" for you to code something that synchronizes threads, gets their output as bytes (for some reason) then echos them. That's completely outside the scope of Click itself.

**Comment by rgryta** [comment]
Well, I'd agree to disagree there, but ok. Tested few more things though and to me it looks like there's a bug here - output on Windows differs from output on Linux due to auto_wrap_for_ansi messing with StringIO. Haven't debugged that method though. If it's not a bug, then ignore this message.

On Windows only first and last tests return colored output. On Linux only 2nd and 4th **don't**.

```python
import click
import io
msg = "msg"

# Test 1
bf = io.StringIO()
bf.write("\033[36m"+msg)
click.secho(bf.getvalue())

# Test 2
bf = io.StringIO()
click.secho(msg, fg="cyan", file=bf)
click.secho(bf.getvalue())

# Test 3
bf = io.StringIO()
click.secho(msg, fg="cyan", color=True, file=bf)
click.secho(bf.getvalue())

# Test 4
bf = io.StringIO()
click.secho(msg, fg="cyan", color=False, file=bf)
click.secho(bf.getvalue())


# Test 5
click.utils.resolve_color_default = lambda x: True # Overriding color to always be True
bf = io.StringIO()
click.secho(msg, fg="cyan", file=bf)
click.secho(bf.getvalue())


# Test 6
click.utils.should_strip_ansi = lambda x,y: False # Overriding stripping to always be False
bf = io.StringIO()
click.secho(msg, fg="cyan", file=bf)
click.secho(bf.getvalue())


# Test 7
click.utils.auto_wrap_for_ansi = lambda x: x # Patching wrapper finally fixes it
bf = io.StringIO()
click.secho(msg, fg="cyan", file=bf)
click.secho(bf.getvalue())
```
