### ISSUE TITLE
default_map updated inside of "group" callback isn't used

### ISSUE THREAD

**Issue by MegaIng** [pallets/click#2472]
I want to have a config file that can be used to define the defaults for the options. While googling, I stumbled across this answer on SO: https://stackoverflow.com/a/73669230/8472976 , which seems to be exactly what I want, using somewhat documented APIs. However, the code no longer works, the `default_map` set in the `foop` callback isn't used.

Slightly reduced example:
```py
import click


@click.group()
@click.pass_context
def foop(ctx):
    config = {"port": 5000}
    ctx.default_map = config


@foop.command()
@click.option('--port', default=8000)
def runserver(port):
    click.echo(f"Serving on http://127.0.0.1:{port}/")


if __name__ == '__main__':
    foop()
```

Expected output: `Serving on http://127.0.0.1:5000/`

but got `Serving on http://127.0.0.1:8000/`

Environment:

- Python version: 3.11
- Click version: latest master, `8.2.0.dev0` ( `58c2d975ef4459c2750f3df9dc93dd970f5f52a7`)

**Comment by davidism** [comment]
The keys in the default map need to correspond to the `group_command_parameter` path used to arrive at the given parameter. In this example, I think it would be `runserver_port`. That said, updating the default map during command execution isn't guaranteed to work and should not be relied on.

**Comment by MegaIng** [comment]
> That said, updating the default map during command execution isn't guaranteed to work and should not be relied on.

`runserver_port` also does not work. Is there an alternative suggestion for how to do this? The documentation in this area is a bit sparse, but everything I found seems to suggest that `default_map` is the way to go. (including the official docs and previous issues here, although it doesn't talk about specifics.)

**Comment by MegaIng** [comment]
The third patry package [`click-config-file`](https://pypi.org/project/click-config-file/) was also relying on this behavior

**Comment by davidism** [comment]
I didn't say `default_map` wasn't supported, I said changing it in the middle of execution isn't. It should be passed as a context option when beginning CLI execution.

**Comment by MegaIng** [comment]
That's true, however this means that passing a config file that provides defaults via a command argument is no longer possible via `default_map`, right? So one would have to preprocess the arguments in some way, or change the definition of all options to look up defaults in a second place. A different package that solves this problem: [`click-configfile`](https://github.com/click-contrib/click-configfile) doesn't support passing in an `--config` option from what I can tell.

So if this is behavior that is currently not (easily) possible to (re-)implement, then I would change this into a FR. Should I open a new issue?

**Comment by MegaIng** [comment]
The documentation mentions that `default_map` is the way to go and it implies that it's somehow possible to use a `--config` parameter: https://click.palletsprojects.com/en/8.1.x/options/#dynamic-defaults-for-prompts https://click.palletsprojects.com/en/8.1.x/options/#values-from-environment-variables .

**Comment by MegaIng** [comment]
Aha, thank you, the hint with nested dictionaries was what I needed. I was kind of confused since the other places that mentioned `default_map` in the documentation didn't explain anything in that regard and didn't link to anywhere.

I also want to point out that you previously said "updating the default map during command execution isn't guaranteed to work", which isn't true according to the docs. (unless you mean something else with execution.)

**Comment by davidism** [comment]
Passing `default_dict` at the beginning is supported, as shown in the linked docs. Changing it during execution may not have the intended effect.

**Comment by MegaIng** [comment]
Well, the linked docs state `The default map can be provided when the script is invoked, or overridden at any point by commands`. So I would expect `click` to correctly honor that promise.
