### ISSUE TITLE
`click.Date`

### ISSUE THREAD

**Issue by jason-curtis** [pallets/click#2473]
`click.DateTime` is great, and you can use `click.DateTime(formats=["%Y-%m-%d"])` to ensure that the value is logically just a date. However, the resulting object is still a `datetime.datetime`, which isn't ideal if you want to be dealing with pure dates.

Right now I'm working around this by using a `click.DateTime()` argument and doing `start_date = start_date.date()` at the top of my function, but that's not ideal because my team considers variable reassignment to be a code smell. I could rename the argument to something else, but that's also something of a kluge.

It'd be great to have a `click.Date` argument type that would act similarly to `click.DateTime` and return a date only.

**Comment by davidism** [comment]
You're welcome to create a custom type that returns what you need. However, dates with no time or timezone information are very ambiguous, and it's best to avoid them. I don't plan to add this directly to Click.
