### ISSUE TITLE
envvar with if statement support

### ISSUE THREAD

**Issue by tenletters10** [pallets/click#2480]
System: MacOS, RHEL, Windows

I was wondering if there is a native click way to handle the usage of os environment variable usage for a default value for an option that can differ based on other factors (in this case os.name). This reasoning for this is because the username environment variable differs on Windows systems vs Unix systems. 

I would like to use this more native way to handle this, but not sure how to handle an if statement condition: https://click.palletsprojects.com/en/8.1.x/options/#values-from-environment-variables

Here is what I am using right now that works just seeing if there is a more click native way to handle this I am not understanding:

```
if os.name == 'nt':
    username = os.environ.get('USERNAME')
elif os.name == 'posix':
    username = os.environ.get('USER')
else:
    username = None

click.option('-u', '--username', default=username, show_default=True, help='The username to authenticate with', prompt='Username'),
```

**Comment by davidism** [comment]
This is something custom you'd do in your own processing, either before calling the cli or inside the command.
