### ISSUE TITLE
Global options - 'bubble up' when unmatched

### ISSUE THREAD

**Issue by JensRoland** [pallets/click#2488]
Many CLI tools have 'global' options like --debug (or --verbose or --silent), --output (json, table, text), --profile, etc. which can be used with any command. If I understand correctly, the current version of Click supports this by configuring the option on the parent group ratehr than on the individual commands, but this requires specifying this 'global' option syntactically 'between' the group name and the command, as in:

`file_converter --debug convert --input foo.csv --format jsonl`

The documentation example on callback invocation (https://click.palletsprojects.com/en/8.1.x/commands/#callback-invocation) shows how to achieve this. However, as a user, this feels a bit clunky, and I would expect it to work even if I provided the `--debug` option after the command:

`file_converter convert --input foo.csv --format jsonl --debug`

This is what I would propose: In order to support the second syntax, I would extend Click such that, when an option is provided which does not exist on the command, Click would 'bubble it up' to the parent group, check for a matching option there, and if found, provide the value as though the option had been provided syntactically 'between' the group name and the command (ie. simply using the existing functionality). If the option is not found on the group, Click would 'bubble it up' another level (if there is another level) until a match is found, or until the it reaches the root Click instance, in which case it will fail with the usual "Error: No such option:" message.

This would have the benefit of providing a more intuitive (less finicky) interface for the user while seamlessly allowing per-command overrides, and with no change needed to existing implementations, as the behavior would only change for what are currently failure cases. All happy path invocations would be unchanged.

**Comment by davidism** [comment]
It's probably possible to do this with some clever use of the context, which stores unknown args. But this is deliberately not a feature, we don't plan to extend it.
