### ISSUE TITLE
Calling argparse from click

### ISSUE THREAD

**Issue by machur** [pallets/click#2494]
Hi, is it possible to call argparse from click somehow? Is there some kind of a wrapper available?

We are using pytorch-lightning in our project and we want to use the latest command line interface for configuration of machine learning pipelines. Unfortunately, it relies on the jsonargparse package. I'm wondering if it's feasible to merge both these two approaches and call LightningArgumentParser via click.

**Comment by davidism** [comment]
Yes, it's possible to override `Command.parse_args`.

**Comment by machur** [comment]
@davidism thanks for the quick reply. 

I have one more question regarding running pytorch-lightning CLI. It relies on nested arguments separated by "dots", e.g., --model.help, --trainer.max_epochs etc. Is there a way to define options in such format in click?

**Comment by machur** [comment]
I just found a similar issue https://github.com/pallets/click/issues/2258 and it looks like there is no support. @elysium1436 Did you find a way around it?

**Comment by davidism** [comment]
Again, you can override `parse_args` to parse whatever you need, but that's not how Click understands args natively.
