### ISSUE TITLE
Path(writable=True) not check subdirectory exist

### ISSUE THREAD

**Issue by natir** [pallets/click#2495]
Thanks for your work on Click.

Maybe I didn't read correctly documentation but on my understanding `click.Path(writable=True)` should check if subfolder in path is exist.

### How to reproduce:

Create file test.py with:
```
import click

@click.command()
@click.option("--output-path", help="File where result is write", type=click.Path(writable=True))
def main(output_path: str) -> None:
    out = open(output_path, "w")
    print("Hello Word", file=out)


if __name__ == "__main__":
    main()
```

Run:
```
python test.py --output-path test
```

No failed and test file contains `Hello Word`

Run:
```
python tmp.py --output-path test/test # I assume you didn't have test folder in run directory
```

Produce this error: 
```
Traceback (most recent call last):
  File "$HOME/tmp.py", line 11, in <module>
    main()
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$HOME/tmp.py", line 6, in main
    out = open(output_path, "w")
          ^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: 'test/test'
```
Expected behavior:
```
Usage: test.py [OPTIONS]
Try 'test.py --help' for help.

Error: Invalid value for '--output-path': Path 'test/test'  is not writable.
```
 
I tried to find an equivalent issue but I failed, I apologize if I create a duplicated issue.

Environment:

- Python version: 3.11.2
- Click version: 8.1.3

**Comment by nicomellon** [comment]
@natir I've been having a look at the [docs](https://click.palletsprojects.com/en/8.1.x/api/#click.Path) and the "writable" check only happens if the file you are writing to already exists.

**Comment by natir** [comment]
So if I understand correctly click does not allow to check that you can write in a file if this file does not exist.

So if I want to check that I can write in a path that does not exist yet I should not use the type click.Path?

Is there a method that would allow me to verify that I can actually write to a file indicated by a path provided by the user directly in click?

In any case, my issue is not really about the right problem.

**Comment by davidism** [comment]
If you need to do other checks, you're welcome to write a custom type, use a parameter callback, or use the command's function.
