### ISSUE TITLE
Allow `Argument(prompt=True)`

### ISSUE THREAD

**Issue by multimeric** [pallets/click#2503]
Currently Click allows `Option(prompt=True)` which enables prompting behaviour. However this argument isn't available for Arguments.

Enabling this would allow a full CLI app to pivot from CLI mode to TUI mode, rather than only partially as is the case now.

**Comment by davidism** [comment]
CLI arguments are positional, there's no way to know which argument is missing and needs a prompt. So the only thing this would allow is to accept some number of args, then prompt for some number of args, not to prompt for an arg in the middle of others.

> Enabling this would allow a full CLI app to pivot from CLI mode to TUI mode, rather than only partially as is the case now.

How would it enable this? Why is this required, why can't a TUI library handle this itself? Note that we're _not_ a TUI library.

**Comment by multimeric** [comment]
I imagine it would work sequentially (left to right), as I presume argument parsing works now. Argument 2 is assumed missing if there are > 1 arguments defined and only 1 provided, etc. 

I know click isn't a TUI library, I'm just saying that this is the motivating case, where the entire interaction can become fully interactive instead of only some parts of the application.

**Comment by davidism** [comment]
Why can't it become interactive without this? I'm fairly sure multiple Click-to-TUI libraries exist already and don't have this issue. Presumably they introspect the parameters and construct the UI from their own rules, not the `prompt` attribute.
