### ISSUE TITLE
Deprecating Python 3.7 for click 9.0

### ISSUE THREAD

**Issue by saroad2** [pallets/click#2511]
Python 3.7 is reaching its [end-of-life date](https://devguide.python.org/versions/).

This issue is here in order to make sure that we deprecate the use of Python 3.7 for the next major release of *click*.
This will allow us to use new neat features introduced in [Python 3.8](https://docs.python.org/3/whatsnew/3.8.html):
* The [walrus operator](https://realpython.com/python-walrus-operator/)
* positional-only and keywords-only parameters
* f-strings with equal signs

**Comment by davidism** [comment]
This will be done with 8.2, but I don't typically keep issues open to track it.
