### ISSUE TITLE
Move click-default-group functionality into Click core

### ISSUE THREAD

**Issue by simonw** [pallets/click#2520]
I have a few different Click programs that use https://github.com/click-contrib/click-default-group in order to provide a default command:

- https://github.com/simonw/datasette so you can run `datasette data.db`
- https://github.com/simonw/llm so you can run `llm "a poem about spiders"`
- https://github.com/simonw/sqlite-utils for `sqlite-utils dogs.db "select id, name from dogs"`

`click-default-group` works OK, but it hasn't been updated since 2019 and I worry that it might eventually stop working since it doesn't seem to be actively maintained.

It also doesn't have a wheel on PyPI. This was a problem for my https://lite.datasette.io/ project which runs Datasette in the browser using Pyodide, because that only works with wheel dependencies.

I ended up shipping this package to PyPI to resolve that, but I'd rather not have to do that! https://pypi.org/project/click-default-group-wheel/

Shipping an official wheel for `click-default-group` would be good too, but I do feel like this would be a great Click core feature.

**Comment by kdeldycke** [comment]
If `click-default-group` is too big for Click core, I might accept a PR for its inclusion in [Click Extra](https://github.com/kdeldycke/click-extra).

Click Extra was basically born as a [collection of patches for unmaintained or slow moving `click-contrib`](https://kdeldycke.github.io/click-extra/issues.html) addons! 😇

**Comment by simonw** [comment]
Worth noting that `click-default-group` started shipping a wheel in 1.2.3 released August 4th 2023: https://pypi.org/project/click-default-group/1.2.3/#files

I'm going to close this issue.
