### ISSUE TITLE
Argument `choices` of `Choice` constructor should be `Collection`, not `Sequence`

### ISSUE THREAD

**Issue by blazewicz** [pallets/click#2525]
Implementation of `click.Choice` currently requires `choices` argument to match `typing.Sequence[str]` type, while a wider one can be used, namely: `typing.Collection[str]` . `Sequence` adds `__getitem__` which is never used on this argument, `Collection[str]` seems to be sufficient here.

Currently mypy will complain when `set` is used as an argument to `click.Choice`:

```python
@click.command()
@click.option("--select", type=click.Choice({"a", "b"})
def command(select):
    ...
```

error:

```text
error: Argument 1 to "Choice" has incompatible type "Set[str]"; expected "Sequence[str]"  [arg-type]
```

There would be no errors in runtime.

**Comment by davidism** [comment]
`Sequence` implies an order, which I want preserve. I don't think `set` should be considered part of the API; yes it works now, and I don't expect that to change, but I would never have expected it to be correct. You can use a `type: ignore[...]` comment if you need to override that.
