### ISSUE TITLE
Feature request: Skip group code when --help is set

### ISSUE THREAD

**Issue by couling** [pallets/click#2535]
To enhance the user experience it would really be better if I could switch off invoking the group script when `--help` is specified on the child. 

The idea here is that the following should NOT print `hello world`.  And desirably, this should also turn off parsing `main()`'s argument validation as well.

Let's say a user invokes this on the shell:
```shell
my-cli some-command --help
```
And the cli command looks something like this:
```python
import click

@click.group
def main() -> None:
    print("hello world")

@main.command()
def some_command() -> None:
    ...

if __name__ == "__main__":
    main()
```
This should NOT print "hello world"

### The problem
There are multiple actions you might want to perform to make way for the underlying command.  Eg: 
 - searching for a configuration file
 - configuring logging or output
 - opening a connection to a database

But this conflicts with the general use case of specifying `--help` which, to most users, means "**_just_** print some help text".

I particularly run into this when the group loads configuration and the configuration file is supposed to be in the current directory or it's parent.  In that case it is right for the group to fail when it finds no configuration.  Except that makes requesting help fail unexpectedly when you don't happen to be in the right directory.

Even if I could detect the command's `--help` from the group and bypass configuration setup, there would still be times when help would fail if, for example they didn't provide a mandatory option.

That is, most users would not expect there to be a semantic difference between:
```shell
some-group --conf /foo/bar some-command --help
```
and
```shell
some-group some-command --help
```
Both should be expected to just print the `some-command` help.

_I realise this might undermin a designed structure of click._

**Comment by davidism** [comment]
See multiple previous discussions about this, this is not possible given Click's extremely dynamic nature.

**Comment by couling** [comment]
Strange. I'd have thought it might be possible by adding an option to delay the execution of the group function until just before the validation and execution of the command.

**Comment by couling** [comment]
@davidism Has something ever been considered around giving an option to delay the execution (`invoke`()`) of a group (MultuCommand) until the child command is ready for it?  If enabled, such an option would knowingly surrender some of the dynamic behaviour of `click` but allow the child command to determine when and if the group function executed.

My [initial test draft](https://github.com/couling/click/commit/a83ebeb423fff2c57817319a818e3533fa16b612) suggested that this might be relatively easy and clean to implement.. _I'm not claiming to have checked every edge case._

... That is to say, if I spent more time on this and submitted as a PR, would the idea have any chance of getting accepted?

**Comment by davidism** [comment]
I've closed this as not planned to indicate that I don't plan to add it.

**Comment by couling** [comment]
@davidism okay that's a shame. It seemed you were closing it as impossible rather than unwilling. 

Thanks anyway.

**Comment by davidism** [comment]
"It's a shame you're unwilling to accept any given suggestion that would add complexity to the library and maintenance of it" is not a kind thing to say. Please avoid leaving that sort of comment in the future.

**Comment by couling** [comment]
@davidism please don't misquote me **that** is unkind. I simply said "it's a shame". In this instance I have three separate use cases for this. It would have been very helpful. It **is** that it won't get implemented. That doesn't mean I don't respect your decision, just expressing disappointment.
