### ISSUE TITLE
Option value b* resolves to build and v* to version (windows 10 only)

### ISSUE THREAD

**Issue by akaliwod** [pallets/click#2536]
If option value is b* or v*, then it is resolved automatically to build and version values

```
import click

@click.command(context_settings=dict(
    ignore_unknown_options=True,
    allow_extra_args=True,
))
@click.option("--myoption")
def hello(myoption):
    print(myoption)

if __name__ == '__main__':
    hello()
```

Example

```
C:\> python.exe menu\test.py --myoption ba*
ba*
C:\> python.exe menu\test.py --myoption b*
bdist
```

Environment:

- Python version: 3.10.4
- Click version: 8.1.3

**Comment by davidism** [comment]
`*` expands shell arguments. Sounds like you have files that match it in the directory you're running from on Windows, but not on Linux.
