### ISSUE TITLE
Requesting `nargs=-1` for options

### ISSUE THREAD

**Issue by jpmvferreira** [pallets/click#2537]
### What should this feature do?
This feature would make it possible to transform a CLI that would take in multiple instances of the same flag, such as
```bash
$ cli argument1 arguments2 --flag1 a --flag1 b --flag2 c
```
Or a tuple with fixed length, such as
```bash
$ cli argument1 arguments2 --flag1 (a,b,c)
```
And instead replace it with the much more familiar and easy to use/understand
```bash
$ cli argument1 arguments2 --flag1 a b c
```

This would allow a dynamic number of arguments provided to a specific option to be provided without repetition of the same flag.

This already suggested in #484, where it was closed arguing that such a feature would see the light of day "maybe someday".
I would like to ask if you if that "someday" could be anytime soon.

I don't see any downsides of having such a feature (as it was already mentioned in the issue referenced before), given that it doesn't make the cli inconsistent or ambiguous in any way.
However, I don't know how much work would go into implementing such a feature.

**Comment by davidism** [comment]
This is not possible to parse unambiguously. You haven't presented any new information or suggestion beyond what's already in the linked issue, so the answer is the same for now.

**Comment by jpmvferreira** [comment]
How is it ambiguous? 
If a new flag doesn't being, then we can easily interpret that has additional arguments provided to the same flag. 
We would always have something like `cli [arguments] --option1 (...) --option2 (...)`, where in the `(...)` any number of arguments can show up and be correctly parsed.

Again, I don't know just how much work would it be to implement such a feature, but in [this stackoverflow post](https://stackoverflow.com/questions/48391777/nargs-equivalent-for-options-in-click) the user Stephen Rauch implemented this feature with a custom class in about 50 lines of code.

**Comment by jpmvferreira** [comment]
Sorry for bothering again about this, but if you're not interested in implementing this feature can you at least provide an hint on how to extend current Click's functionality to include it?
I don't see it raising any issues elsewhere in the code, and because it is quite standard to see CLI utilities with multiple values being passed to an option, I would like to have it in my own CLI's.
