### ISSUE TITLE
Report all validation errors rather than the first one encountered

### ISSUE THREAD

**Issue by skington** [pallets/click#2538]
This was [asked before](https://github.com/pallets/click/issues/1175) but the respondent misunderstood the issue and closed it without proper resolution.

Suppose I have something like this:
```python
#!/usr/bin/env python3

import click

@click.command()
@click.option(
    "--colour-of-bike-shed",
    required=True,
    help="What colour we should paint the bike shed",
)
@click.option(
    "--how-to-stop-teenagers-smoking",
    required=True,
    help="Teenagers smoke behind bike sheds. How should we stop them?"
)
@click.option(
    "--get-everyone-to-sign-off",
    required=True,
    help="Everyone has an opinion about this, so make them all agree"
)

def do_stuff(**options) -> None:
    print("Fine, we'll build a bike shed")

if __name__ == "__main__":
    do_stuff()
```

If I just run the command as-is, I get told off about only one of the options. As I fill each option in, I get told that *psych!* there were *other* missing options that I wasn't told about.

> % python3 build_bike_shed.py
```
Usage: build_bike_shed.py [OPTIONS]
Try 'build_bike_shed.py --help' for help.

Error: Missing option '--colour-of-bike-shed'.
```
> % python3 build_bike_shed.py --colour-of-bike-shed Green
```
Usage: build_bike_shed.py [OPTIONS]
Try 'build_bike_shed.py --help' for help.

Error: Missing option '--how-to-stop-teenagers-smoking'.
```

> % python3 build_bike_shed.py --colour-of-bike-shed Green --how-to-stop-teenagers-smoking "Photo ID"
```
Usage: build_bike_shed.py [OPTIONS]
Try 'build_bike_shed.py --help' for help.

Error: Missing option '--get-everyone-to-sign-off'.
```

> % python3 build_bike_shed.py --colour-of-bike-shed Green --how-to-stop-teenagers-smoking "Photo ID" --get-everyone-to-sign-off "Dave, Brenda and Max all agree now"
```
Fine, we'll build a bike shed
```

I don't know the source code, but judging by the [documentation about callbacks and eager options](https://click.palletsprojects.com/en/8.1.x/options/#callbacks-and-eager-options) I suspect that under the hood click divides options into eager and non-eager, then processes each of them in the order they were supplied, exiting as soon as there's an exception.

That's a quick and easy way to do things, but it has the cost of annoying "computer says no" unfriendly errors like this.

Rather than a sequential, depth-first approach where we exhaustively check an option for validity and then move on, it would be really useful to take a breadth-first approach where we:
1. check whether all required parameters were indeed provided
2. check all parameters' values types
3. only then validate each value, call callbacks etc.

**Comment by davidism** [comment]
There's no way to do this in general, since Click is completely dynamic. Any callback could depend on the results of others, or an option may not even exist if another was not valid first.

**Comment by skington** [comment]
OK, I appreciate that once you have callbacks it's anybody's guess what's going to happen to your options; but what if you don't? Surely for simple cases this would still be useful?

**Comment by davidism** [comment]
But that's not how the processing pipeline works, it goes incrementally. It can't know in general what's required until it gets to it and checks. There's no way for it to "cheat".

**Comment by skington** [comment]
OK, but what I'm suggesting is that the pipeline shouldn't stop at the first error. When checking options for (a) requiredness and (b) type, if it finds an error, it should *carry on checking other options*, and bundle up *all* (a) "I was expecting an option but you didn't provide it" and (b) "you provided an option but the value you supplied failed its type check" errors together.

If it doesn't find any further errors, absolutely it should stop there: not bother type-checking if there were any missing options, for instance. And if there's any sign of callbacks or otherwise monkeying around with the guts of the option definitions it should by default not bother with any of this stuff.

But fundamentally, if there's nothing hugely complicated going on, and there are a bunch of options that are required and you didn't specify *any* of them, the error message you get should be "oh hey, there's a bunch of options you didn't specify" rather than "you didn't specify this one option" followed by "you didn't specify this other option either lol" when you provide that option on your next try.

Because that's just annoying.
