### ISSUE TITLE
Control the evaluation order of parameter callbacks?

### ISSUE THREAD

**Issue by PJBaker** [pallets/click#256]
I would like to use parameter callbacks to validate parameter values, as described [here](http://click.pocoo.org/3/options/#callbacks-for-validation). However, in my program the valid range for one parameter depends on the value passed to another parameter. This seems best handled by requiring my parameter callbacks to be called in a certain order.

Here is a simplified example: a script which prints the n<sup>th</sup> byte of a file. The value passed to `offset` is checked against the size of the file:

``` python
import os
import click

def get_file_size(file):
    position = file.tell()
    file.seek(0, os.SEEK_END)
    size = file.tell()
    file.seek(position, os.SEEK_SET)
    return size

def in_file_callback(ctx, param, value):
    ctx.in_file_size = get_file_size(value)
    return value

def offset_callback(ctx, param, value):
    if value >= ctx.in_file_size:
        raise click.BadParameter('offset must be less than file size')
    return value

@click.command()
@click.argument('in-file', type=click.File('rb'), callback=in_file_callback)
@click.option('--offset', default=0, callback=offset_callback)
def nth_byte(in_file, offset):
    in_file.seek(offset, os.SEEK_SET)
    byte = ord(in_file.read(1))
    print '{:#02x}'.format(byte)

if __name__ == '__main__':
    nth_byte()
```

Unfortunately, this does not work as-is (`AttributeError: 'Context' object has no attribute 'in_file_size'`). It seems that the callbacks for options (such as `offset`) are processed before those for arguments (such as `in-file`). If I change `in-file` to be an option rather than an argument, the script only works if `in-file` is passed before `offset` on the command line:

``` sh
nth_byte.py --in-file test.bin --offset 4 # OK
nth_byte.py --offset 4 --in-file test.bin # AttributeError
```

It seems I need a way to force the callback for `in-file` to always be called before that for `offset`. This is possible using `is_eager`, but that can cause other issues (e.g. #50). It also does not allow for, say, three callbacks which need to be called in a certain order.

Is there any other way to control the evaluation order of parameter callbacks? Or should I use a different approach in this situation, perhaps not using parameter callbacks at all?

**Comment by mitsuhiko** [comment]
I'm going to close this.  This issue likely predates the new callback evaluation order.  If this does not solve it, please open a new one: http://click.pocoo.org/4/advanced/#callback-evaluation-order

**Comment by pjbaker** [comment]
Click 3.3 was the latest version when this issue was created. Has the callback evaluation order changed since that version?

**Comment by untitaker** [comment]
@pjbaker Have you tried `is_eager`?

**Comment by pjbaker** [comment]
>This is possible using is_eager, but that can cause other issues (e.g. #50). It also does not allow for, say, three callbacks which need to be called in a certain order.

**Comment by untitaker** [comment]
Sorry, yeah. I'm not sure how an API would look like for this. I'm not sure if we should even provide one because it allows for writing of very unreadable, unnoticeable interdependent code.

**Comment by jcrotts** [comment]
Agreeing with unittaker, not sure what this would look like, and it would probably lead to some complicated code. Closing this for now, please submit a PR or reopen if this is still needed.
