### ISSUE TITLE
Please add a gloabal settings to disable auto convert `_` to `-`

### ISSUE THREAD

**Issue by eromoe** [pallets/click#2571]
```
import click
from functools import wraps


@click.group()
def cli():
    pass

@cli.command()
def financial_report():
     ...
```

Have to type `python run.py financial-report`  instead of  `python run.py financial_report` .
I know one can assign a name to command , but this is not handy. I have mamy long command with many `_`, I need convert them one by one now. 

I mean, I use click before, as I remember I forgot this behaviour last time and cost one hour to figure out .
Today happen again(long time not to use click), thanks to the terrible memory from last time, I recall this behavior in short time. 

In addition, the error message is misleading. As you see, you have a command named `financial_report` , but it say no there is no.
So the first thing come up to mind is there is some cache didn't clear , balabala. ...

These, all can be solve if click provide a global settings for  disable auto convert `_` to `-` .

**Comment by davidism** [comment]
You can write a decorator that generates the name the way you want instead. Something along the lines of:

```python
import click

def command(name=None, **attrs):
    if name is not None:
        return click.command(name=name, **attrs)

    def decorator(f):
        return click.command(name=f.__name__, **attrs)(f)

    return decorator
```

**Comment by eromoe** [comment]
Yeah I know, but why not add a setting ?  Is there any disadvantage?

**Comment by ThiefMaster** [comment]
What's the advantage of it? Underscores in CLIs are not very common and somewhat weird. Just like single-dash long arguments (`-foo` etc) are super rare.

So if you want to divert from what's common in CLIs, you already have a not-too-hard way of doing it yourself :)

**Comment by eromoe** [comment]
1. Not common in ancient linux rules but follow python style.
2. Handy, just copy function name paste to cmd then you can run it.
3. Kindy for newbie, who don't know ancient rules,and the forgetter.
