### ISSUE TITLE
deprecate `BaseCommand`, merge into `Command`

### ISSUE THREAD

**Issue by davidism** [pallets/click#2589]
As part of rewriting the parser in #2205, I was looking at the complexities of Click's definitions and processing. `BaseCommand` seems to exist to represent a command without the help, parse, and invoke behaviors implemented by `Command`. A test shows implementing `parse_args` to use `optparse`, where the parameters are defined there instead of as the `command.params` collection. This not documented, and subclassing `Command` instead doesn't prevent writing a custom `parse_args` method.

**Comment by davidism** [comment]
@janluke @kdeldycke any feedback on this is appreciated

**Comment by janluke** [comment]
> A test shows implementing parse_args to use optparse, where the parameters are defined there instead of as the command.params collection. 

I'm fine with the removal, especially if that's the only purpose of `BaseCommand` (using something different than `command.params`). Personally I've never made use of `BaseCommand`. In cloup I had a `BaseCommand` too but I quickly removed it because it didn't serve any purpose.

**Comment by kdeldycke** [comment]
Yes, same as @janluke, never had to use it and was quite confused by its existence. Nothing prevent merging that back to `Command`.

So yes, I agree `BaseCommand` could be removed. 👍
