### ISSUE TITLE
Double dash to disable parsing

### ISSUE THREAD

**Issue by amgcc** [pallets/click#2595]
I need to accept some arguments that should be ignored by click.  I am aware that it is possible to enable extra arguments however it has some major drawbacks.  Use of this feature means that misspelled arguments are ignored which can cause issues.  I think it would be helpful to be able to run a click command with a mix of parsed and unparsed arguments.  In practice it would work something like this:

```
command --parsed-arg1=x --parsed-arg2=y -- --unparsed-args ...
```

If --parsed-arg1 was misspelled in this case it would be flagged as an error.  Any arguments after the double-dash would be ignored by click.

If this proposal is rejected, maybe there is a way to hook into post parsing and add custom validation on the extra arguments for unexpected contents.

**Comment by davidism** [comment]
This already exists.

**Comment by amgcc** [comment]
@davidism Please elaborate.  Is this documented anywhere?  I found no references to double-dashes in the click documentation.
