### ISSUE TITLE
ctx.params does not include partial tuples

### ISSUE THREAD

**Issue by seebi** [pallets/click#2597]
given a option `--filter` of `type=(str, str)` and `multiple=True` as well as a completion function for this option, when using the `ctx.params` in the completion function, partial tuples are not populated.

shell: `$ minimal --filter k1 v1 --filter <TAB>`
ctx.params contains the tuple `("k1", "v1")`, which is expected

shell: `$ minimal --filter k1 v1 --filter k2 <TAB>`
ctx.params contains the tuple `("k1", "v1")`, which is expected
BUT `k2` does not appear in ctx.params.

Minimal working example:

``` python
#!/usr/bin/env python
import click


def complete_filter(ctx, params, incomplete):
    return ["ctx.params as str", str(ctx.params)]


@click.command()
@click.option(
    "--filter", "filters_",
    multiple=True,
    type=(str, str),
    shell_complete=complete_filter,
)
def list_command(filters_):
    """Example command"""
    print(filters_)
    pass


if __name__ == "__main__":
    list_command()
```

Example output

``` shell
$ minimal --filter k1 v1 --filter k2
ctx.params\ as\ str                          \{\'filters_\':\ \(\(\'k1\',\ \'v1\'\),\)\}
```

Expected behaviour: `k2` should be available to the completion function.

Environment:

- Python version: 3.11.4
- Click version: 8.1.7

**Comment by davidism** [comment]
This is unlikely to be possible. The value is incomplete, therefore it is not successfully processed yet and can't be in `params`. Happy to review a PR, but I don't plan to keep this issue open.
