### ISSUE TITLE
Colorama - Issue in pyproject.toml with platform_system == 'Windows'

### ISSUE THREAD

**Issue by cdruet** [pallets/click#2608]
Because of `dependencies = ["colorama; platform_system == 'Windows'",]` in [https://github.com/pallets/click/blob/main/pyproject.toml](url) at lines 16-18, poetry specifies `platform_system == "Windows"` when exporting requirements. This leads pip to fail when creating an image based on python:3.10.12-slim-buster.

just removing `and platform_system == "Windows"` from requirements.txt suffice but what's the purpose here of the `platform_system == 'Windows'`?

Environment:

- Python version: 3.10.12
- Click version: >=8.0

**Comment by davidism** [comment]
Our use is correct, report this bug to poetry.
