### ISSUE TITLE
`progressbar(hide=True)` option for hiding the progress bar

### ISSUE THREAD

**Issue by simonw** [pallets/click#2609]
Often when I use the Click `progressbar` I find myself wanting to conditionally hide it. Sometimes it's because there's another option in play which means I have output to display in place of it - others it's because I added a `--silent` option (as seen in `curl`) for disabling it entirely.

It's actually a bit tricky doing this at the moment, due to its use as a context manager.

What I'd really like to be able to do is this:

```python
hide = True  # or False depending on various things

with click.progressbar(items, show_eta=True, hide=hide):
    for item in items:
        process_item(item)
```

**Comment by simonw** [comment]
Here's [one workaround](https://github.com/simonw/sqlite-utils/blob/622c3a5a7dd53a09c029e2af40c2643fe7579340/sqlite_utils/utils.py#L432-L450) I've used for this, which feels pretty messy:

```python
class NullProgressBar:
    def __init__(self, *args):
        self.args = args

    def __iter__(self):
        yield from self.args[0]

    def update(self, value):
        pass


@contextlib.contextmanager
def progressbar(*args, **kwargs):
    silent = kwargs.pop("silent")
    if silent:
        yield NullProgressBar(*args)
    else:
        with click.progressbar(*args, **kwargs) as bar:
            yield bar
```
Then:
```python
        with progressbar(
            length=self.count, silent=not show_progress, label="1: Evaluating"
        ) as bar:
```

**Comment by simonw** [comment]
It looks like there's already a property that could be used for this:

https://github.com/pallets/click/blob/ca5e1c3d75e95cbc70fa6ed51ef263592e9ac0d0/src/click/_termui_impl.py#L107

So the implementation may be as straight-forward as adding a `hide: bool = False` parameter and then doing this:

```python
 self.is_hidden: bool = not hide and not isatty(self.file) 
```

**Comment by simonw** [comment]
I tried this:
```python
        with click.progressbar(
            ids, label="Calculating similarities", show_percent=True
        ) as bar:
            if hide:
                bar.is_hidden = True
```
But it still shows the bar once at the start of the loop, because of this:

https://github.com/pallets/click/blob/ca5e1c3d75e95cbc70fa6ed51ef263592e9ac0d0/src/click/_termui_impl.py#L110-L113

Which calls `render_progress()` before I've had a chance to toggle `is_hidden` to `False`: https://github.com/pallets/click/blob/ca5e1c3d75e95cbc70fa6ed51ef263592e9ac0d0/src/click/_termui_impl.py#L231-L239

**Comment by davidism** [comment]
I'm wary of changing our progress bar at this point. I generally recommend that people use tqdm or rich if they need features beyond what ours provides. Both of them have a way to hide a progress bar.

In this case, it does seem relatively straightforward to modify our existing hide behavior with a parameter, so I think I'm ok with this.
