### ISSUE TITLE
Add CLI test mode to validate arguments

### ISSUE THREAD

**Issue by 0x26res** [pallets/click#2613]
I'm looking at a way to test my application from the CLI.

So for example:
```python
import click


@click.command
@click.option("--what", type=click.STRING, required=True)
def hello(what: str):
    print(what)

if __name__ == "__main__":
    hello()
```

I would like to run:
```
python -m hello --what=foo --validate
```

And click would validate that all the options/arguments are correct, but not run my code. If they are not correct it can throw an exception and return a none zero return code.

I understand there's already extensive testing tools https://click.palletsprojects.com/en/8.1.x/testing/

But they don't work for me. For context I want to use this to validate airflow dags. From airflow all I have access to is module names and arguments. eg: `{"module": "hello", "arguments":['--what=foo']}`. 
I can't use the `CliRunner` because from a module name (`hello`) I can't guess what `Command` is run.

**Comment by davidism** [comment]
Due to its dynamic nature, this is not generically possible in click core, but you may be able to do it for your specific needs.
