### ISSUE TITLE
Script Crashes with torch.compile(model) and Subcommand named tokenize

### ISSUE THREAD

**Issue by prenc** [pallets/click#2615]
I've developed a multi-command program using the Click library, which is executed with the command `my_program test`. The script unexpectedly crashes when both of the following conditions are met:

1. The script contains the line torch.compile(model).
2. One of the subcommands is named tokenize.

If I either remove the torch.compile(model) line or rename the tokenize subcommand to something else (e.g., tokenize_), the script runs without any issues.

Environment:

- Python version: 3.10
- Click version: 8.1.7
- Pytorch version: 2.0.1

The code to fully reproduce the error: https://github.com/prenc/click_bug_demo

**Comment by davidism** [comment]
This is outside the scope of what I can address.   It sounds like there is an issue with torch and the name tokenize. Happy to review a PR, but otherwise this is not something I plan to investigate.
