### ISSUE TITLE
Adding XDG Base Directory Specification support

### ISSUE THREAD

**Issue by Boomatang** [pallets/click#2620]
Currently the Click utils has [get_app_dir](https://github.com/pallets/click/blob/main/src/click/utils.py#L449) which returns the app directory for the platform that is being called. In the unix systems when not forcing posix this returns the app directory under `$XDG_CONFIG_HOME` or defaults to `~/.config`. As part of the XDG spec there is also stated locations for an apps data, state and cache. The user can configure these locations by environment variables but also have know default locations. 

* `$XDG_DATA_HOME` : $HOME/.local/share
* `$XDG_STATE_HOME` : $HOME/.local/state
* `$XDG_CACHE_HOME` : $HOME/.cache

What I would like to see introduced is four functions to return these locations or the location defaults.

* def get_config_dir(): returns $XDG_CONFIG_HOME/<app>
* def get_cache_dir(): returns $XDG_CACHE_HOME/<app>
* def get_data_dir(): returns $XDG_DATA_HOME/<app>
* def get_state_dir(): returns $XDG_STATE_HOME/<app>

The get_config_dir would be returning the same data as get_app_dir but is clear to its propose.

I have being looking at the Mac and Windows spec. For Mac every thing seems to be placed into the `~/Library/Application Support` , but also has `Caches` which be like ` $XDG_CACHE_HOME`. While on windows it seems to mostly want to use `%APPDATA%` or `%LOCALAPPDATA%` which Click currently supports. But there is also `%ProgramData%` which I believe would be similar to the ` $XDG_DATA_HOME`.

This problem is solvable outside of Click as a developer could access these variables and set their defaults. I do not see this as a great developer experiences as get_app_dir uses `_posixify` on some systems which could lead the user to create mismatching directory names in different locations. Which would be misguiding to end users.

## Resource Links
* [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
* [Default Known Folders in Windows](https://learn.microsoft.com/en-us/windows/win32/shell/knownfolderid)
* [MacOS File System Programming Guide](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1)

**Comment by Boomatang** [comment]
I would also like the opportunity to contribute this change.

**Comment by davidism** [comment]
The [platformdirs](https://pypi.org/project/platformdirs/) library already solves all of this, Click doesn't need to also.

**Comment by Boomatang** [comment]
That is the fast change / closing of an issue. Thanks for sharing the link.
