### ISSUE TITLE
Issue with Click Groups

### ISSUE THREAD

**Issue by jeeftor** [pallets/click#2624]
I have the following code (copied from docs)

```python
import click
import sys


@click.group()
@click.option("--debug/--no-debug", default=False)
def cli(debug):
    click.echo(f"Debug mode is {'on' if debug else 'off'}")


@cli.command()  # @cli, not @click!
def sync():
    click.echo("Syncing")


if __name__ == "__main__":
    sys.exit(sync())
```

I'm running `click==8.1.7` and `Python 3.11.2`

I pulled this example from the documentation:

![image](https://github.com/pallets/click/assets/6491743/d135cbb2-c8e4-466c-ba66-40cdce23e3d1)

I expected to get something like the documentation:

<img width="472" alt="image" src="https://github.com/pallets/click/assets/6491743/f2f2a2e6-1a4c-4c60-b253-87abddf27757">

Environment: (Linux/OSX)

- Python version:   3.11.2
- Click version: 8.1.7

Am I doing something obvious?

Initially I was trying to create scripts via `pyproject.toml` but made this simpler example to verify I was seeing the same bug. I've seen this on both Linux and Mac

**Comment by ThiefMaster** [comment]
You need to call `cli()` instead of `sync()`...
