### ISSUE TITLE
Verify type hints matching types of options/args

### ISSUE THREAD

**Issue by potiuk** [pallets/click#2635]
I'd love to see a way to verify if mypy option/argument types are consistent with types of parameters defined in the decorated methods. It seems that it should be possible - many of the types of options have precise expected type of the parameter that accepts the option, so once we (not sure if possible) join the decorated option definition with type-hints - both available to static checkers - we should be able to determine if the type hint is ok.

Maybe I could contribute myself - though I'd need to deeper dive in mypy and type hinting integration with other tools - but I wanted to open an issue first, because maybe this is something that is difficult/impossible or - on the other hand - already possible but I have not found out how. Or maybe someone works on it (searched through issues / PRs and could not find anything though).

Context:

In Airflow development environment (`breeze`) we are using `click` a LOT (including rich-click extension) - it's really cool and helpful and I am very happy with the flexibility and convenience of click. The reason why we need it is that we have likely close to ~ 250 number of options  and multiple tens of commands in it and it's becoming a bit problematic when for example you miss that option has no "default", but it is defined as `str` (instead of `str | None`).

Just the recent example of it https://github.com/apache/airflow/pull/35842 - having type checking working via (for example) mypy plugin, could have prevented this kind of mistake.

Would love to hear what the maintainers think about such a feature.

And of course - kudos for the great library!

**Comment by davidism** [comment]
I'm very hesitant to do something this complex with typing, given my general experience trying to support typing at all so far. Typer wraps Click and includes more integration with typing, but I'm not sure what it does and doesn't support. There are a lot of non-obvious interactions between the many ways a parameter can be defined, such as default sources, prompting, nargs, multiple, callbacks, etc. If you want to figure out how to implement it, I'm willing to consider a proposal and then PR, but it's such a large feature I'd need some commitment to support it after release as well.

**Comment by potiuk** [comment]
> I'm willing to consider a proposal and then PR, but it's such a large feature I'd need some commitment to support it after release as well.

Much appreciated - and thanks for being super candid and open. I will see if I can spare some time on investigations, and I fully agree that if it comes as one that is on a complex-ish side the maintenance burden migh be way more than the benefit,  so let me see when (if?) I can come up with something.  There are often far too many interesting things to do :). 

Not sure how you do it here - but feel free to assign it to me, and I will come back here when I do my part.

**Comment by potiuk** [comment]
No time to look so far and it's not as annoying regularly. I think the assesment on not doing this was a good one. Closing it.
