### ISSUE TITLE
Click's handling of bare double-dash/hyphen '--' is incorrect

### ISSUE THREAD

**Issue by clintolsen** [pallets/click#2637]
Much like the description of https://github.com/pallets/click/issues/1340 which was closed, click's handling of `--` is arguably not correct.

It's a fairly universal behavior that option parsing should STOP when this token is encountered. However, if you enable `allow_interspersed_args`, it continues. At a minimum this token should appear in click.UNPROCESSED when you enable `ignore_unknown_options`.

You could also argue that the behavior of `allow_interspersed_args` isn't quite right because it halts at the first **unknown** option whereas the documentation doesn't mention this. It reads that it controls allowing the mixing of arguments and options.

Is there a combination of click settings that does what I want?

Environment:

- Python version: 3.10
- Click version: 8.1.3

**Comment by Kamilcuk** [comment]
> should STOP when this token is encountered. However, if you enable allow_interspersed_args, it continues

I do not see how that's possible, from https://github.com/pallets/click/blob/cab9483a30379f9b8e3ddb72d5a4e88f88d517b6/src/click/parser.py#L330-L338 .

If `arg` is "--", the parsing for options stops. Consider posing a code [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).
