### ISSUE TITLE
--help usage: [OPTIONS] swapped with COMMAND

### ISSUE THREAD

**Issue by mkbel** [pallets/click#2653]
Python script using click outputs usage when invoked with `--help` parameter, but [OPTIONS] COMMAND signature doesn't work. Script works as intended with signature COMMAND [OPTIONS] .
### Observed behaviour:
`script.py --help`
```
Usage: script.py [OPTIONS] COMMAND [ARGS]...

  Test & calibration scripts

Options:
  --help  Show this message and exit.

Commands:
  readLut
  writeLut
```
Usage says script.py [OPTIONS] COMMAND
When the script is invoked with available option, it doesn't work as expected:

`script.py --help readLut`
```
Usage: script.py [OPTIONS] COMMAND [ARGS]...

  Test & calibration scripts

Options:
  --help  Show this message and exit.

Commands:
  readLut
  writeLut
```
It outputs top level help, instead of command specific help.

But:
`script.py readLut --help`
```
Usage: script.py readLut [OPTIONS]

Options:
  --axis [X|Y]  Axis for reading LUT
  --dir [F|B]   Table for which direction
  --port TEXT   Machine port
  --help        Show this message and exit.
```
Outputs help for COMMAND, which is intended behaviour.
#### Either 

"Usage:" is altered to match observed behaviour (fields COMMAND [OPTIONS] are swapped.)
`script.py --help`
```
Usage: script.py COMMAND [OPTIONS]  [ARGS]...

  Test & calibration scripts

Options:
  --help  Show this message and exit.

Commands:
  readLut
  writeLut
```
#### Or
`script.py --help readLut`
outputs COMMAND specific help, e.g.:
```
Usage: script.py readLut [OPTIONS]

Options:
  --axis [X|Y]  Axis for reading LUT
  --dir [F|B]   Table for which direction
  --port TEXT   Machine port
  --help        Show this message and exit.
```
### Environment:

- Python version: 3.9.0
- Click version: 8.1.3
- Windows 11

**Comment by davidism** [comment]
I can't reproduce the issue with the information provided. When reporting an issue, be sure to include a minimal reproducible example.
