### ISSUE TITLE
Add mechanism to validate remote files in a parameter type

### ISSUE THREAD

**Issue by chrysle** [pallets/click#2661]
Since often files read by programs are not required to be on the local system, but are also received via HTTP(S), I wonder whether Click could include a mechanism to validate the latter type. Could probably the `click.Path` parameter type be extended to work (optionally) with web resources? Or could a separate parameter type, for example `click.URL`, be created?  I'm aware of that the parameter type would probably have a disproportionately large workload, and also of the potential security risk it would have to handle.  

In a case where a program is able to access files from the web and the local system, but the option type, e. g. `click.Path`,
restricts the arguments to local files, validating remote files would cover both cases.

**Comment by ThiefMaster** [comment]
I don't think URLs params are that common in CLI tools, except for those that are HTTP clients (curl, httpie, etc)...
So IMHO this is something you can easily implement in your own code if you need it.

**Comment by chrysle** [comment]
Thanks for the quick response! Actually, I think all tools working with file contents could use such a validation, there are many online indexes / databases / websites hosting resources. I'm asking on behalf of `pip-tools` (which could parse remote constraint files).

I understand text files can also easily be downloaded and queried, but I like an uncluttered file system, and this would be a more comfortable solution.

**Comment by davidism** [comment]
This is outside the scope of Click core. It's not clear what "validate remote files" means in the context of Click. You want to ensure they're reachable? Ensure they download (but not save them according to your next comment)? Ensure they have some contents? Parameter processing happens in order, so processing and validating the full command line would have to wait for the whole file to download first. Click doesn't provide a data caching mechanism, so the download would happen every time. Processing happens during shell completion as well. If you need this, it's something you can provide in an extension, but it's probably better suited to local code that does exactly what that specific case needs.

```python
@click.command
@click.argument("url")
def install(url: str) -> None:
    exists = request.head(url).status == 200
    if not exists:
        ...
    data = requests.get(url).data
    ...
```

**Comment by chrysle** [comment]
Thanks, you're ~~probably~~ right. Is caching (user input, for example) something you'd be open to have in Click?

**Comment by ThiefMaster** [comment]
To me that sounds like a can of worms that's rarely needed but a great way to have CLIs behave weirdly. Not to mention that manual cache invalidation in such a place would be quite tricky.

**Comment by davidism** [comment]
Locating the cache directory is already handled by the platformdirs library. _Doing_ something specific with the cache is up to the specific application, not Click.
