### ISSUE TITLE
Option not working as expected when using a prompt and a callback function.

### ISSUE THREAD

**Issue by warmuthc** [pallets/click#2662]
When adding options to a command, if the option contains both a prompt and a callback function, the callback function will get called twice. The first time, the value is what was set, the second time it is None. When the program starts executing, the value of None is used for the option.

For example:
```
import click


def callback_fn(ctx, param, value):
    print(value)


@click.command()
@click.option(
    "--option_a",
    default="",
    required=False,
    callback=callback_fn,
    prompt=True,
)
def run(option_a):
    print(f"Option A: {option_a}")


if __name__ == "__main__":
    run()

```

When I run the application with no options passed, it prompts me for a value for option_a:
```
Option a []:
```
and I enter
```
something
```
The program then finishes with output:
```
Option a []: something
Callback: something
Callback: None
Option A: None
```

It seems the callback is called twice, the first time with the correct value, and the second time with "None". When it gets into the actual program, the second value has overridden the first.

It works as expected if I remove the callback.

If I set `required=True`, the program fails with
```
Error: Missing option '--option_a'.
```

Environment:

- Python version: 3.9.18
- Click version: 8.0.1

**Comment by davidism** [comment]
Parameter callbacks must return a value. It is called twice to first process the value of the prompt, then the value provided by the prompt to the parameter.
