### ISSUE TITLE
Filter file/path completions by file suffix

### ISSUE THREAD

**Issue by davidagold** [pallets/click#2664]
## Description

If one implements a command that accepts a file only of a given format, it would be nice to limit file/path shell completions to only those with the supported suffix. We propose to include support for designating supported suffixes in `click.Path`/`click.File` so that one can write, for example,

```python
# cli.py

@click.command()
@click.argument('filename', type=click.Path(exists=True, suffix=".png"))
def convert_png(filename):
    """Convert a PNG image to some other format"""
    ...
```

and then have shell completions for `python -m cli convert_png` limited to only `.png` files.

## Can this problem be solved without changes to `click`?

One could extend `click.Path`/`click.File` and each `ShellComplete` subclass, but this functionality is fairly general and it might be nice to have it accessible in the library itself.

## Branch

I've started a [fork](https://github.com/pallets/click/compare/main...davidagold:click:davidagold/path-suffix-filter) that seems to work for `zsh`. Please let me know if this feature would be welcome.

**Comment by davidism** [comment]
It's an interesting suggestion, but I don't plan to add more complexity such as this to the built-in types anymore.

**Comment by davidagold** [comment]
@davidism Understood. Thank you for the prompt response!
