### ISSUE TITLE
Chances for Code/Command Injection vulnerability

### ISSUE THREAD

**Issue by KarthickRaja2002** [pallets/click#2669]
Hi, 

In version 8.0.4, a file in path **"click/_termui_impl.py"** have some chances for Code/Command Injection vulnerability. The details of issues are quoted below.

1. Command Injection:

> 392       c = subprocess.Popen(cmd, shell=True, stdin=subprocess.PIPE, env=env)

In line no. 392, as the value of shell attribute is "True" and cmd is an untrusted input may lead to Command Injection vulnerability.

2. Command Injection

> 492       c = subprocess.Popen(f'{editor} "{filename}"', env=environ, shell=True)

In line no. 492, as the value of shell attribute is "True" may lead to Command Injection vulnerability.

Environment:

- Python version: 3.8.10
- Click version: 8.0.4

Kindly fix this issue.
Thanks in advance.

Regards,
Karthick Raja N.

**Comment by davidism** [comment]
This is not how to responsibly report security issues. If you believe you have found a security issue, use GitHub's private advisory feature under the security tab to report it to us responsibly.

Neither of the locations you've called out appear to be vulnerable, as the input is not untrusted in either case. When responsibly reporting a security issue privately, be sure to demonstrate the issue, not just point to lines with "maybe this is vulnerable".
