### ISSUE TITLE
click.Path() doesn't have any mechanism to return empty strings when you want a file, but no file was specified

### ISSUE THREAD

**Issue by cblackbu** [pallets/click#2675]
When you've specifically requested the return value to be a string data type it still sometimes returns None instead:
click.Path(exists=True, file_okay=True, dir_okay=False, writable=False, readable=True, resolve_path=True, allow_dash=False, **path_type=str**, executable=False)

**Repro:**
Save the attached script and run click_path.py without any arguments.  

**Result:**
C:\Folder>click_path
--file_path argument received:
type=[<class 'NoneType'>]
value=[None]

The file_path shouldn't be none especially since path_type is set to str.  Therefore the bug still persists.

**Expected:**
The file argument should be an empty string not None.  

Environment:

- Python version: 3.10.9
- Click version: 8.1.7

**Comment by cblackbu** [comment]
Hi Guys, This is a sample script and the same one described in the code above.  Thanks, Christian
[click_path.zip](https://github.com/pallets/click/files/14255878/click_path.zip)

**Comment by davidism** [comment]
That's not how options work. Options that aren't given get the value `None`, regardless of type. If you want a different default, set `default` as well.

**Comment by cblackbu** [comment]
Hi David, Sorry I failed to mention it before, but when I tried to set default before I ever wrote this ticket I get the following error.  So my bug is valid would you please reopen this?  

C:\Some\Path>click_path
Usage: click_path.py [OPTIONS]
Try 'click_path.py --help' for help.

**Error: Invalid value for '--file_path' / '-fp': File '' is a directory.**

**Comment by davidism** [comment]
`Path` already has an unreasonable number of arguments that interact in overlapping and confusing ways. I don't plan to add more complexity to `Path`. If you need other behavior, you'll want to write a type that does exactly what you need at this point.

**Comment by davidism** [comment]
To put it another way `path_type` means "if there's a path, this is how it will be presented". If there's no path, it will be `None`.

**Comment by cblackbu** [comment]
Hi David, The problem at this point seems to be that “” is interpreted as a path.  Couldn’t there just be an allow_null_paths that defaults to False.  I don’t think most people using most environments would consider “” to be a path.
