### ISSUE TITLE
Help colors

### ISSUE THREAD

**Issue by dmitrybelyakov** [pallets/click#269]
Hi!

First of all thank you for such a great tool. Coming from PHP there's yet one feature we miss terribly - help colors. The output of a help command may be hard to read if there's much content.

Having commands and their help string printed in color might make the help output more readable. Like this cli tool for example:

![Image of Yaktocat](http://propelorm.org/images/blog/console.png)

Could you please suggest what steps to take to implement such a feature? 
Thanks and have a great day :)

**Comment by johnarnold** [comment]
HelpFormatter in https://github.com/pallets/click/blob/master/click/formatting.py  as a starting point?

**Comment by dawran6** [comment]
Checkout [click-help-colors](https://github.com/r-m-n/click-help-colors). Below is copied from the [example](https://github.com/r-m-n/click-help-colors/blob/master/examples/example.py):

```python
import click
from click_help_colors import HelpColorsGroup, HelpColorsCommand


@click.group(
    cls=HelpColorsGroup,
    help_headers_color='yellow',
    help_options_color='green'
)
def cli():
    pass

@cli.command()
@click.option('--count', default=1, help='Some number.')
def command1(count):
    click.echo('command 1')

@cli.command(
    cls=HelpColorsCommand,
    help_options_color='blue'
)
@click.option('--name', help='Some string.')
def command2(name):
    click.echo('command 2')


if __name__ == '__main__':
    cli()

```

**Comment by dmitrybelyakov** [comment]
@dawran6 awesome! just awesome!

**Comment by dawran6** [comment]
Thanks you're welcome :D
