### ISSUE TITLE
show envvar in error hint

### ISSUE THREAD

**Issue by KotlinIsland** [pallets/click#2695]
```py
@click.command()
@click.option('--a', required=True, envvar="b", show_envvar=True)
def f(a): ...
f()
```
Here I would want the error message to show the env var.

**Comment by davidism** [comment]
Out of curiosity, why does this and the PR start with an emoji in parentheses? That's pretty distracting, and it's not something any other issues/PRs in the Pallets org use.

**Comment by KotlinIsland** [comment]
Because I like it. It got me [banned](https://github.com/pre-commit/pre-commit.com/issues/687) from pre-commit (any all asottile projects) though 🤣

**Comment by davidism** [comment]
Please don't use it unless a project indicates it's how things are done. Otherwise it's just noisy and annoying, exactly what was said in that issue.
