### ISSUE TITLE
Broken code example in docs under Advanced Patterns

### ISSUE THREAD

**Issue by pbhuss** [pallets/click#2707]
In the Managing Resources section of Advanced Patterns, there is [a code example](https://github.com/pallets/click/blob/f8857cb03268b5b952b88b2acb3e11d9f0f7b6e4/docs/advanced.rst?plain=1#L437-L447) where a `Repo` class is used as a context manager to be passed to `Context.with_resource`. 
```python
    class Repo:
        def __init__(self, home=None):
            self.home = os.path.abspath(home or ".")
            self.db = None

        def __enter__(self):
            path = os.path.join(self.home, "repo.db")
            self.db = open_database(path)

        def __exit__(self, exc_type, exc_value, tb):
            self.db.close()
```

The `__enter__` method on `Repo` currently returns `None`, which means that the [code snippet below](https://github.com/pallets/click/blob/f8857cb03268b5b952b88b2acb3e11d9f0f7b6e4/docs/advanced.rst?plain=1#L453-L454) is broken since `repo` is `None` (the result of `__enter__()`).
```python
    with Repo() as repo:
        repo.db.query(...)
```

In the [snippet below that](https://github.com/pallets/click/blob/f8857cb03268b5b952b88b2acb3e11d9f0f7b6e4/docs/advanced.rst?plain=1#L469), we are also assigning `None` to `ctx.obj`, since `ctx.with_resource` returns the result of calling the resource’s `__enter__()` method.
```python
    @click.group()
    @click.option("--repo-home", default=".repo")
    @click.pass_context
    def cli(ctx, repo_home):
        ctx.obj = ctx.with_resource(Repo(repo_home))
```

The fix is to have `Repo.__enter__` return `self`.

- Click version: 8.1.7

**Comment by pyrito** [comment]
@davidism I think this issue should be marked as resolved 😄
