### ISSUE TITLE
Utility to introspect known command arguments

### ISSUE THREAD

**Issue by LecrisUT** [pallets/click#2709]
### Example situation

I have a main command with a few sub-commands, each with individual options. I want to expose one sub-command to `pre-commit` where I simply append the sub-command's keyword, i.e. I call it as `my_command my_sub`. The issue is that the user would want to pass some arguments to `my_command` instead of `my_sub`, but pre-commit only allows adding `args` to the end. The solution is to make a simple wrapper that re-orders the arguments to go to the appropriate level.

That works fine, but we have to manually filter the arguments. It would be nice to instead have utility functions to introspect the known command arguments so that the filtering does not go out-of-sync.

### Feature request

Utility functions that either:
- give all of the `options` that a command has
- split the `known_arguments` of a command

For now supporting only statically introspect-able commands would be fine, i.e. those that are added only via decorators

**Comment by davidism** [comment]
> pre-commit only allows adding args to the end

Yeah, but that doesn't prevent you from passing what you want:

```
command: my_command
additional_args: --opt a my_sub --other b
```

Besides that, it's already possible to introspect the available options and commands, so I'm not really clear what else would be needed or what it would do.

**Comment by LecrisUT** [comment]
Let's dig into this a bit more. Consider the `.pre-commit-hooks.yaml`
```yaml
- entry: my_command
  args: --opt a my_sub --other b
```
Now the user would want to add `--root /path/to/root` to `my_command` so they write in the `.pre-commit-config.yaml`
```yaml
    - id: "..."
      args: [ --root, /path/to/root ]
```
This is than expanded and used as
```console
$ my_command --opt a my_sub --other b --root /path/to/root
```

Note how `--root` is passed to `my_sub` instead of `my_command`. I don't remember the documentation page on how to make arguments pass from command to subcommand, but I remember trying that out and having had troubles with clashing `kwargs` that made adding `--root` as an option to `my_sub` and having it transparently passed down to `my_command` not possible. (Don't remember if it was even possible)

Now handling one argument is doable, but this CLI is growing rather quick and keeping synced all of the possible arguments that it supports can quickly be problematic. That's why it would be useful to write an automatic way of filtering the arguments so that we can re-order the arguments such that internally we have these equivalent:
```console
$ precommit_my_command --opt a my_sub --other b --root /path/to/root
$ my_command --root /path/to/root --opt a my_sub --other b
```

**Comment by LecrisUT** [comment]
> Besides that, it's already possible to introspect the available options and commands, so I'm not really clear what else would be needed or what it would do.

I couldn't find the relevant API or documentation page
