### ISSUE TITLE
Autocorrect wrong/misspelled option with the suggested unique possibility.

### ISSUE THREAD

**Issue by yusufraji** [pallets/click#2710]
In the current version of click, a wrong (long) option which doesn't exist raises a `NoSuchOption` error. And if there are any close possibilities, those possibilities are presented to the user for consideration.

Using the example of a simple Click program from Click's documentation:
```python
# main.py
import click

@click.command()
@click.option('--count', default=1, help='Number of greetings.')
@click.option('--name', prompt='Your name',
              help='The person to greet.')
def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for x in range(count):
        click.echo(f"Hello {name}!")

if __name__ == '__main__':
    hello()
```

and running `python main.py --naem John`, we get the following output:

```sh
Usage: main.py [OPTIONS]
Try 'main.py --help' for help.

Error: No such option: --naem Did you mean --name?
```

In some failure cases like this, there is only one suggested possibility. It would be great to provide a way to automatically run the command with the unique possible option, rather than just failing. This will improve developer, and user experience.

**Suggested behaviour/output**

```sh
Warning: No such option: --naem
Continuing under the assumption that you meant "--name".
Hello John!
```
This behaviour is inspired by Git's autocorrect.

**Comment by davidism** [comment]
Sorry, I don't plan to add this type of complexity to Click at this point. This also sounds really dangerous to automatically do something if the user doesn't write the correct thing. You wouldn't expect Python function calls to do that either.
