### ISSUE TITLE
Optionally expand global variables in parameters?

### ISSUE THREAD

**Issue by hunandy14** [pallets/click#2741]
https://github.com/pallets/click/issues/1096
According to this article, I know the reason behind it and I also think it is a good thing.
But I would like to ask if appending can be made optional?

For example, the following usage

```
@click.option('--path', '-p', expand_args=False)
@click.option('--identity', '-id')
@click.argument('args', expand_args=False)
def demo(path, identity, type, args):
 """Demo""
```

At some point, uncontrolled expansion can cause problems. I want to pass symbols in but don't know how to start.
This may not be too complicated work, hope it can help me how to pass '*' into the parameter

---

Currently I pass it in like this

```
from click import core
def _no_expand_args(args): return args
core._expand_args = _no_expand_args
```

It's just that I think this is a bit stupid, but my ability is limited and I can't think of a better way for the time being.

**Comment by davidism** [comment]
I'm currently happy with the decisions in the linked thread. I don't want to add further complexity to `Option` and `Argument`. If you don't want expansion behavior everywhere, disable it and expand only where you need it. You can do that with custom parameter callbacks or types.

**Comment by hunandy14** [comment]
Thanks Reply

Understand, I never thought that the callbacks function can actually handle it. I think what you are saying may be like this.

```
def np_expand_args():
    """np_expand_args"""

@click.option('--path', '-p', callback=np_expand_args())
@click.option('--identity', '-id')
@click.argument('args', callback=np_expand_args())
def demo(path, identity, args):
    """Demo""

```

I have no idea how to design the callbacks function. Can you give me some tips on how to design np_expand_args()
