### ISSUE TITLE
Click does not detect duplicate option flags

### ISSUE THREAD

**Issue by apmorton** [pallets/click#2748]
It is possible to inadvertently have multiple options that have overlapping flags.  Click doesn't detect or warn about this scenario, and it becomes impossible to provide a value for the first option.

```python
import click

@click.command()
@click.option('-a')
@click.option('-a', '--long-a')
def main(a: str, long_a: str):
    print(a)
    print(long_a)

if __name__ == '__main__':
    main()
```

```bash
$ rpy script.py -a 1
None
1

$ rpy script.py --long-a 2 -a 1
None
1

$ rpy script.py -a 1 --long-a 2
None
2
```

Environment:

- Python version: 3.11
- Click version: 8.1.7

**Comment by davidism** [comment]
It's not possible to detect this without expensive checks that would slow down command execution.

**Comment by apmorton** [comment]
I'm not familiar with the click internals, so maybe I'm missing something here, but I don't see why this check would be expensive?

This feels like something that boils down to keeping a set of strings somewhere and checking for overlap when adding new options?
