### ISSUE TITLE
Cursor Keys show escape characters like ^[[D when inputting missing options

### ISSUE THREAD

**Issue by anrub** [pallets/click#2751]
When missing an option, click requests the input of that option from the user. When I try to use the cursor keys to navigate forward, backward of the inputted value, I get the escape codes of the cursor keys like ^[[D and ^[[C instead of navigating.

```
import click

@click.group()
def cli():
    """Simple CLI for arithmetic operations."""
    pass

@cli.command()
@click.option('--x', prompt="X")
@click.option('--y', prompt="Y")
def add(x, y):
    """Adds two numbers."""
    click.echo(f"The sum of {x} and {y} is {x + y}.")

if __name__ == '__main__':
    cli()
```

Executing the main.py without options:
```
$ python main.py add
X: 1234^[[D^[[D
```

I would expect the cursor to get to the beginning of the line, instead of escape characters printed.

Environment:
Tried on different shells, OSs with same behaviour.

Ubuntu 22.04.4 LTS / Mac
zsh / bash / iTerm2 / xfce4-terminal 

- Python version:
Python 3.10.12

- Click version:
click 8.1.7

**Comment by davidism** [comment]
That's a property of input in terminals. It's not something Click can control. You can try enabling readline, if it's available.

**Comment by anrub** [comment]
> That's a property of input in terminals. It's not something Click can control. You can try enabling readline, if it's available.

Thank you, you are right. I installed the pyreadline pip module and `import readline` in the the main.py - now it is working.
