### ISSUE TITLE
List of commands when creating a concrete class from `click.MultiCommand` does not display any commands in the CLI.

### ISSUE THREAD

**Issue by SH2282000** [pallets/click#2755]
### what the bug is
Not sure if this is the _desired behavior_ but returning the list of commands when creating a concrete class from `click.MultiCommand` does not display any commands in the CLI. 

#### minimal reproducible example that demonstrates the bug
```python
import click

class MyCLI(click.MultiCommand):

    def list_commands(self, ctx):
        return ['foo', 'bar']

    def get_command(self, ctx, name):
        pass

cli = MyCLI(help='Load subcommands dynamically.')

if __name__ == '__main__':
    cli()
```

### full traceback
There was no exception, but the commands does not appear as you can see below.
```shell

$ python test.py
Usage: test.py [OPTIONS] COMMAND [ARGS]...

  Load subcommands dynamically.

Options:
  --help  Show this message and exit.```

<!--
Describe the expected behavior that should have happened but didn't.
-->

I need to create commands dynamically and do not use decorators for this. Could someone be my saver, I read quite a lot of doc. already.

Environment:

- Python version: `3.8.14`
- Click version: `8.1.7`

**Comment by davidism** [comment]
`get_command` needs to also return command objects, which are what contain the help information. `list_commands` is used to get what names to call `get_command` with. If there's no corresponding command, it's not a command and so is not listed.
