### ISSUE TITLE
CliRunner.invoke doesn't capture stdout from logging

### ISSUE THREAD

**Issue by mjperrone** [pallets/click#2761]
This is a revival of https://github.com/pallets/click/issues/2497

I am hitting the issue described in that issue when using CliRunner. It is preventing me from being able to test the stdout and stderr of my click CLI commands.

The previous issue was closed with @davidism saying "Duplicate of existing issues about pretest's logging capture." Since I am unable to comment on that issue, I am creating a new one.

I would love to be pointed at the referenced duplicate issue so I can understand better what the issue and solutions are.

Ideally I would love to see some kind of workaround documented: Is there a way I can use python's builtin `logging` library in a way that would allow CliRunner to capture the output?

**Comment by davidism** [comment]
Here are open issues about pytest: https://github.com/pallets/click/issues?q=is%3Aissue+is%3Aopen+pytest
Here are open issues about logging: https://github.com/pallets/click/issues?q=is%3Aissue+is%3Aopen+logging

Happy to review PRs fixing this, but I haven't personally had issues with it so I'm not in the best position to investigate and fix it. Closing this as I think the existing issues cover it.

**Comment by kdeldycke** [comment]
This is going to be addressed in v8.4.0 by https://github.com/pallets/click/pull/3391 which introduce a new `capture="fd"` mode to `CliRunner`.
