### ISSUE TITLE
double-dash handling does not support wrapper scripts.

### ISSUE THREAD

**Issue by amgcc** [pallets/click#2765]
There is no wayto terminate processing of a `click.Argument` with `--` (double-dash).  In the previous issue I raised #2596 which was closed without resolution, I was instructed to use `click.Argument` to handle my use case.  This might have worked except for the fact that `click` strips `--` from the arguments such that its impossible to determine where the "extra" arguments begin.  There are a large number of reports [1] on this issue, enough such that I think it would be worthwhile to add better support to terminate argument processing when a `--` is encountered.  In the interim, I have to resort to this [clever suggestion](https://github.com/pallets/click/discussions/2596#discussioncomment-8791045) but I still think its best if click handled this without resorting to hacks. 

```
import click
import sys

@click.command(context_settings=dict(
    # these options have no impact on this behavior
    ignore_unknown_options=True,
    allow_interspersed_args=True,
))
@click.argument('paths', nargs=-1, type=click.Path())
@click.pass_context
def cli(ctx, paths):
    print('Paths:', paths)


if __name__ == "__main__":
    cli()
```

```
$ python clickdemo.py file1.txt file2.txt -- extra1 extra2
Paths: ('file1.txt', 'file2.txt', 'extra1', 'extra2')
```

The expected result would be either with the double dash or excluding it and all the following arguments.  The current behavior is very unhelpful because should I want to slice off the extra args manually, I can't because there is no way to find the position of the `--` double-dash.

```
Paths: ('file1.txt', 'file2.txt', '--', 'extra1', 'extra2')
```
OR
```
Paths: ('file1.txt', 'file2.txt')
```

Environment:

- Python version: `3.11.9`
- Click version: `8.1.7`

[1.] Other Issues referencing this functionality
* https://github.com/pallets/click/issues/619
* https://github.com/pallets/click/issues/1340
* https://github.com/pallets/click/discussions/2596
* https://github.com/pallets/click/issues/2637

**Comment by davidism** [comment]
`--` is not intended as a separator to identify different arguments. Its _only_ purpose is to turn off option parsing and treat tokens starting with `-` as arguments no matter what. If you want your own `--` token to identify different sets of arguments, you'd type `-- -- value value`, and the second `--` would be treated as an argument token in the resulting list.

**Comment by amgcc** [comment]
According to [posix guidelines](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02), use of `--` to disable option parsing is exactly what click does.  However, I would like to know whether click should better support creation of wrapper scripts.  What I am trying to do is have click process some arguments then optionally allow the user to provide additional arguments to pass to a wrapped utility (in this case pytest).  

**Example**
```
my_pytest_wrapper dir1 dir2 dir2 -- --other --args --to --pass --to --pytest
```

There appears to be no way to support this behavior in click without pre-processing arguments and manually interacting with `sys.args`.  I am unsure how many others would find such a feature useful but I at least wanted to be clear about what I'm trying to achieve and see if there is a better way to accomplish this using the existing functionality of the library.

**Comment by davidism** [comment]
There is no way to unambiguously have two separate `nargs=-1` arguments, no. Again, the `--` is not an argument separator, you're getting thrown off by that since it does visually look like one. What you're asking for is "I want to parse "a b c d e" as `[a, b] [c, d, e]`, where both lists can be arbitrary length, which is not possible. You need to rethink your argument design, for example by using a token to indicate where your dir list ends and argument list begins.
