### ISSUE TITLE
Please consider breaking click into click-core and click-ui

### ISSUE THREAD

**Issue by oz123** [pallets/click#2776]
Probably quite an unusual request, but let me explain.
Click advertises itself as "Python composable command line interface toolkit", and it is tremendously popular for its awesome documentation and API.

However, by itself, it is quite big and not so composable. It contains code to support both Windows and Linux terminals, coloring and styling in addition to command line parsing and application welding.

So, if I build a simple command line tool for Linux only, and I am not interested in coloring my output, I still get those dependencies. 
In another case, if I want coloring and multi OS support, but I prefer using `rich` for console UI, I get both rich and click's logic for handling terminals and colors.

If we could install click core for the CLI and application parsing, we could do:

```
pip install click
```
For a full-blown click with bells and whistles:

```
pip install click[termui] 
```
Would install all the rest for console handling and colors.

This is not an easy thing to do, and will require good communications to the community, but I think overall it would be a great benefit for click and the rest of the Python eco-system too.

**Comment by ThiefMaster** [comment]
How would it improve things? It has no dependencies (besides colorama on windows only), and except having a smaller package to install, it would just add more work for maintainers - and also users who'd now need to install two packages or add an extra.

**Comment by oz123** [comment]
It would improve things for maintainers as people can work on the graphics side of thing separately.
As for consumers: they don't need to install 2 packages, directly. They just need to install `click[what-ever-name]`.
You would be surprised how many packages out there install both rich and click, and by removing a lot of weight from click, you can slightly improve the disk space, and network traffic.
