### ISSUE TITLE
click.STRING distorts --some_arg * instead of passing a *, it gives every file in the current folder as Error: Got unexpected extra arguments

### ISSUE THREAD

**Issue by cblackbu** [pallets/click#2782]
**If you pass * to any string argument in click, your script won't receive the "*" string.  Instead you get the following error message (where file1, file2, etc. is every file in working directory):**
C:\some_path>asterisk.py -sc *
Usage: asterisk.py [OPTIONS]
Try 'asterisk.py --help' for help.

Error: Got unexpected extra arguments (...file1, file2, etc.)

**Just rename the attached asterisk.txt to asterisk.py (sorry loss prevention security in place at my employer).**  

**Environment:**

- Python version: 3.10
- Click version: 8.1.7

**Comment by cblackbu** [comment]
[asterisk.txt](https://github.com/user-attachments/files/17173604/asterisk.txt)

**Comment by cblackbu** [comment]
Hi David,  
I appreciate the background, but even if the expansion is deliberate, it's still broken.  If I have set the data type to click.STRING, then it should just be a long delimited string.  It's not.  It results in an error message. I still see the current behavior as a bug.

**Comment by davidism** [comment]
You got a single string for it. You also got a bunch of extra rags from the expansion. An expansion is the equivalent of typing multiple values. The error is talking about the extra arguments, not the type of the first argument.

**Comment by cblackbu** [comment]
Hi David,
Either there’s a way to use a standalone * with click.STRING or it’s a bug.  Which is it?

**Comment by davidism** [comment]
I already told you how above.

**Comment by cblackbu** [comment]
Hi David,
You told me how to turn off expanding "*" via windows_expand_args=False.  That's fine if I want to use * for something else.  My point is if someone actually wants expansion, has a click.STRING argument, there should be a way to receive a string with multiple delimited paths.  You have not provided any scenario where click successfully turns "*" --> "file1.ext;file2.ext;file3.ext".
