### ISSUE TITLE
Context.find_object behavior differs from documentation

### ISSUE THREAD

**Issue by aaron0browne** [pallets/click#279]
[Here](http://click.pocoo.org/3/complex/#ensuring-object-creation) the documentation states that Context.find_object will raise an error if the object can't be found, but it doesn't seem to as of 3.3: https://github.com/mitsuhiko/click/blob/3.3/click/core.py#L315-L321

**Comment by fdavis** [comment]
Looks like a doc bug. The only place find_object is called raises an error if the object returned is None

https://github.com/pallets/click/blob/master/click/decorators.py#L61
