### ISSUE TITLE
v8.1.8 Release Plan

### ISSUE THREAD

**Issue by AndreasBackx** [pallets/click#2793]
Summary of the status of v8.1.8 included issues and pull requests. I think I'd want to move this to a GitHub project, but this is good enough for now as I don't have access to that.

# Pull Requests & Issues

- [x] #2607
	- [x] Needs an additional CHANGES.rst mention.
- [x] #2563 
- [x] #1477
	- [x] Mostly ready, awaiting a tiny question before ready to merge.
- [x] #2273
  - Straightforward and includes necessary tests.
- [x] #2453
  - Straightforward, 2 better error messages.
- [x] #2731

## Potentially Included

- ~~#2767~~
  - Moved to 8.2.0 because failing tests and not worth delaying 8.1.8 for. 
- [x] #2639 
- [x] #2811

**Comment by kdeldycke** [comment]
@AndreasBackx you made excellent work on the upcoming 8.1.8 and 8.2.0 release! Last Click release was 15 months ago, so v8.1.8 looks already good to me to be released as it is. Anything I can help with to have 8.1.8 out?

**Comment by AndreasBackx** [comment]
The only thing holding 8.1.8 back is my question on #1477. My plan was to otherwise land it as-is. I've been away the last 2 weeks though should be ready to wrap 8.1.8 and 8.2.0 up.

If you want to help, the best way would be to:
1. Leave feedback on the unchecked PR/issue items in the #2789.
2. Join the Pallets Discord where chatting is a bit easier: https://discord.gg/pallets.

**Comment by kdeldycke** [comment]
> 2. Join the Pallets Discord where chatting is a bit easier: https://discord.gg/pallets.

Ok, that's where the action is! :)

**Comment by davidism** [comment]
@kdeldycke I could have sworn I had a conversation with you a while ago and added you to this repo. Did I forget to add you? Did I misremember?

**Comment by kdeldycke** [comment]
> @kdeldycke I could have sworn I had a conversation with you a while ago and added you to this repo. Did I forget to add you? Did I misremember?

😄 ahah I don't think so. Or I don't remember either! 😅

Maybe it was @janluke, who was pretty active and involved with Click internals via its https://github.com/janluke/cloup project?

**Comment by bckohan** [comment]
Looks like this is ready to go?

**Comment by AndreasBackx** [comment]
@bckohan it is. I simply haven't found the time recently to go through the release process. Leaving to see family tomorrow as well for the holidays. Trying to get this out before the end of the year along with 8.2.0.
