### ISSUE TITLE
Unable to configure "COMMAND" or [ARGS] metavars when using click.Group

### ISSUE THREAD

**Issue by gaston-haro** [pallets/click#2806]
When using `click.Group` you can customize options and arguments metavars but you cannot customize the COMMANDS autogenerated metavar in help output when you add commands to the group.

```python
@click.group(options_metavar='<options>')
def cli():
    """A random set of productivity shortcuts"""
    pass

@cli.command(short_help='Some subcommand')
def commA():
    click.echo('This is subcommand A')
```

It would output:
```bash
Usage: cli <options> COMMAND [ARGS]...

  A random set of productivity shortcuts

Options:
  --help  Show this message and exit.

Commands:
  comma  Some subcommand
```

Resuling in inconsistencies between "<options>", "COMMAND" and "[ARGS]". I would like to be able to produce:

```bash
Usage: cli <options> command [args]...
```

**Comment by stoneG** [comment]
Can you update the `@click.group` decorator to the following:

```python
@click.group(options_metavar='<options>', subcommand_metavar='command [args]...')
def cli():
```

Or am I not understanding your issue?

**Comment by gaston-haro** [comment]
> ```python
> subcommand_metavar
> ```

Yes, that works. I guess those options are not in the docs.

**Comment by stoneG** [comment]
Oh great - I was taking a look at resolving your issue and saw that kwarg
