### ISSUE TITLE
Support for prefixed options

### ISSUE THREAD

**Issue by AdrianCert** [pallets/click#2810]
I would like to introduce this concept for matching options that starts with a well defined string (prefix) where witch is after is completely arbitrary

As example following will be possible

```py
@click.command()
@click.option(
    '--cfg.*',
    'cfg_values',
    multiple=True,
    callback=parse_dot_notation,
    help="Set nested config keys using dot notation.",
)
...
```

I don't mind how syntax will look like on definition as long in the end i can capture all the option and received as a variable!

As implementation, if I would be assigned with this task>
At [/parser.py:484](https://github.com/pallets/click/blob/main/src/click/parser.py#L484C18-L484C33) if will introduce a new function 
```py
        try:
            _ok = self._match_prefix_opt(norm_long_opt, explicit_value, state)
            if not _ok: 
                 self._match_long_opt(norm_long_opt, explicit_value, state)
        except NoSuchOption:
```

I see this a problem that parser can resolve

Please let me know your option about that! As well I'm willing to invest the effort implementing this!

**Comment by davidism** [comment]
You can do this without any change to Click. Make the option `--cfg` and process the value as `key=value`.

```python
import click


def cfg_to_dict(ctx: click.Context, param: click.Parameter, value: list[str]) -> dict[str, str]:
    out: dict[str, str] = {}

    for item in value:
        k, _, v = item.partition("=")
        out[k] = v

    return out

@click.command
@click.option("--cfg", multiple=True, callback=cfg_to_dict)
def cli(cfg: dict[str, str]) -> None:
    click.echo(cfg)


if __name__ == "__main__":
    cli()
```

```
$ python example.py --cfg=abc=123 --cfg=def=xyz
{'abc': '123', 'def': 'xyz'}
```

**Comment by AdrianCert** [comment]
Yes! I know that! I just want this feature!
