### ISSUE TITLE
Set the `catch_exceptions` value for the whole runner

### ISSUE THREAD

**Issue by azmeuk** [pallets/click#2817]
I always pass `catch_exceptions=False` for all my test suites.
It would be convenient to configure this value once for all in `CLIRunner` for example.

For example, we could add a `CLIRunner.catch_exceptions` parameter, and make `invoke` use that value if not directly passed in parameter of `invoke`. Then I would just have to put the runner in a pytest fixture and that would do the thing for me.

If that is OK, I can open a PR for this.

What do you think?

**Comment by Rowlando13** [comment]
Look like catch_exceptions=True is the default option, so you should not need to pass it in. 
![image](https://github.com/user-attachments/assets/a7821496-6597-4e07-87a6-148bd302329d)

**Comment by azmeuk** [comment]
My bad, I meant the other way. I edit the OP.

**Comment by davidism** [comment]
Might make more sense to add the param to `__init__`, and default to `None` in `invoke`. If it's `None`, it will use whatever was set in `__init__`.
