### ISSUE TITLE
Use python-atomicwrites for atomic file writes?

### ISSUE THREAD

**Issue by untitaker** [pallets/click#320]
https://github.com/untitaker/python-atomicwrites

Armin thinks that it should be an optional dependency, just for Windows support (like colorama).

**Comment by untitaker** [comment]
Decided to postpone this, Click's current thing supports Windows. The only advantage `python-atomicwrites` has is the better advanced API and the support for asserting that the target files don't exist.

**Comment by davidism** [comment]
Going to close this. atomicwrites is cool, but we're unlikely to add an external dependency, although a click-atomicwrites extension could add a type that used it instead.
