### ISSUE TITLE
Autocomplete support for zsh

### ISSUE THREAD

**Issue by fried** [pallets/click#323]
Bash autocompletion works well, but I would really like zsh to work as well

**Comment by tony** [comment]
Related https://github.com/mitsuhiko/click/issues/241.

Has zsh implementation: https://github.com/kislyuk/argcomplete

I have to release a ``tmuxp.bash``, ``tmuxp.zsh`` and ``tmuxp.tcsh`` to get autocomplete working with argcomplete. https://github.com/tony/tmuxp/tree/master/pkg

See also aws-cli's advanced completion: https://github.com/aws/aws-cli/tree/develop/bin

**Comment by flying-sheep** [comment]
> The user has to source the correct one depending on their `$SHELL`

if their `$SHELL` is zsh and you install globally, you can just put `_tmuxp` into `$fpath`, which by default contains `/usr/{,local/}share/zsh/site-functions`.

**Comment by bb4242** [comment]
As an alternative to implementing native zsh completion, you can also use zsh's [bash completion compatibility mode](http://stackoverflow.com/questions/3249432/i-have-a-bash-tab-completion-script-is-there-a-simple-way-to-use-it-from-zsh).  To use it, add

    autoload bashcompinit
    bashcompinit
    eval "$(_FOO_BAR_COMPLETE=source foo-bar)"

to your `.zshrc`.  The last line assumes your click script is called `foo-bar`; see the [click docs](http://click.pocoo.org/5/bashcomplete/) for more info.

**Comment by cbandera** [comment]
@bb4242 thanks for the tipp, that works well.

**Comment by eyalev** [comment]
@bb4242's answer should be added to the docs at: http://click.pocoo.org/5/bashcomplete/

**Comment by fdavis** [comment]
Closed since we have two related pull requests with active discussion and development
#865 and #869
