### ISSUE TITLE
Ctrl-C in a pager causes program to quit

### ISSUE THREAD

**Issue by amjith** [pallets/click#350]
I'm using `echo_via_pager()` in my program to display the output through a pager. But while I'm in the pager if Ctrl-C is pressed then system.exit(1) is called, without giving me an opportunity to handle it. 

I'm using this inside a [repl](https://github.com/dbcli/pgcli) and I'd like to have the ability to handle Ctrl-C. 

Here's an example to reproduce: 

```
import click

@click.command()
@click.option('--foo', prompt=True)
def cli(foo):
    try:
        click.echo_via_pager('foo=%s' % foo)
    except click.Abort:
        print('Tada!')
```

If you run this example and press Ctrl-C while in the pager, it will print 'Aborted!' and quit the program, I'd expect to see the message 'Tada!' instead.

**Comment by untitaker** [comment]
You can still catch SystemExit

**Comment by amjith** [comment]
I tried catching SystemExit and it still doens't work as I expect. 

```
import click

@click.command()
@click.option('--foo', prompt=True)
def cli(foo):
    try:
        click.echo_via_pager('foo=%s' % foo)
    except SystemExit:
        print('Tada!')
```

It still prints `Aborted!` and quits the program.

**Comment by untitaker** [comment]
In my terminal it seems that `^C` kills both pager and program **and** leaves the terminal in an unusuable state.

**Comment by untitaker** [comment]
In your case you need to catch KeyboardInterrupt though.

**Comment by amjith** [comment]
You're right if I catch KeyboardInterrupt it is handled. But it still doesn't solve the problem. 

Looks like the ^C is surfaced by click but the pager is never killed. So even if I handle the KeyboardInterrupt the `less` command continues to print the contents on the screen. 

I feel like the ^C in the page need to be handled by click here: https://github.com/mitsuhiko/click/blob/master/click/_termui_impl.py#L306..L311

Wrap that line in `try/except KeyboardInterrupt` and then call `c.terminate()` and then reraise that KeyboardInterrupt. 

Otherwise there is no way for an app to call the echo_via_pager() and keep working when a user presses ^C in the pager.

**Comment by untitaker** [comment]
I've pushed a fix to 4.x-maintenance and master that fixes your issue. It swallows `^C`, `echo_via_pager` doesn't raise an exception.

This behavior is then consistent with the other pager methods I've seen. I'm not sure if that's the behavior we want, but anything else is fairly hard to implement given the behavior of `less`.
