### ISSUE TITLE
Support for `docker` like arguments termination

### ISSUE THREAD

**Issue by omribahumi** [pallets/click#360]
Is it possible to replace the `--` termination with something else?

I would like to wrap the `docker run` command with my own, preserving the `docker` behaviour.

The `docker run` command arguments are:

```
Usage: docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
```

The `IMAGE` parameter terminates the command line arguments (and is retrievable from the command line parser). I would like to do the same with click. Essentially, this means that the `--` termination would be configurable and retrievable.

The implementation I had in mind is specifying an extra keyword argument to the `@click.argument()` decorator (something like terminating=True)

Any thoughts?

**Comment by untitaker** [comment]
I'd say that it's not a good idea to wrap existing CLIs with Click, because click has many opinions on e.g. helptext formatting that allow you to create nice CLIs very quickly, but not exactly replicate existing ones.

>The IMAGE parameter terminates the command line arguments (and is retrievable from the command line parser).

That's wrong, it seems to terminate the options. You can do the same with Click:

    import click

    @click.group()
    def cli():
        pass

    @cli.command()
    @click.argument('image')
    @click.argument('command', nargs=-1)
    def run():
        '''
        Adasdasdas
        '''
        pass

    cli()

In this case the `command` list specifies command and args to execute in the docker image -- this is not a difference in usage, but only in the helptext.

**Comment by omribahumi** [comment]
@untitaker that's not what I want. For example:

```python
#!/usr/bin/env python
import click

@click.group()
def cli():
    pass

@cli.command()
@click.argument('image')
@click.argument('command', nargs=-1)
def run(image, command):
    print 'image', image
    print 'command', command

cli()
```

Then, if I do something like:
```
$ ./clicktest.py run image 'a b' c d
image image
command (u'a b', u'c', u'd')
```

It works ok. But when I do something like:
```
$ ./clicktest.py run image 'a b' c d --arg
Usage: clicktest.py run [OPTIONS] IMAGE [COMMAND]...

Error: no such option: --arg
```

The behavior I want is "IMAGE" to terminate the arguments so I'll be able to read
```python
('a b', 'c', 'd', '--arg')
```

**Comment by untitaker** [comment]
I see, but again, it's not arguments, you mean options.

**Comment by omribahumi** [comment]
@untitaker I mentioned wanting to imply `--` :)

**Comment by omribahumi** [comment]
@untitaker could you give me a lead on how to implement this? I'll do it and create a pull request

**Comment by mitsuhiko** [comment]
You should be able to implement this by making an `image` subcommand and then doing this: http://click.pocoo.org/4/advanced/#forwarding-unknown-options

**Comment by omribahumi** [comment]
@mitsuhiko `image` is not static

**Comment by untitaker** [comment]
`click.UNPROCESSED` doesn't seem to be enough, Click still intercepts anything that starts with `--`.

**Comment by mitsuhiko** [comment]
Removing the parsing for `--` might be nearly impossible.  I just looked through this a bit and it's just way too far in the wrong part of the stack to make this not handled.

**Comment by jcrotts** [comment]
Closing this it seems like it would be really difficult to implement per mitsuhiko, and the use case looks somewhat limited.
