### ISSUE TITLE
Document CLI in sphinx with a sphinx extension

### ISSUE THREAD

**Issue by Diaoul** [pallets/click#381]
I see you are using [sphinx directives](https://github.com/mitsuhiko/click/blob/master/docs/clickdoctools.py) to run some code and document your examples, any chance you could make that a sphinx extension for mere mortals that want to document their own CLI with sphinx?

Or is there a better way to integrate `cli --help` within a sphinx documentation?

**Comment by Diaoul** [comment]
Related to #255, discussed in https://github.com/mitsuhiko/click/issues/127#issuecomment-45338536 and https://github.com/mitsuhiko/click/pull/234#issuecomment-73091167.

Isn't most of the work already done with [clickdoctools.py](https://github.com/mitsuhiko/click/blob/master/docs/clickdoctools.py)?

**Comment by untitaker** [comment]
If anybody creates such an extension, it'd be nice to have it on https://github.com/click-contrib

**Comment by meejah** [comment]
I did hack something like this together at one point, but it would take some (probably non-trivial) amount of work to make it good enough for "real" use. If someone is interested in doing that, I can find it -- I don't have time in the immediate future...

**Comment by pwm1234** [comment]
I second the request for a nice way to document a click application. Click is quite nice, but now that I have to write a "User's Guide" kind of document for my click application, I am struggling to find a way to keep the documentation current with the application arguments and usage text.

**Comment by t-8ch** [comment]
I have written something like that. I just stupidly prints the `--help` messages though.

This sphinx extension: [jiffyboxdoctools.py](https://github.com/AmadeusITGroup/python-jiffybox/blob/0d5f0d681c12bf3708873327f19bb237b75efa30/doc/jiffyboxdoctools.py)

With this invocation:
```
.. jiffybox:click-help:: jiffybox
```
Yields:
http://python-jiffybox.readthedocs.io/en/latest/cli.html

(Currently GPL3, but it should be possible to make it BSD)

**Comment by rbonthond** [comment]
I'm using https://pythonhosted.org/sphinxcontrib-programoutput/, so I can do ".. command-output:: mycli cmd --help" in my documentation.

**Comment by tony** [comment]
The ``--help`` by itself isn't enough for me imo.

I'm switching from argparse to click in a few projects. The standard library argparse thing I used was https://github.com/ribozz/sphinx-argparse. So it looks like I need something to replace that for click.

Example output: https://sphinx-argparse.readthedocs.io/en/latest/sample.html

**Comment by stephenfin** [comment]
I have this done in [sphinx-click](https://github.com/stephenfin/sphinx-click). I think that should satisfy most requests.

**Comment by stephenfin** [comment]
I also noted that [someone started work on this](https://bitbucket.org/birkenfeld/sphinx-contrib/pull-requests/104/) for [sphinxcontrib.autoprogram](https://pythonhosted.org/sphinxcontrib-autoprogram/) but it never got in :disappointed:

**Comment by rbonthond** [comment]
@stephenfin sphinx-click looks great, awesome!

**Comment by jcrotts** [comment]
sphinx-click was added to click-contrib, and seems like it will handle most use cases. If there is a need for additional work please open a new request.
