### ISSUE TITLE
How to put context in custom object? 

### ISSUE THREAD

**Issue by codekiln** [pallets/click#387]
I have a nested application like the [complex cli example](https://github.com/mitsuhiko/click/blob/master/examples/complex/complex/cli.py), where a custom object is passed through a custom decorator composed with `click.make_pass_decorator` and `ensure=True`. 

If I put `@pass_context` on the constructor of the class, I get a stack trace with `TypeError: __init__() takes exactly 2 arguments (1 given)`. Since there is not currently global access to the context object, I need access to the context, but I'd rather not pass two separate classes, my custom class as well as the context class to each of my methods. 

What is the preferred method of solving this? 

Use case: I'd like to get easy access to the command line options in called methods without having to pass more than one parameter down the call chain.

**Comment by untitaker** [comment]
This has radically changed with Click 5.0. You can use `click.get_current_context()`, but it should be used rarely and I'm not sure if it's overkill in your case.

>Use case: I'd like to get easy access to the command line options in called methods without having to pass more than one parameter down the call chain.

Without knowing the details, I suspect that not passing the options explicitly blurs your API boundaries and introduces unnecessary dependencies.

**Comment by fdavis** [comment]
Closing since there have been no updates.
Please reopen if you have further issues

**Comment by voidloop** [comment]
I'm interested in an answer of this issue. I have a similar problem when I would like create a pass decorator where the constructor takes one argument. Where is the right patter in this situations?

```python
class Dummy:
    def __init__(self, state=None):
        if state is None:
            ctx = click.get_current_context()
            state = ctx.ensure_object(State)
        self.x = state.x

pass_dummy = click.make_pass_decorator(Dummy, ensure=True)
```
Is it right? Is there a better way to do that?
Thank you.
