### ISSUE TITLE
Running a script with an unknown option does not show usage

### ISSUE THREAD

**Issue by pombredanne** [pallets/click#392]
It just shows:

```
script -d
Error: no such option: -d
```

Usage should be displayed IMHO

For instance:

```
 ./scancode  -d
Usage: scancode [OPTIONS] <input> <output_file>
Error: no such option: -d
```

See also #393

**Comment by untitaker** [comment]
How does showing the usage help with this? It only shows that options can be applied.

**Comment by pombredanne** [comment]
@untitaker You are right, it does not help too much. #393 suggest adding how to get to the help.
For instance this is what happens with wget:
```
$ wget
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
```
and git
```
$ git -sdfsdf
Unknown option: -sdfsdf
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```

So displaying either how to get to --help or a longer line that list all options/args values would likely be better.

**Comment by tobywf** [comment]
Any progress? Something like this really improves user experience for long commands. Currently, I'm hacking around this by monkey-patching `get_usage` in the CLI entry point module:
```python
click.Context.get_usage = click.Context.get_help
```
This means that any error results an output as if the user had specified `--help`. So far, I haven't seen any negative effects, just happy users.

**Comment by mbiokyle29** [comment]
+1

**Comment by davidism** [comment]
Decision made to keep current "see --help" message in #502.
