### ISSUE TITLE
Allow custom retainable temporary directories in CLIRunner.isolated_filesystem

### ISSUE THREAD

**Issue by DasIch** [pallets/click#395]
I would like to propose two changes to `CLIRunner.isolated_filesystem`, which I believe would significantly improve the experience of debugging tests using it:
1. Add an argument that allows users to specify the temporary directory.
2. Add an argument indicating that the temporary directory shouldn't be deleted (if an exception occurs).

The current behavior of `isolated_filesystem` of creating a random temporary directory without allowing specifying a specific directory or even a (partial) name and deleting it no matter what, makes it impossible to inspect the directory in case of test failures to gather more information. Even if the directory wouldn't be deleted, it's difficult to find.

By allowing the user to define a temporary directory, it's possible to take advantage of mechanisms such as [py.test's `tmpdir` fixture](http://pytest.org/latest/tmpdir.html) or other systems to separate setup code from the actual test and to make the directory known to the user for inspection.

**Comment by untitaker** [comment]
Totally agree on 1, will merge a PR doing this. Not sure we need 2 as separate arg, we could assume user cleans up themselves if they pass their own directory.

Off topic, I'd like to see a click-contrib package that integrates Click's testing tools more tightly with pytest.

On 29 July 2015 00:16:57 CEST, "Daniel Neuhäuser" <notifications@github.com> wrote:
>I would like to propose two changes to `CLIRunner.isolated_filesystem`,
>which I believe would significantly improve the experience of debugging
>tests using it:
>
>1. Add an argument that allows users to specify the temporary
>directory.
>2. Add an argument indicating that the temporary directory shouldn't be
>deleted (if an exception occurs).
>
>The current behavior of `isolated_filesystem` of creating a random
>temporary directory without allowing specifying a specific directory or
>even a (partial) name and deleting it no matter what, makes it
>impossible to inspect the directory in case of test failures to gather
>more information. Even if the directory wouldn't be deleted, it's
>difficult to find.
>
>By allowing the user to define a temporary directory, it's possible to
>take advantage of mechanisms such as [py.test's `tmpdir`
>fixture](http://pytest.org/latest/tmpdir.html) or other systems to
>separate setup code from the actual test and to make the directory
>known to the user for inspection.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/click/issues/395

-- 
Sent from my phone. Please excuse my brevity.
