### ISSUE TITLE
stream to echo_via_pager

### ISSUE THREAD

**Issue by untitaker** [pallets/click#409]
There should be a possibility to launch the pager while still generating the data it is supposed to show. Proposed API:

```
with echo_via_pager() as f:
    f.write('foobar')
```

**Comment by mitsuhiko** [comment]
I think this might be impossible to support given how the pager fallbacks work.

**Comment by untitaker** [comment]
In that case I think it makes sense to just skip the fallbacks that don't support this.

I need this because I want to write something like `git log` which takes incredibly long to load when buffering all commits before showing the pager.

**Comment by meejah** [comment]
+1
I'm currently working around this by collecting all my lines in some list and then echoing them, but for large inputs this can take a while (and, obviously, for *really* large inputs, exhaust memory). So, the user experience is bad for large inputs since it appears nothing is happening...

**Comment by stefreak** [comment]
I pushed a solution using generators. I'd love to get some early feedback and would finish the implementation if the design is pleasing :)
