### ISSUE TITLE
man page generation

### ISSUE THREAD

**Issue by anarcat** [pallets/click#434]
it would be pretty awesome if click had some hooks to generate a complete manpage, including extra docstrings tagged with relevant decorators.
- [prior art, with optparse](https://andialbrecht.wordpress.com/2009/03/17/creating-a-man-page-with-distutils-and-optparse/)
- [derived implementation, in monkeysign](https://sources.debian.net/src/monkeysign/2.0.2/monkeysign/documentation.py/#L13)

would PRs for this be welcome? on the roadmap?

**Comment by lovette** [comment]
I've had a lot of success using [help2man](https://www.gnu.org/software/help2man/) to create man pages for custom shell scripts. But I haven't used Click yet, so I can't say whether the help output it generates is compatible.

**Comment by JetpackJohn** [comment]
I definitely second this suggestion.  When I was looking for a CLI toolkit to use, man page generation was high on my list.  Other features ended up with Click at the top of the pack, but I do wish it had this feature.

There are plenty of ways to document my program and/or the code itself, but to generate a man page I would end up copying almost all of the data I have already specified with Click.

**Comment by anarcat** [comment]
i just found out about #381 which could fix this problem by using Sphinx to generate the documentation, and then the manpage...
