### ISSUE TITLE
Add option to include carriage return to echo()

### ISSUE THREAD

**Issue by Stefan-Code** [pallets/click#438]
I am proposing an option to tell echo to include a carriage return (`\r`) in addition to the newline for proper printing in raw terminal mode. The updated echo function could look like this:

``` python
def echo(message=None, file=None, nl=True, err=False, color=None, carriage_return=False)
```

With `carriage_return=True` it should do:

``` python
message += u'\r\n'
```

instead of 

``` python
message += u'\n'
```

Again, this feature would be useful to prevent [this](http://stackoverflow.com/questions/12231794/python-in-raw-mode-stdin-print-adds-spaces) from happening when printing in raw terminal mode without a carriage return added to the newline. It would be nice to have this feature because overwriting the echo function has quite a lot of internal click dependencies.
I can submit a pull request for this if desired.

**Comment by untitaker** [comment]
Before a PR we should figure out why this is needed for raw mode.

On 11 October 2015 00:08:39 CEST, Stefan <notifications@github.com> wrote:
>I am proposing an option to tell echo to include a carriage return
>(`\r`) in addition to the newline for proper printing in raw terminal
>mode. The updated echo function could look like this:
>```python
>def echo(message=None, file=None, nl=True, err=False, color=None,
>carriage_return=False)
>```
>With `carriage_return=True` it should do:
>```python
>message += u'\r\n'
>```
>instead of 
>```python
>message += u'\n'
>```
>Again, this feature would be useful to prevent [this]
>(http://stackoverflow.com/questions/12231794/python-in-raw-mode-stdin-print-adds-spaces)
>from happening when printing in raw terminal mode without a carriage
>return added to the newline.
>I can submit a pull request for this if desired.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/click/issues/438

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment]
Also it'd be sensible to test various terminal emulators if there's no indication this is standard behavior.

On 11 October 2015 00:08:39 CEST, Stefan <notifications@github.com> wrote:
>I am proposing an option to tell echo to include a carriage return
>(`\r`) in addition to the newline for proper printing in raw terminal
>mode. The updated echo function could look like this:
>```python
>def echo(message=None, file=None, nl=True, err=False, color=None,
>carriage_return=False)
>```
>With `carriage_return=True` it should do:
>```python
>message += u'\r\n'
>```
>instead of 
>```python
>message += u'\n'
>```
>Again, this feature would be useful to prevent [this]
>(http://stackoverflow.com/questions/12231794/python-in-raw-mode-stdin-print-adds-spaces)
>from happening when printing in raw terminal mode without a carriage
>return added to the newline.
>I can submit a pull request for this if desired.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/click/issues/438

-- 
Sent from my phone. Please excuse my brevity.

**Comment by Stefan-Code** [comment]
So after doing some research, this happens because enabling raw mode
>disables any 'implementation-defined' output processing. On Linux (and probably many others) this is the setting that normally **turns a newline into a CR-NL sequence**. [(source)]( https://utcc.utoronto.ca/~cks/space/blog/unix/CBreakAndRaw)

This can also be verified in the [current python source code for tty.py (3.4)](https://hg.python.org/cpython/file/3.4/Lib/tty.py) in line 22.
I tested the "normal Linux tty" without a graphical environment, gnome-terminal and xterm. They all behave the same.
Adding the `carriage_return` option would also retain API compability I guess. It should be possible to auto-detect the terminal state and then either add the `\r` character exists for other projects though (in case anyone else is reading this).

**Comment by untitaker** [comment]
I wonder if it makes sense to add \r iff stdout is a tty.

I'm worried about piping to files, where programs would generate files with Windows line endings.

On 11 October 2015 12:20:10 CEST, Stefan <notifications@github.com> wrote:
>So after doing some research, this happens because enabling raw mode
>>disables any 'implementation-defined' output processing. On Linux (and
>probably many others) this is the setting that normally **turns a
>newline into a CR-NL sequence**. [(source)](
>https://utcc.utoronto.ca/~cks/space/blog/unix/CBreakAndRaw)
>
>This can also be verified in the [current python source code for tty.py
>(3.4)](https://hg.python.org/cpython/file/3.4/Lib/tty.py) in line 22.
>I tested the "normal Linux tty" without a graphical environment,
>gnome-terminal and xterm. They all behave the same.
>Adding the `carriage_return` option would also retain API compability I
>guess. It should be possible to auto-detect the terminal state and then
>either add the `\r` character exists for other projects though (in case
>anyone else is reading this).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/click/issues/438#issuecomment-147179125

-- 
Sent from my phone. Please excuse my brevity.

**Comment by Stefan-Code** [comment]
Well if the tty is in cooked mode or even cbreak mode adding `\r` is not needed. I'm not exactly sure what happens if it's added anyways, probably nothing. 
Changing echo to include `\r` breaks the API though in case anyone is doing inline printing (like a changing percentage in on line). So the only possibility is an additional option I guess.

**Comment by untitaker** [comment]
i see, but wonder if it's worth adding an extra option or if echo(x + "\r\n", nl=False) is good enough for this case. Either way you'd have to write extra code to get carriage returns.

On 11 October 2015 12:24:49 CEST, Stefan <notifications@github.com> wrote:
>Well if the tty is in cooked mode or even cbreak mode adding `\r` is
>not needed. I'm not exactly sure what happens if it's added anyways,
>probably nothing. 
>Changing echo to include `\r` breaks the API though in case anyone is
>doing inline printing (like a changing percentage in on line). So the
>only possibility is an additional option I guess.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/click/issues/438#issuecomment-147179251

-- 
Sent from my phone. Please excuse my brevity.

**Comment by Stefan-Code** [comment]
I think it would be a great feature to have. Your decision though :)

**Comment by Stefan-Code** [comment]
Right now my implementation for patching click's echo function looks like this in case anyone runs into the same issue:
```python
from click import echo as click_echo
def echo(message=None, file=None, nl=True, err=False, color=None, carriage_return=False):
    """
    Patched click echo function.
    """
    message = message or ''
    if carriage_return and nl:
        click_echo(message + '\r\n', file, False, err, color)
    elif carriage_return and not nl:
        click_echo(message + '\r', file, False, err, color)
    else:
        click_echo(message, file, nl, err, color)
```

**Comment by jcrotts** [comment]
I don't think this is common enough to warrant a new flag. I think the best approach would be to wrap or patch echo.

Going to close this for now, happy to review a PR for it though
