### ISSUE TITLE
Unwrapping of --help information

### ISSUE THREAD

**Issue by rkadam** [pallets/click#441]
Hi There,

I'm finding Click library very useful for developing command line application in Python. One such application that I've developed is [Automate Atlassian from Command Line](https://github.com/rkadam/automate_atlassian_command_line)

One slightly annoying thing I've noticed is, --help options are not displayed to length of terminal. I've read about use of \b value, but don't seem that's applicable.

<img width="703" alt="screen shot 2015-10-24 at 4 39 22 pm" src="https://cloud.githubusercontent.com/assets/1423996/10713344/9a809444-7a6e-11e5-9c0c-8a58cb46546c.png">

Your guidance here will be very helpful.

Thank you,
Raju

**Comment by rkadam** [comment]
Looks like there is already similar bug filed: https://github.com/mitsuhiko/click/issues/204

**Comment by chris-hailstorm** [comment]
Try this:

```CONTEXT_SETTINGS = dict(
    max_content_width=400
)
```

Then when you define the command or group, include that setting:

```@click.group(
    chain=False,
    context_settings=CONTEXT_SETTINGS,
    )
```

This allows the help content to be up to 400 characters wide, and will shrink to the actual screen.
