### ISSUE TITLE
progressbar does not allow update of 0

### ISSUE THREAD

**Issue by nchammas** [pallets/click#447]
``` python
with click.progressbar(length=5) as progress_bar:
    progress_bar.update(0)
```

This throws a `float division by zero` error, which I believe is caused by [this line here](https://github.com/mitsuhiko/click/blob/89d3bfda52d151762e732738b828312a240bf89e/click/_termui_impl.py#L229).

The reason I ran into this is because I'm trying to use `progressbar` to track the status of remote resources which do work at unpredictable intervals. I pass in something like `work_remaining_start - work_remaining_end` to `progress_bar.update()` in a loop that periodically checks these remote resources, and sometimes this difference is 0.

Does it make sense for `update()` to accept a step of 0?

**Comment by nchammas** [comment]
One good reason to allow this, at least for my use case, is that you can update the "current item" while you are waiting for work to be done, like a heartbeat.

For example:

```python
with click.progressbar(length=5, item_show_func=lambda x: current_time()) as progress_bar:
    wait_some_time()
    work_done = check_remote_resource_for_progress()
    progress_bar.update(work_done)
```

So even if no work was done on a given iteration, you can still update the progress bar with something like the current time to indicate that things are still working.

If I understand correctly, `show_eta` doesn't kick in until after the first step has been made, and it probably is unreliable for this situation where you are waiting on remote resources to do work.

An alternative solution for this "heartbeat" use case may be to add an option similar to `show_eta` which shows a timer that simply counts up.

**Comment by fdavis** [comment]
I think @nchammas is right and we can just default to 0 instead of doing that division if this is called with 0

https://github.com/mitsuhiko/click/blob/89d3bfda52d151762e732738b828312a240bf89e/click/_termui_impl.py#L229
