### ISSUE TITLE
click command from Repl

### ISSUE THREAD

**Issue by smorin** [pallets/click#460]
Can click be used from the Repl.

"I apologize for posting this hear but didn't see a mailing list or discussion group"

Typical expected usage:
$ click_app.py command2 subcommand6 --arg1=value1 somearg
$ click_app.py help
$ click_app.py help subcommand2

Repl usage:
$ python
>  import click_app
>  click_app.run_string('command2 subcommand6 --arg1=value1 somearg')
>  click_app.run_string('help')
>  click_app.run_string('help subcommand2')

**Comment by untitaker** [comment]
Check out https://github.com/click-contrib/click-repl
