### ISSUE TITLE
Allow @click.option(nargs=-1)

### ISSUE THREAD

**Issue by flying-sheep** [pallets/click#484]
hi! it would be very good to have this as i need it for compatibility.

i checked and there is nothing in the posix standard disallowing it.

also there is no reason not to allow all non-ambiguous combinations.

with this definition:

```py
@click.argument('stuff', nargs=-1)
@click.option('-s', '--switch')
@click.option('-f', '--foo', nargs=-1)
def utility(stuff, switch, foo):
	...
```

the invocation

`utility herp derp -s --foo bar baz`

should be as unambiguous as is

`utility -s --foo bar baz -- herp derp`

or

`utility --foo bar baz -s herp derp`

---

and even if you disagree: allowing *one* variadic option and requiring all further options and arguments to be non-variadic would also be perfectly unambiguous.

**Comment by flying-sheep** [comment]
hello?

**Comment by untitaker** [comment]
Is http://click.pocoo.org/5/options/#multiple-options feasible in your case?

TBH I don't think this is worth the added **large** complexity.

**Comment by flying-sheep** [comment]
that’s how i do it right now, but it makes the CLIs inconsistent.

but tbh. the multi-option variant is more obvious anyway.

i wonder why the complexity is so high. can you elaborate a bit?

**Comment by untitaker** [comment]
Currently Click prevents ambiguities before starting to parse arguments.

A change to a model where Click has to detect ambiguous arg variants is essentially refactoring half of `click.core`.

**Comment by flying-sheep** [comment]
how about fine-graining this using three states? definitely ambiguous, maybe ambiguous, not ambiguous.

and in the maybe case we parse everything and bail once we find a ambiguity

**Comment by untitaker** [comment]
That's the complexity I was talking about.

**Comment by flying-sheep** [comment]
so leave it open as some “maybe someday” feature request or just close it?

**Comment by untitaker** [comment]
We really might do this "maybe someday", but I think it's not within reach right now.

For this reason I'll close this to prevent having the bugtracker filled with a lot of "maybe someday" ideas.

Sorry for the late response BTW.
