### ISSUE TITLE
Cannot ignore unknown options

### ISSUE THREAD

**Issue by asmodehn** [pallets/click#489]
I m having a problem (on 6.2) that might be related to this issue https://github.com/mitsuhiko/click/issues/473. In my case, this http://click.pocoo.org/6/api/#click.Context.ignore_unknown_options doesn't seem to behave as documented.
I still get a parser error for unspecified options : 

``` python
import click
import rester
@click.command(context_settings=dict(
    ignore_unknown_options=True,
))
@click.option('--log', default='INFO', help='log help')
@click.option('--tc', help='tc help')
@click.option('--ts', help='ts help')
def roster(log, tc, ts):
    """A wrapper around Rester's cli runner that ignores unexpected arguments."""
    rester.apirunner.run()

if __name__ == '__main__':
    roster()
```

```
$ ./scripts/roster --tc rostests/testRosServices.json -sdlkfjs lksjdfsf
Usage: roster [OPTIONS]

Error: Got unexpected extra arguments (-sdlkfjs lksjdfsf)
```

**Comment by wagnerluis1982** [comment]
According to documentation (http://click.pocoo.org/6/advanced/#forwarding-unknown-options) you have to pass `allow_extra_args=True` to `context_settings` and get the remaining args with `ctx.args`.

Or you have to add a `@click.argument('args')` to receive the args.

**Comment by jcrotts** [comment]
Closed, @wagnerluis1982's answer is correct.
