### ISSUE TITLE
eager required options suppress help

### ISSUE THREAD

**Issue by bgschiller** [pallets/click#50]
When there is an option that has `is_eager=True` as well as `required=True`, it will suppress the help message. Perhaps the `--help` option needs to be somehow _more_ eager than other options?

Here's a failing example:

``` python
import click

def get_from_source(ctx,value):
    return value or ctx.params['source']

@click.command()
@click.option('--source',
    is_eager=True,
    required=True,
    help='source file')
@click.option('--dest',
    callback=get_from_source,
    help='destination file. If not supplied, operates in place.')
def process_file(source,dest):
    print 'source:',source
    print 'dest:',dest

if __name__=='__main__':
    process_file()
```

Running this example produces:

``` bash
bash$ python process_file.py --help
Usage: process_file.py [OPTIONS]

Error: Missing option "--source"
```

I would expect (and prefer) to see the following, which is what you get if you turn `is_eager` to `False`.:

``` bash
bash$ python process_file.py --help
Usage: process_file.py [OPTIONS]

Options:
  --source=SOURCE  source file  [required]
  --dest=DEST      destination file. If not supplied, operates in place.
  --help           Show this message and exit.
```

It can be helpful to know the motivation. I'm trying to use a callbacks to validate my input and convert the `train` parameter from a comma separated list `training_set1,training_set2,training_set3` to a python list. The `train` parameter is required. If the `test` parameter is not specified, it is taken as the first entry in the `train` list. Because `test` depends on the processed, validated version of `train`, I have `train` set to be 'eager'.

**Comment by ZenithDK** [comment]
I have run into this issue as well. Parsing the argument "APPLICATION_ROOT" I retrieve a list of directories inside that path, and then the `-l` parameter must be one of those dirs.

The way it is now, unless I specify a valid dir, I will not get any help text?

My code is:
```
application_dir = ''
voiceprompts_dir = ''

available_languages = []

def validate_and_set_paths(ctx, param, value):
    global available_languages, application_dir, output_dir, voiceprompts_dir, voiceprompts_wav_dir, ignored_dirs

    if not os.path.isdir(value):
        logging.error('Provided parameter is not a directory'.format(value))
        return False
    else:
        application_dir = os.path.abspath(value)
        voiceprompts_dir = os.path.join(application_dir, 'voiceprompts')

    if not os.path.isdir(voiceprompts_dir):
        logging.error('Voiceprompts directory does not exist: {}'.format(voiceprompts_dir))
        return False

    dirnames = os.walk(voiceprompts_dir).next()[1]
    for dirpath in dirnames:
        #logging.info('dirpath: {}'.format(dirpath))
        available_languages += [dirpath]

    available_languages += ['ALL']

def validate_chosen_languages(ctx, param, value):
    for language in value:
        if language not in available_languages:
            raise click.BadParameter('\n\tLanguage parameter provided ({}) must one of the following: {}'.format(language, available_languages))

    return value

@click.command(context_settings=CONTEXT_SETTINGS)
@click.argument('application_root',
                type=click.Path(exists=True),
                callback=validate_and_set_paths,
                required=True,
                is_eager=True)
@click.option('--languages', '-l',
              multiple=True,
              default=['ALL'],
              help='Language to convert',
              callback=validate_chosen_languages)
def main(application_root, languages):
    # Do stuff
    pass

if __name__ == '__main__':
    main()
```

**Comment by s7anley** [comment]
@mitsuhiko I used same approach as @bgschiller, since user of script can change desired order of options which could change flow or break it. Is there another way how to define order of options instead of abusing `is_eager` which is breaking the help now.

**Comment by skycaptain** [comment]
@s7anley: You need to preserve the order of your options if you want to use these options in other options callback function; see [here](http://click.pocoo.org/6/advanced/#callback-evaluation-order). A workaround (if you like to call it as such) would simply be putting your callback function inside your command function and passing the context:

```python
def baz_callback(ctx, baz):
    if baz is None:
        ctx.abort("Use baz!")

    return baz.lower()

@click.command()
@click.option('--foo',
              required=True)
@click.option('--bar')
@click.option('--baz')
@click.pass_context
def process_file(ctx, foo, bar, baz):
    if bar is None:
        bar = foo

    baz = baz_callback(ctx, baz)

    print(foo, baz)
```

**Comment by s7anley** [comment]
@skycaptain thanks for tips. I eventually did what I wanted in own decorator, which is executed last so, all the parameters provided by user are either there or not.
