### ISSUE TITLE
click.pocoo.org redirects to version 5 docs (not version 6)

### ISSUE THREAD

**Issue by rsyring** [pallets/click#503]
`http://click.pocoo.org/` redirects to `http://click.pocoo.org/5/` but 6 is the latest stable version.  Is that intended?

**Comment by jeanleonino** [comment]
:+1:

**Comment by mitsuhiko** [comment]
That is currently intended because there are some issues with Click 6 that I did not have the time to fix (in particular the chain support is badly broken on 6.0).

**Comment by jeanleonino** [comment]
@mitsuhiko thanks! I guess you can close the issue then.

**Comment by jeanleonino** [comment]
@mitsuhiko (but it kinda means v6 it's not stable, haha)

**Comment by aussio** [comment]
Heh, I kept running into this as well. Is this still an issue? It's been a good bit of time since the last update. 😄

**Comment by tony** [comment]
http://click.pocoo.org/latest/api/ forward to http://click.pocoo.org/5/api/

I would expect http://click.pocoo.org/6/api/

Is the chain issues something fixable *within* version 6, or is it waiting for the next version release?

**Comment by robeastham** [comment]
Just discovered Click. I'm interested in what the status of this issue is at the moment. For new projects which version is recommended 5 or 6? 

I'm intending to use it in combination with the Flask integration for 0.11 mentioned here http://flask.pocoo.org/docs/0.11/cli/ .

**Comment by vkotovv** [comment]
@mitsuhiko if Click 6 has some parts broken, then it should be marked as unstable maybe? Redirect to 5 is a bit misleading right now

**Comment by nedbat** [comment]
This continues to be confusing.  Choose one or the other: 6 is stable, or it isn't.
