### ISSUE TITLE
Question about argument documentation conventions

### ISSUE THREAD

**Issue by dlwhiteman** [pallets/click#505]
I noticed in all the examples of documenting command arguments, the argument names are written in all caps, e.g. NAME or COUNT.  I am fairly new to command line tool development, and was wondering if this is a standard convention.  I couldn't find anything on the Internet that mentions documenting arguments in all capital letters.  Can you please point me to something that mentions this?  I am trying to provide evidence to our team's documentation writers.  Also, if this is the convention, how do you document multi-word argument names?  Do you use a hyphen, underscore, or nothing between the words (e.g. ERROR_COUNT)?

**Comment by jcrotts** [comment]
There is no standard that I'm aware of, but I think representing the metavars in caps is pretty common. For longer words you would use underscores as in "ERROR_COUNT".
