### ISSUE TITLE
Retain context between successive commands

### ISSUE THREAD

**Issue by Overdrivr** [pallets/click#506]
I have writen an application that connects to a serial port, do some stuff with it, etc.

Is there a way to keep the connection object (or any data, really) between successive commands ?

`pass_context` is a good start for exchanging data between commands, however I fail to understand how to retain the context between successive commands. Some basic print debugging showed me that the context is destroyed every time a command is finished. 

I suppose my application would be sort of daemonized, but before starting daemon threads on my own I was wondering if there was a straighforward manner to do it.

I've seen this sort of example (https://github.com/mitsuhiko/click/blob/master/examples/naval/naval.py) that has the same philosophy, however it's just the interface. How can the 'backend' be written ?

**Comment by Overdrivr** [comment]
Basically, I am looking for writing a terminal application, like with this module https://docs.python.org/3.4/library/cmd.html but with click's nice syntax

**Comment by davidism** [comment]
Click is a library for writing commands (CLI), what you're looking for is an interactive terminal application (I've seen them called TUI). You're looking for something like the built-in [cmd]() or [curses](https://docs.python.org/3/library/curses.html), or nicer wrappers around curses like [blessed](https://github.com/jquast/blessed).
