### ISSUE TITLE
one general command for multiple groups?

### ISSUE THREAD

**Issue by arnm** [pallets/click#507]
```python
@click.group()
def group1():
    pass

@click.group()
def group2():
    pass

@group1.command()
@group2.command()
def cmd():
    print 'cmd'
```

Why can't this be done? I would have to duplicate the same code only for it to be available to be invoked by group2.

I know this is an very basic use case and would probably argue that groups wouldn't be needed for a general command such as this one but this feature would be extremely helpful in more complex use cases.

For example, I'm utilizing the pipeline feature and the "generators" all produce the same type of data and the "processors" all intake the same type of data but not necessarily the same data. The group defines what specific data is produced but it's always the same type of data. There are some general "processors" (e.g one which prints the data to the screen) which would work the same no matter what group they are under.

**Comment by untitaker** [comment]
If you really need to, you can do:

    def cmd():
        print "cmd"

    group1.command()(cmd)
    group2.command()(cmd)
