### ISSUE TITLE
Unable to Create Commands from Inside a Class.

### ISSUE THREAD

**Issue by TechnicalBro** [pallets/click#523]
I've been using Click for a while with some smaller, non-dynamic CLI application and found it pretty fun to use. After I finished a rough sketch of the idea, I wanted to further this by making it pluggable, via classes.

Is Click not able to have commands registered inside a Class?

There's alot more to it than this, though, currently I wrote up a test to show how this feature doesn't work, and I'm curious if there's a way to do it. If so, please inform me.

Here's my test code.

```
import click

CONTEXT_SETTINGS = dict(
    auto_envvar_prefix='COMPLEX'
)


class AppContext(object):
    def __init__(self):
        self.name = "Brandon"
        self.greeting = "Hello, "
        self.after_greet = "FROM THE OTHER SIIIIIIIIIIDE"


class Commands(object):
    def __init__(self):
        self.commands = ["perform_hello", "perform_otherside"]

    @click.command("hello")
    def perform_hello(self, ctx):
        print("%s%s" % (ctx.greeting, ctx.name))

    @click.command("otherside")
    def perform_otherside(self, ctx):
        print("%s" % ctx.after_greet)


commands = Commands()


class ClickCLITest(click.MultiCommand):
    def __init__(self, **kwargs):
        super(ClickCLITest, self).__init__(**kwargs)

    def get_command(self, ctx, cmd_name):
        name = "perform_%s" % cmd_name
        if name not in commands.commands:
            return
        return getattr(commands, name)

    def list_commands(self, ctx):
        cmds = []

        for cmd in commands.commands:
            if cmd.startswith("perform_"):
                cmds.append(cmd.replace("perform_", ""))

        cmds.sort()
        return cmds


pass_context = click.make_pass_decorator(AppContext, True)


@click.command(cls=ClickCLITest, context_settings=CONTEXT_SETTINGS)
@pass_context
def run_app(ctx):
    print("Beginning App Execution")


if __name__ == "__main__":
    run_app()
```

The way my app is designed, is much like the test code above. Only difference is I don't use get_attr or anything of that nature, I actually subclass a Plugin class, then tag a method as the command.

I'd really like to be able to make click commands inside classes, as opposed to top level functions. Is this possible? At all?

**Comment by untitaker** [comment]
No, that's not how Click is supposed to be used at all, and TBH I don't really see the point of it. You're using classes as if they were modules.
