### ISSUE TITLE
Allow implementing bash complete functions for individual args 

### ISSUE THREAD

**Issue by travis-bear** [pallets/click#534]
It would be really useful to be able to define my own bash complete logic for certain arguments.  For example, I may want to query a database or a web api for a list of possible values.  See python's argcomplete library for an example of how custom completer functions might look.

**Comment by DEvil0000** [comment]
there is `autocompletion=get_my_complete` with method signature `def get_my_complete(ctx, args, incomplete): ` `return []`

**Comment by davidism** [comment]
See #1484
