### ISSUE TITLE
Cannot apply `invoke_without_command=False` to multiple subcommands

### ISSUE THREAD

**Issue by mikezaccardo** [pallets/click#539]
I'd like to require that all subcommands (more than just one) be present in order for execution to proceed.

If I set `invoke_without_command=False` for the parent command, the only requirement is that at least one of the subcommands be present, not all.

When no subcommands are supplied, the usage output looks like this:

```
main.py [OPTIONS] COMMAND1 [ARGS]... [COMMAND2 [ARGS]...]...
```

The second command is listed as optional and execution will proceed if I only supply one command, which is not what I want.  I also can't use `invoked_subcommand` to check because that will return `*` whenever one or more subcommands are present.

Python: v2.7.11
Click: v6.3

**Comment by untitaker** [comment]
This is interesting, but I doubt whether it's good UI. Could you elaborate on the concrete usecase?

**Comment by fdavis** [comment]
Closing since there has been no update. 
Please reopen with use case details if you are still interested in this feature
