### ISSUE TITLE
How can I split my Click commands, each with a set of sub-commands, into multiple files?

### ISSUE THREAD

**Issue by grundic** [pallets/click#541]
Here is the link to the [stackoverflow](http://stackoverflow.com/questions/34643620/how-can-i-split-my-click-commands-each-with-a-set-of-sub-commands-into-multipl). I'm not the original author of this question, but I have the same problem, so decided to ask here.
Could you please help with it if it's ever possible?
The only possible solution I know is loading subcommands dynamically like in [complex example](https://github.com/mitsuhiko/click/tree/master/examples/complex), but I thought maybe there could be better solution.
Thank you.

**Comment by untitaker** [comment]
It is considered rude to crosspost questions in the bugtracker, especially if they already have answers.
