### ISSUE TITLE
Decode UTF-8 before invoking type=...

### ISSUE THREAD

**Issue by laurivosandi** [pallets/click#542]
Hi,

it seems when I try to use eg. type=ip_address on Python 2.x the bytes are passed as-is to the ip_address function and it fails to decode it because it's not unicode object. If there is no good reason I think it would be good idea to decode UTF-8 before passing it to the type=... function.

**Comment by untitaker** [comment]
This is impossible to change in a backwards-compatible manner, and while it might have made more sense to go "unicode-everywhere" in Click's APIs, I think it's definetly too late now. Afaict it'd also be out of line with many stdlib functions in Python 2, which only handle bytestrings properly. So even if Click started to decode the data to unicode, passing it to a stdlib function would create an implicit conversion using the ASCII encoding, which makes your program crash anyway. Therefore I doubt it'd be worth the compatibility breakage in Click's API.

My personal recommendation is to just use Python 3 if you don't want to care about unicode.

**Comment by mitsuhiko** [comment]
type is not supposed to be used that way anyways. The correct way is to implement a custom click type if you cannot deal with unicode data.
