### ISSUE TITLE
group commands with prefix

### ISSUE THREAD

**Issue by objaa** [pallets/click#554]
Hi,

How i can group commands  with prefix?

operations for group1
> script.py myprefix list
> script.py myprefix create ARG
> script.py myprefix delete ARG
> script.py myprefix update ARG1 ARG2

operations for group2
> script.py myprefix2 list
> script.py myprefix2 create_other ARG ARG2
> script.py myprefix2 update_foo ARG1 ARG2

i can create one command with many optional args, but it not better way.
Can i split functions list, create, delete, bul call with prefix?

**Comment by untitaker** [comment]
You are thinking of command groups: http://click.pocoo.org/5/commands/

**Comment by objaa** [comment]
`import click

@click.group()
def cli(debug):
    click.echo('Debug mode is %s' % ('on' if debug else 'off'))

@cli.command()
def sync():
    click.echo('Synching')

if __name__ == '__main__':
    cli()
`

sync command calling from cmd as: **script.py sync**, but i need call with prefix **script.py _foo_ sync**.

**Comment by untitaker** [comment]
Then create a new sub-group using `cli.group`.

**Comment by untitaker** [comment]
Also please don't abuse the issue tracker for support requests. I will lock this issue now.
