### ISSUE TITLE
--help doesn't get forwarded when using click.UNPROCESSED

### ISSUE THREAD

**Issue by nickjj** [pallets/click#556]
To forward command line options and flags, the Click documentation recommends that you do this:

```python
@click.command(context_settings=dict(
    ignore_unknown_options=True,
))
@click.option('-v', '--verbose', is_flag=True, help='Enables verbose mode')
@click.argument('timeit_args', nargs=-1, type=click.UNPROCESSED)
def cli(verbose, timeit_args):
    """A wrapper around Python's timeit."""
    cmdline = ['python', '-mtimeit'] + list(timeit_args)
    if verbose:
        click.echo('Invoking: %s' % ' '.join(cmdline))
    call(cmdline)
```
That can be found here: http://click.pocoo.org/6/advanced/#forwarding-unknown-options

---

**The problem is**, let's say you're wrapping another utility and you want to view the help menu for that utility. That's commonly accessed in 4 different ways:

1. Running the command with no options or aguments
2. `help`
3. `-help`
4. `--help`

The first 3 ways are supported by Click without issues.

However, the last one fails because instead of forwarding it to the utility, Click just reports back its own help for the command you've created.

I feel like this is a bug because you would expect to see the utility's help menu, not yours.

**Comment by untitaker** [comment]
Click forwards unknown options... but `--help` is a known option! All the other examples you give are not.

I think you're supposed to use `add_help_option=False` to the keyword args of `click.command(..)`, as per http://click.pocoo.org/6/api/#click.Command

**Comment by nickjj** [comment]
Your recommend works, thanks.

Is it worth adding that to the documentation's code snippet listed in the issue? I've used Click extensively but didn't even know that option existed, because this happened to be the first time I ever wanted to fully wrap a third party utility.

That option kind of goes hand in hand with wrapping a utility.

**Comment by untitaker** [comment]
I'm not sure. After all the help output for the wrapper command is demoed further below, and how would you document the `-v` option of the wrapper if you forward `--help` as well?

Perhaps as a bullet point in the "list of things that are important to know", mention that `add_help_option` is a thing.

Anyway I'll close this, feel free to open a PR about the doc change if you care enough :))
