### ISSUE TITLE
support FORCE_COLOR in click.echo

### ISSUE THREAD

**Issue by flying-sheep** [pallets/click#558]
FORCE_COLOR is supported by many tools (e.g. node’s popular `chalk`). setting it to anything enables colors even if the autodetection wouldn’t.

i think `click.echo` should support it.

**Comment by untitaker** [comment]
You can set `ctx.color = True` to force color output, so it's trivial to implement this in usercode. I personally don't think this behavior should be added to Click itself, *even though* Click stands for reasonable defaults, I think it makes the logic too complex to easily fit in the user's head.

**Comment by untitaker** [comment]
What would also help is more example applications with this convention.

**Comment by flying-sheep** [comment]
well, the [chalk JS package](https://www.npmjs.com/package/chalk) has [those 13&hairsp;000](https://www.npmjs.com/browse/depended/chalk) depending packages.

this (transitively) includes nearly all node.js command line applications.

but yeah: there’s no real standard for this. [just check this mess](https://github.com/chalk/supports-color/blob/master/index.js)

i think we have `FORCE_COLOR`, `CLICOLOR`, `CLICOLOR_FORCE`, `LS_COLORS`, `GREP_COLORS`, and various `--color` options, e.g. `--color=always|auto|off` in GNU tools. `CLICOLOR[_FORCE]` seems to be a good idea (certainly the most clear and intuitive way), but [none of the bug reports](http://bixense.com/clicolors/) had any impact.

convenient and expected would IMHO be to have a method that automatically adds a GNU-like `--color` option, as well as support for the whole env variable mess like supports-color does.

**Comment by flying-sheep** [comment]
for semantics:

* `FORCE_COLOR` ≠ 0, `CLICOLOR_FORCE` ≠ 0, `--color=always` force it to be on
* `CLICOLOR` ≠ 0, `--color`, `--color=auto` means autodetection
* `CLICOLOR=0`, `FORCE_COLOR=0`, `--color=off` force it to be off
*  `CLICOLOR_FORCE=0` just means no forcing, just like it being unset

**Comment by jcrotts** [comment]
Closing this because it is closely related to the following issue.
https://github.com/pallets/click/issues/558

Happy to review a PR if you have a proposed implementation.

**Comment by flying-sheep** [comment]
uh, #558 is *this* issue. which one do you really mean?

**Comment by jcrotts** [comment]
Hah good catch https://github.com/pallets/click/issues/1090

**Comment by flying-sheep** [comment]
NP. Why did you close this one though? The other one came later and contains much less information than what I researched above.

**Comment by jcrotts** [comment]
You are right, I am trying to consolidate issues on the tracker. I do appreciate the background you gave it was helpful context. I just closed this one because it had been stale for longer.

I'm not sure there is a clean way to implement this, but i'm not completely opposed to it. Happy to look at a PR if you have an idea on implementation.

**Comment by flying-sheep** [comment]
OK, I just moved my stuff there then
