### ISSUE TITLE
why is "-script.py" appended to my program names?

### ISSUE THREAD

**Issue by dmahugh** [pallets/click#563]
I've created a few simple command-line tools with Click, and I'm really liking it but I have one consistent anomaly in the displayed help text for all of my commands.

If, for example, my program is named foo.py, then when I run it with only the `--help` option the first line of the help text says this:

`Usage: foo-script.py [OPTIONS]`

Why does it append "-script" to the program name? Is this behavior intended? It makes the help text incorrect, as the actual command is `foo`, not `foo-script`. Thanks for any guidance on this!

**Comment by untitaker** [comment]
See https://github.com/pallets/click/issues/365, this is tracked in pip/setuptools apparently.
