### ISSUE TITLE
_NonClosingTextIOWrapper conflicts with Theano

### ISSUE THREAD

**Issue by zstomp** [pallets/click#564]
After updating Theano from 0.7.0 to 0.8.2 I'm getting the following error:

> Exception TypeError: TypeError("'NoneType' object is not callable",) in \<bound method \_NonClosingTextIOWrapper.\_\_del\_\_ of \<\_io.TextIOWrapper encoding='UTF-8'\>\> ignored

Tested with Click 5.1 and 6.6 on Python 2.7.11.

**Comment by mitsuhiko** [comment]
What is Theano?

**Comment by untitaker** [comment]
Apparently it is some sort of library. It doesn't appear to use Click, so I guess @zstomp uses both Theano and Click in his application.

@zstomp Please provide a full traceback of the error, because the error you provided doesn't make sense (in `click._compat._NonClosingTextIOWrapper.__del__`, all exceptions are caught)

**Comment by zstomp** [comment]
My bad, sorry for the vague report. The error appears exactly as above, no traceback provided. As I understand it, this is normal interpreter behavior when things crash in `__del__()`.

Now that I've got a minute to debug it, I tried blank `except:` instead of `except Exception:`, and it caught it. Then I tried extending the handler to catch the stack trace, but it just can't `print` or `write` it to a file, the result is the same error message.

All I can think of is to find which part of my or library code triggers it. Let me know if you have better ideas of catching it.

**Comment by untitaker** [comment]
@zstomp A very basic application to reproduce the issue would be very useful so I can debug myself.

**Comment by zstomp** [comment]
Ok, it boils down to

```
import click
import theano.tensor


@click.command()
def main():
    click.echo("Test")


if __name__ == '__main__':
    main()

```

To set things up easily, install [Miniconda](http://conda.pydata.org/miniconda.html) package/environment manager, then
```
$ conda create -n test scipy
$ . activate test
$ pip install click==6.6 theano==0.8.2
```

**Comment by avloss** [comment]
having same issue - looking forward to a fix

**Comment by mitsuhiko** [comment]
Looking at the source I have no idea how that error can even occur.

**Comment by avloss** [comment]
yes
Theano==0.8.1
click==6.6

I'll try investigating myself quickly.

**Comment by mitsuhiko** [comment]
My guess is that this is something in Theano and not click. We're not doing crazy things here.

**Comment by avloss** [comment]
You're right it's probably Theano

https://github.com/pallets/click/blob/57c6f09611fc47ca80db0bd010f05998b3c0aa95/click/_compat.py#L71

this is what causing exception. Anyways - this is wrapped in "except: pass" so I'm hoping that Theano will work as expected. Will update if it'll be giving me any more problems.

**Comment by zstomp** [comment]
It turns out the problem is with [six](https://pythonhosted.org/six/) that is used by Theano. If you `import six.moves.builtins`, you get the above-mentioned error.

**Comment by mitsuhiko** [comment]
Six' magic strikes again. There is nothing we can do here. Someone should report this against theano.

**Comment by zstomp** [comment]
Could you please elaborate? Is Six known for causing problems? Report on Theano for what, get rid of Six??

**Comment by amol-** [comment]
@zstomp telling Theano to avoid using `six.moves` and explicitly import the compatibility functions is probably the right solution. See https://pythonhosted.org/six/index.html#module-six.moves

**Comment by nouiz** [comment]
Why not report this to six? I don't undertand the problem with Theano. Do we badly use six? for six.moves.builtins, we do:

from six.moves.builtins import min as builtin_min
import six.moves.builtins as builtins
from six.moves import builtins

We where still using __builtins__ at one place. I'm using the six version in this PR: https://github.com/Theano/Theano/pull/4733

**Comment by zstomp** [comment]
@nouiz I did report this to six, nothing so far. Theano is not a problem per se, six.moves.builtins is.

**Comment by nouiz** [comment]
Can you give the link to that report?

**Comment by zstomp** [comment]
https://bitbucket.org/gutworth/six/issues/157/sixmovesbuiltins-causes-strange-exception

**Comment by tdhopper** [comment]
Does anyone have a workaround for this in the meantime?

**Comment by mitsuhiko** [comment]
This is not a problem with click unfortunately. The workaround would be to not use six moves. The entire thing is just conceptinally problematic. We had many issues in the pallets project with this sort of hackery.

**Comment by tdhopper** [comment]
@mitsuhiko I get that. I have theano as a dependency though.

**Comment by mitsuhiko** [comment]
As mentioned you need to reach out to theano for this to stop using six moves. This is outside of our control.

**Comment by untitaker** [comment]
Please file this against Theano.
