### ISSUE TITLE
`click.option` silently swallows invalid *args.

### ISSUE THREAD

**Issue by PWiggins84** [pallets/click#568]
As demonstrated below, the code for checking the choice type does not verify the entire string and will pass if a subset is given.

    [click]$ setrackinfo ifcfg-param add 1
    Usage: setrackinfo ifcfg-param add [OPTIONS] NODEID INTF PARAM [VALUE]

    Error: Missing argument "Choice(['public', 'private'])".
    [click]$ setrackinfo ifcfg-param add 1 pub
    Usage: setrackinfo ifcfg-param add [OPTIONS] NODEID INTF PARAM [VALUE]

    Error: Missing argument "Choice(['mtu', 'xmit_hash_policy'])".

I imagine the convert function should be updated to ensure that the given input is actually in the choices and not just a subset is matched.

    class Choice(ParamType):
       ....
       ....
        def convert(self, value, param, ctx):
            # Exact match
            if value in self.choices:
                return value

**Comment by untitaker** [comment]
Sorry, but I have absolutely no idea what you're referring to. Please give:

* a reproducible, minimal example, including sourcecode.
* a command to execute including expected output

**Comment by PWiggins84** [comment]
@ifcfgParam.command('add')
@click.argument('nodeID', click.IntRange(1, 24))
@click.argument('intf', click.Choice(['public','private']))
@click.argument('param', click.Choice(['mtu','xmit_hash_policy']))
@click.argument('value', nargs=1, default=0)
def addIfcfgParam(**kwargs):
    print "Add ifcfgParam"
    pprint.pprint(kwargs)


On the command line if I pass "pub" instead of "public" it will accept it (and it should not)

**Comment by untitaker** [comment]
You need to pass your `click.Choice` instance explicitly with the type kwarg. Click probably should validate this better and show a nicer error message.

**Comment by PWiggins84** [comment]
I'm sorry, I do not follow. How do you mean pass it explicitly?

**Comment by untitaker** [comment]
click.option(name, type=click.Choice(...))

On 30 April 2016 22:50:24 CEST, PWiggins84 <notifications@github.com> wrote:
>I'm sorry, I do not follow. How do you mean pass it explicitly? 
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/click/issues/568#issuecomment-215994007

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by PWiggins84** [comment]
Isn't that what I am doing here for the argument?
@click.argument('intf', click.Choice(['public','private']))

**Comment by untitaker** [comment]
Again, no.

On 30 April 2016 23:19:38 CEST, PWiggins84 <notifications@github.com> wrote:
>Isn't that what I am doing here for the argument?
>@click.argument('intf', click.Choice(['public','private']))
>
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/click/issues/568#issuecomment-215996108

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by PWiggins84** [comment]
I just realized what you were saying. thank you.
Added the type= portion to explicitly set it. Works as expected now.
thank you.

**Comment by untitaker** [comment]
Continuing at https://github.com/pallets/click/issues/574
