### ISSUE TITLE
Defaults for choice ?

### ISSUE THREAD

**Issue by stuaxo** [pallets/click#576]
Is there any chance of allowing defaults for choice, like this:

```@click.option('--dry-run', type=click.Choice(['pass', 'fail']), default="pass")```

Cheers
S

**Comment by stuaxo** [comment]
(This would set 'dry_run' to "pass" if --dry-run is passed - if --dry-run is not passed, it would be None)

**Comment by untitaker** [comment]
This code is working as-is.

**Comment by stuaxo** [comment]
Just found this out + came back to close this, thanks for your time.
