### ISSUE TITLE
Editor.edit_file doesn't block if editor is 'gvim'

### ISSUE THREAD

**Issue by zblach** [pallets/click#580]
Feel free to close if this is a design feature, but gvim by itself doesn't block execution when invoked via shell process. The captured exit code (_termui_impl.py:405, in click 6.4) only tracks whether the editor failed to be invoked, rather than the exit code of the editor itself as it would be seen with 'vim'

If gvim is invoked with the -f flag, then it behaves as expected.

**Comment by blueyed** [comment]
AFAIK you are required to use `-f` when using `gvim`, and there is not much that click can do about it.
So this issue should get closed.

**Comment by fdavis** [comment]
Thanks @blueyed 
looks like you'll need to set `-f` to prevent it from forking just like when running `git commit`
https://stackoverflow.com/posts/3764528/revisions
