### ISSUE TITLE
getchar() fails to raise KeyboardInterrupt on Python3

### ISSUE THREAD

**Issue by mbr** [pallets/click#583]
On Python3 (click6.6), getchar() will just pass on Ctrl+C instead of raising a KeyboardInterrupt. I would assume this is because `ch == '\x03:` should be `ch == b'\x03'` in `_termui_impl.py`.

**Comment by jcrotts** [comment]
@mbr What platform were you on?

**Comment by davidism** [comment]
I reproduced this on Linux. It may have been happening on Windows as well, but it looks like #1108 addresses that incidentally.
