### ISSUE TITLE
testing.CliRunner.isolation(): Potential bug while trying to store the old process environment

### ISSUE THREAD

**Issue by jenisys** [pallets/click#586]
I stumbled over the following problem while inspecting the code (in the current repository HEAD).
It just does not look right that the new env-value is used to as env-key (name of the environment variable in the existing process environment).

CONTEXT: [click/testing.py#L216](https://github.com/pallets/click/blob/master/click/testing.py#L216)

``` python
# -- FILE: click/texting.py:213ff in method CliRunner.isolation()
       old_env = {}
        try:
            for key, value in iteritems(env):
                old_env[key] = os.environ.get(value)    #< PROBLEMATIC LINE: new value usage as env-key
                if value is None:
```

PROBABLY SHOULD BE:

``` python
               old_env[key] = os.environ.get(key)
```

**Comment by jsmedmar** [comment]
This has been fixed, should be closed: https://github.com/pallets/click/blob/master/click/testing.py#L216
