### ISSUE TITLE
add help to click argument

### ISSUE THREAD

**Issue by borismod** [pallets/click#587]
I would like to be able to specify help on positional arguments. 

``` Python

@click.group()
def cli():
    click.echo(u'shellfoundry - CloudShell shell command-line tool')
    pass

@cli.command()
@click.argument(u'name', help='Shell name to be created')
@click.argument(u'template', default=u'default', help='Template to be used')
def new(name, template):
    """
    Create a new shell based on a template.\r\n
    """
    NewCommandExecutor().new(name, template)
```

The above code throws the below exception:

> Traceback (most recent call last):
>   File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "C:\Python27\lib\runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "c:\work\GitHub\shellfoundry\shellfoundry__main__.py", line 6, in <module>
>     from bootstrap import cli
>   File "shellfoundry\bootstrap.py", line 36, in <module>
>     @click.argument(u'template', default=u'default', help='Template to be used')
>   File "C:\Python27\lib\site-packages\click\decorators.py", line 151, in decorator
>     _param_memo(f, ArgumentClass(param_decls, **attrs))
>   File "C:\Python27\lib\site-packages\click\core.py", line 1693, in __init__
>     Parameter.**init**(self, param_decls, required=required, **attrs)
> TypeError: **init**() got an unexpected keyword argument 'help'

**Comment by tony** [comment]
I just encountered this.

http://click.pocoo.org/6/documentation/

> Arguments cannot be documented this way. This is to follow the general convention of Unix tools of using arguments for only the most necessary things and to document them in the introduction text by referring to them by name.

Is this to say the best practice would be to document the argument in the docstring itself?

**Comment by Evidlo** [comment]
I think they mean to put a reference to the argument in the command long-help.  For example, heres a script with command `show` that accepts an argument `PATH`.
```
[evan@blackbox ~] ph show -h
Usage: ph show [OPTIONS] PATH

show the contents of an entry, where PATH is the entry path

optional arguments:
  -h, --help     show this help message and exit
  --field FIELD  show the contents of a specific field as plaintext
```

So in this case you'd want to use both `help` and `short_help`, where `short_help` is a shorter command description that doesn't contain information about `PATH`.

**Comment by hadsed** [comment]
Please do, I've also just been hit with this.

**Comment by Nukesor** [comment]
Would love to see this feature as well!

**Comment by davidism** [comment]
As the docs quoted earlier say, Click intentionally does not implement this.

**Comment by vesche** [comment]
I know this is closed, but I'll just +1 this feature request. It could be completely optional.

I'm making a project right now where this would be really helpful.
