### ISSUE TITLE
Would you add an option for better handling default value

### ISSUE THREAD

**Issue by c-bata** [pallets/click#588]
Hi, this is awesome library.

When I create command line interface using click, it's difficult to handle default value.
For example, creating CLI for `run` function like:

```
import click

def run(msg='Hello'):
    print('-- this is run func')
    print(msg)

@click.command()
@click.option('--msg', help='Number of greetings')
def hello(*args, **kwargs):
    print('-- this is hello func')
    print(kwargs)
    run(*args, **kwargs)

if __name__ == '__main__':
    hello()
```

And running it:

```
$ python click_test.py 
-- this is hello func
{'msg': None}
-- this is run func
None
```

This problem's simple solution is add default option like `default="Hello"` in `click.option`. But it's a duplicate with run function's default value.

Other solution is delete option when option doesn't input like:

```
@click.command()
@click.option('--msg', help='Number of greetings')
def hello(*args, **kwargs):
    print('-- this is hello func')
    print(kwargs)
    if kwargs['msg'] is None:
        del kwargs['msg']
    run(*args, **kwargs)
```

But it's a pain to delete each option. So, I want a something good option for handling default value and making a previous example's output like:

```
$ python click_test.py 
-- this is hello func
{'msg': None}
-- this is run func
Hello
```

Would you consider that?

**Comment by untitaker** [comment]
Can't you do:

    MSG_DEFAULT = 'Hello'

    @click.command()
    @click.option('--msg', default=MSG_DEFAULT)
    def hello(msg):
        run(msg=msg)

IMO this problem often presents itself outside of Click as well, I don't think Click in particular should solve it.

**Comment by c-bata** [comment]
@untitaker Thanks for your opinion.
As you mentioned, this isn't good proposal very much.
I close this issue.
