### ISSUE TITLE
Send help text through $PAGER when it won't fit in one terminal screen

### ISSUE THREAD

**Issue by b-jazz** [pallets/click#592]
I'm always thankful when a program dumps help text through PAGER, and only when it is longer than one terminal screenful. Is there any reason not to have Click take care of this automatically for the user, maybe with an option to turn it off.

**Comment by untitaker** [comment]
You can probably implement this behavior yourself by overriding some methods on `Command`, but I really don't think the user would *expect* this sort of behavior.

**Comment by forkbong** [comment]
You can use something like that: 

```python
def echo(data):
    """Print message to stdout or via a pager if it doesn't fit on screen."""
    _, terminal_lines = click.get_terminal_size()
    # Plus one line for the prompt
    if data.count('\n') + 1 >= terminal_lines:
        click.echo_via_pager(data)
    else:
        click.echo(data)
```

FWIW git does this so I've started to expect it :)

**Comment by untitaker** [comment]
You can also `export LESS=-F`.

**Comment by jcrotts** [comment]
There is a good implementation of this posted above. Closing this since there is a good work around, happy to review docs or implementation PRs.
