### ISSUE TITLE
KeyboardInterrupt while testing

### ISSUE THREAD

**Issue by voronin-opensoft** [pallets/click#595]
Python 2.7
click 6.6

How to emulate keyboard interrupt in testing inove? "\x03" doesn't work.
```python
runner = CliRunner()
runner.invoke(cli, command, input='ENTER\nENTER\n\x03')
```

**Comment by untitaker** [comment]
Please use StackOverflow for questions.

**Comment by untitaker** [comment]
Locking because of https://github.com/pallets/click/issues/596
