### ISSUE TITLE
Add Date-related parameter types

### ISSUE THREAD

**Issue by numbsafari** [pallets/click#603]
I apologize if this is the wrong way to open this up, I went to the IRC channel and posted there but did not really get any response.

Many of the scripts I write have date options, e.g.:

```
$ my-app import-task --start-date=2015-01-01 --end-date=2016-01-01
$ my-app import-task --date=2015-01-01 --lookback=3days
$ my-app import-task --lookback=1week
```

- Explicit dates/times.
- `timedelta`s
- Defaults settable to `now`/`utcnow`

I think this would be pretty trivial to add, focused strictly on the built-in `datetime` package. One could take advantage of other date parsing utility libraries, but that would add dependencies that might not be needed by others.

I'm willing to make a PR for this, just wanted to get a bit of feedback or a nod before submitting something from left field. Also, if you think simple "DateType" support would be better as a `click-contrib` package, and I'll go that route.

**Comment by ddaws** [comment]
I agree that this is a common use case. I am also willing to contribute, and am curious if the correct route is to submit a PR or create a click-contrib package.

**Comment by ddaws** [comment]
I have created a repo called `click-datetime` and have started working on supporting Datetime objects. @numbsafari I sent you an invite as a contributor to the repo.

**Comment by untitaker** [comment]
I think a better path for now would be click-contrib. I can invite either of you as member such that you can create your own repos there (and transfer existing ones).

**Comment by ddaws** [comment]
@untitaker sounds good. I have created https://github.com/ddaws/click-datetime and will migrate to click-contrib when added.

**Comment by untitaker** [comment]
Done

**Comment by ddaws** [comment]
@untitaker should this issue be closed because this functionality is now available via a contrib package?

**Comment by untitaker** [comment]
Yes, thanks for the reminder.

**Comment by Jaza** [comment]
@ddaws - thanks for contributing `click-datetime`, was looking for exactly this (and I kinda expected it to be in Click core, but hey, dates / times can get complicated, so maybe it's better in a separate project), will give it a try now.

**Comment by ddaws** [comment]
@Jaza glad it's useful to you. It is very minimal so please let me know if there is any functionality you would like to see added :)
