### ISSUE TITLE
Why are long/double data types not defined?

### ISSUE THREAD

**Issue by testn** [pallets/click#609]
Hi

Is there any specific reason why long/double data types are not defined? What if I need to parse an argument that requires 64-bit support?

**Comment by testn** [comment]
@untitaker Do you happen to know the reason behind that?

**Comment by jcrotts** [comment]
Double is not a supported type in Python. Int and long were unified in this PEP https://www.python.org/dev/peps/pep-0237/  So that is probably why it was included.
In python ints are arbitrary precision (unless you are using the scistack).

Is there a specific use case you are trying to target?

**Comment by untitaker** [comment]
OP is clearly confused about the nature of ints and floats in Python, I propose we close this issue.
