### ISSUE TITLE
Better redirect to http://click.pocoo.org/6/ ?!

### ISSUE THREAD

**Issue by marble** [pallets/click#614]
At the moment http://click.pocoo.org/ redirects to http://click.pocoo.org/5/ - not showing there's a '6'!

Redirect http://click.pocoo.org/ to http://click.pocoo.org/6/ would be better I guess.

PS: Keep on with the cool stuff you're doing :-))
PPS: Yes, I see, this #614 is (kind of) duplicate of #503, #597

**Comment by r-m-n** [comment]
#503

**Comment by untitaker** [comment]
Duplicate of https://github.com/pallets/click/issues/503
