### ISSUE TITLE
Running doctest on functions using click

### ISSUE THREAD

**Issue by asmodehn** [pallets/click#620]
The main module of a package I am developing has a structure like : 
```
[...]
@click.group()
def cli():
    pass

@cli.command()
@click.option('-h', '--host', default=None)
@click.option('-p', '--port', default=None)
def run(host, port):
"""
>>> run('127.0.0.1','8080')
"""
[...]

if __name__ == '__main__':
    cli()
```

When trying to run doctest from pycharm : 
```
/usr/bin/python2.7 /opt/alexv/pycharm-community-2016.2/helpers/pydev/pydevd.py --multiproc --qt-support --client 127.0.0.1 --port 37642 --file /opt/alexv/pycharm-community-2016.2/helpers/pycharm/docrunner.py /home/alexv/rostful/rostful/__main__.py
Testing started at 오후 7:43 ...
Connected to pydev debugger (build 162.1237.1)
warning: Debugger speedups using cython not found. Run '"/usr/bin/python2.7" "/opt/alexv/pycharm-community-2016.2/helpers/pydev/setup_cython.py" build_ext --inplace' to build.
pydev debugger: process 11882 is connecting

Usage: docrunner.py [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  run  Start rostful server.

Process finished with exit code 0
Empty test suite.
```

It would be pretty awesome to be able to doctest commands build with click easily.
Is there an example of how to do this somewhere ?

The only way I found to get docrunner to detect my test on `run()` here, is to : 

- not call `cli()`
- comment all my decorators for the `run()` method

Thanks for the help !

**Comment by untitaker** [comment]
I don't think this should happen from within Click.
IMO doctest is barely good enough for testing pure libraries, I can't see much value in using it for entire stateful applications. A normal CLI-test sets up a temporary directory for your application's configuration files, and with doctest, this is not doable in an elegant way unless Click would specifically support it.

This rather seems like a good candidate for https://github.com/click-contrib
