### ISSUE TITLE
How about a `click.required_option` alias?

### ISSUE THREAD

**Issue by wagnerluis1982** [pallets/click#621]
In my projects I use an alias `required_option` defined with code:

```python
required_option = functools.partial(click.option, required=True)
```

This very simple issue propose to include this neat alias to the core. This way we know instantly the required and non-required options, for example:

```python
@click.command()
@click.required_option('--username')
@click.option('--retries', default=1)
def main(username, retries):
    ...
```

**Comment by untitaker** [comment]
I don't see a need for this to be in Click itself.
