### ISSUE TITLE
TypeError: Options cannot have nargs < 0

### ISSUE THREAD

**Issue by matejaputic** [pallets/click#622]
I'd like to add an option that can take a variable number of values, for example:

`./command --opt 1 2 3` or `./command --opt 1 2 3 4 5 6 7`

could be equally valid. I tried doing this by setting `nargs=-1` but I get the above error.

Is there any way to use callbacks to make this happen? 

Side note: How do we tell that we've parsed the last option value and that the next value is an argument? 

One way could be to separate option values with a delimiter, like a comma, and then the first argument would be proceeded by a space, for example. I can imagine this custom behavior could be defined in a callback, but I need some help getting started.

**Comment by ZenithDK** [comment]
Could you paste the code in question so we can help see if there's errors in your code?
