### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by ZenithDK** [pallets/click#624]
I see a lot of questions, suggestions and comments in the issue tracker - maybe it would be an idea to move this away to a https://www.discourse.org/ discussion forum and have the issue tracker be for identified tasks/bugs?

Just a suggestion to help you cut down on the amount of issues.

**Comment by ZenithDK** [comment]
And I would suggest making it easier to find this: https://github.com/pallets/click/blob/master/CONTRIBUTING.rst

It has links to StackOverflow (you should modify it to point to the "click" tag) - and also IRC (which I tried locating earlier but couldn't).

**Comment by untitaker** [comment]
CONTRIBUTING.rst is linked when creating a new issue, but it doesn't keep people from hijacking the issue tracker. StackOverflow should suffice.

**Comment by ZenithDK** [comment]
It links to CONTRIBUTING.rst, yes - but the link text says "Please review the guidelines for contributing to this repository."

I think it would work better if it was stated more explicitly? Just my 0.02$

**Comment by untitaker** [comment]
We can add the same stuff to the issue template.

On 3 August 2016 19:47:28 CEST, Lasse Bigum <notifications@github.com> wrote:
>It links to CONTRIBUTING.rst, yes - but the link text says "Please
>review the guidelines for contributing to this repository."
>
>I think it would work better if it was stated more explicitly? Just my
>0.02$
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/click/issues/624#issuecomment-237306092

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
Renamed issue... I think a template is sufficient.

**Comment by fdavis** [comment]
I agree we should standardize on issue templates, feature requests, and where we should discuss things and that they should all be reachable from the README.rst.
cc @davidism

**Comment by davidism** [comment]
Copy the ones from Flask.
