### ISSUE TITLE
Why does Click pass None for unset options?

### ISSUE THREAD

**Issue by simonvanderveldt** [pallets/click#627]
This seems like the same issue/an extension of #588

I'm making a CLI around an existing module which already has some defaults in it's arguments.
I didn't expect it but Click apparently always passes `None` for options if they are not set, instead of not passing them at all which is what I expected.

How can I best do this? Checking if an option `== None` doesn't really sound good.
Is there anything that can be done to enhance this?

**Comment by untitaker** [comment]
Not really, as I haven't noticed anybody else complaining about this sort of behavior I'd say there's no need for Click to change.

I wouldn't map an existing internal API 1:1 anyway and always create a wrapper function. Otherwise you can't set proper help output, for example.

**Comment by jrobeson** [comment]
this is kind of annoying when trying to migrate beets to click with our optparse compatibility layer. We were hoping not to have to change any of the internals, but we still might have to now :(
