### ISSUE TITLE
Bash completion for arguments not working

### ISSUE THREAD

**Issue by xificurC** [pallets/click#628]
Option arguments don't seem to show up after hitting tabs after a dash, while the documentation says option arguments get completed. Here is a stripped down example:

`$ cd test`
`$ virtualenv .test`
`$ . ./.test/bin/activate`
`$ cat tester.py`

```python
import click

@click.command()
@click.option('--hi', help='hi')
def cli(hi):
    click.echo(hi)
```

`$ cat setup.py`

```python
from setuptools import setup

setup(
    name = 'tester',
    version = '0.1',
    py_modules = ['tester'],
    install_requires = [
        'Click',
    ],
    entry_points = """
    [console_scripts]
    tester=tester:cli
    """,
)
```

`$ pip install --editable .`
`$ _TESTER_COMPLETE=source tester > tester-complete.sh`
`$ . tester-complete.sh`
`$ tester --<TAB><TAB>` <-- doesn't show the `hi` option.

`$ python --version`
`Python 3.4.3`

`$ pip list | grep click`
`click (6.6)`

`$ bash --version`
`GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)`

`$ cat tester-complete.sh`

```bash
_tester_completion() {
    COMPREPLY=( $( env COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   _TESTER_COMPLETE=complete $1 ) )
    return 0
}

complete -F _tester_completion -o default tester;
```

The command otherwise works fine.
`$ tester --help`

```
Usage: tester [OPTIONS]

Options:
  --hi TEXT  hi
  --help     Show this message and exit.
```

`$ tester --hi there`
`there`

**Comment by pgkelley4** [comment]
I ran into this issue too and wasted time fixing it before I saw this :(

I think it only happens when you chain commands more than 2 levels though. I'm going to upload a PR that has a unit test that fails without the fix. I also added a unit test that succeeds before the fix with your example xificurC.

**Comment by xificurC** [comment]
@pgkelley4 hehe, that happens. Thanks for the unit tests!

**Comment by untitaker** [comment]
Closed with https://github.com/pallets/click/commit/8af7ec14f3d936e02c2e4ee62d3573593868e07e
