### ISSUE TITLE
Should `pass_context` be updating `co_argcount`? 

### ISSUE THREAD

**Issue by j2kun** [pallets/click#631]
After upgrading from click 4.1 to click 6.6 (python 3.5, which may be relevant), I started getting a strange error message:

```
$ my_click_program
/path/to/project/venv/lib/python3.5/dist-packages/click/core.py:874: Warning: Invoked legacy parameter callback "<function my_function at 0x7f3004ecfd08>".  The new signature for such callbacks starting with click 2.0 is (ctx, param, value).
  value, args = param.handle_parse_result(ctx, opts, args)
```

I tracked this down to a CLI argument callback function that was wrapped with `@pass_context`. The quick fix is to remove that decorator, but in the interest of finding a root cause, I noticed that `@pass_context` appears to update the wrapped function metadata incorrectly. Specifically, the callback invoker looks for `callback.__code__.co_argcount` and expects it to be either completely missing or at least 3. Passing a callback through `pass_context` wipes away the argcount.

```
ipdb> n
> /path/to/project/venv/lib/python3.5/site-packages/click/decorators.py(19)pass_context()
     17     def new_func(*args, **kwargs):
     18         return f(get_current_context(), *args, **kwargs)
---> 19     return update_wrapper(new_func, f)
     20 
     21 

ipdb> g = update_wrapper(new_func, f)
ipdb> g
<function my_function at 0x10860bea0>
ipdb> g.__code__
<code object new_func at 0x107947270, file "/path/to/project/venv/lib/python3.5/site-packages/click/decorators.py", line 17>
ipdb> g.__code__.co_argcount
0
ipdb> f.__code__.co_argcount
3
```

I don't know enough about Python to tell whether this is a bug in the `update_wrapper` function or a bug in click, or neither. It's clear that I shouldn't have placed `pass_context` on the callback in the first place, but I thought I'd let you folks know, in case it actually is a bug in click.

**Comment by untitaker** [comment]
You should not have to use `pass_context` in that way since the context is already passed for parameter callbacks.

It might be that this applies for your own pass decorators (`make_pass_decorator`), but I'm not sure if those work in this context anyway.

**Comment by j2kun** [comment]
@untitaker I know now that I shouldn't use it, but this was some old code that I didn't even write, and for whatever reason in click 4.1 it produced no warning message. 

> It might be that this applies for your own pass decorators (make_pass_decorator), but I'm not sure if those work in this context anyway.

I don't know what `make_pass_decorator` is. From my perspective, `click` is expecting some attribute on a function to be properly set, and this is an instance where click code unsets that data. Now that I think about it, it seems reasonable that `update_wrapper` can't know what the new argument count will be (in this case it's increased by 1 based on logic unknownto `update_wrapper`), so `pass_context` should be responsible for updating the `co_argcount`. Maybe a line like the following is enough:

```
g = update_wrapper(new_func, f)
g.__code__.co_argcount = 1 + f.__code__.co_argcount
return g
```

**Comment by untitaker** [comment]
This warning happens because the click decorators don't modify the function signature such that the wrapper function matches the wrapped one. Python still lacks a clean way to do this: http://blog.dscpl.com.au/2014/01/how-you-implemented-your-python.html

**Comment by davidism** [comment]
I don't think this is relevant any more. The legacy behavior you were seeing a warning about is removed in 8.0. `pass_context` seems to work correctly. If you have a reproducible example I can take a look again.
