### ISSUE TITLE
custom argument parser

### ISSUE THREAD

**Issue by michaelshobbs** [pallets/click#633]
Not sure if this is the correct place for questions; as this probably isn't an "issue" per se. In any case, is it possible to pass all arguments on a particular command to a custom arg parser?

I'm having difficulty parsing the following input example:
```
click_cmd var1=value var2="quoted with space value"
```

Any direction would be greatly appreciated!

**Comment by untitaker** [comment]
As per the [contributing file](https://github.com/pallets/click/blob/master/CONTRIBUTING.rst#support-questions), please use StackOverflow for questions.

What is wrong with normal (`--`-prefixed) options though?

**Comment by michaelshobbs** [comment]
Ah didn't even think to look at the contributing doc. Sorry about that.

Yeah I thought about multiple `--config` options but wasn't a fan of that UI.

**Comment by untitaker** [comment]
I'll close this since the question is answered.
