### ISSUE TITLE
Contexts not shared if a function installed as entry_points

### ISSUE THREAD

**Issue by eromoe** [pallets/click#634]
My code like below :

```
@click.group(invoke_without_command=True)
@click.option('--dbpath')
@click.pass_context
def cli(ctx, dbpath):
    db = init_db(dbpath)
    ctx.obj['db'] = db 
    ctx.db = db 
    return ctx
```

```
@cli.command()
....
@click.pass_context
def check(ctx, **kwargs):
    ....
    run_check(ctx.obj['db '], urls)

def pmain():
    cli()

def pcheck():
    check()

```

And I write a setup with entry_points:

```
    entry_points={
        'console_scripts': [
            'pcheck=app.run:pcheck',
            'pmain=app.run:pmain'
        ]
    },
```

if I run `pcheck`, I got error because `ctx.ob` and `ctx.parent` are None. 
But `pmain check` works.

I'd like initiate a lot of things in `cli`, then reuse in child command,  how can I make `pcheck` work as entry_points?

**Comment by davidism** [comment]
Running `pcheck` means you didn't run `pmain`, so `pmain` was never able to put anything in the context. You'll need to set up defaults for the context, either in the command or when calling it.

```python
def pcheck():
    db = get_default_connection()
    check(obj={"db": db})
```
