### ISSUE TITLE
Python 2.7: py2exe 0.6.9 bundling with click 6.6 fails

### ISSUE THREAD

**Issue by carlescufi** [pallets/click#635]
Bundling a script with py2exe 0.6.9 that contains click 6.6 seems to fail to run:

https://github.com/pallets/flask/issues/1966
https://github.com/NordicSemiconductor/pc-nrfutil/issues/9

Using an earlier version of click (5.1) seems to fix the issue

**Comment by jcrotts** [comment]
Are you still trying to do this with a recent version of click? I don't think the py2exe package has been updated since 2014, so it may not be something we could support anyway.

**Comment by carlescufi** [comment]
@jcrotts I'm not, no. This was a while back, I haven't tried recently, fine with you closing this.

**Comment by jcrotts** [comment]
Nice, sorry it was stale for so long!
