### ISSUE TITLE
Support for interactive mode

### ISSUE THREAD

**Issue by fluffybeing** [pallets/click#64]
An interactive mode for click in which the user is presented with a separate command shell will make it more user friendly and the command plugins available from the command line are automatically configured as commands within the shell.

For example.

``` shell
$ ClickDemo
(ClickDemo) help
```

**Comment by liviobait** [comment]
Hello, no news on this functionality?

**Comment by edusantana** [comment]
@mitsuhiko where is this separate package?

**Comment by davidism** [comment]
https://github.com/click-contrib/click-repl
