### ISSUE TITLE
Export option arguments to help string for string interpolation

### ISSUE THREAD

**Issue by dev-zero** [pallets/click#640]
I usually have a default value for options, for example something like this:

```python
@click.option('--uuid', '-u', type=click.UUID,
              default='73be5ec6-44d5-4410-88f6-51aa23c1a1dd',
              help='calendar UUID (default: 73be5ec6-44d5-4410-88f6-51aa23c1a1dd)')
```

Instead of having to repeat it or factor it out into a separate variable, it would be much easier if click would export the arguments directly to the help string as a dict for interpolation, such that one could write:

```python
@click.option('--uuid', '-u', type=click.UUID,
              default='73be5ec6-44d5-4410-88f6-51aa23c1a1dd',
              help='calendar UUID (default: {default})')
```

... or did I miss something in the documentation of click?

**Comment by joeleong** [comment]
is `click.Option`'s `show_default` parameter sufficient?

ex:
``` python
@click.option('--uuid', '-u', type=click.UUID,
              default='73be5ec6-44d5-4410-88f6-51aa23c1a1dd',
              show_default=True,
              help='calendar UUID')
```

**Comment by dev-zero** [comment]
Sure, but it seems undocumented, see also #646.

**Comment by untitaker** [comment]
Okay, then I think it makes sense to close this issue as duplicate.
