### ISSUE TITLE
Progress bar should advance at end of loop

### ISSUE THREAD

**Issue by jdno** [pallets/click#651]
I'm using the progress bar with a piece of code like this:

``` python
with click.progressbar(some_list) as bar:
    for element in bar:
        element.long_calculation
```

It seems that the progress bar updates every time it enters the loop, which for the last element means the bar shows everything has been completed, although the last computation just started. It would be great if it would show the progress in terms of results, not as an iterator.

I looked briefly at the implementation in [_termui_impl.py](https://github.com/pallets/click/blob/master/click/_termui_impl.py), but the rendering seems to be closely linked to the `pos` attribute and I don't feel comfortable to mess with that. 😒

**Comment by untitaker** [comment]
This just seems like a off-by-one error to me.

**Comment by jdno** [comment]
Might be. The ETA is definitely off by one.

Here is the small script I used to test this:
```python
import time

import click

@click.command()
@click.option('--count', default=1)
def test(count):
    with click.progressbar(range(count)) as bar:
        for x in bar:
            time.sleep(2)

if __name__ == '__main__':
    test()
```
