### ISSUE TITLE
Is there a way to call a decorated method directly?

### ISSUE THREAD

**Issue by ws1088** [pallets/click#657]
```
@click.command()
def a():
    pass

@click.command()
def b():
  return a()

main.add_command(a)
main.add_command(b)
if __name__ == '__main__':
    main()
```

Hi, is the above possible? I got some bogus error saying that there is an extra argument 'b' while running myprogram.py b

```
Usage: myprogram.py [OPTIONS]

Error: Got unexpected extra argument (b)
```

**Comment by untitaker** [comment]
Please search the closed issues before opening a new one, also this belongs on StackOverflow rather than the issue tracker.

On 19 September 2016 11:18:46 CEST, ws1088 <notifications@github.com> wrote:
>```
>@click.command()
>def a():
>    pass
>
>@click.command()
>def b():
>  return a()
>
>main.add_command(a)
>main.add_command(b)
>if __name__ == '__main__':
>    main()
>```
>
>Hi, is the above possible? I got some bogus error saying that there is
>an extra argument 'b' while running myprogram.py b
>
>```
>Usage: myprogram.py [OPTIONS]
>
>Error: Got unexpected extra argument (b)
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/click/issues/657

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
