### ISSUE TITLE
Can't use inspect.getsourcelines() for defined commands

### ISSUE THREAD

**Issue by ghost** [pallets/click#658]
version: 6.6

I'm just playing with my own API documentation generator, where I use the standard `inspect` module for getting an object location (`inspect.getsourcelines(object)`) in a file. It works fine for everything except my defined commands, where I got the following traceback:

```
TypeError: <click.core.Group object at 0x7f6dfedb0a58> is not a module, class, method, function, traceback, frame, or code object
```

when calling: (example)

``` python
# Sample file

import inspect

import click


@click.command()
def function_name():
    some_codes


inspect.getsourcelines(function_name)
```

**Comment by jcrotts** [comment]
This is not an issue with click, but an issue with the usage of inspect.https://stackoverflow.com/questions/43506378/how-to-get-source-code-of-function-that-is-wrapped-by-a-decorator for some background on a similar problem.
