### ISSUE TITLE
missing file exception.py in click package Version 6.6

### ISSUE THREAD

**Issue by dijoje** [pallets/click#660]
Hello,

after an upgrade of Ubuntu 14.04.5 LTS (Python 3.4) my Flask application did not run. The error was 

> 'module' object has no attribute 'UsageError'

exception.py was not in the click directory, after download this file from here (GIT), my application starts and everything was fine. 

Thanks for your work,
Dirk

**Comment by untitaker** [comment]
I'm not sure what to do. Where did you download Click previously?

**Comment by dijoje** [comment]
First I installed flask from the Ubuntu 14.04 LTS repository, everything fine. Then after a package update of Ubuntu last week I get the described problem. First I try to update click with pip3 with no success.

So I guess that the file is missing in the repository: https://launchpad.net/ubuntu/trusty/amd64/python3-click/0.4.21.1 . In the Python package (https://pypi.python.org/pypi/click/6.6) is the file included. 

Maybe pip3 did not install the file. So I think it seems to be a problem of Ubuntu 14.04.

Sorry and best regards,
Dirk

**Comment by ThiefMaster** [comment]
That click version looks ancient. Two-year-old ancient. I guess another reason why using your distro's package manager is not a good idea for Python stuff. I'd rather use a virtualenv and then install the latest versions of click, flask, etc. in there.

**Comment by dijoje** [comment]
Okay, thank you for your help

**Comment by untitaker** [comment]
Apparently latest Ubuntu's `python3-click` is this Click: http://packages.ubuntu.com/xenial/python3-click
