### ISSUE TITLE
CliRunner and multiple inputs

### ISSUE THREAD

**Issue by mandeep** [pallets/click#666]
Hi all,

When using something like:

```
@click.command()
@click.password_option()
def cli(password): ...
```

It is not possible to test both the first Password prompt, and its confirmation prompt with CliRunner. CliRunner will enter the first input, but then the confirmation prompt remains unnoticed. Is there something else that needs to be used with CliRunner, or is this behavior unintended?

**Comment by jkarimi91** [comment]
I am wondering the same thing; is it not possible to pass multiple inputs to the `CliRunner`?

**Comment by jcrotts** [comment]
It is possible to pass multiple inputs to CliRunner see the [docs](http://click.pocoo.org/5/testing/)
If you are still having issues could you post a specific verifiable example and re-open the issue.

**Comment by mandeep** [comment]
@jcrotts this is an example taken from the docs:

```
import click
from click.testing import CliRunner


def test_encrypt():
    @click.command()
    @click.password_option()
    def encrypt(password):
        click.echo('The password is {}' .format(password))

    runner = CliRunner()
    result = runner.invoke(encrypt, input='ABC')
    assert result.exit_code == 0
    assert result.output == 'ABC'
```

When the test runs, the input hangs. I'm unsure if this is the same scenario I ran across back in 2016 but hopefully it puts us on the right track.

**Comment by kevindawson** [comment]
how to test:
 @click.password_option()
yes please @jcrotts
