### ISSUE TITLE
click.testing CliRunner(): How do I pass a ctx to CliRunner()?

### ISSUE THREAD

**Issue by benjaminweb** [pallets/click#670]
SUPPORT QUESTION
Python 3.5.2
Click 6.6

I write this issue after getting no reaction on #pocoo and #python.
I am aware of violating in a way [guidelines for contributing](https://github.com/pallets/click/blob/master/CONTRIBUTING.rst).

A [search](https://github.com/search?l=Python&q=CliRunner+ctx&ref=searchresults&type=Code&utf8=✓) for `CliRunner` and `Context` on github did not recover any piece of code I could borrow from.

The nearest would be [this](https://github.com/hgschmie/gcontainer/blob/a7337253237c83376871835630b84012c01801fd/tests/test_context.py#L24-L38).

click's documentation did not deliver any help to the point: [here](http://click.pocoo.org/6/api/#click.Context.invoke) and [here](http://click.pocoo.org/6/complex/#complex-guide)

It's not a problem to set up a context. It's not a problem to invoke a command in it.
But it's a problem (for me) to get a result object for further assertion statements — like CliRunner() does.

**How can I pass a ctx (Context) to CliRunner?**

`CliRunner` lists no parameter to provide a context in its [documentation](http://click.pocoo.org/5/api/#click.testing.CliRunner.invoke).

The following should qualify as a minimum working example.
The real problem is a bit different.
It could be solved by moving the click decorated function into its own function for test coverage. Then the click function would be rendered almost useless.

```
import click
from click.testing import CliRunner

class Config():
    def __init__(self):
        self.value = 651

@click.command()
@click.pass_context
def print_numberinfo(ctx):
    if not hasattr(ctx.obj, 'value'):
        ctx.obj = Config()
    click.echo(ctx.obj.value)

def test_print_numberinfo():
    ctx = click.Context(print_numberinfo, obj = Config())
    ctx.obj.value = 777
    runner = CliRunner()
    # how do I pass ctx to runner.invoke?
    result = runner.invoke(print_numberinfo)
    assert result.output == str(ctx.obj.value) + '\n'```

**Comment by fmichea** [comment]
Hey,

I'm not involved with the project but I was wondering how to do this too and found a work around you might be able to adapt to your use case. In my case I wanted to initialize `ctx.obj` and get that value back.

Here is what it looks like:

```
@pytest.fixture
def hs_cmd():
    ctx_obj = dict()

    @click.group()
    @click.pass_context
    def main(ctx):
        ctx.obj = ctx_obj

    @main.command('cmd')
    @some_custom_argument_adder
    def cmd():
        pass

    def invoker(args):
        args = shlex.split('cmd ' + args)
        return (click.testing.CliRunner().invoke(main, args), ctx_obj)

    return invoker
```

Then to use it I do:

```
result, ctx = hs_cmd('--opt ...')
```

Hope that helps you get in the right direction

**Comment by untitaker** [comment]
First of all:

>I write this issue after getting no reaction on #pocoo and #python. I am aware of violating in a way guidelines for contributing.

Still rude.

You can pass `obj=Config()` to `runner.invoke`, but passing context is not supported.

**Comment by benjaminweb** [comment]
You are right, @untitaker I should have posted it directly on StackOverflow:

http://stackoverflow.com/questions/40443368

How do I pass the `obj=Config()` to `runner.invoke`?

The nearest would be [this](https://github.com/pallets/click/blob/30fc626263db82e9f339ca8810d207ab089d5575/tests/test_context.py#L173-L186) which I don't understand.

@untitaker can we get it right on StackOverflow including as a reference for other users?

(as I miss credits, I can't post all links on StackOverflow)

**Comment by untitaker** [comment]
I answered your question there.

**Comment by laixintao** [comment]
Met the same problem here, thanks!

**Comment by kakshay21** [comment]
Can we pass context now? @benjaminweb
