### ISSUE TITLE
Teardown code / code ran after execution

### ISSUE THREAD

**Issue by stevenroose** [pallets/click#677]
I noticed that all code after the call to the main group is no longer executed. This means that the click command code itself does an `os.exit()` or something. 

Is there a different way to specify code to be executed after the command is handled successfully?

If not, consider this a feature request.

**Comment by untitaker** [comment]
[ctx.call_on_close](http://click.pocoo.org/5/api/#click.Context.call_on_close)

**Comment by stevenroose** [comment]
Thanks, @untitaker. However, I get an error.

```python
@click.group()
@click.pass_context
def cli(ctx):
    ctx.call_on_close(_on_close())

def _on_close():
    print("test")

if __name__ == '__main__':
    cli()
```

When using any command, it does print "test", but it also throws this:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/click/core.py", line 699, in main
    ctx.exit()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 483, in exit
    sys.exit(code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/steven/git/cli/cli.py", line 293, in <module>
    fabricio()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 699, in main
    ctx.exit()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 330, in __exit__
    self.close()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 419, in close
    cb()
TypeError: 'NoneType' object is not callable
```

The mentioned line is the line with the main command (`cli()`).

**Comment by untitaker** [comment]
You have to pass the function, not its return value.

On 22 October 2016 13:24:35 CEST, Steven Roose <notifications@github.com> wrote:
>Thanks, @untitaker. However, I get an error.
>
>```python
>@click.group()
>@click.pass_context
>def cli(ctx):
>    ctx.call_on_close(_on_close())
>
>def _on_close():
>    print("test")
>
>if __name__ == '__main__':
>    cli()
>```
>
>When using any command, it does print "test", but it also throws this:
>```
>Traceback (most recent call last):
>File "/usr/lib/python3.5/site-packages/click/core.py", line 699, in
>main
>    ctx.exit()
>File "/usr/lib/python3.5/site-packages/click/core.py", line 483, in
>exit
>    sys.exit(code)
>SystemExit: 0
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "/home/steven/git/cli/cli.py", line 293, in <module>
>    fabricio()
>File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in
>__call__
>    return self.main(*args, **kwargs)
>File "/usr/lib/python3.5/site-packages/click/core.py", line 699, in
>main
>    ctx.exit()
>File "/usr/lib/python3.5/site-packages/click/core.py", line 330, in
>__exit__
>    self.close()
>File "/usr/lib/python3.5/site-packages/click/core.py", line 419, in
>close
>    cb()
>TypeError: 'NoneType' object is not callable
>```
>
>The mentioned line is the line with the main command (`cli()`).
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/click/issues/677#issuecomment-255522818

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
