### ISSUE TITLE
Unexpected exceptions with Context.call_on_close()

### ISSUE THREAD

**Issue by stevenroose** [pallets/click#678]
As suggested by @untitaker in #677, I used `Context.call_on_close()`. The code looks like this:
```python
@click.group()
@click.pass_context
def cli(ctx):
    ctx.call_on_close(_on_close())

def _on_close():
    print("test")

if __name__ == '__main__':
    cli()
```

When using anyof the defined commands, it does print "test", but it also throws these:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/click/core.py", line 699, in main
    ctx.exit()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 483, in exit
    sys.exit(code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/steven/git/cli/cli.py", line 293, in <module>
    fabricio()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/click/core.py", line 699, in main
    ctx.exit()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 330, in __exit__
    self.close()
  File "/usr/lib/python3.5/site-packages/click/core.py", line 419, in close
    cb()
TypeError: 'NoneType' object is not callable
```

The mentioned line is the line with the main command (`cli()`).

**Comment by untitaker** [comment]
You need to use `_on_close` instead of `_on_close`, since you're supposed to pass a function, not its return value.

**Comment by untitaker** [comment]
I intended to respond to your question in the other thread, but it seems reply-with-email doesn't properly work anymore.

**Comment by stevenroose** [comment]
Oh yeah of course, stupid mistake.

(I tried this by e-mail too)

**Comment by untitaker** [comment]
You need to pass the FUNCTION, not the result of its invocation to call_on_close. This means to drop the () in your code...

On 23 October 2016 11:24:53 CEST, Steven Roose <notifications@github.com> wrote:
>As suggested by @untitaker in #677, I used `Context.call_on_close()`.
>The code looks like this:
>```python
>@click.group()
>@click.pass_context
>def cli(ctx):
>    ctx.call_on_close(_on_close())
>
>def _on_close():
>    print("test")
>
>if __name__ == '__main__':
>    cli()
>```
>
>When using anyof the defined commands, it does print "test", but it
>also throws these:
>```
>Traceback (most recent call last):
>File "/usr/lib/python3.5/site-packages/click/core.py", line 699, in
>main
>    ctx.exit()
>File "/usr/lib/python3.5/site-packages/click/core.py", line 483, in
>exit
>    sys.exit(code)
>SystemExit: 0
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
>  File "/home/steven/git/cli/cli.py", line 293, in <module>
>    fabricio()
>File "/usr/lib/python3.5/site-packages/click/core.py", line 716, in
>__call__
>    return self.main(*args, **kwargs)
>File "/usr/lib/python3.5/site-packages/click/core.py", line 699, in
>main
>    ctx.exit()
>File "/usr/lib/python3.5/site-packages/click/core.py", line 330, in
>__exit__
>    self.close()
>File "/usr/lib/python3.5/site-packages/click/core.py", line 419, in
>close
>    cb()
>TypeError: 'NoneType' object is not callable
>```
>
>The mentioned line is the line with the main command (`cli()`).
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/click/issues/678

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
