### ISSUE TITLE
Seems to be no way to set the argument name separate from help string

### ISSUE THREAD

**Issue by BMBurstein** [pallets/click#685]
This is my use case:

```
@cli.command()
@click.argument('paths', 'path', nargs=-1, type=click.Path(writable=True, dir_okay=True))
def commit(comment, paths):
```

What i am trying to do is have the parameter name to the function be `paths`, but have the help text display:

```
Usage: cli commit [PATH]...
```

However, I only seem to be able to get one of these. Either the parameter name to the function is `path`, or the help text says `[PATHS]...`

**Comment by borgstrom** [comment]
You want `metavar`

```
@cli.command()
@click.argument('paths', metavar='PATH', nargs=-1, type=click.Path(writable=True, dir_okay=True))
def commit(comment, paths):
```

See: http://click.pocoo.org/6/api/#parameters

**Comment by BMBurstein** [comment]
I have to do
```
@cli.command()
@click.argument('paths', metavar='[PATH]...', nargs=-1, type=click.Path(writable=True, dir_okay=True))
def commit(comment, paths):
```
Which seems unnatural

**Comment by untitaker** [comment]
Sorry, but `metavar` is the way to go.
