### ISSUE TITLE
"hide_input" Option shows default value with "prompt=True"

### ISSUE THREAD

**Issue by xpac1985** [pallets/click#687]
Hey,
I'm pretty new to click and python, but I haven't found anything about this in the documentation.

I have a click option, that looks like
`@click.option("-p", "--password", default=lambda: config["password"] if "password" in config else "", required=True, prompt=True, hide_input=True)`

The `config["password"]` is sometimes being filled before by an earlier option, callback script etc - the point being, I hoped that this configuration would only lead to a prompt if default is None.
With the current configuration, it always prompts me, even with the default being set, and the prompt shows the default value, although hide_input is True.

I understand why this is most likely desired behaviour.
However - is there a way to work around this (only prompt for input if default is None)? Or better - fill a value for that option (that is not called default), that disables the prompting? Or did I understand something wrong? ;)

**Comment by ThiefMaster** [comment]
FYI, assuming `config` is a dict you can replace `config["password"] if "password" in config else ""` with `config.get('password', '')`

**Comment by xpac1985** [comment]
I changed it as follows:
`@click.option("-p", "--password", default=lambda: config["password"], required=True, prompt=("password" not in config), hide_input=True)`

This only enables the prompt if config has no value, meaning default will also be empty, meaning the prompt has to appear.
Everything's fine - found a good solution myself, but maybe this will help somebody else with the same problem ;-)
