### ISSUE TITLE
release 7.0

### ISSUE THREAD

**Issue by jsmedmar** [pallets/click#689]
Sure this is not an issue, but couldn't find another place to ask. When will be 7.0 released? I'm dying to use the `hide` option. I'd like to avoid installing from github!

Cheers and thank you for this amazing project.

**Comment by sirosen** [comment]
I think `hide` could be added safely to a 6.x release, unless the code has diverged so far that it's impossible.

If you don't need custom `click.Option` subclasses in your code, you can band-aid this.
This is the approach that I'm taking until this feature is released, and it's been working fine for several months now:

1. Define a custom `click.Option` subclass which provides the behavior of the `hide` parameter
```python
class HiddenOption(click.Option):
    """
    HiddenOption -- absent from Help text.

    Supported in latest and greatest version of Click, but not old versions, so
    use generic 'cls=HiddenOption' to get the desired behavior.
    """
    def get_help_record(self, ctx):
        """
        Has "None" as its help record. All that is needed.
        """
        return
```

2. Use it as the `cls` kwarg to your options to make them hidden

```python
@click.command('mycommand')
@click.option('--myflag', is_flag=True, cls=HiddenOption)
def mycommand(myflag):
    print('myflag: {}'.format(myflag))
```

3. Profit

**Comment by jsmedmar** [comment]
@sirosen I was exploring and there doesn't seem an easy way to do the same thing for `Command`, correct?

**Comment by sirosen** [comment]
@davidism, is this closed because 7.0 is being released shortly? Or just clearing the backlog?
I don't mind click maintainers trying to keep a clean backlog; just curious.


Also, @jsmedmar, I never noticed you `@mentioned` me -- sorry about that. I don't know of any easy way to make a hidden command type. You might have to hook into the help formatting system and define a custom help formatter to get that functionality.

**Comment by jsmedmar** [comment]
haha its been a while! looking forward to 7.0

**Comment by davidism** [comment]
7.0 is not being released right now, just cleaning these up since we already know people want releases.
