### ISSUE TITLE
same option description but different option name

### ISSUE THREAD

**Issue by cyboflash** [pallets/click#690]
I'm developing a tool which configures hardware registers. All the registers are pretty much the same, the only difference is their names.

Right now I have the following code
```
@cli.command()
@click.option('--r0', type=click.IntRange(-2, 0xffffffff, clamp=False), default=-2)
@click.option('--r1', type=click.IntRange(-2, 0xffffffff, clamp=False), default=-2)
@click.option('--r2', type=click.IntRange(-2, 0xffffffff, clamp=False), default=-2)
@click.option('--r3', type=click.IntRange(-2, 0xffffffff, clamp=False), default=-2)
@click.option('--r4', type=click.IntRange(-2, 0xffffffff, clamp=False), default=-2)
def mydevice(r0, r1, r2, r3, r4):
    click.echo('mydevicel')
```

As you can see the only difference is the name. It would be nice to have a way to create multiple options like this using one line, just varying the names of options.

**Comment by ambv** [comment]
You can do that using `functools.partial` objects:
```
from functools import partial
r_option = partial(click.option, type=click.IntRange(-2, 0xffffffff, clamp=False), default=-2)

@click.command()
@r_option('--r0')
@r_option('--r1')
@r_option('--r2')
@r_option('--r3')
@r_option('--r4')
def mydevice(r0, r1, r2, r3, r4):
    ...
```

You could automate this further but remember, "explicit is better than implicit".

**Comment by untitaker** [comment]
Yeah you can remove repetition from every decorator call like that.
