### ISSUE TITLE
Need a way to run a function before a prompt

### ISSUE THREAD

**Issue by ashxjain** [pallets/click#691]
It'll be great to run a function before a prompt (menu-style).

Here's what i want:

Say a function f(), lists two columns: ID & ITEMS.

ID ITEMS
1   Item1
2  Item2

And there is a click prompt, which asks for an Item to be selected:

> Select an Item: 1

I need some functionality like the following with prompt api, which runs a function f before showing the prompt:
click.option('--item', prompt="Select an Item", **pre-callback=f**)

Is there a way to do this?

**Comment by bjinwright** [comment]
This would be helpful for me as well.

**Comment by daggemann** [comment]
What about removing the prompt, change the option to is_flag=True, and use a callback to handle the prompt for you? The selected item could then be stores in ctx.obj['selected_item'], and passed to the command using the @pass_context decorator.

**Comment by bjinwright** [comment]
I think what he's describing is something like this. 

https://gist.github.com/bjinwright/65c5a454a6c0cd028f8df6f6ba22c1de

**Comment by daggemann** [comment]
I did not think about using ctx.params, but that might be better. This is what I ended up with: [https://gist.github.com/daggemann/9ee62089b20741071c6966488cd91c98](url)
It is somewhat similar to that given in the documentation here: [http://click.pocoo.org/6/advanced/#parameter-modifications](url)

**Comment by jcrotts** [comment]
Could someone present a more specific use case for this? It seems like something that could be handled better with regular callbacks, additional options, or maybe custom decorators etc.

I think the concept of a pre-callback is confusing, and it feels somewhat redundant.

I'm going to close this, but if someone has a proposed implementation of this feature, or more clarity on some use cases it solves, happy to reopen.

**Comment by davidism** [comment]
Rather than prompting in the option, prompt in the command with `click.prompt()` after showing whatever you need to for the selection.
