### ISSUE TITLE
what I am doing wrong here

### ISSUE THREAD

**Issue by devcorn** [pallets/click#692]
I am trying click (Command line interface package for Python), while running the following code I get error `Error: No such command "abcd"`

```
@click.group()
@click.option('--source', required=True)
@click.pass_context
def cli(ctx, source):
    ctx.obj = "pass it"

@cli.command()
@click.argument('abcd')
@click.pass_context
def hello(ctx, abcd):
    click.echo("Hello, World")


if __name__ == '__main__':
    cli()
```
I am running it as follows

`python playclick.py --source this abcd`

**Comment by untitaker** [comment]
Please ask questions on StackOverflow.
