### ISSUE TITLE
PEP 484 stubs for Click 6.6 available on typeshed

### ISSUE THREAD

**Issue by ambv** [pallets/click#693]
Hi, just to let you know, I added Click support to typeshed which is used by Mypy and pytype for type definitions of third-party libraries that don't themselves provide type annotations.

Here's the relevant stubs: https://github.com/python/typeshed/tree/master/third_party/3.6/click

I created them by hand, following your sources pretty closely, which means they are pretty detailed. If there's anything that's missing or wrong, make sure to bug me on https://github.com/python/typeshed/issues.

Let me know if you have any concerns or questions. Thanks!

**Comment by untitaker** [comment]
LGTM at first glance, I apprechiate the effort!

**Comment by untitaker** [comment]
(I assume there isnt anything to do on our side, so Im going to close this)

**Comment by dfee** [comment]
I'm a little late to the party, but https://github.com/python/typeshed/blob/master/third_party/2and3/click/core.pyi#L281 should return a `typing.List[str]`, no?
