### ISSUE TITLE
stdout is not wrapped

### ISSUE THREAD

**Issue by nowox** [pallets/click#694]
With this example: 

```
#!/usr/bin/env python
import click

@click.command()
def main():
    line = ">" + ("*" * 500)
    print(line)
    click.echo(line)

if __name__ == '__main__':
    main()
```

I get this output where my line is not wrapped (so I cannot see all of it): 

```
$ tput cols
42
$ ./toto.py
>*****************************************
>*****************************************
```

I am rather expecting this: 

```
./toto.py
>********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
```

Is it a normal behavior?

**Comment by untitaker** [comment]
I cannot reproduce this, `tput cols` has no effect. Have you tried another terminal?

**Comment by nowox** [comment]
So it's a terminal dependent issue :( I am on Cygwin/[mintty](https://github.com/mintty/mintty)). 

I haven't tried it on another terminal. 

What could possibly be the cause of this issue?

**Comment by untitaker** [comment]
You should try another terminal, or check if this issue occurs with other programs as well.

However, I'm going to close this because I don't think this is an issue with Click.
