### ISSUE TITLE
enable -h as an alias for --help

### ISSUE THREAD

**Issue by crustymonkey** [pallets/click#700]
Maybe I'm just not finding this in the docs, but is there a way to enable `-h` as an alias for `--help`?  If not, could this option be added?

**Comment by rbonthond** [comment]
CONTEXT_SETTINGS = {'help_option_names': ['-h', '--help']}
@click.group(context_settings=CONTEXT_SETTINGS)

**Comment by crustymonkey** [comment]
Awesome, thanks Robin.

**Comment by remort** [comment]
What if i generate completion file during package build ? Could you add this functionality in the app ?
