### ISSUE TITLE
implicit action of empty [console_scripts]

### ISSUE THREAD

**Issue by LuisBL** [pallets/click#707]
I'm reading a project that use click and I did not understand how setuptools integration works, I've read the doc on http://click.pocoo.org/5/setuptools/
 
I can't found in the documentation what is the behavior of `[console_scripts]` with an empty body (without e.g. `yourscript=yourscript:cli` line) ::

    entry_points="""\
      [console_scripts]
      """,

Here is my setup::

    setup(
      name='app',
      packages=find_packages(),
      include_package_data=True,
      zip_safe=False,
      install_requires=None,
      # http://click.pocoo.org/5/setuptools/
      entry_points="""\
      [console_scripts]
      """,)

**Comment by untitaker** [comment]
An empty `[console_scripts]` doesn't do anything (it is equal to the default setting). But I don't see that in the docs you link? There's always a script defined right below.

**Comment by untitaker** [comment]
Also I think this question is better suited for StackOverflow or IRC.
