### ISSUE TITLE
click.testing should not patch stdout and stderr to the same StringIO

### ISSUE THREAD

**Issue by Julian** [pallets/click#708]
https://github.com/pallets/click/blob/d3f36e884e18f374c3e4e6cf062ba19f100d0fd6/click/testing.py#L167

It probably also shouldn't touch either of these if they've already been patched externally, e.g. if `sys.stdout != sys.__stdout__` or `sys.stderr != sys.__stderr__`, as was my case (I had passing tests that started to fail when click started overriding my patches, so now I have to un-override them even later than that with some really really ugly code).

**Comment by Julian** [comment]
#371 seems relevant, but not exactly a dupe. Even if there wasn't separate attributes on the result object (which I am not using), it'd be nice if click didn't make accessing output more difficult.

**Comment by untitaker** [comment]
Could you elaborate why ``sys.stdout is sys.stderr`` is a problem for you?

> It probably also shouldn't touch either of these if they've already been patched externally

That behavior will also be problematic, all test runners do this.

**Comment by Julian** [comment]
Yes, sorry.

I have tests for an app that makes assertions about stdout and stderr. After porting it to click, now I have to write:

```
        class Fixed(object):
            def __getattr__(self, attr):
                return getattr(real_main, attr)

            def main(this, *args, **kwargs):
                stdout, sys.stdout = sys.stdout, self.stdout
                stderr, sys.stderr = sys.stderr, self.stderr
                real_main.main(*args, **kwargs)
                sys.stdout = stdout
                sys.stderr = stderr
        return Fixed()
```

and have `CliRunner().invoke(Fixed())` instead to get click to stop mixing them so that my assertions continue to pass, otherwise click will mix the output together.

> That behavior will also be problematic, all test runners do this.

Not all :P. But to be clear, are you saying that makes it a good idea to do this, or just that click won't be able to change its behavior because py.test will confuse it into thinking someone's patched stdout? I guess that's reasonable, I can't think of a nice way to avoid that (although I would like a way to avoid all of the isolation that `CliRunner.invoke` tries to do and to just have it be doing "catch exit, return result").

**Comment by untitaker** [comment]
>I have tests for an app that makes assertions about stdout and stderr

I see, so you have tests that need to disambiguate between stdout and stderr? In that case I think #371 would be easier to implement while satisfying your usecase.

>that click won't be able to change its behavior because py.test will confuse it into thinking someone's patched stdout?

Exactly this, though py.test has an alternative capturing mode IIRC (patching fds instead of the normal `sys.std*` attrs). But that's of not much use here.

>(although I would like a way to avoid all of the isolation that CliRunner.invoke tries to do and to just have it be doing "catch exit, return result").

But that's most of what `CliRunner` does. If you don't want that, you might as well invoke the cmd yourself and catch SystemExit.

**Comment by Julian** [comment]
> I see, so you have tests that need to disambiguate between stdout and stderr? In that case I think #371 would be easier to implement while satisfying your usecase.

Yeah exactly, although is it? Isn't this a dependency of #371? It should be less work to do, no?

> Exactly this, though py.test has an alternative capturing mode IIRC (patching fds instead of the normal sys.std* attrs). But that's of not much use here.

Yup understood, makes sense.

> But that's most of what CliRunner does. If you don't want that, you might as well invoke the cmd yourself and catch SystemExit.

It's more that the fact that `CliRunner` exists means that it seems to be the most "reliable" public API for doing whatever click claims is going to be necessary to invoke a CLI without actually doing it via a command line. Like there are probably parts of `isolation` that I actually *do* want, e.g. anything that actually *belongs* to click (e.g. where `click.echo` goes) I want click to manage isolating, and anything it does not own, like `sys.stdout` I want it to leave alone.

(Thanks for the replies, makes sense mostly)

**Comment by untitaker** [comment]
>Yeah exactly, although is it? Isn't this a dependency of #371? It should be less work to do, no?

Yes, sure, though it's not the end goal.

>It's more that the fact that CliRunner exists means that it seems to be the most "reliable" public API for doing whatever click claims is going to be necessary to invoke a CLI without actually doing it via a command line. Like there are probably parts of isolation that I actually do want, e.g. anything that actually belongs to click (e.g. where click.echo goes) I want click to manage isolating, and anything it does not own, like sys.stdout I want it to leave alone.

Perhaps we would get away with just patching `echo` instead of the entire stdio, but at this point this will break people's tests who don't channel their entire stdio through click's termui functions. And there are reasons for that, e.g. migrating legacy code to click.

In the end I think it's intended that `CliRunner` emulates a run of the given command, therefore it needs to patch the entire stdio.

**Comment by untitaker** [comment]
Can we close this and track this at #371 only?

**Comment by Julian** [comment]
Yeah fine with me, thanks!
