### ISSUE TITLE
Click errors out when running on Windows with the GAE development server sandbox

### ISSUE THREAD

**Issue by cdman** [pallets/click#711]
This prevents Flask 0.12 from running under the GAE development server on Windows. See this issue: https://github.com/pallets/flask/issues/2139

Probably the pragmatic solution here is:

- add a try/catch around importing msvcrt: https://github.com/pallets/click/blob/master/click/_compat.py#L166
- if the import fails, log a warning (error?) and just use `set_binary_mode = lambda x: x`
- or perhaps we can be stricter and say that `set_binary_mode` won't work in this case and use `set_binary_mode = lambda _: None`?

**Comment by yairohayon** [comment]
This fix is no good - still opening with Flask 0.12 and Click 6.7

**Comment by sorgloomer** [comment]
Created App Engine issue, maybe they can push this better or provide a builtin workaround: https://issuetracker.google.com/issues/72043776
