### ISSUE TITLE
Git Bash adds C:/Program Files/Git to strings with leading slash

### ISSUE THREAD

**Issue by johnpneumann** [pallets/click#713]
Python Version: 2.7
Click Version: 6.7

## Description
When sending strings to a click command where it has a leading slash in the path, `C:/Program Files/Git` is inserted at the front of the string. This only occurs on Windows using Git Bash and does not affecting Powershell or the regular cmd prompt.

## Example:
```python
# click_git_bash.py
import click

@click.command()
@click.argument('bar')
def foo(bar):
    """This modifies the path to have C:\\Program Files\\Git\\ in the path
    if bar starts with a leading slash."""
    click.echo(bar)
    return 0

if __name__ == "__main__":
    foo()
```

Output:
```
$ python click_git_bash.py path/with/no/leading/slash
path/with/no/leading/slash
$ python tmp/click_git_bash.py /path/with/leading/slash
C:/Program Files/Git/path/with/leading/slash
```

Expected:
```
$ python click_git_bash.py /path/with/leading/slash
/path/with/leading/slash
```

**Comment by untitaker** [comment]
That is expanded by your shell, not Click. Your program just echoes out what it finds in `sys.argv`.

**Comment by johnpneumann** [comment]
Got it. Thanks for the clarification.
