### ISSUE TITLE
bad behaviour with double quotes and ! character on option

### ISSUE THREAD

**Issue by ryantownshend** [pallets/click#715]
python --version
Python 3.5.2

click (6.6) and 6.7

Without quotes functions cleanly
```
python double_quote_spike.py --note hi!
hi!
```

Single quotes functions cleanly
```
python double_quote_spike.py --note 'hi!'
hi!
```

Double quotes generates error
```
python double_quote_spike.py --note "hi!"
-bash: !": event not found
```

[double_quote_spike.py gist](https://gist.github.com/ryantownshend/f348835eb06a52a583c4580efd41effc)

**Comment by untitaker** [comment]
That error is from bash, it has nothing to do with Click.
