### ISSUE TITLE
--help for a subcommand runs parent command

### ISSUE THREAD

**Issue by jbillhei** [pallets/click#717]
In this case, if you pass --help to the subcommand, the cli() command will run, but the subcommand does not (and should not).  But I don't want the parent command to run either (in my case, I'm using it to set up common context for subcommands).

Is this intended behavior?

If so, is there any way to tell if --help was passed?  I can't find anything within the context, command, or param objects that contain the actual values passed in.  All I see is the meta data.  They even seem to have the methods that process the actual value, but then don't actually store it anywhere.

```
@click.group()
@click.pass_context
def cli(ctx):
    print "do stuff"


@cli.command()
@click.pass_context
def subcommand(ctx):
    pass
```

**Comment by untitaker** [comment]
You should implement some sort of lazy initialization for your context data instead of generating it eagerly. That will solve your problem without determining beforehand whether it is needed.

Also please ask questions on StackOverflow.
