### ISSUE TITLE
Configurable "Repeat for confirmation:" text

### ISSUE THREAD

**Issue by remort** [pallets/click#723]
It would be nice to be able to set this prompt confirmation text.

**Comment by mattoufoutu** [comment]
This is also something I'd like, and I'd be willing to submit a PR for this if it can make things faster, but I wonder if it would have any chance to be merged when I see the amount of unanswered issues and PR's. If the repo owner passes by, do you think it would be worth it to work on a PR?

**Comment by Saif807380** [comment]
I'd like to work on this.
