### ISSUE TITLE
prompt=True overrides required=False

### ISSUE THREAD

**Issue by pjz** [pallets/click#726]
# What I'm using:
Click 6.7, python 2.7

# What I did:
```
@click.option("--company", prompt=True, required=False, help="The user's company")
...
```

# What I expected:

I expected the user to, once prompted, be able to just press [Enter], easily skipping the option if it wasn't relevant.

# What happened:

The user was forced to enter a company, though most anything - even whitespace - works.

**Comment by pjz** [comment]
So the answer seems to be 'set a default' - perhaps the default could be defaulted to '' if required == False ?

**Comment by jcrotts** [comment]
I agree that it is a little unclear, but you could provide a default of [] or [None], and I think it would be clear to the user that it was not required and they could just accept that default.

I don't think there is enough of a use case here to change the behavior of the flags, but happy to review a PR if you want to make one.
