### ISSUE TITLE
pycharm + unittest: cannot get input in console

### ISSUE THREAD

**Issue by chananshgong** [pallets/click#727]
In Pycharm, when using unittest package and right clicking the test and selecting "run" the running window console halts doesn't respond to typing. This disables the ability to debug code with click commands. If I run the same function from command line or just run the file as script, it runs.

```
import click
import unittest


def z():
    click.confirm('are you sure?')


class Test(unittest.TestCase):
    def test(self):
        z()


if __name__ == '__main__':
    unittest.main()
```

**Comment by ThiefMaster** [comment]
Not sure how that's a click bug. Unittests are not supposed to prompt for user input (that should be provided by the test!). I guess PyCharm also doesn't expect tests to wait for user interaction.
