### ISSUE TITLE
Can ctx.forward/invoke be used with the chained command pattern?

### ISSUE THREAD

**Issue by jakeogh** [pallets/click#738]
Is it possible to define aliases for chained commands? In the example[1] view() is an attempted alias of disp(), but calling view() does not result in a call to disp() because it's not in the @processor pipeline.
The code is a combination of:
http://click.pocoo.org/6/advanced/#invoking-other-commands
https://github.com/pallets/click/blob/master/examples/imagepipe/imagepipe.py

[1] https://github.com/jakeogh/invoke

**Comment by davidism** [comment]
Based on #1323, we're probably just going to remove chain eventually, since it has a bunch of problems. I'm going to close this for now since it hasn't seen any movement, and it's a fairly complex external example that is too much for me to debug.
