### ISSUE TITLE
Allow multiple arguments for inner subcommands in command chains

### ISSUE THREAD

**Issue by Gig77** [pallets/click#740]
From the docs:

> When using multi command chaining you can only have one command (the last) use nargs=-1 on an argument. 

Thus the following will not work

`$ cli cmd1 arg1 arg2 cmd2`

because `cmd2` could be either an argument to `cmd1` or a subcommand.

I want to use quotes to disambiguate. Thus,

`$ cli cmd1 arg1 arg2 "cmd2"`

would lead to `cmd2` being interpreted as argument to `cmd1`, whereas

`$ cli cmd1 arg1 arg2 cmd2`

would greedily interpret `cmd2` as subcommand.

How difficult would it be to implement this behavior? I am thinking about modifying click myself and appreciate any pointers into the right direction. 

I am also open for other suggestions how to solve this problem, because I really would like to have all my subcommands operate with multiple arguments.

**Comment by Gig77** [comment]
Just realized that this would not work, because quotes (") are interpreted by the shell already and removed before Click parses the command line. 

Maybe what I ask for is just not possible or even sensible, but I would just love to know if people have thought about this.

**Comment by pauloalves86** [comment]
Curly brackets could be used:

`$ cli cmd1 \{arg1 arg2\} cmd2`

This would allow subcommands and options as well:

`$ cli cmd1 \{subcmd arg1 --opt=1\} cmd2 cmd3 \{subcmd arg2 --opt=2\}`

**Comment by davidism** [comment]
Thanks for the suggestion. See #1323, the chain feature is unlikely to see more development. Beyond that, this request is probably not possible, and we don't want to add a completely new syntax either.
