### ISSUE TITLE
Clarify the implemented command line conventions

### ISSUE THREAD

**Issue by andy-maier** [pallets/click#741]
Click states that it "fully follows the Unix command line conventions" (on http://click.pocoo.org/6/why/).

Because lateron it refers to "POSIX compliant argument handling", I assume that this means that click conforms to 12.2 "Utility Syntax Guidelines" in  POSIX.1-2008 (http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02).

These guidelines however do not cover long options names at all.

It would be good if Click in its documentation clearly described the implemented command line conventions. This can be done for example by providing a reference to some other document plus describing any deviations or additions.

**Comment by untitaker** [comment]
Long-form options are IIRC an "extension" by GNU, I guess it's somewhere in https://www.gnu.org/prep/standards/standards.html

**Comment by dougharris** [comment]
I think the nuance here is that Click supports developers in creating command line tools which follow Unix command line conventions. Click allows developers to follow, or not follow, good option practice as much as or as little as they like. I'll submit a PR which modifies this feature description.
