### ISSUE TITLE
Document supported Python versions

### ISSUE THREAD

**Issue by mjpieters** [pallets/click#743]
Currently, there is no (easy to find) overview of what Python versions Click supports.

* The README is silent on the subject
* `setup.py` has trove identifiers for `Programming Language :: Python` and `Programming Language :: Python :: 3`, implying only Python 3 is supported.
* Although the distributed wheel on PyPI is built to be version agnostic, the Py Version column is set to the confusing value of  *3.5* implying that the package only works on that Python version (_*_).
* The [Python 3 page in the documentation](http://click.pocoo.org/6/python3/) decries Python 3 for how it handles text, and tells you to stick to Python 2 instead.
* The [travis config](https://github.com/pallets/click/blob/master/.travis.yml) shows the project is tested against 2.6, 2.7, 3.3 - 3.5 and pypy. This may or may not amount to the officially supported version list.

Please add, to the README and perhaps to the quickstart, a clear list of officially supported Python versions, and update the project trove classifiers to include, at least, `Programming Language :: Python :: 2`, or preferably all supported versions.

---
(*) the Py Version column  was taken from the Python version that built the wheel; use [`twine`](https://pypi.python.org/pypi/twine) to upload wheels instead and [that column will be set correctly](http://stackoverflow.com/questions/40415349/what-does-the-py-version-in-pypi-project-page-mean-and-does-it-matter).

**Comment by schlamar** [comment]
BTW, click fails with Python 2.6 on Windows (ref https://github.com/kennethreitz/requests/pull/3988).

**Comment by PyDever** [comment]
was this ever added?
