### ISSUE TITLE
help information in subcommand list

### ISSUE THREAD

**Issue by GrayMissing** [pallets/click#749]
Hello, I'd like to know whether it's possible to show more detail in subcommand list, including args, options. e.g.
```
help      Displays help for command.
```
to
```
help <command>      Displays help for command.
```

**Comment by fdavis** [comment]
Currently if you overwrite short_help when the option/arg is defined that will show up in the help for the command list, but its hard coded to be very brief currently.
  
There is a larger question of support for customizing formatting brought up in #513 but I'm not certain how long it will be before that is scoped out or released.
Feel free to reopen for further assistance
