### ISSUE TITLE
use -h as a shorthand for --help?

### ISSUE THREAD

**Issue by hyao** [pallets/click#75]
Is it possible to use -h as a shorthand for --help? or is it better to even make that default?

Thanks,

**Comment by techtonik** [comment]
Is it possible to setup it once globally instead of bloating every decorator?

**Comment by techtonik** [comment]
@mitsuhiko `@click.group(context_settings=CONTEXT_SETTINGS)` is undocumented https://click.palletsprojects.com/en/7.x/api/#click.Group
