### ISSUE TITLE
get_os_args() returns wrong arguments on Python2 if click is imported after sys.argv has changed

### ISSUE THREAD

**Issue by NiklasRosenstein** [pallets/click#751]
If click is imported after `sys.argv` has already been modified, `click.utils.get_os_args()` returns a wrong arguments list. This is because `_initial_argv_hash` is initialized with the hash of the already modified `sys.argv` list.

**Comment by jcrotts** [comment]
Hey looks like you fixed the issue in your library. If this is still a problem with Click 7.X please reopen this.
