### ISSUE TITLE
Run click command from __main__.py / IDE support

### ISSUE THREAD

**Issue by ericfrederich** [pallets/click#752]
# Question

How would I construct a `__main__.py` which properly invokes the top-level cli command.
... say for instance in the [complex example](https://github.com/pallets/click/tree/master/examples/complex)?

# Background

The examples in this repo all have a `setup.py` which specify an entry_point which points to a click command.  Once installed via `pip install --editable .` I can run the script from a terminal, but how do I run it from within an IDE?  There is no *script* to execute within the repository... just one that gets installed into your Python installation or your venv.

The blog post "[Python Apps the Right Way: entry points and scripts](https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/)" advocates creating a `__main__.py` file as well for your main entry point.

This actually gives me two different ways to execute this under PyCharm (and I'm guessing other IDEs as well).

- Specify `__main__.py` as your script
- Leave the *Script* field blank and specify `-m my_project` as the *Interpreter options*

**Comment by untitaker** [comment]
Please use StackOverflow for questions, as per https://github.com/pallets/click/blob/master/CONTRIBUTING.rst

**Comment by ericfrederich** [comment]
No problem... would you accept a pull request which changes the examples and documentation if I get a decent answer?

**Comment by untitaker** [comment]
Of course!
