### ISSUE TITLE
[Feature Request] Allow for Argument enumerations within tab completion

### ISSUE THREAD

**Issue by brianbruggeman** [pallets/click#753]
The basic thought here is that providing a set of enumerations for an argument would properly setup click for tab completion...

For example:

```

@command
@click.argument('arg-name', enumerations=some_iterable)
def some_command(arg_name):
    """Runs some-command..."""
```

And when I run this in a shell...

```
$ some-command <tab>
<list of enumerations here>
```

**Comment by stopthatcow** [comment]
Hi @brianbruggeman I have implemented something similar, check out this PR: https://github.com/pallets/click/pull/755
Feedback is welcome!

**Comment by brianbruggeman** [comment]
@stopthatcow Awesome.  Thanks for this!

**Comment by stopthatcow** [comment]
@untitaker I think this can be closed.

**Comment by untitaker** [comment]
Thanks
