### ISSUE TITLE
Bash auto-complete of options not working properly in command chains

### ISSUE THREAD

**Issue by Gig77** [pallets/click#754]
Example:

    $ cli cmd1 cmd2 --<TAB><TAB>

Auto-completes options of `cmd1`, not `cmd2`.

Observed in Python version 3.5.2 and click version 6.6.

**Comment by stopthatcow** [comment]
@Gig77 try with latest develop. I believe that #755 should fix this.

**Comment by Gig77** [comment]
Not working for me in 7.0 development version. `cmd1` has no arguments, only options, and `cmd2` is a valid subcommand.

**Comment by stopthatcow** [comment]
@Gig77 please post a snippet of your test case and I will take a look.

**Comment by stopthatcow** [comment]
This works for me:

`import click

@click.group()
def cli():
    pass

@click.group()
@click.option('-n', is_flag=True)
def cmd1(n):
    pass

@cmd1.command()
@click.option('-b', is_flag=True)
def subcmd(b):
    pass

cli.add_command(cmd1)
`

**Comment by Gig77** [comment]
Thanks for looking into it! In chain mode it did not work for me:

```
@click.group(chain=True)
def cli():
	pass

@cli.command()
@click.option('-n', is_flag=True)
def cmd1(n):
	pass

@cli.command()
@click.option('-b', is_flag=True)
def subcmd(b):
	pass

cli.add_command(cmd1)
```

**Comment by stopthatcow** [comment]
I see the issue and will take a more in depth look this weekend.
