### ISSUE TITLE
Click should provide means to customize write

### ISSUE THREAD

**Issue by Kentzo** [pallets/click#756]
Sometimes the output machinery embedded in click is not desirable. At least the function that performs write should be customizable to give a user a chance to handle and process all errors that may happen.

**Comment by untitaker** [comment]
This is not very specific. Could you name a particular situation where the current behavior is undesirable?

**Comment by Kentzo** [comment]
With current design it's impossible to control how errors are being handled in `echo` and all other functions that end up using it. 

In particular, we have a problem when message cannot be represented in `latin-1`. Since this is part of the output that _must_ be printed and never cause an exception (at least not due to encoding) I need to customize the behavior. In particular, I'd change [from](https://github.com/pallets/click/blob/c8e2110/click/utils.py#L260):
```
if message:
    file.write(message)
```
to:
```
if message:
    try:
        file.write(message)
    except UnicodeEncodeError as e:
        file.write(message.encode(e.encoding, errors='backslashreplace').decode(e.encoding))
```

(I'm using Python 3, Python 2 compatibility may require adjustments)

**Comment by untitaker** [comment]
If you encounter encoding errors like that you really should set your system locale to a correct (i.e. UTF-8) value.

**Comment by Kentzo** [comment]
@untitaker Not always you can control the encoding of stdout. And that's a different (and not a simple) story of why it's that restricted in my case.

My point is that you can have a UTF-16-only string and you may want to still print it (handling arbitrary logging, data stream, whatever?) even when you have crippled 'latin-1'. Granted, one could use custom printing, but then it'll require to give up all the conveniences of `click`.

**Comment by KiYugadgeter** [comment]
Hello, I think `errors` should use `replace` instead of `backslashreplace`.
In python2, `echo` prints `?` at #705 .

**Comment by untitaker** [comment]
We could provide a possibility for the user to replace `click.echo` with a custom function (that lives on the context), but stuff like #757 is not sensible.

**Comment by KiYugadgeter** [comment]
sys.stdout.encoding returns system default encoding of stdout by default.

**Comment by untitaker** [comment]
I am talking about backslashreplace, not the encoding.

**Comment by KiYugadgeter** [comment]
Is it possible to add `errors` argument to echo function?
Or should not do this for backward compatibility?

    click.echo(message, file, nl, errors="strict", error, color)

**Comment by untitaker** [comment]
Sure, but that solves only a subset of all problems. It doesn't affect echo()
calls outside of your code.

**Comment by KiYugadgeter** [comment]
`errors` argument should passed when create a new Command object?

    click.Command(name, context_settings=None, callback=None, params=None, errors="restrict", help=None, epilog=None, short_help=None, options_metavar='[OPTIONS]', add_help_option=True)

**Comment by untitaker** [comment]
I already made my proposal to have a variable on the context for this above.

**Comment by KiYugadgeter** [comment]
Thanks!

I am python beginner.
Would you mind describing about your proposal?

**Comment by Kentzo** [comment]
`replace` is bad, because it's not lossless. With `backslashreplace` data can be later processed and restored.

Replacing `echo` is fine, but default `echo` should be available through public interface so it can be called from custom implementation.

**Comment by KiYugadgeter** [comment]
@Kentzo I agree it,  data resiliency was lacked in my point.

**Comment by untitaker** [comment]
`backslashreplace` also mangles data, it is not a good default.

**Comment by Kentzo** [comment]
@untitaker Hmm, could you give me an example of mangling that cannot be recovered?

**Comment by untitaker** [comment]
It mangles data in the sense that it converts it into a format that isn't expected. Technically it's not mangling, but if you follow down that road, some forms of mojibake would acceptable as long as they're reversible.

**Comment by Kentzo** [comment]
@untitaker Could you give me some direction of how I would address it in an acceptable way?

**Comment by untitaker** [comment]
I am not entirely sure, but it might be a good idea to make `click.echo` use `get_current_context()`, then check whether there's a replacement function for `click.echo` defined on that context, and use it.

I'd like to get more input from other maintainers on this, cc @ThiefMaster @mitsuhiko @davidism

**Comment by Kentzo** [comment]
Are there any particular steps that can be made with the up to date version of click?

**Comment by davidism** [comment]
I don't want to go down the path of adding function overrides to the context right now. If you're having issues with output, open a specific issue. Note that you can echo bytes, so if you have a weird string that you want to output, encode it to bytes then pass that to `echo`.
