### ISSUE TITLE
Q: GUI generator?

### ISSUE THREAD

**Issue by marble** [pallets/click#759]
Is somebody aware of a gui generator for a click enabled application?

**Comment by ThiefMaster** [comment]
How would you generate a GUI from a commandline app?

**Comment by untitaker** [comment]
Those things do exist for argparse, but please don't ask questions on the bugtracker.

**Comment by marble** [comment]
@untitaker Sorry for disturbing. It's a pity there isn't an easily accessible group for discussion. @ThiefMaster Probably I wasn't clear enough. "To generate a gui for entering the parameters" is what I mean. Because we've specified everything vor Click already.

**Comment by traverseda** [comment]
https://github.com/szsdk/quick
