### ISSUE TITLE
lazy defaulting to on for "w" is confusing

### ISSUE THREAD

**Issue by matthayes** [pallets/click#760]
I had a param with `click.File("w")`.  I was really confused that the file wasn't being created.  I even tried closing it and it still wasn't created.  It turns out I wasn't writing any records because the input dataset was empty.  This is really confusing default behavior.  I think it should create an empty file.  It's also inconsistent.  If the file already exists then it will be replaced with a 0 byte file; if the file doesn't already exist then no file is created.

click==6.7

**Comment by makarchuk** [comment]
> If the file already exists then it will be replaced with a 0 byte file; if the file doesn't already exist then no file is created.
That's exactly how `open(filename, 'w')` works, isn't it? If you want to preserve your old file if it exists you should probably user `'a'`(for "append") mode

**Comment by matthayes** [comment]
That's not how `open` behaves according to this:

```
f=open("test", "w")
f.close()
```

The file `test` exists after this code runs.

**Comment by ThiefMaster** [comment]
>  It's also inconsistent. If the file already exists then it will be replaced with a 0 byte file; if the file doesn't already exist then no file is created.

Are you sure this happens without writing to it? `open()` does but I'd expect click's `File` in lazy mode to only do the `open()` call the first time something is written to it.

**Comment by matthayes** [comment]
I think `File` does only do the `open()` call the first time something it is written to it.  What I meant was that defaulting to lazy mode for `File` is confusing (to me at least).  My expectation was that by default the file would be created regardless of whether content was written or not.

**Comment by fdavis** [comment]
I've labelled as documentation because this behavior appears to be by design: https://github.com/pallets/click/blob/79275462d36bf91078acc074ffdd406c9d1d0d89/click/types.py#L361

As long as this is documented lazy open seems like a safe default behavior.

**Comment by fdavis** [comment]
Read through the [docs section](http://click.pocoo.org/5/arguments/#file-opening-safety) on this and it seems good to me.
Please reopen if you have any further issues
