### ISSUE TITLE
Python error can't assign to operator

### ISSUE THREAD

**Issue by nelqatib** [pallets/click#762]
Hi,

I'm trying to figure out how @click works with some basic examples. However, I come across this error on [a basic value option](http://click.pocoo.org/6/options/):

![image](https://cloud.githubusercontent.com/assets/16545838/24829405/6780ed54-1c71-11e7-9979-69450628be38.png)

(I have @click 6.6 installed )

Thanks in advance!

**Comment by davidism** [comment]
You're still in the Python prompt, you need to be in the shell prompt (bash, zsh, etc.).
