### ISSUE TITLE
Avoid collisions with builtins, keywords, etc.

### ISSUE THREAD

**Issue by mmessmore** [pallets/click#763]
I'm writing an ansible inventory script and it requires that the script implement a `--list` option.  This results in me having to collide with the type `list`, at least as far as I can tell (feel free to school me on this one). 

Here's a dummy example:
```
@click.command()
@click.option('--list/--nolist', default=False)
def cli(list):
    if list:
        print json.dumps(['foo', 'bar', 'baz'])
```

I would like to be able to force this to be passed as a parameter named _list or really anything that doesn't collide with a builtin or keyword or really anything that's in my current namespace.

If I'm missing something, please let me know, but I've stared at the docs and the source and don't see how to get around this cleanly.

**Comment by ThiefMaster** [comment]
already possible:

   @click.option('--list/--nolist', 'list_', ...)
