### ISSUE TITLE
Flags with optional = argument

### ISSUE THREAD

**Issue by andyneff** [pallets/click#764]
Is it possible to have a flag argument with an optional argument when using the `=` operator?

For example, on `grep` on GNU systems, it has

```
--color[=WHEN], --colour[=WHEN]
              Surround the matched (non-empty) strings, matching lines, context lines, file names, line numbers, byte offsets, and separators (for fields and groups of context lines) with escape sequences to display them in color on
              the terminal.  The colors are defined by the environment variable GREP_COLORS.  The deprecated environment variable GREP_COLOR is still supported, but its setting does not have priority.   WHEN  is  never,  always,  or
              auto
```

- `grep --color ...` results in color being set to "auto"
- `grep --color=always ...` results in color being set to "always"
- `grep --color always ...` does NOT result in color being set to "always", but still "auto" and always is interpreted as what ever arguments come next

Slightly more complicated situation (`rsync` for example) combining multiple single letter versions of these together.

- `rsync -ravB=1000`, so flags "r", "a", and "v" are "set" and "B" is set to 1000.

**Comment by jpassaro** [comment]
See #1229 , which if accepted would allow users to do this pretty easily by subclassing Option
