### ISSUE TITLE
Assembling CLI's from the click.option decorators applied to multiple functions

### ISSUE THREAD

**Issue by alshedivat** [pallets/click#766]
Hi there! I recently found `click` and totally liked the library.

One particular question I couldn't find the answer to is: does click support assembling CLI's from the `click.option` decorators applied to not only the main function but sort of sprinkled around other (auxiliary) functions?

Here is an example of what I mean.

```python
import click

@click.option("--d", default=1)
@click.option("--f", default=2)
@click.option("--g", default=3)
def foo(d, f, g):
    # do something

@click.command()
@click.option("--a", default=1)
@click.option("--b", default=2)
@click.option("--c", default=3)
def main(a, b, c):
    # Do something here; use a, b, and c arguments
    foo() # call foo assuming the arguments are provided through the cli

if __name__ == '__main__':
    main()
```

Basically, I would like to distribute the decorators around multiple functions (perhaps, some of them are methods of some classes in a module/library). I am wondering if this is possible?

**Comment by untitaker** [comment]
Hello @alshedivat, this question has already been asked a few times here, but I couldn't find the answer. The answer to this reveals itself if you keep in mind how decorators work: `click.option(...)` returns a function, which takes a function (`main`) and returns some object. Therefore you can transform this:

    @click.command()
    @click.option(..)
    def foo():
        pass

into:

    myoption = click.option(..)

    @click.command()
    @myoption
    def foo():
        pass

which can be transformed into:

    def myoption(f):
        f = click.option(..)(f)
        return f

    @click.command()
    @myoption
    def foo():
        pass

at this point you can add more lines like the first one in `myoption` to add more options to each command that is decorated with `@myoption`.

Hope I could help.
