### ISSUE TITLE
group subcommands act as if they where the main command breaking invocation

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pallets/click#768]
on click (6.7)

i started with a simple hack:
```
import click
import subprocess
import json


def doborg(*args):
    return json.loads(subprocess.check_output(
        ['borg', '--json'] + list(args)))


@click.group()
def main():
    pass


@main.command()
@click.argument('repo', type=click.Path(), nargs=1)
def list(repo):
    print(doborg('list', repo))
```

and i get 

```
$ backuptool list
Usage: backuptool list [OPTIONS] REPO

Error: Missing argument "repo".
$ backuptool list ../borg
Usage: backuptool [OPTIONS] REPO

Error: Got unexpected extra argument (../borg)
```

*edit*

python is 3.5.3

**Comment by untitaker** [comment]
I can't reproduce this issue with this reduced example:


```
import click

@click.group()
def cli():
    pass

@cli.command()
@click.argument('foo', type=click.Path(), nargs=1)
def sub(foo):
    pass

cli()
```

**Comment by RonnyPfannschmidt** [comment]
@untitaker i did some further investigation, the issue presents as soon as i add the subprocess call

**Comment by RonnyPfannschmidt** [comment]
@untitaker as far as i can tell this presents a endless recursion back into click, i have no idea whats happening there

**Comment by untitaker** [comment]
Oh wow, I can reproduce this with the original code. This happens when invoking an arbitrary Click application (like borg is).

**Comment by untitaker** [comment]
Lol nope.

You are calling `list` in your `doborg`, but that's your command function now.

**Comment by RonnyPfannschmidt** [comment]
Ouch, that's mega blindness on my side, I'm going to find a hole and crawl into it
