### ISSUE TITLE
Ignore option-like arguments after first positional argument

### ISSUE THREAD

**Issue by NiklasRosenstein** [pallets/click#785]
I would like an argument that consumes any argument after the first, be it option-like or not.

```python
import click

@click.command(context_settings={'ignore_unknown_options': True})
@click.argument('filename')
@click.argument('args', nargs=-1)
@click.option('-v', '--verbose', is_flag=True)
def main(filename, args, verbose):
  print('loading', filename, 'with args', args, 'verbose:', verbose)

main()
```

Running this with `python test.py foobar baz --verbose --spam`, I want it to print

    loading foobar with args ('baz', '--verbose', '--spam') verbose: False

but what it actually prints is

    loading foobar with args ('baz', '--spam') verbose: True

Is there a way to achieve this behaviour with Click?

<sub>*Edit*: Fixed missing `foobar` argument in example commandline.</sub>

**Comment by davidism** [comment]
To treat values that look like options as arguments, use `--` to turn off option parsing and treat remaining values as arguments.

```
python example.py foobar baz -- --verbose --spam
```
