### ISSUE TITLE
Param with nargs is empty tuple rather than None when unspecified

### ISSUE THREAD

**Issue by ericfrederich** [pallets/click#789]
Parameters that are unspecified should be either None or their default value.

In the case that you specify `@click.option('--foo', '-f', nargs=2)` when `--foo` isn't specified on the command line the foo variable is an empty tuple rather than `None`.

It is useful to determine whether something was specified or not using `if foo is None:`

I think this should be the default behavior.  If you want an empty tuple to be the default, then specify it with `@click.option('--foo', '-f', nargs=2, default=())`

## edit
Another fact to help make my point is that nargs when combined with type seems to also cause issues.
For exmaple `@click.option('--foo', '-f', nargs=2, type=(int, int))` will cause the following.

`TypeError: It would appear that nargs is set to conflict with the composite type arity.`

This happens because an empty tuple is passed.  Again, my opinion is that if it wasn't specified (command line, environment variable, etc)... then it should be set to None and this arity shouldn't be checked either.

**Comment by ericfrederich** [comment]
Thoughts on this?

**Comment by fdavis** [comment]
You should be able to workaround the default or type checking with your own callback (sample pasted below)

I definitely agree with you that the default NoneType instead of an empty Tuple should at least be an option since an if statement like `if foo is not None` is a common pattern.

I'm not sure we [currently can support](http://click.pocoo.org/5/parameters/#parameter-types) a tuple type check like you have listed there but you could define your own parameter type to allow for validating that `type=(int, int)`

**Comment by jingpengw** [comment]
I got the same problem. @fdavis 's `default_none` works for me.

**Comment by jingpengw** [comment]
the callback solution actually is not working correctly. the parameter will always be None even if I give it some number!

**Comment by ericfrederich** [comment]
I say
* change the default behavior to `None` if it's not specified
* If developers want an empty tuple to be the default, they should explicitly set `default=()`
* If tests pass, then merge it

**Comment by pjz** [comment]
I disagree. For nargs != 1, the usual pattern is to have to iterate over the args (or join them, or something else that requires a list), so it's cleaner to default to an empty tuple.

**Comment by jingpengw** [comment]
I think if it is defined explicitly like "default=None", it should return
None. If user set the "default=()", it should return empty tuple.

Jingpeng Wu
Postdoc in Princeton Neuroscience Institute, Princeton University, NJ
website: jingpengw.com

**Comment by davidism** [comment]
Fixed by #1687
