### ISSUE TITLE
Autocomplete should not complete subcommands while expecting required argument or option

### ISSUE THREAD

**Issue by Gig77** [pallets/click#790]
Suppose my `cli` has two subcommands, `sub1` and `sub2`. `sub1` has an option `-o` that requires a value. This option has an autocomplete function assigned to it. 

When I enter

`$ cli sub1 -o <tab><tab>
`

autocomplete not only suggests my allowed values for `-o`, but also `sub2`. However, since an option value is required after `-o`, `sub2` is an invalid suggestion at this point. 

The same happens with required arguments.

Is there a possibility to suppress autocompletion of subcommands while still in the context of required arguments or options?

Python version is `Python 3.5.2 :: Anaconda 4.2.0 (64-bit)` and Click version is `7.0-dev`.

**Comment by Gig77** [comment]
The same behavior is observed if `-o` has no user-defined autocomplete function but predefined choices.

**Comment by stopthatcow** [comment]
This was likely broken in fixing #774 I will take a look.

**Comment by stopthatcow** [comment]
@Gig77 Please take a look at https://github.com/pallets/click/pull/806 and see if this fixes your issue. If you like please feel free to suggest additional test cases.
