### ISSUE TITLE
question:  how-to initialise a dict and group click functions

### ISSUE THREAD

**Issue by nskalis** [pallets/click#797]
Hi,

I would like to initialise a global variable, in this case a dictionary called `DOC`, after passing a number of command line arguments and using the `click` library

I have tried the following:

```
#!/usr/bin/python3

import os
import sys
import yaml
import logging
import click


DOC = {}


@click.group()
def cli():
    pass

@click.command()
@click.option("--logger-file", required=True, default='{}/blabla/cfg/logger.{}.yml'.format(os.environ['HOME'],os.path.basename(__file__)), show_default=True, help="YAML logging configuration file")
@click.pass_context
def cli_logger_file(ctx, logger_file):
    if os.path.exists(logger_file):
        try:
            with open(logger_file, "rt") as f:
                ctx.DOC = yaml.safe_load(f.read())
                print( "logger" )
        except Exception as e:
            print( str(e) )
            sys.exit()
    else:
        sys.exit()


if __name__ == '__main__':
    cli_logger_file()
    print( "hi!" )
    print( DOC )
```

But when I run it, the output is:

```
$ python3 etc.py --logger-file=/home/blabla/cfg/logger.src.app.component.yml
logger
{}
```

Could you please help me understand:

1. Why the `DOC` is not initialised ?
2. Why I do not see `hi!` being printed ?
3. Why if i replace `@click.command()` with `@cli.command()` it does not recognise the command-line option `--logger-file` ?

**Comment by ThiefMaster** [comment]
Why do you expect the context to be magically applied to global variables? If you want this you need to do it manually (or just use `global DOC` and `DOC = ...` instead of using the context for it).

**Comment by nskalis** [comment]
`sys.exit()` is not called unless there is an exception or the file is not found, which is not the case, right ?
what about the `click.group` decorator, if I do:

```
@click.group()
def cli():
    pass

@cli.command()
@click.option("--logger-file", required=True, default='{}/ip-spotlight/cfg/logger.{}.yml'.format(os.environ['HOME'],os.path.basename(__file__)), show_default=True, help="YAML logging configuration file")
def cli_logger_file(logger_file):
    pass

if __name__ == '__main__':
    cli()
```

I get:
```
Error: no such option: --logger-file
```

**Comment by ThiefMaster** [comment]
Yes, it is: https://github.com/pallets/click/blob/master/click/core.py#L709

And you forgot to patse how you are calling your script when it fails.

**Comment by nskalis** [comment]
Thanks. This is how it is called:
```
$ python3 etc.py --logger-file=/home/app/blabla/cfg/logger.src.app.component.yml
Error: no such option: --logger-file
```

What about having `click` just initialising my script, in other words, after parsing the command-line arguments I would like `main()` to continue instead of calling `sys.exit()` ?

**Comment by ThiefMaster** [comment]
That's simply not how click works - but you could use a custom Context that ignores `exit()` calls with `code=0`.

And you are calling it the wrong way! By using a group you make the commands in there subcommands of the group so you need to call it like this:

    $ python3 etc.py cli_logger_file --logger-file=/home/app/blabla/cfg/logger.src.app.component.yml

BTW, `python3 etc.py --help` is your friend
