### ISSUE TITLE
Invalid Escape Sequences in Python 3.6

### ISSUE THREAD

**Issue by cooperlees** [pallets/click#802]
I'd like to fix the following invalid escape sequences scattered across the click code.

click/core.py:1253: DeprecationWarning: invalid escape sequence \s
  """
click/_compat.py:14: DeprecationWarning: invalid escape sequence \[
  _ansi_re = re.compile('\033\[((?:\d|;)*)([a-zA-Z])')
click/decorators.py:111: DeprecationWarning: invalid escape sequence \s
  ""

If no one disagrees, I'll create a diff making these r''

**Comment by cooperlees** [comment]
Created https://github.com/pallets/click/pull/807

**Comment by segevfiner** [comment]
BTW, I think this will become a hard error in Python 3.7

**Comment by jcrotts** [comment]
Closing this because it was merged in https://github.com/pallets/click/pull/807
