### ISSUE TITLE
Using string for 'type': exception hard to figure out

### ISSUE THREAD

**Issue by goerz** [pallets/click#803]
Erroneously using a string for the `type` argument in click produces a traceback that is hard to figure out. E.g. using

    @click.option('--dim', type='int')

where `'int'` is used instead of `int` produces the following error when running the program:

    [...]
    File "/home/goerz/Documents/Programming/qdynpylib/QDYN/_lb2diss.py", line 126, in <module>
        @click.argument('config', type=click.File('r'))
    File "/home/goerz/anaconda3/lib/python3.5/site-packages/click/decorators.py", line 170, in decorator
        _param_memo(f, OptionClass(param_decls, **attrs))
    File "/home/goerz/anaconda3/lib/python3.5/site-packages/click/core.py", line 1454, in __init__
        Parameter.__init__(self, param_decls, type=type, **attrs)
    File "/home/goerz/anaconda3/lib/python3.5/site-packages/click/core.py", line 1262, in __init__
        self.type = convert_type(type, default)
    File "/home/goerz/anaconda3/lib/python3.5/site-packages/click/types.py", line 516, in convert_type
        return FuncParamType(ty)
    File "/home/goerz/anaconda3/lib/python3.5/site-packages/click/types.py", line 82, in __init__
        self.name = func.__name__
    AttributeError: 'str' object has no attribute '__name__'

It is especially hard to figure out what went wrong because the traceback originates from the *last* decorator, in this case

    @click.argument('config', type=click.File('r'))

instead of the earlier one for `dim` that's actually the cause of the problem. I had to successively comment out decorators before finding the error. It would be nice if click could catch this Exception earlier, giving an indication of where the problem originates.  This is for click version 6.6.

**Comment by goerz** [comment]
I'm not sure it will work quite as easiy, as`type` could also be a tuples of type instances, for [multi-valued options](http://click.pocoo.org/5/options/#tuples-as-multi-value-options). The [click-internal types](http://click.pocoo.org/5/api/#types) also do not fulfill `isinstance(x, type)`. Nonetheless, there is probably only be a small number of types that the `type` value could conceivably have, so this could still work.

**Comment by sirosen** [comment]
Yeah, the `type` logic is a bit more complex than I'd realized.
After looking a bit at [how types are processed](https://github.com/pallets/click/blob/master/click/types.py#L518-L557), it looks like the type conversion logic fails-over to assuming that the `type` is callable.

I think we just need to add a check at the end of `convert_type` which errors if `callabe(type)` is false.

**Comment by cdeil** [comment]
I made the same error as @goerz and thus found this issue.

Just for future reference, here's a complete example to trigger the error @goerz mentioned above:
```
$ cat a.py 
import click

@click.command()
@click.option('--dim', type='asdf')
def cli(dim):
    print(dim)

cli()

$ python a.py 
Traceback (most recent call last):
  File "a.py", line 4, in <module>
    @click.option('--dim', type='asdf')
  File "/Users/deil/code/click/click/decorators.py", line 170, in decorator
    _param_memo(f, OptionClass(param_decls, **attrs))
  File "/Users/deil/code/click/click/core.py", line 1477, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
  File "/Users/deil/code/click/click/core.py", line 1283, in __init__
    self.type = convert_type(type, default)
  File "/Users/deil/code/click/click/types.py", line 557, in convert_type
    return FuncParamType(ty)
  File "/Users/deil/code/click/click/types.py", line 82, in __init__
    self.name = func.__name__
AttributeError: 'str' object has no attribute '__name__'
```

I tried to read `click/types.py` and understand the problem. It's not obvious to me what `FuncParamType` is, and why it's created at the end of `convert_type` if nothing else matches. Is this a good idea?

Slightly related: I think there is a bug in `FuncParamType.convert`: there's a `str.decode` call, that can't work on Python 3, no?
https://github.com/pallets/click/blob/7404b066ec59cd21d6af0d7106c56988e0e2029c/click/types.py#L92
I'm just starting to familiarise myself with click. Can someone make a click example where such a `FuncParamType` is supposed to be created? (that class has zero test coverage, i.e. no such example in the click tests).

**Comment by mitsuhiko** [comment]
Going to close this issue as I'm unable to change this. Python is sadly a weakly typed language and we can't capture all the cases here.

**Comment by cdeil** [comment]
Just in case you hadn't seen that part of my comment: this line will always raise an AttributeError on Python 3 since there is no `str.decode`:
https://github.com/pallets/click/blob/7404b066ec59cd21d6af0d7106c56988e0e2029c/click/types.py#L92
(or this line is never reached on Python 3, then it might be fine, it's not clear to me)

**Comment by mitsuhiko** [comment]
That code branch is dead on Python 3.
