### ISSUE TITLE
Strikethrough support

### ISSUE THREAD

**Issue by WhyNotHugo** [pallets/click#805]
I'd love to see strike-through support for [`style`](http://click.pocoo.org/5/api/#click.style). AFAIK, most modern terminals support this.

From what I understand, this is "code number 9", and can be tested via `echo -e "\e[9mtest\e[0m"`.

**Comment by VictoryChang** [comment]
Taking a look at this enhancement request.

**Comment by VictoryChang** [comment]
There are only a certain number of terminals that have support for strikethrough. Do we want to include this functionality with caution that this heavily depends on the user's terminal?

Mac's terminal for example does not appear to have support for strikethrough.

**Comment by ThiefMaster** [comment]
PuTTY also doesn't support it.

**Comment by jcrotts** [comment]
This might be a better fit for https://github.com/click-contrib then?

**Comment by VictoryChang** [comment]
Agreed. Is this relevant to an existing repo or can another one be created?

**Comment by VictoryChang** [comment]
Feel free to take this Issue. 
The core modification will be in termui.py under the style method and it can be tested using a combination of click.echo() and click.style().

**Comment by BALaka-18** [comment]
@davidism I am working on this Issue. Informed here.
