### ISSUE TITLE
support for disallowing repeated options?

### ISSUE THREAD

**Issue by jairideout** [pallets/click#808]
Click allows options to be repeated in a command, and if `multiple=False` only the last option's value is recorded. I understand this is intentional and documented behavior to support overriding shell alias defaults.

Is there a way to disable this behavior so that Click raises an error if `multiple=False` and an option is repeated?

**Comment by sirosen** [comment]
There is not, unfortunately, as far as I know.

We were looking into this problem in a project I work on and a coworker of mine put together [this workaround](https://github.com/globus/globus-cli/pull/297/files), which uses a custom subclass of `click.Option`.
I still haven't gotten to reviewing his work, but this is definitely a viable approach.

**Comment by jairideout** [comment]
Thanks for following up @sirosen! We ended up taking a [similar approach](https://github.com/qiime2/q2cli/pull/144/files#diff-44ff2ad43bb595b5c6e94c8afadfa34d) by subclassing `click.Option` and providing a `@click.option` replacement decorator.

In the `click.Option` subclass we wrap the option's `callback` to check for repeated options and error if necessary. The subclass supports `multiple` and `count` parameters as usual, in which case the callback wrapping and validation is skipped (in our project we have use-cases for single-only and repeatable options).

**Comment by davidism** [comment]
Going to close this as I think it's better not to encourage disabling the alias override capability. This seems like a less common use case, and can be accomplished with a wrapper/custom type that sets arguments and validates appropriately.
