### ISSUE TITLE
blink=True doesn't blink

### ISSUE THREAD

**Issue by yochem** [pallets/click#810]
In your example "colors" you have
```python
click.echo(click.style('I am blinking', blink=True))
```
Unfortunately, it doesn't blink. I have tried it with different terminals ([Hyper](https://github.com/zeit/hyper) and [Termination](https://github.com/Fred-Barclay/Termination)). This are the outputs: 

![Termination](https://user-images.githubusercontent.com/23235841/27185240-08f41622-51e5-11e7-87f2-400cd7e5fd27.png)
![Hyper](https://user-images.githubusercontent.com/23235841/27185239-08f1cc0a-51e5-11e7-92c2-fc65d717022e.png)

**Comment by davidism** [comment]
The terminal has the final say in how it displays text. For example, xfce-terminal doesn't blink text, but konsole does.
