### ISSUE TITLE
Why explicitly require LC_ALL be UTF-8 when all other locale settings are UTF-8?

### ISSUE THREAD

**Issue by warsaw** [pallets/click#811]
On Ubuntu 17.04

```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=en_US.UTF-8
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES=en_US.UTF-8
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

So as you can see it's effectively UTF-8.  LC_ALL is not defined because of [reasons](https://askubuntu.com/questions/140601/ubuntu-doesnt-set-lc-all-why#140605).  Why specifically is setting LC_ALL required?  Why aren't the individual LC_* and LANG* settings enough?

**Comment by warsaw** [comment]
I'm still curious about the recommendations, but I've debugged my issue to something unrelated.  Sorry for the noise!

**Comment by untitaker** [comment]
I don't think Click does anything special here, but rather just uses whichever locale settings the interpreter has picked up.
