### ISSUE TITLE
Typo? `Synching` vs `Syncing`

### ISSUE THREAD

**Issue by delirious-lettuce** [pallets/click#813]
https://english.stackexchange.com/questions/681/synced-or-synched

Many of them seem to think `sync` is more common than `synch`.

```python
@cli.command()
def sync():
    click.echo('Synching')
```
https://github.com/pallets/click/blob/b5239afafe6e36f53defabb392ac5264e0f5eb6b/docs/commands.rst#callback-invocation

**Comment by ThiefMaster** [comment]
:+1: on syncing. However, this is just example code, you could just change the wording there to "Synchronizing"

**Comment by delirious-lettuce** [comment]
@ThiefMaster ,

Ya, I didn't mean to imply it was a big deal or anything. I just thought it might be a typo.

One example on that stackoverflow page was `async` instead of `asynch`. Again, I know it's just short for `asynchronous` but `async` seems more common.
