### ISSUE TITLE
How to use "from" as a command variable?

### ISSUE THREAD

**Issue by renatoliveira** [pallets/click#820]
If I understood correctly, when a command is declared using `@click.option()` then the variable name is the value that is passed on the first parameter. Correct me if I'm wrong on this.

But what if I want to declare something like `@click.option('--from', promt='Origin')`? When using `from` on a function declaration, the code becomes invalid, since `from` is a keyword.

**Comment by davidism** [comment]
Either give it a different name with the first arg or capture it with `kwargs`.

```python
@click.command()
@click.option('other', '--from')
def keyword(other):
    click.echo(other)
```

```python
@click.command()
@click.option('--from')
def keyword(**kwargs):
    click.echo(kwargs)
```
