### ISSUE TITLE
Handling of special characters in getchar

### ISSUE THREAD

**Issue by pkch** [pallets/click#821]
When the user presses arrow up, the `click.getchar()` returns b'\xe0'. This behavior is probably good, but I guess it should be documented (along with other special characters), since it's not a valid utf-8 value even though the terminal encoding is utf-8. (The naive `click.getchar().decode('utf-8')` would crash on this example with `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 0: unexpected end of data`.)

**Comment by fdavis** [comment]
hey @pkch is this still an issue for you? I don't seem to get this running on master (different python3 invocation because I seem to get a str type back in py3)

```
(.clickve) [~/git/click]$ python2 -c 'import click;print(click.getchar().decode("utf-8").__repr__())'
u'\x1b[A'
(.clickve) [~/git/click]$ python -c 'import click;print(bytes(click.getchar(),"utf-8").__repr__())'
b'\x1b[A'
```
