### ISSUE TITLE
Inconsistent return type from click.getchar()

### ISSUE THREAD

**Issue by pkch** [pallets/click#822]
It [seems](https://github.com/python/typeshed/pull/1473#issuecomment-313962504) that `click.getchar()` will return `bytes` under python 3 / Windows, and `str` under any other combination of python version and platform. Is this the intended behavior or a bug?

I wanted to update the stub for `click` but if it's a bug and can be fixed soon, I can leave the typeshed stub unchanged.

**Comment by ScottSturdivant** [comment]
The [documentation ](http://click.pocoo.org/6/api/#click.getchar) states: 

> This will always return a unicode character

I've witnessed the same behavior (``bytes`` w/Python3 and Windows, ``str`` elsewhere) and to me, this inconsistency is a bug.

**Comment by kip-13** [comment]
The python 3 [doc's](https://docs.python.org/2/library/msvcrt.html#msvcrt.getch) is clear with this:
> Read a keypress and return the resulting character as a byte string

In python 2 the [doc](https://docs.python.org/2/library/msvcrt.html#msvcrt.getch) say this:
> Read a keypress and return the resulting character

**Comment by JelleZijlstra** [comment]
Those are docs for the standard library, not for click.

**Comment by kip-13** [comment]
@JelleZijlstra I know, but if you see the code of [getchar](https://github.com/pallets/click/blob/master/click/_termui_impl.py#L519) you understand why I mentioned the module `msvcrt`

**Comment by sirosen** [comment]
Closed by #1108
