### ISSUE TITLE
click vs python-fire

### ISSUE THREAD

**Issue by balta2ar** [pallets/click#827]
Could you please extend the docs with a comparison to python-fire ("why" section)? Thank you.

**Comment by balta2ar** [comment]
@davidism would you care to comment please?

**Comment by max-sixty** [comment]
It was a shame this was closed unanswered. 
After reviewing both tools, we're staying on Click given its more explicit interface. While you can do as you wish, a response to the question would be helpful context and demonstrate openness.

**Comment by davidism** [comment]
There are a ton of command line libraries, it's unmaintainable to keep a comparison list up to date, and I don't really like the idea of telling people what one library thinks of another in general. Our docs should, as in your case, sell us without comparisons. The existing comparisons to argparse (standard library) and docopt (different goals) are mostly there to point out what Click is.

Personally, I'm sure Fire is fine for what it's designed for, but I know nothing about it so I can't say what it's design goals were, let alone how it compares to Click in a fair way.
