### ISSUE TITLE
Redeploy the website

### ISSUE THREAD

**Issue by eli-b** [pallets/click#829]
Looks like the website isn't serving the latest version of the docs.
Compare the line "At the moment, it is strongly recommended to" in [https://github.com/pallets/click/blob/master/docs/python3.rst](https://github.com/pallets/click/blob/master/docs/python3.rst) with the line "At the moment, it is strongly recommended **is** to" in [http://click.pocoo.org/5/python3](http://click.pocoo.org/5/python3).

**Comment by cubranic** [comment]
Also, http://click.pocoo.org/ redirects to http://click.pocoo.org/latest/, which then redirects to http://click.pocoo.org/5/. I thought the 'latest' should be v6 stream?

**Comment by cubranic** [comment]
@davidism 'click.pocoo.org' still redirects to v5. Can you provide the reason for your decision to close the issue? The web site is clearly not serving the docs for the current version on PyPI, which is v6.7.

**Comment by davidism** [comment]
#503

**Comment by cubranic** [comment]
That's useful, thanks.

**Comment by davidism** [comment]
Unless you're running into a specific issue with chains in 6, use 6.
