### ISSUE TITLE
Legacy 1.x option handling mis-identifying situation

### ISSUE THREAD

**Issue by joshorr** [pallets/click#833]
When you use the `make_pass_decorator` with an option callback like in the code snippet at the end of this issue, it mid-identifies the method as a 1.0 option method, and passes the wrong arguments to the method.

Traced the problem to `click.core.invoke_param_callback(...)`. It thinks the number of args is zero, because of the use of (*args, **kwargs) in the decorator.

I can change my method to be `config_schema(__name__, option_value):`, but this will break when you get around to removing this legacy adaptation, as at that point it will go to the 2.0 style.

Not sure what the best solution here is, but thought I would open an issue as it seems to be the incorrect behavior.

Code Example/Reference:

```
pass_config = click.make_pass_decorator(__name__, ensure=True)


@pass_config
def config_schema(__name__, ctx, name, schema):
    pass


schema_option = click.Option(
    param_decls=['--schema'],
    default='testing',
    help='Schema to use, defaults to "testing".',
    callback=config_schema,
)


command.params.append(schema_option)
```

**Comment by davidism** [comment]
This behavior started raising a better `DeprecationWarning` in 7.1, and will be removed in 8.0.
