### ISSUE TITLE
Improve behavior of `show_default` with feature switches

### ISSUE THREAD

**Issue by jwodder** [pallets/click#836]
Consider:

```
import click

@click.command()
@click.option('-A', '--asc', '--ascending', 'direction', flag_value='asc',
              default=True, show_default=True, help='Sort in ascending order')
@click.option('-D', '--desc', '--descending', 'direction', flag_value='desc',
              help='Sort in descending order')
def main(opt):
    pass

if __name__ == '__main__':
    main()
```

```
$ python feature-switches.py --help
Usage: feature-switches.py [OPTIONS]

Options:
  -A, --asc, --ascending    Sort in ascending order  [default: True]
  -D, --desc, --descending  Sort in descending order
  --help                    Show this message and exit.
```

Yes, technically, it *is* true that `--ascending` is the default, but that's not really the best way to show it.  When using `show_default` with feature switches, it would make more sense to just show `[default]` instead of `[default: True]` next to the description of the default option.

**Comment by jcrotts** [comment]
I'm not sure this is enough of an argument for changing the way options are listed. Feel free to submit a PR with an implementation though and I'd be happy to look at it.

Also In your case it might make sense to make the flag options custom classes that are mutually exclusive, so its really clear to your user.
https://stackoverflow.com/questions/37310718/mutually-exclusive-option-groups-in-python-click
