### ISSUE TITLE
Provide behaviour without raising Abort() exception

### ISSUE THREAD

**Issue by wavvs** [pallets/click#839]
```python
def prompt(text, default=None, hide_input=False, confirmation_prompt=False,
           type=None, value_proc=None, prompt_suffix=': ', show_default=True, err=False,
           show_choices=True):
```
For example, need behaviour without raising Abort() exception in `prompt` function.

**Comment by ThiefMaster** [comment]
What exactly are you asking for? In which case do you want Abort to not be raised?

**Comment by wavvs** [comment]
I've several `click.prompt` functions and I would not like handling exception, because in my case I should do it in several places and it'll be excess to write blank try-except in each case, so I thought you could add feature I described above. Thanks.

**Comment by ThiefMaster** [comment]
Again, what are you doing that triggers exceptions?

**Comment by wavvs** [comment]
Sorry, it's keyboard interrupt.

**Comment by ThiefMaster** [comment]
Did you CTRL+C? Why would you NOT want to abort in that case? You are not supposed to catch that exception btw, except to do some cleanup and then terminate or abort whatever the user was doing.

**Comment by wavvs** [comment]
1. Yes, ctrl+c
2. _Default behaviour_
```
>>> import click
>>> a = click.prompt('sdv') # ctrl+c
sdv: Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\click\termui.py", line 73, in prompt_func
    return f('')
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\click\termui.py", line 89, in prompt
    value = prompt_func(prompt)
  File "C:\Python34\lib\site-packages\click\termui.py", line 80, in prompt_func
    raise Abort()
click.exceptions.Abort
```
_Desired behaviour_
```
>>> import click
>>> a = click.prompt('sdv', <some argument here>) # ctrl+c
>>>
```
[Reason](https://github.com/pallets/click/issues/839#issuecomment-321890222)
If I'm wrong somewhere I'm sorry. Thank you.

**Comment by atapin** [comment]
@ThiefMaster please take a look at https://github.com/dbcli/mycli/issues/517 for the use case

**Comment by jcrotts** [comment]
Closing this, you can catch the exception and handle it around your click entry point, or make a wrapper for the click prompt to do this.
