### ISSUE TITLE
A way not to sys.exit after printing help

### ISSUE THREAD

**Issue by davidc** [pallets/click#845]
I'm using click interactively. Everything works fine until the user enters an incomplete command - e.g. there is "vm show" and "vm list" but they just enter "vm". The help is correctly printed, but it then exits the whole program. Can we have something on the context indicating it is being called interactively and never to exit?

I have tried overriding ctx.exit but either it doesn't work or I'm doing it wrong; in any case this seems an ugly way to hack around it.

```python
def interactive_mode():
    while True:
        command_line = prompt()

        ctx = cli.make_context(None, command_line.strip().split(' '))

# does not work:
#        def new_exit(self, code=0):
#            print("exit requested")
#        ctx.exit = new_exit

        try:
            cli.invoke(ctx)
        except Exception as e:
            print(e)


@click.group(invoke_without_command=True if sys.stdout.isatty() else False)
@click.pass_context
def cli(ctx):
    if ctx.invoked_subcommand is None:
        print("Going interactive!")
        interactive_mode()
    pass


@click.group()
def vm():
    """VM Operations"""
    pass


cli.add_command(vm)


@click.command()
def list():
    """List VMs"""
    print("Listing VMs")


vm.add_command(list)

if __name__ == '__main__':
    cli()


```

**Comment by untitaker** [comment]
Please catch `SystemExit`. You also might want to check out `click-repl`.
