### ISSUE TITLE
Question: abusing click to parse other apps command lines

### ISSUE THREAD

**Issue by pmatos** [pallets/click#847]
I am wondering if anyone has been able to abuse click to parse command lines of other programs. Imagine I want to create a `git` command line parser `gitp` but instead of receiving a command line like git, it receives a file with several git calls and for each it parses its command line and stores somewhere in a database.

How would I be able to abuse click like this? Any suggestions?

**Comment by untitaker** [comment]
Please use StackOverflow for questions.
