### ISSUE TITLE
Asyncio integration

### ISSUE THREAD

**Issue by tailhook** [pallets/click#85]
It would be nice if I could do:

```
@click.command()
@ascyncio.coroutine
def command():
    yield from whatever
```

I think the only place that should be changed to make that work would be `Context.invoke` (check if function is coroutine, do `loop.run_until_complete()`). But it's hard to subclass context in current click.

Would you mind making this functionality built-in?

**Comment by jamesstidard** [comment]
Just curious if this is still the recommended practice now that async/await is a first-class language feature.

I feel a little dirty having to redundantly decorate all my commands with a `@coroutine` wrapper as well as a `async def`. Or maybe theirs a neater way that I've not thought of where I don't need to decorate each command.

Thanks - minor thing I know.

**Comment by Tails** [comment]
> Just curious if this is still the recommended practice now that async/await is a first-class language feature.
> 
> I feel a little dirty having to redundantly decorate all my commands with a `@coroutine` wrapper as well as a `async def`. Or maybe theirs a neater way that I've not thought of where I don't need to decorate each command.
> 
> Thanks - minor thing I know.

Any update on this? Is it possible to pass an async generator into a progressbar as iterable for example?

**Comment by chrahunt** [comment]
Just to reinforce that this does not need to be in click, there are plugins like [click-contrib/trio-click](https://github.com/click-contrib/trio-click) that provide the desired functionality.

**Comment by amitkot** [comment]
Can this issue be re-opened and considered?

**Comment by jodal** [comment]
This is an updated version making use of `asyncio.run()` from Python 3.7:

``` python
import asyncio
from functools import wraps

def coro(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        return asyncio.run(f(*args, **kwargs))

    return wrapper
```

Usage:

``` python
@click.command()
@coro
async def command():
    await asyncio.sleep(1)
    click.echo("Delayed hello")
```

**Comment by vartagg** [comment]
BTW, there is the fork of click, which allows to use it with asyncio https://github.com/python-trio/trio-click

**Comment by rabernat** [comment]
New click user here. Thanks for this great tool.

I naively tried decorating a coroutine with `@click.command()` and received the cryptic error:

```
sys:1: RuntimeWarning: coroutine 'main' was never awaited
```

I believe it would be reasonable for `@click.command()` to examine the function it is decorating and, if a coroutine is found, automatically wrap it with the `@coro` decorator suggested above. In the meantime, the workaround worked great.
