### ISSUE TITLE
[RFC] new Executable param type

### ISSUE THREAD

**Issue by blueyed** [pallets/click#856]
It would be derived from `Path` (which would get a new flag `executable`), and then `Executable` would look for if a command exists in `$PATH` - using `shutil.which` (https://github.com/python/cpython/blob/3.6/Lib/shutil.py#L1093), which would need to be vendored then for older Python versions.

This would allow for validation of params that are then meant to be run, e.g. via `subprocess.call`.

**Comment by fdavis** [comment]
@blueyed, thanks for the feedback!
As far as workarounds go you should be able to achieve this [with callbacks](http://click.pocoo.org/5/advanced/#parameter-modifications)

I'm not sure I understand the use case though. Could you provide more detail about what you need to accomplish with this new type?

**Comment by davidism** [comment]
It's an interesting idea, but it's also fairly niche, the number of checks available to `Path` are getting out of hand, and this check can be done really easily in a callback if needed.
