### ISSUE TITLE
Can I access ctx within @resultcallback function?

### ISSUE THREAD

**Issue by haje01** [pallets/click#858]
I am trying Multi Command Pipelines as explained in http://click.pocoo.org/5/commands/#multi-command-pipelines

I need to invoke other command within result callback function.
But @pass_context decorator does not work since it is not a command.
Are there any ways to access ctx in result callback function?

**Comment by dsully** [comment]
You can use:

```
import click

ctx = click.get_current_context()
```

To get the global context.
