### ISSUE TITLE
TypeError with ClickException on Python 3

### ISSUE THREAD

**Issue by blueyed** [pallets/click#862]
```python
from click.exceptions import UsageError
exc = UsageError('foo')
print(exc)
```

> `TypeError: __str__ returned non-string (type bytes)`

This seems to be there since a while already: https://github.com/pallets/click/commit/8c6c150

**Comment by mitsuhiko** [comment]
This is fixed in 9bd66b397fd85f11330afd19ab72390616b2bf48
