### ISSUE TITLE
Release of 6.8 bugfixes?

### ISSUE THREAD

**Issue by jensens** [pallets/click#885]
We are using this convinient library in the new [plonecli](https://github.com/plone/plonecli) and are depending on some of the fixes scheduled for an upcoming 6.8 release. 

- Is there already a date for this release? 
- Is there any work to be done before, were we may help? 

A release soon would be really great!

**Comment by BurakDev** [comment]
Need release too, is the release planned ? @mitsuhiko

**Comment by pawelad** [comment]
I'd also be happy to help and am really excited about #755

**Comment by MrTango** [comment]
We really could use an release here.
@mitsuhiko @untitaker how can we help to make this happen?

**Comment by aldanor** [comment]
The latest release was over a year ago, with master being almost 200 commits ahead. Wondering if 6.8 is planned anytime soon?

**Comment by mitsuhiko** [comment]
Yep. Probably this month.

**Comment by jafd** [comment]
/me looks at the calendar...
...Oh, it's almost June.

While more contributors could certainly help squashing bugs, I don't see how outside contributors can help with release management.
