### ISSUE TITLE
Documentation appears incorrect for passing context

### ISSUE THREAD

**Issue by combusean** [pallets/click#888]
http://click.pocoo.org/6/commands/#passing-parameters

In this documentation, it looks like obj is initialized automatically by passing it in under the `if __name__` conditional.   

I haven't found that to be the case with click 6.7.  `ctx.obj` was constantly `None` until I initialized it to a hash in the `group` block listed here.  After that, it worked as expected.

https://github.com/pallets/click/issues/200

Is this normal behavior?

**Comment by nelsonlim** [comment]
Same issue here. 

```
@click.group()
@click.option('--debug/--no-debug', default=False)
@click.pass_context
def cli(ctx, debug):
    ctx.obj['DEBUG'] = debug

@cli.command()
@click.pass_context
def sync(ctx):
    click.echo('Debug is %s' % (ctx.obj['DEBUG'] and 'on' or 'off'))

if __name__ == '__main__':
    cli(obj={})
```
The above code block from the documentation does not work for me. context.obj seems to always return None. 

```
@click.group()
@click.option('--debug/--no-debug', default=False)
@click.pass_context
def cli(ctx, debug):
    if ctx.obj is None:  # Doesn't work as of 3.0
        ctx.obj = {}
    ctx.obj['DEBUG'] = debug

@cli.command()
@click.pass_context
def sync(ctx):
    click.echo('Debug is %s' % (ctx.obj['DEBUG'] and 'on' or 'off'))

if __name__ == '__main__':
    cli(obj={})
```
This works though. Is this suppose to be the correct usage? If it is, then the documentation needs to be updated.

Thanks!

**Comment by lordmauve** [comment]
I was not able to reproduce under Python 2.7, 3.5, 3.6, 3.7, 3.8 under any tag 6.3-7.0. Documented example works as intended.

**Comment by davidism** [comment]
Thanks for checking, the example works for me as well.
