### ISSUE TITLE
[Help required] Display command help if required parameter is missing

### ISSUE THREAD

**Issue by robinbowes** [pallets/click#891]
I'm writing a cli app using click
Invocation looks something like this:

```
$ mps deploy --component web --stage dev --label build_1234
```

If I type `mps` without any command I get the top-level help output, ie. that which is displayed with `--help` option. This is what I want to happen

 If I type `mps deploy` without any options it throws a `Missing option --component` error because the `--component` option is required. This is not what I want to happen.

In the event of any missing options, I'd like to display the command-level help output ie. that which is displayed when I run `mps deploy --help`.

Is there some way I can intercept the `Missing option` error and display the full `mps deploy --help` output?

**Comment by Quimoniz** [comment]
I had a similar issue, did you try using the context, like in [this example](https://github.com/pallets/click/issues/886)?

For me using `click.echo(ctx.get_help())` worked.

**Comment by davidism** [comment]
Decision made to keep current "see --help" message in #502.
