### ISSUE TITLE
Choice option with "multiple=True" breaks with generator expressions

### ISSUE THREAD

**Issue by sscherfke** [pallets/click#892]
If you populate the choices of a `click.option('--name', multiple=True, type=click.Choice())` with a generator expression and not with a list, the order in which click accepts the options becomes relevant.

This script reproduces the issue (it is not as minimal as it could be to make the use-case more clear):

```python
import click


OPTIONS = {
    'warning': 4,
    'refactor': 8,
    'convention': 16,
}


@click.command()
# Breaks with generator expression
@click.option('--ignore', '-i', multiple=True,
              type=click.Choice(o[0] for o in sorted(OPTIONS.items(), key=lambda i: i[1])))
# Works with normal list
# @click.option('--ignore', '-i', multiple=True,
              # type=click.Choice([o[0] for o in sorted(OPTIONS.items(), key=lambda i: i[1])]))
def main(ignore):
    click.echo(ignore)


if __name__ == '__main__':
    main()
```

```console
$ python clickwtf.py -i refactor -i convention
('refactor', 'convention')

$ python clickwtf.py -i convention -i refactor
Usage: clickwtf.py [OPTIONS]

Error: Invalid value for "--ignore" / "-i": invalid choice: refactor. (choose from )
```

- Python versino: 3.6.3 
- click version: 6.7

**Comment by mitsuhiko** [comment]
Generator expressions are not supported there and there is no plan to support this. The choices need to be a sequence and not an iterable

**Comment by sscherfke** [comment]
I can understand that, but I think the docs should then be more clear about this. Or, alternatively, generators should be rejected with a `TypeError`, because currently you can just pass a generator, trigger the bug and be very confused until you find out what happend.

**Comment by mitsuhiko** [comment]
But similar breakage happens if you pass strings, integers etc. Python is (sadly) a weakly typed language and it's tricky to avoid all such things. I think it's a very rare case that someone would pass a generator expression here in particular because syntax wise it's mostly a syntax error.

**Comment by sscherfke** [comment]
But something like "use a list or it might brake in subtle ways" in the docs would still help a bit :)

**Comment by mitsuhiko** [comment]
Fair. Accepting a PR for that :D
