### ISSUE TITLE
with statement never runs exit code when calling a click.Command

### ISSUE THREAD

**Issue by galv** [pallets/click#894]
Hi,

I'm a new user. I'm intrigued, but have run into an annoying bug. Steps to reproduce:

Click 6.7, python 2.7

```
import click
from contextlib import contextmanager


@contextmanager
def my_context():
    print "enter"
    yield
    print "exit"


@click.command()
def run():
    print "Running click command"


if __name__ == '__main__':
    with my_context():
        run()
```

Output I get:

```
enter
Running click command
```

Expected output:
```
enter
Running click command
exit
```

The work around is to put the with statement within the fun() function, but it's a little disappointing and ugly given that adds an extra level of indentation.

**Comment by ThiefMaster** [comment]
Most likely click uses `sys.exit()` which raises `SystemExit`. If you want the post-yield code of a context manager to run, you need to write your context manager like this (doing this is always a good idea, not just with click):

```
try:
    yield
finally:
    ...
```

**Comment by galv** [comment]
Thank you for the python-foo! I didn't realize that.

I also want to point out based on sleuthing in the source code that you can call your click command with standalone_mode=False, to prevent the confusing silent exit (If SystemError propagates all the way to the start of a python script, it *won't* print a stack trace, which is out of line with the way most execeptions work).

**Comment by ThiefMaster** [comment]
`SystemExit` never prints a stack trace, simply because it is not an error but an exception that indicates that Python should exit (because `sys.exit()` has been called). FYI, this is not a click thing but simply how Python works

**Comment by galv** [comment]
I'm aware. I am noting this for posterity in case others are confused, since the absence of a stack trace suggests that an exception is not being thrown.
