### ISSUE TITLE
Is this project still active/ maintained?

### ISSUE THREAD

**Issue by jensens** [pallets/click#895]
The project looks like the maintainer(s) abandoned it, because

- there  are 62 open pull requests
- 209 open issues
- no recent bugfix releases
- no responses to issues.

**Comment by ShahriyarR** [comment]
+ same question

**Comment by mitsuhiko** [comment]
It is active and maintained. If the pace does not satisfy people then consider this to be a call for more participants :)

**Comment by jensens** [comment]
@mitsuhiko Sure - I can help releasing maintenance releases, see #885

**Comment by mitsuhiko** [comment]
Closing this for #885 now.
