### ISSUE TITLE
Update docs?

### ISSUE THREAD

**Issue by delirious-lettuce** [pallets/click#898]
I just came across this typo in both version 5 & 6 docs (the word `is`):

> it is strongly recommended ***is*** to use Python 2

* http://click.pocoo.org/5/python3/#python-3-support
* http://click.pocoo.org/6/python3/#python-3-support

But looking at the `click` repo itself, I noticed that this typo was already fixed by @jmorganc in #566 on Apr 27, 2016. It seems like the docs on `click.pocoo.org` are out of date?

**Comment by davidism** [comment]
existing docs don't get rebuilt

**Comment by delirious-lettuce** [comment]
@davidism ,

Ok, it just seemed odd to merge #566 almost two years ago but never update the actual docs.
