### ISSUE TITLE
Pager eats color codes on Windows

### ISSUE THREAD

**Issue by MinchinWeb** [pallets/click#901]
`click.echo_with_pager()` eats the embedded ANSI colour codes, at least on my machine. I'm using Clcik 6.7 (from pip), Python 3.6.3 on Windows 10 x64.

Below is the same text, the first though the pager, and the second through the "normal" `click.echo()` function:

![image](https://user-images.githubusercontent.com/1548809/33798713-e00d6340-dcda-11e7-9871-8f58c1a4527e.png)

**Comment by fdavis** [comment]
possibly related to #857

**Comment by bildzeitung** [comment]
Looks like this works if a parameter is passed in for `color` in `echo_with_pager()`, e.g.

![image](https://user-images.githubusercontent.com/56396/57233662-131b4f80-6fed-11e9-930d-d88c5104a50b.png)

**Comment by jcrotts** [comment]
@bildzeitung Is this unclear in the documentation or can this be closed?
