### ISSUE TITLE
Explicit list of sub-commands; only import when needed

### ISSUE THREAD

**Issue by cdeil** [pallets/click#904]
I love click and want to use it to construct a command line interface that has a lot of sub-commands. I want to maintain those sub-commands in separate files and, to have fast `--help` for the main command, as well as fast execution of the sub-commands, I would like to only import the file containing a sub-command if needed. This is for speed, importing my whole analysis package takes a few seconds, and I'd like to have `--help` on the main command be fast.

I've seen http://click.pocoo.org/5/commands/#custom-multi-commands but that doesn't do what I want, it imports all files containing sub-commands even if I just do `--help` on the main command.

So what I want is to have an explicitly list of sub-commands like e.g.
```
sub_commands = [
    dict(name='cmd1', module='cmd1_package.cmd1_module', func='cmd1_cli', description='Sub-command 1'),
    dict(name='cmd2', module='cmd1_package.cmd2_module', func='cmd2_cli', description='Sub-command 2'),
]

```
and use that to make the list of available sub-commands on the help of the main command, and then if a given sub-command is in the args, import and execute that.

I've looked a bit at `MultiCommand` (see https://github.com/cdeil/python-cli-examples/blob/master/click/greet/cli_mc.py), but I couldn't figure out how to achieve the lazy-loading yet.

**Comment by stopthatcow** [comment]
This can be resolve by using lazy imports. I maintain a CLI that uses click and uses this trick to lazily import modules the first time they are used. See [here](https://github.com/stopthatcow/zazu/blob/ac49310cedda554a8bedcc6241b14c10dd9b28f9/zazu/util.py#L11)
Another way to be sure that your CLI starts quickly is to build and install it a bidst_wheel. 
While this CLI has lots of dependencies and subcommands but it launches in <70ms.

**Comment by blueyed** [comment]
See also #945 - I think this issue here can be closed, and the documentation should get improved (via #945).

**Comment by dsully** [comment]
I had a similar need, and have two click.Group subclasses, one of which loads pre-generated help in the form of a Python module (it could be JSON, or whatever).

```
class GeneratedHelpGroup(click.Group):

    def format_commands(self, ctx: click.Context, formatter) -> None:
        """Invoked when '--help' needs to generate the 'commands' section of the help text.

        We override it to provide a fast top level help
        """

        if ctx.parent:
            path = [ctx.parent.info_name, ctx.parent.invoked_subcommand]
        else:
            path = [ctx.info_name]

        rows: List[Tuple[str, str]] = []

        module = import_module(_package_name(base=GENERATED_PACKAGE, path=path))

        if module:
            rows = module.text

        if rows:
            with formatter.section('Commands'):
                formatter.write_dl(rows)
```

GENERATED_PACKAGE is just the base package to your help. Something like: ['mycli', 'generated'] which corresponds to a Python package.

If there is interest, I can package this up into a module.
