### ISSUE TITLE
click.echo_via_pager() throws not enough memory on Windows7

### ISSUE THREAD

**Issue by abhisheksinha89** [pallets/click#905]
echo_via_pager method causes the following issue on Windows 7 SP1:
Not enough memory

Repro:
```
import click

if __name__ == '__main__':
    click.echo_via_pager("Hello mate!")
```

My investigation shows this line to be the issue:
https://github.com/pallets/click/blob/92532b58b1205b70737f837567f67c59949f3dc2/click/_termui_impl.py#L360

I am not aware of any good workarounds and this is causing users of https://github.com/dbcli/mssql-cli on windows7 this very same issue. 

Can you please let us know any workarounds you are aware of or does it need to fixed in click?

**Comment by davidism** [comment]
Closing as we don't support Windows 7 (and neither does Microsoft as of 2020-01-14). If your project wants to use a pager where it's supported and also support Windows 7, you could pick which function to use:

```python
if not win7:
    echo_via_pager = click.echo_via_pager
else:
    echo_via_pager = click.echo
```
