### ISSUE TITLE
Better pretty print support when click.choice has a large array of items

### ISSUE THREAD

**Issue by joeheyming** [pallets/click#910]
I am using click.choice with 38 items.  I tried to make it look nicer by sorting the items, but it still is very dense:

--foo-bar    [item0|item1|item2|item3|item4|item5|item6|item7|item8|item9|item10|item11|item12|item13|item14|item15|item16|item17|item18|item19|item20|item21|item22|item23|item24|item25|item26|item27|item28|item29|item30|item31|item32|item33|item34|item35|item36|item37]

It would be nice to say:

click.Choice(myItems, itemsPerRow=4)

then it would output:

--foo--bar    [ item0 | item1 | item2 | item3 |
		 item4 | item5 | item6 | item7 |
		 item8 | item9 | item10 | item11 |
		 item12 | item13 | item14 | item15 |
		 item16 | item17 | item18 | item19 |
		 item20 | item21 | item22 | item23 |
		 item24 | item25 | item26 | item27 |
		 item28 | item29 | item30 | item31 |
		 item32 | item33 | item34 | item35 |
		 item36 | item37 ]

or something like that.

**Comment by mitsuhiko** [comment]
I'm unlikely going to work on this. I would be willing to accept a patch if it's well executed however.

**Comment by joeheyming** [comment]
Do you like my idea of adding an additional argument? Or do you have any other ideas?

**Comment by mitsuhiko** [comment]
I don't think rendering should be controlled by the parameters more than it already is. Ideally the auto rewrapping takes into account the rendering of items better automatically.
