### ISSUE TITLE
how to deal with reserved words options

### ISSUE THREAD

**Issue by ali7line** [pallets/click#915]
`@click.option('--dir', '-d', type=click.Path(exists=True, dir_okay=True), metavar='DIR')`

 --dir replaces dir which is a reserved word, anyway to change it?

**Comment by LuckyJosh** [comment]
You can specifiy the variable name in a third positional argument to `click.option`. The argument being a string containing no dashs. 
Like it is done here with `"transformation"`: 
http://click.pocoo.org/5/options/#feature-switches

**Comment by fdavis** [comment]
Thanks for the Q&A feel free to reopen if your issue is not properly addressed
