### ISSUE TITLE
Conditionally disable prompts

### ISSUE THREAD

**Issue by choovick** [pallets/click#921]
First of all, thanks a lot for this great package! CLI made easy!

I'm using `prompt` parameter in my options so CLI can be used interactively and well as scripted.
Also applying `default` parameters to each required option so users have to type less.

**Problem:** Defaults do not apply to options which have `prompt` parameter, and I cant find an elegant way to control that behaviour.

So when using CLI in non-interactive manner I have to specify all command options even the ones that have defaults.
Ideally I'm looking for an option to disable prompts globally, this way when using CLI in non-interactive way, I have to only specify options that have no defaults and are required.

But so far all my explorations are unsuccessful.

Any help or hints on how to approach this is appreciated. Thanks!

**Comment by choovick** [comment]
Hi @lbenka,

Thanks for getting traction on this, still using amazing Click CLI and considering to use other library to enable conditional user prompts, but it will be great if Click did it out of the box.

You example is perfect, quiet switch to suppress user inputs will be useful to be used in CD/DC pipelines where user is not evolved.

Our company builds another nodejs based cli and it behaves as following:
If one of parameters is provided, user input also gets disabled. As the result defaults will applied or error will be generated if required params are not provided.

Hope this clarifies things.

**Comment by OskarPersson** [comment]
Until there is a built-in solution, this answer on Stackoverflow describes a useful workaround:

https://stackoverflow.com/questions/32656571/python-click-adding-an-option-that-modifies-the-behavior-of-other-parameters

For a `-q` flag you could do:

```python
def deactivate_prompts(ctx, param, value):
    if value:
        for p in ctx.command.params:
            if isinstance(p, click.Option) and p.prompt is not None:
                p.prompt = None
    return value

@click.command()
@click.option('-q/--quiet', default=False, is_eager=True, expose_value=False, callback=deactivate_prompts)
@click.option('--count', prompt='How many times?' default=1, help='Number of greetings.')
@click.option('--name', prompt='Your name?', help='The person to greet.', default='computer')
def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for x in range(count):
        click.echo('Hello %s!' % name)
    ...
```

**Comment by pisymbol** [comment]
I am having a similar issue in that defaults in general are not honored by prompt=True. So something like this:

```
@click.option('-u', '--username', prompt=True, default=lambda: os.environ.get('USER', ''), metavar='<username>', help='Username')
```

IF the user calls my command line tool with: USER=foobar foocli the user is still asked for username (it shows the default value though). 

Shouldn't prompt honor default values?

**Comment by davidism** [comment]
@pisymbol it would never prompt then, since you've specified a default. See the PR linked above your comment in this thread: #1618

**Comment by pisymbol** [comment]
@davidism If no default is specified, prompt, i.e. None.
