### ISSUE TITLE
Feature discuss: about logger.

### ISSUE THREAD

**Issue by wangwenpei** [pallets/click#923]
Thanks Click, it's awesome! 
I am planing add logger feature to click. but I am not sure it can be merged. 
maybe we should discuss it first?

I am the author of [Cliez](https://github.com/wangwenpei/cliez).  it's a CLI tool like Click with same goal. we‘ve use it in our projects for years . Recently, we are migrating our projects from Django to Flask, and we found `Click`. it's really a good idea use decorator instead parsers.

after I read the `Click` code. I found it should add a logger feature like `Cliez`. it may look like this:

```
@click.command()
@click.option('--swarm')
@click.option('--k8s')
def deploy(swarm, k8s):
    click.echo('hi')

    #--------> new feature code    
    click.logger.debug('debug')
    click.logger.info('info')
    #<--------
    pass

```
and of course, we may need set logger level feature too.
I am thinking about it. it may looks like this (DRAFT VERSION, just for disscus).

```
@click.command(logger_config={ 
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': { 
        'standard': { 
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        },
    },
    'handlers': { 
        'default': { 
            'level': 'INFO',
            'formatter': 'standard',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': { 
        '': { 
            'handlers': ['default'],
            'level': 'INFO',
            'propagate': True
        },
        'django.request': { 
            'handlers': ['default'],
            'level': 'WARN',
            'propagate': False
        },
    },
'click_priority':10       # <--------- click custom option 
})
@click.logging_option()
def logging():
    pass



```

`click_priority` is used to control merge order  to work with other people command code.

`@click.logging_option` is equal 

```
@click.option('--logging',type=click.Choice(['debug', 'info',
                                              'warning', 'error', 'critical'
 ]))
@click.option('--logging-channel',multiple=True)

```

this is used to as a switch for user.

**Comment by flokli** [comment]
Maybe you'd like to have a look at https://github.com/click-contrib/click-log ;-)

**Comment by wangwenpei** [comment]
I see it, some of feature is I need. 
well, I will make this feature as extension.  

closed.
