### ISSUE TITLE
Bash completion is broken when a default value is specified for a Choice Argument

### ISSUE THREAD

**Issue by atherra** [pallets/click#925]
Adding a default value to an argument of the Choice type will hose autocompletion. Can be tested as follows:
 
Slightly modifying test_argument_choice test example in test_bashcomplete.py to add a default argument:
```
def test_argument_choice():
    @click.command()
    @click.argument('arg1', required=False, type=click.Choice(['arg11', 'arg12']))
    @click.argument('arg2', required=False, type=click.Choice(['arg21', 'arg22']), default='arg21')
    @click.argument('arg3', required=False, type=click.Choice(['arg', 'argument']))
    def cli():
        pass

    assert list(get_choices(cli, 'lol', [], '')) == ['arg11', 'arg12']
    assert list(get_choices(cli, 'lol', [], 'arg')) == ['arg11', 'arg12']
    assert list(get_choices(cli, 'lol', ['arg11'], '')) == ['arg21', 'arg22']
    assert list(get_choices(cli, 'lol', ['arg12', 'arg21'], '')) == ['arg', 'argument']
    assert list(get_choices(cli, 'lol', ['arg12', 'arg21'], 'argu')) == ['argument']
```

Result:
```
Traceback (most recent call last):
  File "test_compl.py", line 19, in <module>
    test_argument_choice()
  File "test_compl.py", line 14, in test_argument_choice
    assert list(get_choices(cli, 'lol', ['arg11'], '')) == ['arg21', 'arg22']
AssertionError
```

**Comment by atherra** [comment]
Looks like the logic in _bashcomplete.is_incomplete_option is unable to distinguish between an argument value provided by the user and the one defined as the default.

@stopthatcow any tips to work around this, or would that require a change in click's core?

**Comment by stopthatcow** [comment]
I have not tested thi ans will later this evening but If required=false and default is set...how can click differentiate an unsupplied arg2 (defaulted) from a supplied arg3? I may be wrong but is this is actually a valid case?

**Comment by stopthatcow** [comment]
Looking into this more, this is deeper than just the bash completion layer...some changes will need to be made to core.py to not fill the value with the default in the special case of completion parsing. Currently completion treats defaulted values as if they are already supplied by the user.

**Comment by atherra** [comment]
@stopthatcow that's about what I'd gathered. Thank you for taking a look.

**Comment by stopthatcow** [comment]
@atherra you can take a look at my CL #930 and see if it fixes your issue.
