### ISSUE TITLE
Argument with "--foo" inside quotes is interpreted as an option

### ISSUE THREAD

**Issue by jesseshieh** [pallets/click#933]
Hi, I tried to pass "--foo" as an argument (not an option) to a click command and got an error
```
$ gigalixir set_config bar FOO "--foo"
Error: no such option: --foo
```

The command is set up like this
```
@cli.command()
@click.argument('app_name')
@click.argument('key')
@click.argument('value')
@click.pass_context
def set_config(ctx, app_name, key, value):
```

Since "--foo" is in quotes, I did not expect it to be interpreted as an option.

I can work around this by using `--`, but this isn't what I expected.
```
$ gigalixir set_config bar FOO -- --foo
```

**Comment by ThiefMaster** [comment]
That's completely normal, because quotes are parsed by the shell. You need to escape them or quote them again (`'"--foo"'`) so click actually sees the inner quotes.

**Comment by jesseshieh** [comment]
Ah okay, thanks for explaining!
