### ISSUE TITLE
Importing group commands from separate module

### ISSUE THREAD

**Issue by ejmg** [pallets/click#937]
Hi there.

I have two modules. My driver, `cli.py`, and then another, `parser.py`, which is in a subdirectory, `commands`.

I know one can create a group as follows:

```python
@click.group()
def cli():
    pass
@cli.command()
def foo():
    click.echo("sup")
```
and so forth.

However, according to the docs, if I were to define my subcommands in a separate module (as I have), I must add them as such in `cli.py`:

```python
from myModule.commands import foo, bar

@click.group()
def cli():
    pass
cli.add_command(foo)
cli.add_command(bar)
```
and so forth.

Is there any way to avoid the above and instead declare my subcommands like in the first example while also keeping them in a separate module? 

Importing my driver `cli` into `parser.py` seems to trigger a circular dependency and tells me `AttributeError: module 'myPackage' has no attribute 'cli'` when I attempt using decarators like `@cli.command()`. Actual code as follows:

```python
from quoteBot.quoteBot import cli

@cli.command()
def extractTXT(file):
    """Extracts quotes from a .txt file.

    :param file: the file being parsed
    """
    click.echo("extractTXT called!")
```
Using `import quoteBot.quoteBot` syntax throws the same error, FYI.

This is not a "make or break" issue, I am just interested to know if such logic is possible. Thank you for your time.

**Comment by nelsonlim** [comment]
Could you clarify the folder structure of your .py files? 

Is it?
```
-cli.py
-myModule/
    -commands/
        -parser.py
```

It's a bit hard to tell what the issue might be.

**Comment by ejmg** [comment]
My bad, that is clearly something I should have included. Here is the package:
```bash
├── LICENSE
├── MANIFEST.in
├── quoteBot
│   ├── commands
│   │   ├── authenticate.py
│   │   ├── __init__.py
│   │   ├── parser.py
│   │   └── tweet.py
│   ├── __init__.py
│   ├── __main__.py
│   └── quoteBot.py
├── README.rst
```

My naming might have slightly changed since the original post. `cli` is **inside quotebot.py** and is still the driver.

Thank you for taking the time to respond :slightly_smiling_face:
