### ISSUE TITLE
Passing argument as differently named parameter

### ISSUE THREAD

**Issue by tuukkamustonen** [pallets/click#949]
Trying to get `click.argument` passed with different name to function because variable name is shadowed from higher scope (e.g. `input`, `print`, or whatever imports you might have).

http://click.pocoo.org/6/parameters/#parameter-names states:

> Parameters (both **options** and **arguments**) accept a number of positional arguments which are the parameter declarations. Each string with a **single dash** is added as short argument; each string starting with a **double dash** as long one. If a string is added **without any dashes**, it becomes the internal parameter name which is also used as variable name.

I think it indirectly tells that:

- It *is* possible to pass option as different variable name (e.g. `click.option('--input', 'input_')`)
- It *is not* not possible to pass argument as different name? Because docs just state that string without dashes becomes parameter name, and with `click.argument` we are indeed passing string without dashes, so it's not possible to do something like `click.argument('input', 'input_')`?

Tried it on `test.py`:

```python
import click

@click.command()
@click.argument('input', 'input_')
def hello(input_):
    print('hello')

if __name__ == '__main__':
    hello()
```

Run:

```console
$ python test.py hello
Traceback (most recent call last):
    ...
TypeError: hello() got an unexpected keyword argument 'foo'
```

How can I pass argument as different variable name to the function?

What does `click.argument('first', 'second')` really do, as there's no direct exception thrown from it (but `click.argument('first', 'second', 'third')` throws error instead)?

Running click 6.7.

**Comment by tuukkamustonen** [comment]
Trying to answer myself: found out there is `metavar` parameter, that does the trick:

```
@click.argument('input_', metavar='INPUT')
def hello(input_):
    ...
```

`metavar` just "renames" the parameter in help:

```
Usage: clicktest.py [OPTIONS] FOO_  # not
Usage: clicktest.py [OPTIONS] FOO   # but
```

Would it make sense to mention `metavar` at http://click.pocoo.org/6/parameters/#parameter-names?

On the other hand, I'm still not sure what `click.argument('first', 'second')` does, and why there are two different practices to renaming variable (another positional argument vs. `metavar`)?

**Comment by dawran6** [comment]
Thanks for reporting this. I think the documentation is wrong. In the source code, Option and Argument parses the arguments differently.

I believe this section is only true for Option type:

> Each string with a single dash is added as short argument; each string starting with a double dash as long one. If a string is added without any dashes, it becomes the internal parameter name which is also used as variable name.

**Comment by alexbozhenko** [comment]
Those paragraphs are still little confusing:
https://click.palletsprojects.com/en/7.x/options/#name-your-options
https://click.palletsprojects.com/en/7.x/parameters/#parameter-names

In parameters section, information about strings with single and double dashes is irrelevant, right?

Probably example like this should be added:
```
click.Argument(["other_arg"], metavar="SOME_OTHER_ARG")
```

And also should this behavior be changed?:
```
click.Argument(["other_arg", "other_arg_name_that_does_nothing"])
```
