### ISSUE TITLE
Context.invoke doesn't run callback on the other command

### ISSUE THREAD

**Issue by maroux** [pallets/click#950]
When invoking a command using `ctx.invoke(other_cmd, ...)`, I expected that the parameters passed would be validated per `other_cmd`'s `callback` methods as declared on the arguments but that seems to be not the case.

Is this a known thing? Is there a workaround?

**Comment by fdavis** [comment]
I'm going to guess this is not a known thing and probably a bug. 
http://click.pocoo.org/5/advanced/#invoking-other-commands

Sample code partially taken from docs linked above. I run with the `cli()` call and the arg `dist` to show this bypasses the callback and I call `cmd()` with `--foo -1` to show I still run into the validation error when calling directly
  

```python
import click
cli = click.Group()

def validate_pos_int(ctx, param, value):
    if value < 0:
        raise click.BadParameter('Value needs to be positive')
    return value

@cli.command()
@click.option('--foo', default=1)
@click.pass_context
def dist(ctx, foo):
    ctx.forward(cmd)
    ctx.invoke(cmd, foo=-1)

@click.command()
@click.option('--foo', callback=validate_pos_int, default=1)
def cmd(foo):
    click.echo(foo)

cli()
#cmd()
```

```
$ python 950.py dist
1
-1
$ vim 950.py ; python 950.py --foo -1  #vim to comment cli(), uncomment cmd()
Usage: 950.py [OPTIONS]

Error: Invalid value for "--foo": Value needs to be positive
```

**Comment by davidism** [comment]
This is intentional behavior. `invoke` occurs in user code, after the command line processing is over, so it should be passed valid Python values that do not need to be processed. See #1124 for a detailed explanation.
