### ISSUE TITLE
AppVeyor builds

### ISSUE THREAD

**Issue by blueyed** [pallets/click#957]
Where can the builds be seen?
https://ci.appveyor.com/project/pallets/click does not seem to exist, and https://ci.appveyor.com/project/mitsuhiko/click appears to be out of date.

Would be nice to have the status integrated with PRs then, too.

**Comment by mitsuhiko** [comment]
Fixed.

**Comment by blueyed** [comment]
Thanks.  (https://ci.appveyor.com/project/mitsuhiko/click)
But it's not enabled for PRs still, is it? (neither on AppVeyor itself nor the GH status integration)

**Comment by blueyed** [comment]
Ah, it is working apparently: https://ci.appveyor.com/project/mitsuhiko/click/history.
Thanks again.
