### ISSUE TITLE
Not support upper case option.

### ISSUE THREAD

**Issue by ahui132** [pallets/click#961]
```
import click
@click.command()
@click.option('-act', default='start')
@click.option('-D', default=False)
def inout(D, act):
    print(D, act)

inout()
```
This code not work: `Error: no such option: -d`

**Comment by ThiefMaster** [comment]
`-act` is wrong, you want `--act`. That might cause such a problem. Also, you probably want `is_flag-True` for the `-D` switch.

**Comment by ahui132** [comment]
```
import click
@click.command()
@click.option('--act', default='start')
@click.option('--D', default='xxx')
def inout(D, act):
    print(D, act)

inout()
```
Same error

**Comment by ThiefMaster** [comment]
Generally, short (single-letter) options use a single dash, while long options use two dashes. Almost all command line tools do this.

Actually looking at your error again, you define  `-d` but your option is named `-D`...

**Comment by ahui132** [comment]
The options is case sensitive, while the function defined accepts lower case only. That's what makes me confused.  
```
$ cat <<MM | p -
import click
@click.command()
@click.option('-D', is_flag=True)
def inout(d):
    print(d)

inout()
MM
False
```

**Comment by ThiefMaster** [comment]
Since Python variables should be `snake_case` it makes sense for click to convert them to lowercase. You can override the name of the kwarg if you prefer something different.
