### ISSUE TITLE
Specify option defaults in configuration file with command line overrides

### ISSUE THREAD

**Issue by jmarkow** [pallets/click#971]
Thanks for the awesome library.  I'm trying to achieve the following:  allow the user to specify option *defaults* in a yaml configuration file.  That is, the user specifies the location of a yaml file as an option for a command, then the file specifies the default value for each parameter.  This way if the user passes a config file along with some command line options, the command line options override the config file.  So, e.g.

```sh
my_app -config-file options.yaml --option1 override_value --option2 override_value
```
I've figured out how to read in the configuration file and override option values, but I would like `option1` and `option2` in this example to take their values from the command line, rather than the options file per [this snippet](https://stackoverflow.com/questions/46358797/python-click-supply-arguments-and-options-from-a-configuration-file). 

```python
def CommandWithConfigFile(config_file_param_name):

    class CustomCommandClass(click.Command):

        def invoke(self, ctx):
            config_file = ctx.params[config_file_param_name]
            if config_file is not None:
                with open(config_file) as f:
                    config_data = yaml.load(f, yaml.RoundTripLoader)
                    for param, value in ctx.params.items():
                        if param in config_data:
                            ctx.params[param] = config_data[param]

            return super(CustomCommandClass, self).invoke(ctx)

    return CustomCommandClass
```

 So I think what I'm after is having the config file specify the defaults rather than the option values themselves, but I'm not sure how to proceed.

**Comment by phha** [comment]
[I've written a module](https://github.com/phha/click_config_file) that does exactly this. It's using configobj, not yaml by default, but you can easily drop in your own parser.

```python
def myprovider(file_path, cmd_name):
    with open(file_path) as config_data:
        return json.load(config_data)[cmd_name]

@click.command()
@click.option('--name', default='World')
@click_config_file.configuration_option(provider=myprovider)
def hello(name):
    click.echo('Hello {}!'.format(name))
```

**Comment by chaoflow** [comment]
@jmarkow An alternative approach could be to use the default_map:

```python
import click

@click.group(invoke_without_command=True)
@click.pass_context
def cli(ctx):
    ctx.default_map = {'command': {'foo': 2}}

@cli.command()
@click.option('--foo', default=0)
@click.pass_context
def command(ctx, foo):
    print(foo)

if __name__ == '__main__':
    cli(default_map={'command': {'foo': 1}})
```

If you want the defaults to be already effective for the base command there might be these options:
1. get click to reparse the command-line in the base command
1. manually look for and parse config file option in __main__

**Comment by chaoflow** [comment]
This seems to be related to #590 .

**Comment by jmarkow** [comment]
@chaoflow that sounds promising!  I'll try this out.

**Comment by jcrotts** [comment]
Is this still an issue? It seems like the workarounds provided are sufficient.
