### ISSUE TITLE
Using Format_Usage

### ISSUE THREAD

**Issue by jmcgrath207** [pallets/click#974]
I am trying to use the format_usage function. Could you provide a example of using this?

Ideally I want to use this with  the `@click.group` and `@click.command`

http://click.pocoo.org/5/api/#click.Command.format_usage
format_usage(ctx, formatter)

Thanks

**Comment by PyDever** [comment]
Hi John! First, you got my follow! Cool stuff! Second, did you check `/docs`? I believe there are examples.

**Comment by PyDever** [comment]
Correction, there are no examples. My apologies.

**Comment by PyDever** [comment]
I will try to add some if I have time.

**Comment by VictoryChang** [comment]
Taking a look at this request
