### ISSUE TITLE
Click docs 

### ISSUE THREAD

**Issue by Ublimjo** [pallets/click#975]
```sphinx.util.compat``` is removed in 1.7.0b1

```
sphinx-build -b html -d _build/doctrees   . _build/html.  
Running Sphinx v1.7.2.  
   
Extension error:.  
Could not import extension clickdoctools (exception: cannot import name 'Directive').  
make: *** [Makefile:40: html] Error 2.  
```

**Comment by PyDever** [comment]
Please format your code next time. it is very hard to read when you do not do so.

**Comment by PyDever** [comment]
Also check your copy of the make file

**Comment by dawran6** [comment]
@Ublimjo you are using the Makefile under `docs/`, right? I was able to reproduce the issue by:

```
$ cd docs/
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.7.4

Extension error:
Could not import extension clickdoctools (exception: cannot import name 'Directive')
make: *** [html] Error 2
```

**Comment by dawran6** [comment]
From http://www.sphinx-doc.org/en/master/changes.html#id37:

> Deprecated
> 1.6b1
> sphinx.util.compat.Directive class is now deprecated. Please use instead docutils.parsers.rst.Directive

We could:

1. Just change the import statement and support 1.7+, or 
1. Back-port by using this try-except block: 

```python
try:
    from sphinx.util.compat import Directive
except ImportError:
    from docutils.parsers.rst import Directive
```

IMO 1. is cleaner and easier to maintain.

**Comment by dawran6** [comment]
Found a related PR #883
