### ISSUE TITLE
Skip group functionality when passing --help to a subcommand

### ISSUE THREAD

**Issue by dbrakman** [pallets/click#977]
If a group performs some preprocessing before invoking a subcommand, is it possible to skip this if the --help option is passed to that subcommand?

In click 5.1, the following would, when called with `python script.py subcmd --help`, print the subcmd help without printing the "Perform preprocessing" string.
```python
def detect_subsequent_help(ctx):
    try:
        return any(helpname in ctx.args for helpname in ctx.help_option_names)
    except:
        return False


@click.group()
@click.pass_context
def cli(ctx):
    if not detect_subsequent_help(ctx):
        click.echo('Perform preprocessing')


@cli.command()
def subcmd():
    click.echo('Perform subcommand functionality')
```

Is there a way to achieve the same outcome in click 6.7?

#473 suggests it is not possible, but I ask anyway in case the --help opiton is a special case. Alternatively, is it possible to view callbacks from the Context object, such as through MultiCommand.get_command() and Context.invoked_subcommand?

#108 suggests decorators as a solution, but I'm still struggling to detect the --help option on a subcommand before invoking the decorator for that subcommand.
<details><summary>My attempt is here:</summary><p>
class HelpFinder(object):

&nbsp;&nbsp;&nbsp;&nbsp;def __init__(self):

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.help = False
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.help_command_name = None
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.ctx = None

pass_help = click.make_pass_decorator(HelpFinder, ensure=True)

def help_option(f):
&nbsp;&nbsp;&nbsp;&nbsp;def callback(ctx, param, value):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;help_finder = ctx.ensure_object(HelpFinder)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;if value:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;help_finder.help = value
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;help_finder.help_command_name = ctx.command.name
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;help_finder.ctx = ctx
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return value
&nbsp;&nbsp;&nbsp;&nbsp;return click.option('--help/--no-help',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;expose_value=False,
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;help='Eager option to stop command execution and print help',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;callback=callback)(f)

def real_help_option(f):
&nbsp;&nbsp;&nbsp;&nbsp;f = help_option(f)
&nbsp;&nbsp;&nbsp;&nbsp;return f

@click.group(add_help_option=False)
@real_help_option
@pass_help
def cli(help):
&nbsp;&nbsp;&nbsp;&nbsp;if not help.help:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;click.echo('Perform preprocessing')
&nbsp;&nbsp;&nbsp;&nbsp;elif help.help_command_name == 'cli':
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;click.echo(help.ctx.get_help())

@cli.command(add_help_option=False)
@real_help_option
@pass_help
def subcmd(help):
&nbsp;&nbsp;&nbsp;&nbsp;if not help.help:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;click.echo('Perform subcommand functionality')
&nbsp;&nbsp;&nbsp;&nbsp;elif help.help_command_name == 'subcmd':
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;click.echo(help.ctx.get_help())
</p></details>

**Comment by dbrakman** [comment]
It's not currently possible to use backticks for proper code formatting inside a `<details>` code block: https://github.com/dear-github/dear-github/issues/166#issuecomment-326108215.

The second code block is properly reproduced here:
```python
class HelpFinder(object):
    def __init__(self):
        self.help = False
        self.help_command_name = None
        self.ctx = None

pass_help = click.make_pass_decorator(HelpFinder, ensure=True)


def help_option(f):
    def callback(ctx, param, value):
        help_finder = ctx.ensure_object(HelpFinder)
        if value:
            help_finder.help = value
            help_finder.help_command_name = ctx.command.name
            help_finder.ctx = ctx
        return value
    return click.option('--help/--no-help',
                        expose_value=False,
                        help='Eager option to stop command execution and print help',
                        callback=callback)(f)


def real_help_option(f):
    f = help_option(f)
    return f


@click.group(add_help_option=False)
@click.pass_context
def cli(help):
    if not help.help:
        click.echo('Perform preprocessing')
    elif help.help_command_name == 'cli':
        click.echo(help.ctx.get_help())


@cli.command(add_help_option=False)
@real_help_option
@pass_help
def subcmd(help):
    if not help.help:
        click.echo('Perform subcommand functionality')
    elif help.help_command_name == 'subcmd':
        click.echo(help.ctx.get_help())
```

**Comment by PyDever** [comment]
thanks. i am working on your issue now.

**Comment by PyDever** [comment]
i agree with the docs. It does not appear to be possible.

**Comment by PyDever** [comment]
sorry :disappointed:
