### ISSUE TITLE
Docs claim version 6 to be stable but is (apparently) incomplete

### ISSUE THREAD

**Issue by WoLpH** [pallets/click#979]
Not sure who can change this, but the main documentation url: http://click.pocoo.org/

Points towards http://click.pocoo.org/5/ instead of http://click.pocoo.org/6/

**Comment by PyDever** [comment]
I believe version six is unstable. I could be wrong. The main docs should point to version five in my opinion.

**Comment by PyDever** [comment]
yeah. good idea. "stable" is very relative to many things.

**Comment by PyDever** [comment]
well how about "[DOCS] Claim version 6 to be stable but is incomplete"

**Comment by PyDever** [comment]
because it can be stable yet still incomplete

**Comment by dougharris** [comment]
Dupe of #503

**Comment by WoLpH** [comment]
You're right, I'll close this
