### ISSUE TITLE
Click: Is it still maintained? 

### ISSUE THREAD

**Issue by PyDever** [pallets/click#981]
Not trying to be a pain, but why are there are 64 open pull requests and 228 open issues, a huge portion of which havent been addressed by people of importance? Is click even on the pallets radar anymore?

**Comment by dawran6** [comment]
Click is definitely part of the pallets project IMO since flask uses it. Hope it finds its maintainer soon :)

**Comment by davidism** [comment]
Yes, it is still maintained.
