### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by Yasujizr** [pallets/click#983]
![cl ck](https://user-images.githubusercontent.com/36993664/39429989-45b314ae-4c95-11e8-9c74-7885d4e7a3a5.jpg)

Hi,

I have studied your work and I think a new design will make you more visible. I designed for you, I hope you like it and you want to use it. If you want to reach me, you can look at the my profile. I can give you all the formats of the design free. If you want a change please specify.

![example](https://user-images.githubusercontent.com/36993664/39436769-a3fb1e14-4ca7-11e8-8741-8c2dbe5ab7f9.jpg)

**Comment by PyDever** [comment]
ooh

**Comment by PyDever** [comment]
pretty

**Comment by Yasujizr** [comment]
Thank u, I hope, Project Owner likes and uses it.

**Comment by Yasujizr** [comment]
Thank u, I send mail to PO.

**Comment by dsully** [comment]
Thanks, we're not changing the logo right now.
