### ISSUE TITLE
Deriving default map from parent leads to unexpected behaviour for ctx.invoke

### ISSUE THREAD

**Issue by chaoflow** [pallets/click#988]
## Summary

- When running ctx.invoke(cmd) a default map for cmd will be looked up in the default map for ctx. This only works if cmd is a child of the current command. For siblings ctx.parent.invoke(cmd) is a workaround.
- When invoking a command like this the default map will be set, but not used. A workaround is to pass its contents as keyword arguments to invoke.
- keyword arguments passed like this to invoke are not subject to the usual processing, i.e. [callbacks will not trigger](https://github.com/pallets/click/issues/950) and type definitions will not be used.
- It would be great if it would be possible to pass a default_map to the invoke call, used in the usual way. Does anybody see an easy way to achieve this?

## Discussion

```python
import click

@click.group(invoke_without_command=True)
@click.pass_context
def cli(ctx):
    ctx.default_map = {
        'command': {'foo': 1},
        'other': {'bar': 10},
    }

@cli.command()
@click.option('--foo', default=0)
@click.pass_context
def command(ctx, foo):
    print(foo)
    ctx.invoke(other)

@cli.command()
@click.option('--bar', default=0)
@click.pass_context
def other(ctx, bar):
    print(ctx.default_map)
    print(bar)

if __name__ == '__main__':
    cli()
```

When invoking ``cmd other`` directly, its default_map is correct, whereas when it is invoked via ``cmd command`` its parent context is not ``cmd`` but ``cmd command``.

This can be worked around by changing the default map before invoking the other command:

```python
@cli.command()
@click.option('--foo', default=0)
@click.pass_context
def command(ctx, foo):
    print(foo)
    ctx.default_map = ctx.parent.default_map
    ctx.invoke(other)
```

result:
```
$ cmd command
1
{'bar': 10}
0
```

### Follow-up problem: The default_map is not used when invoking a subcommand.

This can be fixed in core.Context.invoke:

```diff
diff --git a/click/core.py b/click/core.py
index b307407..60b19fe 100644
--- a/click/core.py
+++ b/click/core.py
@@ -536,7 +536,11 @@ class Context(object):
 
             for param in other_cmd.params:
                 if param.name not in kwargs and param.expose_value:
-                    kwargs[param.name] = param.get_default(ctx)
+                    default = ctx.lookup_default(param.name)
+                    if default is None:
+                        kwargs[param.name] = param.get_default(ctx)
+                    else:
+                        kwargs[param.name] = default
 
         args = args[2:]
         with augment_usage_errors(self):
```

Changing the default_map of the current command feels wrong, this might be better:
```diff
diff --git a/click/core.py b/click/core.py
index b307407..43608f4 100644
--- a/click/core.py
+++ b/click/core.py
@@ -529,14 +529,20 @@ class Context(object):
         if isinstance(callback, Command):
             other_cmd = callback
             callback = other_cmd.callback
-            ctx = Context(other_cmd, info_name=other_cmd.name, parent=self)
+            default_map = kwargs.pop('default_map', None)
+            ctx = Context(other_cmd, info_name=other_cmd.name, parent=self,
+                          default_map=default_map)
             if callback is None:
                 raise TypeError('The given command does not have a '
                                 'callback that can be invoked.')
 
             for param in other_cmd.params:
                 if param.name not in kwargs and param.expose_value:
-                    kwargs[param.name] = param.get_default(ctx)
+                    default = ctx.lookup_default(param.name)
+                    if default is None:
+                        kwargs[param.name] = param.get_default(ctx)
+                    else:
+                        kwargs[param.name] = default
 
         args = args[2:]
         with augment_usage_errors(self):
```

```python
@cli.command()
@click.option('--foo', default=0)
@click.pass_context
def command(ctx, foo):
    print(foo)
    other_map = ctx.parent.default_map['other']
    ctx.invoke(other, default_map=other_map)
```

~~## Conclusion:~~

No patching needed, instead pass values as kwargs.

```python
@cli.command()
@click.option('--foo', type=Foo, default=0)
@click.pass_context
def command(ctx, foo):
    other_map = ctx.parent.default_map['other']
    ctx.invoke(other, **other_map)
```

Remaining issue:
- [ ] the option type is not used when invoking another command likes this, instead the raw default values are passed.

**Comment by chaoflow** [comment]
### Follow-up Problem: the option type is not used when invoking another command likes this, instead the raw default values is passed.

**Comment by chaoflow** [comment]
Turns out there is an easier way, see Conclusion above.

**Comment by jpsamper2009** [comment]
@chaoflow Your work around above will work only if the `other` function only needs the information in the default map's `other`. It will in fact fail, if the `other` function needs `command` from the default map too. For example, the code from the top with the fix from the conclusion:

```python
import click

@click.group(invoke_without_command=True)
@click.pass_context
def cli(ctx):
    ctx.default_map = {
        'command': {'foo': 1},
        'other': {'bar': 10},
    }

# Original command
@cli.command()
@click.option('--foo', default=0)
@click.pass_context
def command1(ctx, foo):
    print(foo)
    ctx.invoke(other) 

# Workaround in "Conclusion"
@cli.command()
@click.option('--foo', default=0)
@click.pass_context
def command2(ctx, foo):
    print(foo)
    other_map = ctx.parent.default_map['other']
    ctx.invoke(other, **other_map)

# My proposed workaround
@cli.command()
@click.option('--foo', default=0)
@click.pass_context
def command3(ctx, foo):
    print(foo)
    other_map = ctx.parent.default_map['other']
    ctx.parent.invoke(other, **other_map)

@cli.command()
@click.option('--bar', default=0)
@click.pass_context
def other(ctx, bar):
    print(ctx.default_map)
    print(bar)

if __name__ == '__main__':
    cli()
```

Results:
```bash
$ python3 ./context_passing.py command1 
0
None
0
$ python3 ./context_passing.py command2
0
None
10
$ python3 ./context_passing.py command3
0
{'bar': 10}
10
$ python3 ./context_passing.py other
{'bar': 10}
10
```

`other` called from `command3` has the same context as when calling `other` directly.

**Comment by chaoflow** [comment]
@jpsamper2009 thx! I added a summary at the top.

**Comment by davidism** [comment]
> * When running ctx.invoke(cmd) a default map for cmd will be looked up in the default map for ctx. This only works if cmd is a child of the current command. For siblings ctx.parent.invoke(cmd) is a workaround.
> * When invoking a command like this the default map will be set, but not used. A workaround is to pass its contents as keyword arguments to invoke.

> * It would be great if it would be possible to pass a default_map to the invoke call, used in the usual way. Does anybody see an easy way to achieve this?

`default` map is a nested map of commands to maps of argument for that command and subsequent commands. When a subcontext is created, it takes the map of the command that was called. So if you expect that command to invoke other commands, you would provide the maps for them at that nesting level.

```
    ctx.default_map = {
        'command': {'foo': 1, 'other': {'bar': 12}},
        'other': {'bar': 10},
    }

> * keyword arguments passed like this to invoke are not subject to the usual processing, i.e. [callbacks will not trigger](https://github.com/pallets/click/issues/950) and type definitions will not be used.

`invoke` only calls commands with arguments, it does not trigger command line procesing again. This is intended. Once you're inside the Click functions, you're in Python and should be working with Python values, command line parsing only happens once. There are a bunch of other discussions on this where I probably worded the explanation better.
